Repository ustaxcourt/ef-cms, pull requests merged in 2021-06, with the labels that each got.

#1278 Bug 7581: Public Docket Record - Served Parties column not being populated
  docs/entities/PublicCase.md
  shared/src/business/entities/cases/PublicDocketEntry.js
  shared/src/business/entities/cases/PublicDocketEntry.test.js
  shared/src/business/utilities/getFormattedCaseDetail.js
  shared/src/business/utilities/getFormattedCaseDetail.test.js
  web-client/integration-tests-public/journey/unauthedUserViewsCaseDetail.js
  web-client/src/presenter/computeds/public/publicCaseDetailHelper.test.js
Labels: bugfix

#1279 Bug 7944: 'Edit Title' 'Order Type' dropdown is not pre-populated
  web-client/integration-tests/journey/docketClerkEditsOrderFromMessage.js
  web-client/src/presenter/actions/CourtIssuedOrder/setEditOrderTitleDataOnModalAction.js
  web-client/src/presenter/actions/CourtIssuedOrder/setEditOrderTitleDataOnModalAction.test.js
  web-client/src/presenter/sequences/openEditOrderTitleModalSequence.js
Labels: bugfix

#1303 8384 - Ensure old mapping records are removed before creating new ones
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/prioritizeCaseInteractor.js
  shared/src/business/useCases/prioritizeCaseInteractor.test.js
  shared/src/business/useCases/unprioritizeCaseInteractor.js
  shared/src/business/useCases/unprioritizeCaseInteractor.test.js
  shared/src/business/useCases/updateCaseTrialSortTagsInteractor.js
  shared/src/business/useCases/updateCaseTrialSortTagsInteractor.test.js
  shared/src/business/useCases/updatePetitionDetailsInteractor.js
  shared/src/business/useCases/updatePetitionDetailsInteractor.test.js
  shared/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.js
  shared/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.test.js
  shared/src/persistence/dynamo/cases/updateCaseTrialSortMappingRecords.js
  shared/src/persistence/dynamo/cases/updateCaseTrialSortMappingRecords.test.js
  web-api/src/applicationContext.js
Labels: bugfix

#1283 Bug 7946: File Upload element for "Supporting Document" is not consistent with other file inputs
  web-client/src/views/FileDocument/SecondarySupportingDocumentForm.jsx
  web-client/src/views/FileDocument/StateDrivenFileInput.jsx
  web-client/src/views/FileDocument/SupportingDocumentForm.jsx
Labels: bugfix

#1258 Bug 7514: Filing fee status text should be sentence case not title case
  docs/entities/Case.md
  docs/entities/CaseInternal.md
  shared/src/business/entities/EntityConstants.js
  shared/src/business/utilities/getFormattedCaseDetail.test.js
  web-api/migration-terraform/main/lambdas/migration-segments.js
  web-api/migration-terraform/main/lambdas/migrations/0001-filing-fee-text-casing.js
  web-api/migration-terraform/main/lambdas/migrations/0001-filing-fee-text-casing.test.js
  web-api/migration-terraform/main/lambdas/migrations/0017-remove-draft-order-state.js
  web-api/migration-terraform/main/lambdas/migrations/0017-remove-draft-order-state.test.js
  web-api/migration-terraform/main/lambdas/migrations/0018-remove-nested-draft-order-state.js
  web-api/migration-terraform/main/lambdas/migrations/0018-remove-nested-draft-order-state.test.js
  web-api/migration-terraform/main/lambdas/migrations/0019-remove-values-from-cases.test.js
  web-api/migration-terraform/main/lambdas/migrations/0020-add-entity-name-for-correspondences.js
  web-api/migration-terraform/main/lambdas/migrations/0020-add-entity-name-for-correspondences.test.js
  web-api/migration-terraform/main/lambdas/migrations/0021-practitioner-search-upper-case.js
  web-api/migration-terraform/main/lambdas/migrations/0021-practitioner-search-upper-case.test.js
  web-api/migration-terraform/main/lambdas/migrations/0022-practitioner-admissions-date.js
  web-api/migration-terraform/main/lambdas/migrations/0022-practitioner-admissions-date.test.js
  web-api/migration-terraform/main/lambdas/migrations/0023-set-served-docket-entries-as-completed.js
  web-api/migration-terraform/main/lambdas/migrations/0023-set-served-docket-entries-as-completed.test.js
  web-api/migration-terraform/main/lambdas/migrations/0024-docket-entry-docket-number-served-parties-code.js
  web-api/migration-terraform/main/lambdas/migrations/0024-docket-entry-docket-number-served-parties-code.test.js
  web-api/migration-terraform/main/lambdas/migrations/0025-add-contacts-to-petitioners-array.js
  web-api/migration-terraform/main/lambdas/migrations/0025-add-contacts-to-petitioners-array.test.js
  web-api/migration-terraform/main/lambdas/migrations/0026-hearing-remove-gsi1pk.js
  web-api/migration-terraform/main/lambdas/migrations/0026-hearing-remove-gsi1pk.test.js
  web-api/migration-terraform/main/lambdas/migrations/0026-update-to-stricter-date-format.js
  web-api/migration-terraform/main/lambdas/migrations/0026-update-to-stricter-date-format.test.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/formattedCaseDetail.test.js
Labels: Blue/Green Migration, bugfix

#1293 Bug 8008: PDF Signature Stamp Slightly Off
  shared/src/business/useCases/generateSignedDocumentInteractor.js
  shared/src/business/useCases/generateSignedDocumentInteractor.test.js
  shared/src/business/utilities/htmlGenerator/index.scss
  web-client/src/styles/custom.scss
Labels: bugfix

#1346 Bug 8176: use consistent valid format for practitioner original bar state
  docs/entities/NewPractitioner.md
  docs/entities/Practitioner.md
  shared/src/business/entities/IrsPractitioner.test.js
  shared/src/business/entities/NewPractitioner.test.js
  shared/src/business/entities/Practitioner.js
  shared/src/business/entities/Practitioner.test.js
  shared/src/business/entities/PrivatePractitioner.test.js
  shared/src/business/useCases/getUserInteractor.test.js
  shared/src/business/useCases/practitioners/createPractitionerUserInteractor.test.js
  shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.js
  shared/src/business/useCases/practitioners/validateAddPractitionerInteractor.test.js
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.test.js
  shared/src/business/useCases/users/setUserEmailFromPendingEmailInteractor.test.js
  shared/src/business/useCases/users/updateUserPendingEmailInteractor.test.js
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.test.js
  shared/src/test/mockUsers.js
  shared/src/utilities/JoiValidationDecorator.js
  web-api/migration-terraform/main/lambdas/migration-segments.js
  web-api/migration-terraform/main/lambdas/migrations/0002-original-bar-state.js
  web-api/migration-terraform/main/lambdas/migrations/0002-original-bar-state.test.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/journey/admissionsClerkAddsNewPractitioner.js
  web-client/src/presenter/actions/validateAddPractitionerAction.test.js
  web-client/src/presenter/actions/validatePractitionerAction.test.js
  web-client/src/views/Practitioners/PractitionerForm.jsx
Labels: Blue/Green Migration

#1374 Bug 8424: do not check isRead when computing qcNeeded for docket entries
  shared/src/business/entities/WorkItem.js
  shared/src/business/entities/WorkItem.test.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/workitems/setWorkItemAsReadInteractor.js
  shared/src/business/useCases/workitems/setWorkItemAsReadInteractor.test.js
  shared/src/business/utilities/getFormattedCaseDetail.js
  shared/src/business/utilities/getFormattedCaseDetail.test.js
  shared/src/persistence/dynamo/workitems/setWorkItemAsRead.js
  shared/src/persistence/dynamo/workitems/setWorkItemAsRead.test.js
  web-api/src/applicationContext.js
  web-api/swagger.json
Labels: bugfix

#1428 Bug 8489: correctly link to manifest and favicons in pug template
  web-client/src/index-public.pug
  web-client/src/index.pug
  webpack.config.client.js
Labels: bugfix
