Repository ustaxcourt/ef-cms, pull requests merged in 2022-09, with the labels that each got.

#2502 9591 Enable Tracked Items Operations for Petitions Clerk Users
  shared/src/authorization/authorizationClientService.js
  shared/src/authorization/authorizationClientService.test.js
  web-client/src/presenter/computeds/caseDetailHelper.hasTrackedItemsPermission.test.js
Labels: to test

#2490 Bug 9590: Check for inactivePractitioner role
  shared/src/business/useCases/users/setUserEmailFromPendingEmailInteractor.js
  shared/src/business/useCases/users/setUserEmailFromPendingEmailInteractor.test.js
Labels: bugfix, to staging

#2496 BUG 9553: multi page clinic letters
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCaseHelper/trialSessions/serveGeneratedNoticesOnCase.js
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.js
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.test.js
Labels: to staging

#2487 devex - skip the email service check since it often fails constanstly
  cypress-readonly/integration/public/health-check.cy.js
Labels: to staging

#2439 9497 - adding another load test script to verify we can support traffic
  artillery/read-qc-section-messages.yml
  package.json
Labels: to staging

#2483 DevEx 998: Complete transition to Luxon from Moment
  shared/src/business/utilities/DateHandler.formats.test.js
  shared/src/business/utilities/DateHandler.js
  web-client/src/presenter/computeds/formattedTrialSessions.js
Labels: to staging

#2489 Bug 9574: Document links to some notices are not available to the public terminal user
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.js
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.js
Labels: to staging

#2508 9579 Stamp Order: Add Hyphens On Stamp Clauses
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.jsx
  web-client/src/views/StampMotion/ApplyStamp.jsx
Labels: to staging

#2457 9535: consolidated cases on trial session working copy
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.getTrialSessionStatus.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFiler.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.test.js
  web-api/src/applicationContext.js
  web-client/integration-tests/journey/petitionsClerkVerifiesConsolidatedCaseIndicatorSentMessagesBox.js
  web-client/integration-tests/journey/petitionsClerkVerifiesLeadCaseIndicatorSentMessagesBox.js
  web-client/src/applicationContext.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.filtering.test.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.test.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/presenter/utilities/processFormattedMessages.test.js
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.jsx
  web-client/src/views/Messages/MessagesIndividualCompleted.jsx
  web-client/src/views/Messages/MessagesIndividualInbox.jsx
  web-client/src/views/Messages/MessagesIndividualOutbox.jsx
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.jsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.jsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.jsx
Labels: to staging

#2505 Devex 1079: Don't allow object passed to winston logger to overwrite any of our defaultMeta fields
  web-api/src/applicationContext.js
  web-api/src/createLogger.js
  web-api/src/createLogger.test.js
Labels: to staging

#2501 devex - using more parallel calls to reduce page load times
  web-client/src/presenter/sequences/chooseWorkQueueSequence.js
  web-client/src/presenter/sequences/chooseWorkQueueSequence.test.js
  web-client/src/presenter/sequences/gotoDashboardSequence.js
  web-client/src/presenter/sequences/gotoMessagesSequence.js
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.js
Labels: to staging

#2512 9559 alternate trial clerk
  shared/src/business/entities/trialSessions/NewTrialSession.js
  shared/src/business/entities/trialSessions/NewTrialSession.test.js
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFilter.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  web-client/integration-tests/docketClerkEditsACalendaredTrialSession.test.js
  web-client/src/presenter/actions/TrialSession/computeSubmitTrialSessionDataAction.js
  web-client/src/presenter/actions/TrialSession/computeSubmitTrialSessionFormDataAction.test.js
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.js
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.test.js
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.js
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.test.js
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.js
  web-client/src/presenter/computeds/sessionAssignmentHelper.js
  web-client/src/presenter/computeds/sessionAssignmentHelper.test.js
  web-client/src/presenter/sequences/submitTrialSessionSequence.js
  web-client/src/presenter/sequences/updateTrialSessionSequence.js
  web-client/src/presenter/state.js
  web-client/src/styles/forms.scss
  web-client/src/views/TrialSessions/SessionAssignmentsForm.jsx
Labels: to test

#2509 9603 - fixing validation error with end date
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.js
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.test.js
  web-client/src/ustc-ui/DateInput/DateInput.jsx
  web-client/src/ustc-ui/DateInput/DatePickerComponent.jsx
  web-client/src/views/TrialSessions/SessionInformationForm.jsx
Labels: to staging

#2503 9591 Enable Tracked Items Operations for Petitions Clerk Users
  shared/src/authorization/authorizationClientService.js
  shared/src/authorization/authorizationClientService.test.js
  web-client/src/presenter/computeds/caseDetailHelper.hasTrackedItemsPermission.test.js
Labels: to staging

#2507 9585 Consolidation: Edit Docket Entry Screen
  web-client/integration-tests/docketClerkCompletesQcOnLeadCase.test.js
  web-client/integration-tests/helpers.js
  web-client/src/presenter/sequences/openConfirmInitiateServiceModalSequence.js
Labels: to staging

#2464 DevEx - refactoring the app context into multiple files
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.js
  shared/src/business/useCaseHelper/workItems/updateAssociatedJudgeOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateAssociatedJudgeOnWorkItems.test.js
  shared/src/business/useCaseHelper/workItems/updateCaseStatusOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateCaseStatusOnWorkItems.test.js
  shared/src/business/useCaseHelper/workItems/updateCaseTitleOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateCaseTitleOnWorkItems.test.js
  shared/src/business/useCaseHelper/workItems/updateDocketNumberSuffixOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateDocketNumberSuffixOnWorkItems.test.js
  shared/src/business/useCaseHelper/workItems/updateTrialDateOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateTrialDateOnWorkItems.test.js
  shared/src/business/useCases/correspondence/archiveCorrespondenceDocumentInteractor.js
  shared/src/business/useCases/correspondence/archiveCorrespondenceDocumentInteractor.test.js
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.js
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.test.js
  shared/src/persistence/dynamo/workitems/updateWorkItemAssociatedJudge.js
  shared/src/persistence/dynamo/workitems/updateWorkItemAssociatedJudge.test.js
  shared/src/persistence/dynamo/workitems/updateWorkItemCaseStatus.js
  shared/src/persistence/dynamo/workitems/updateWorkItemCaseStatus.test.js
  shared/src/persistence/dynamo/workitems/updateWorkItemCaseTitle.js
  shared/src/persistence/dynamo/workitems/updateWorkItemCaseTitle.test.js
  shared/src/persistence/dynamo/workitems/updateWorkItemDocketNumberSuffix.js
  shared/src/persistence/dynamo/workitems/updateWorkItemDocketNumberSuffix.test.js
  shared/src/persistence/dynamo/workitems/updateWorkItemTrialDate.js
  shared/src/persistence/dynamo/workitems/updateWorkItemTrialDate.test.js
  web-api/jest.config.js
  web-api/src/applicationContext.js
  web-api/src/getPersistenceGateway.js
  web-api/src/getUseCaseHelpers.js
  web-api/src/getUseCases.js
Labels: to staging

#2542 9497 identify consolidated cases in qc display to test
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.js
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.test.js
  shared/src/business/useCases/processStreamRecords/processWorkItemEntries.js
  shared/src/persistence/elasticsearch/searchClient.test.js
Labels: to test

#2452 Devex 1028 contribution guide
  CONTRIBUTING.md
  docs/README.md
  docs/_sidebar.md
  docs/additional-resources/_sidebar.md
  docs/additional-resources/how-we-work.md
  docs/code-review.md
  docs/external-contributions.md
  docs/pr-workflow.md
  docs/running-locally.md
Labels: to staging

#2093 Upgrading Dynamsoft to 17.2.5
  docs/environments.md
  shared/src/business/useCases/health/getHealthCheckInteractor.ts
  shared/src/persistence/dynamsoft/getScannerInterface.js
  shared/src/persistence/dynamsoft/getScannerInterface.test.js
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/bin/destroy-app.sh
  web-client/build-dist.sh
  web-client/terraform/common/cloudfront-edge/header-security-lambda.js
  web-client/terraform/main/setup_dynamsoft.sh
Labels: to staging

#2519 9564: Dedicated Docket View for Exhibits
  shared/src/business/entities/EntityConstants.js
  web-client/integration-tests/docketClerkConsolidatesCasesCoversheets.test.js
  web-client/integration-tests/docketRecordFilterJourney.test.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryForTrialExhibit.js
  web-client/src/getConstants.js
  web-client/src/presenter/computeds/formattedDocketEntries.js
  web-client/src/presenter/computeds/formattedDocketEntries.test.js
  web-client/src/presenter/state.js
  web-client/src/styles/custom.scss
  web-client/src/styles/overrides.scss
  web-client/src/views/DocketRecord/DocketRecordHeader.jsx
Labels: to staging

#2545 Dependency updates week of 09 12 22
  .circleci/config.yml
  Dockerfile
  docs/team-process.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: dependencies, to staging

#2525 9497 identify consolidated cases in qc display test
  README.md
  shared/src/business/entities/EntityValidationConstants.js
  shared/src/business/entities/OutboxItem.js
  shared/src/business/entities/OutboxItem.test.js
  shared/src/business/entities/WorkItem.js
  shared/src/business/entities/WorkItem.test.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.consolidatedCases.test.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.test.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.test.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.ts
  shared/src/business/useCases/processStreamRecords/processCaseEntries.test.ts
  shared/src/business/useCases/processStreamRecords/processCaseEntries.ts
  shared/src/business/useCases/processStreamRecords/processWorkItemEntries.test.ts
  shared/src/business/useCases/processStreamRecords/processWorkItemEntries.ts
  shared/src/persistence/elasticsearch/bulkIndexRecords.js
  shared/src/persistence/elasticsearch/bulkIndexRecords.test.js
  shared/src/persistence/elasticsearch/getIndexNameForRecord.js
  shared/src/persistence/elasticsearch/getIndexNameForRecord.test.js
  shared/src/persistence/elasticsearch/helpers/formatWorkItemResult.js
  shared/src/persistence/elasticsearch/helpers/formatWorkItemResult.test.js
  shared/src/persistence/elasticsearch/helpers/searchClauses.js
  shared/src/persistence/elasticsearch/messages/getCompletedSectionInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getCompletedUserInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getSectionInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getSectionOutboxMessages.js
  shared/src/persistence/elasticsearch/messages/getUserInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getUserOutboxMessages.js
  shared/src/persistence/elasticsearch/searchClient.js
  shared/src/persistence/elasticsearch/searchClient.test.js
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForSection.js
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForSection.test.js
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForUser.js
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForUser.test.js
  web-api/elasticsearch/efcms-work-item-mappings.js
  web-client/integration-tests/docketClerkConsolidatedCaseWorkItemsJourney.test.js
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/docketClerkAddsPaperFiledPendingDocketEntryAndSavesForLater.js
  web-client/integration-tests/journey/docketClerkAssignWorkItemToSelf.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedLeadCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/docketClerkViewsQCSectionInbox.js
  web-client/integration-tests/journey/petitionsClerkAddsPractitionersToCase.js
  web-client/integration-tests/journey/practitionerCreatesNewCase.js
  web-client/integration-tests/journey/practitionerFilesDocumentForOwnedCase.js
  web-client/integration-tests/petitionsClerkBlockConsolidatedCasesJourney.test.js
  web-client/src/presenter/actions/EditDocketRecord/completeDocketEntryQCAction.js
  web-client/src/presenter/computeds/formattedWorkQueue.js
  web-client/src/presenter/computeds/formattedWorkQueue.test.js
  web-client/src/views/WorkQueue/IndividualWorkQueueInProgress.jsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.jsx
  web-client/src/views/WorkQueue/IndividualWorkQueueOutbox.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.jsx
Labels: to staging

#2562 9592 hybrid case filter
  web-client/integration-tests/filterAHybridTrialSession.test.js
  web-client/integration-tests/journey/petitionsClerkViewsAHybridTrialSessionsFilteredEligibleCases.js
  web-client/integration-tests/modifyRespondentContactInfo.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.test.js
  web-client/src/presenter/state.js
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
  web-client/src/views/TrialSessionDetail/TrialSessionDetail.jsx
Labels: to test

#2523 2379 consolidated order caption
  .circleci/config.yml
  package-lock.json
  scripts/dynamo/setup-add-docket-numbers-to-orders-flag.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.test.ts
  shared/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.ts
  shared/src/business/utilities/documentGenerators/order.js
  shared/src/business/utilities/documentGenerators/order.test.js
  shared/src/business/utilities/htmlGenerator/components/order-docket-header.scss
  shared/src/business/utilities/pdfGenerator/components/OrderDocketHeader.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/Order.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/Order.test.js
  shared/src/proxies/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlProxy.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/docketClerkCreatesOrderWithAddedDocketEntries.test.js
  web-client/integration-tests/journey/docketClerkCreatesAnOrderWithAddedDocketNumbers.js
  web-client/integration-tests/journey/docketClerkEditsOrderAndChecksAddedDocketNumbers.js
  web-client/src/presenter/actions/CaseConsolidation/hasAlreadyAddedDocketNumbersAction.js
  web-client/src/presenter/actions/CaseConsolidation/hasAlreadyAddedDocketNumbersAction.test.js
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.js
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.test.js
  web-client/src/presenter/actions/CaseConsolidation/setupConsolidatedCasesForAddedDocketNumbersAction.js
  web-client/src/presenter/actions/CaseConsolidation/setupConsolidatedCasesForAddedDocketNumbersAction.test.js
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.js
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.test.js
  web-client/src/presenter/actions/CourtIssuedOrder/isFormPristineAction.js
  web-client/src/presenter/actions/CourtIssuedOrder/isFormPristineAction.test.js
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.js
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.test.js
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.js
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.test.js
  web-client/src/presenter/actions/setAddedDocketNumbersAction.js
  web-client/src/presenter/actions/setAddedDocketNumbersAction.test.js
  web-client/src/presenter/actions/setDefaultTabStateAction.js
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.js
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.test.js
  web-client/src/presenter/computeds/createOrderHelper.js
  web-client/src/presenter/computeds/createOrderHelper.test.js
  web-client/src/presenter/presenter.js
  web-client/src/presenter/sequences/gotoCreateOrderSequence.js
  web-client/src/presenter/sequences/gotoEditOrderSequence.js
  web-client/src/presenter/sequences/openAddDocketNumbersModalSequence.js
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.js
  web-client/src/presenter/sequences/submitUpdateAddDocketNumbersToOrderSequence.js
  web-client/src/presenter/state.js
  web-client/src/views/CreateOrder/AddDocketNumbersModal.jsx
  web-client/src/views/CreateOrder/CreateOrder.jsx
Labels: to staging

#2563 9592 hybrid case filter
  web-client/integration-tests/filterAHybridTrialSession.test.js
  web-client/integration-tests/journey/petitionsClerkViewsAHybridTrialSessionsFilteredEligibleCases.js
  web-client/integration-tests/modifyRespondentContactInfo.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.test.js
  web-client/src/presenter/state.js
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
  web-client/src/views/TrialSessionDetail/TrialSessionDetail.jsx
Labels: to staging

#2591 Documentation update
  README.md
  docs/README.md
  docs/ci-cd.md
  docs/deploying.md
  docs/getting-started.md
  docs/teamcharter.md
  docs/what-is-dawson.md
Labels: to staging

#2582 Dependency updates
  .eslintrc.js
  .github/workflows/api.yml
  .github/workflows/client.yml
  .github/workflows/lint.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  package-lock.json
  package.json
  web-client/src/styles/custom.scss
  web-client/src/styles/icons.scss
  web-client/src/styles/modals.scss
  web-client/src/styles/overrides.scss
  web-client/src/ustc-ui/DollarsInput/DollarsInput.jsx
Labels: to staging

#2609 9610 hybrid case type counts to test
  package-lock.json
  web-client/src/presenter/computeds/trialSessionDetailsHelper.js
  web-client/src/presenter/computeds/trialSessionDetailsHelper.test.js
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDeadlines/CaseDeadlines.jsx
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.jsx
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
Labels: to test
