Repository ustaxcourt/ef-cms, pull requests merged in 2022-12, with the labels that each got.

#2831 9681 Refactor service of multi-docketable documents on consolidated groups
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/WorkItem.js
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.js
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.js
  shared/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.js
  shared/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.test.js
  shared/src/business/useCaseHelper/stampDocumentForService.js
  shared/src/business/useCaseHelper/stampDocumentForService.test.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.consolidatedCases.test.ts
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.consolidatedCases.test.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.test.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.test.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.ts
  shared/src/persistence/dynamo/documents/deleteDocketEntry.ts
  shared/src/proxies/documents/addPaperFilingProxy.js
  shared/src/proxies/documents/fileAndServeCourtIssuedDocumentProxy.js
  shared/src/proxies/documents/serveExternallyFiledDocumentProxy.js
  shared/src/proxies/serveCourtIssuedDocumentProxy.js
  shared/src/test/mockTrial.js
  web-api/src/app.js
  web-api/src/cases/fileAndServeCourtIssuedDocumentLambda.js
  web-api/src/cases/serveCourtIssuedDocumentLambda.js
  web-api/src/documents/addPaperFilingLambda.js
  web-api/src/documents/serveExternallyFiledDocumentLambda.js
  web-api/src/getUseCaseHelpers.ts
  web-api/src/notifications/connectLambda.js
  web-client/integration-tests/docketClerkAddsPaperFilingOnLeadCase.test.js
  web-client/integration-tests/docketClerkConsolidatesCases.test.js
  web-client/integration-tests/docketClerkServesCourtIssuedDocumentOnLeadCaseFromMessageDetail.test.js
  web-client/integration-tests/docketClerkServesPaperFiledDocumentOnLeadCaseFromMessageDetail.test.js
  web-client/integration-tests/docketRecordJourney.test.js
  web-client/integration-tests/journey/docketClerkServesDocumentFromCaseDetailDocumentView.js
  web-client/integration-tests/journey/petitionsClerk1ServesCourtIssuedDocumentFromMessageDetail.js
  web-client/integration-tests/orderSearchJourneyAndKeyword.test.js
  web-client/integration-tests/petitionsClerkCaseDeadlineFromOrderForFilingFee.test.js
  web-client/integration-tests/stampDispositionJudgeJourney.test.js
  web-client/src/getConstants.js
  web-client/src/presenter/actions/CaseConsolidation/flipConsolidatedCaseAllCheckboxAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.test.js
  web-client/src/presenter/actions/DocketEntry/isCoversheetNeededAction.js
  web-client/src/presenter/actions/DocketEntry/isCoversheetNeededAction.test.js
  web-client/src/presenter/actions/DocketEntry/servePaperFiledDocumentAction.js
  web-client/src/presenter/actions/DocketEntry/servePaperFiledDocumentAction.test.js
  web-client/src/presenter/actions/DocketEntry/submitAddPaperFilingAction.js
  web-client/src/presenter/actions/DocketEntry/submitAddPaperFilingAction.test.js
  web-client/src/presenter/actions/TrialSession/computeSubmitTrialSessionFormDataAction.test.js
  web-client/src/presenter/actions/serveCourtIssuedDocumentAction.js
  web-client/src/presenter/actions/serveCourtIssuedDocumentAction.test.js
  web-client/src/presenter/actions/setDocketEntrySelectedFromMessageAction.js
  web-client/src/presenter/sequences/openConfirmInitiateCourtIssuedFilingServiceModalSequence.js
  web-client/src/views/ConfirmInitiateCourtIssuedFilingServiceModal.jsx
  web-client/src/views/ConfirmInitiatePaperFilingServiceModal.jsx
Labels: to staging

#2873 3287: updates and feedback
  shared/src/business/entities/EntityConstants.js
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  shared/src/business/utilities/generateSelectedFilterList.js
  shared/src/business/utilities/generateSelectedFilterList.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.jsx
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.trialStatus.test.js
Labels: to test

#2853 OpEx 1107: Environment Switcher
  .gitignore
  scripts/env/aws-accounts/example.env
  scripts/env/defaults-example
  scripts/env/environment-switcher.md
  scripts/env/environments/00-common
  scripts/env/environments/example.env
  scripts/env/environments/local-example.env
  scripts/env/set-env.zsh
  scripts/env/unset-env.zsh
Labels: to staging

#2536 USTC-2535 index on reconciliation report
  docs/api/v2.yaml
  shared/src/business/entities/ReconciliationReportEntry.js
  shared/src/persistence/elasticsearch/getReconciliationReport.js
  web-client/integration-tests/journey/irsSuperuserGetsReconciliationReport.js
Labels: to staging

#2900 9745 Bugfix - Cleanup
  docs/aws.md
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/8f04b515-95b3-4515-8225-9cdd889fd4ad._S3rver_metadata.json
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/8f04b515-95b3-4515-8225-9cdd889fd4ad._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/8f04b515-95b3-4515-8225-9cdd889fd4ad._S3rver_object.md5
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/d4a9662b-ca30-4bf4-b7fd-a3c976a84fb7._S3rver_metadata.json
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/d4a9662b-ca30-4bf4-b7fd-a3c976a84fb7._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/d4a9662b-ca30-4bf4-b7fd-a3c976a84fb7._S3rver_object.md5
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/streams-local.js
Labels: to staging

#2866 9479: Remove Stamp Disposition Feature Flag and all related code
  scripts/dynamo/delete-stamp-disposition-feature-flag.sh
  scripts/dynamo/enable-stamp-disposition.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/documentViewerHelper.js
  web-client/src/presenter/computeds/documentViewerHelper.showApplyStampButton.test.js
  web-client/src/presenter/computeds/messageDocumentHelper.js
  web-client/src/presenter/computeds/messageDocumentHelper.showApplyStampButton.test.js
  web-client/src/presenter/sequences/gotoCaseDetailSequence.js
  web-client/src/presenter/sequences/gotoMessageDetailSequence.js
Labels: to staging

#2894 9684 Message Display: Display Place and Date of Trial Session When Case is Calendared
  shared/src/business/entities/Message.js
  shared/src/business/entities/MessageResult.js
  shared/src/business/entities/MessageResult.test.js
  shared/src/business/useCases/messages/getInboxMessagesForSectionInteractor.test.ts
  shared/src/business/useCases/messages/getInboxMessagesForSectionInteractor.ts
  shared/src/business/useCases/messages/getInboxMessagesForUserInteractor.test.ts
  shared/src/business/useCases/messages/getInboxMessagesForUserInteractor.ts
  shared/src/business/useCases/messages/getOutboxMessagesForSectionInteractor.test.ts
  shared/src/business/useCases/messages/getOutboxMessagesForSectionInteractor.ts
  shared/src/business/useCases/messages/getOutboxMessagesForUserInteractor.test.ts
  shared/src/business/useCases/messages/getOutboxMessagesForUserInteractor.ts
  shared/src/business/utilities/abbreviateState.js
  shared/src/business/utilities/abbreviateState.test.js
  shared/src/persistence/elasticsearch/helpers/searchClauses.js
  web-api/elasticsearch/efcms-case-mappings.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/messagesTableJourney.test.js
  web-client/src/applicationContext.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedMessages.test.js
  web-client/src/views/Messages/MessagesIndividualInbox.jsx
  web-client/src/views/Messages/MessagesIndividualOutbox.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: Do Not Merge, to test

#2897 3287: Update trial status types
  docs/migrations.md
  scripts/dynamo/setup-updated-trial-session-types-flag.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.js
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.test.js
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.js
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.test.js
  shared/src/business/utilities/generateSelectedFilterList.js
  shared/src/business/utilities/generateSelectedFilterList.test.js
  shared/src/business/utilities/pdfGenerator/components/SelectedFiltersSection.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.jsx
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.2.png
  types/TEntity.d.ts
  web-api/migration-terraform/main/lambdas/migrations/0003-update-trial-session-working-copy-status.js
  web-api/migration-terraform/main/lambdas/migrations/0003-update-trial-session-working-copy-status.test.js
  web-api/migration-terraform/main/lambdas/migrationsToRun.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/swagger.json
  web-client/src/presenter/actions/TrialSessionWorkingCopy/computeTrialSessionWorkingCopyFilterValuesAction.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/computeTrialSessionWorkingCopyFilterValuesAction.test.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/setDefaultWorkingCopyValuesAction.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/setDefaultWorkingCopyValuesAction.test.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.filtering.test.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.trialStatus.test.js
  web-client/src/presenter/sequences/gotoTrialSessionWorkingCopySequence.js
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.jsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopyFilterHeader.jsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.jsx
Labels: Blue/Green Migration, to staging

#2905 9684 Message Display: Display Place and Date of Trial Session When Case Status = Calendared
  shared/src/business/entities/Message.js
  shared/src/business/entities/MessageResult.js
  shared/src/business/entities/MessageResult.test.js
  shared/src/business/useCases/messages/getCompletedMessagesForSectionInteractor.test.ts
  shared/src/business/useCases/messages/getCompletedMessagesForSectionInteractor.ts
  shared/src/business/useCases/messages/getCompletedMessagesForUserInteractor.test.ts
  shared/src/business/useCases/messages/getCompletedMessagesForUserInteractor.ts
  shared/src/business/useCases/messages/getInboxMessagesForSectionInteractor.test.ts
  shared/src/business/useCases/messages/getInboxMessagesForSectionInteractor.ts
  shared/src/business/useCases/messages/getInboxMessagesForUserInteractor.test.ts
  shared/src/business/useCases/messages/getInboxMessagesForUserInteractor.ts
  shared/src/business/useCases/messages/getOutboxMessagesForSectionInteractor.test.ts
  shared/src/business/useCases/messages/getOutboxMessagesForSectionInteractor.ts
  shared/src/business/useCases/messages/getOutboxMessagesForUserInteractor.test.ts
  shared/src/business/useCases/messages/getOutboxMessagesForUserInteractor.ts
  shared/src/business/utilities/abbreviateState.js
  shared/src/business/utilities/abbreviateState.test.js
  shared/src/persistence/elasticsearch/helpers/searchClauses.js
  web-api/elasticsearch/efcms-case-mappings.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/messagesTableJourney.test.js
  web-client/src/applicationContext.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedMessages.test.js
  web-client/src/views/Messages/MessagesIndividualInbox.jsx
  web-client/src/views/Messages/MessagesIndividualOutbox.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: Blue/Green Migration, to staging

#2877 Bugfix 9654 docket entry
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/courtIssuedDocument/generateCourtIssuedDocumentTitle.test.ts
  shared/src/business/useCases/courtIssuedDocument/generateCourtIssuedDocumentTitle.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.getNeedsNewCoversheet.test.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.needsNewCoversheet.test.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.ts
  shared/src/business/useCases/externalDocument/generateExternalDocumentTitle.test.ts
  shared/src/business/useCases/externalDocument/generateExternalDocumentTitle.ts
  shared/src/business/utilities/getDescriptionDisplay.js
  shared/src/business/utilities/getDescriptionDisplay.test.js
  shared/src/business/utilities/getDocumentTitleForNoticeOfChange.js
  shared/src/business/utilities/getDocumentTitleForNoticeOfChange.test.js
  shared/src/business/utilities/getFormattedCaseDetail.js
  web-api/src/applicationContext.js
  web-client/integration-tests/docketClerkExternalDocumentQCWorkflow.test.js
  web-client/integration-tests/journey/docketClerkQCsDocketEntry.js
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/applicationContext.js
  web-client/src/applicationContextPublic.js
  web-client/src/presenter/actions/CaseAssociationRequest/generateCaseAssociationTitleAction.js
  web-client/src/presenter/actions/CaseAssociationRequest/generateCaseAssociationTitleAction.test.js
  web-client/src/presenter/actions/CaseDetail/createMessageAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/generateCourtIssuedDocumentTitleAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/generateCourtIssuedDocumentTitleAction.test.js
  web-client/src/presenter/actions/DocketEntry/setCompleteDocketEntryAlertAction.js
  web-client/src/presenter/actions/DocketEntry/setCompleteDocketEntryAlertAction.test.js
  web-client/src/presenter/actions/EditDocketRecord/completeDocketEntryQCAction.js
  web-client/src/presenter/actions/EditDocketRecord/completeDocketEntryQCAction.test.js
  web-client/src/presenter/actions/EditDocketRecordEntry/generateTitlePreviewAction.js
  web-client/src/presenter/actions/EditDocketRecordEntry/generateTitlePreviewAction.test.js
  web-client/src/presenter/actions/FileDocument/generateTitleAction.js
  web-client/src/presenter/actions/FileDocument/generateTitleAction.test.js
  web-client/src/presenter/actions/FileDocument/generateTitleForPaperFilingAction.js
  web-client/src/presenter/actions/FileDocument/generateTitleForPaperFilingAction.test.js
  web-client/src/presenter/actions/FileDocument/generateTitleForSupportingDocumentsAction.js
  web-client/src/presenter/actions/FileDocument/generateTitleForSupportingDocumentsAction.test.js
  web-client/src/presenter/actions/FileDocument/setPreviousDocumentDocketEntryAction.js
  web-client/src/presenter/actions/FileDocument/setPreviousDocumentDocketEntryAction.test.js
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.js
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.test.js
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.js
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.js
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.js
  web-client/src/presenter/computeds/formattedDocketEntries.js
  web-client/src/presenter/computeds/formattedWorkQueue.js
  web-client/src/presenter/computeds/selectDocumentTypeHelper.js
  web-client/src/presenter/sequences/completeDocketEntryQCAndSendMessageSequence.js
  web-client/src/presenter/sequences/completeDocketEntryQCSequence.js
  web-client/src/presenter/sequences/gotoEditCourtIssuedDocketEntrySequence.test.js
  web-client/src/presenter/sequences/gotoEditDocketEntryMetaSequence.test.js
  web-client/src/presenter/sequences/openCompleteAndSendMessageModalSequence.js
Labels: to staging

#2917 9742 Recent Messages: Update w/ Trial Session Info
  web-client/integration-tests/messagesTableJourney.test.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/recentMessagesHelper.js
  web-client/src/presenter/computeds/recentMessagesHelper.test.js
  web-client/src/views/WorkQueue/RecentMessagesInbox.jsx
Labels: to test

#2921 9746: draft docs missing doctype
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.js
  web-client/src/presenter/computeds/caseDetailEditHelper.js
  web-client/src/presenter/computeds/caseDetailEditHelper.test.js
Labels: to test

#2929 9741-add application package to practitioner document types map
  shared/src/business/entities/EntityConstants.js
Labels: to test

#2907 Dependency updates Week of 12/12/2022
  .circleci/config.yml
  package-lock.json
  package.json
Labels: to staging

#2910 Devex ts more ts refactor
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  shared/src/notifications/retrySendNotificationToConnections.test.ts
  shared/src/notifications/retrySendNotificationToConnections.ts
  shared/src/notifications/sendNotificationToConnection.test.ts
  shared/src/notifications/sendNotificationToConnection.ts
  shared/src/notifications/sendNotificationToUser.test.ts
  shared/src/notifications/sendNotificationToUser.ts
  types/TEntity.d.ts
  types/TNotificationEntity.d.ts
Labels: to staging

#2920 9742 Recent Messages: Update w/ Trial Session Info
  web-client/integration-tests/messagesTableJourney.test.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/recentMessagesHelper.js
  web-client/src/presenter/computeds/recentMessagesHelper.test.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/views/WorkQueue/RecentMessagesInbox.jsx
Labels: to staging

#2941 9741 new application package category test
  .circleci/config.yml
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.js
Labels: to test

#2915 Devex 1077: Elasticsearch Package has been deprecated
  package-lock.json
  package.json
  scripts/delete-old-infrastructure-pre-migration.sh
  shared/admin-tools/elasticsearch/check-reindex-complete.js
  shared/admin-tools/elasticsearch/check-reindex-complete.test.js
  shared/admin-tools/elasticsearch/docket-entry-search.js
  shared/admin-tools/elasticsearch/docket-inbox.js
  shared/admin-tools/elasticsearch/find-cases-linked-to-practitioners.js
  shared/admin-tools/elasticsearch/find-deadlines.js
  shared/admin-tools/elasticsearch/find-petitioners-missing-cases.js
  shared/admin-tools/elasticsearch/get-users.js
  shared/admin-tools/elasticsearch/health-migration.js
  shared/admin-tools/elasticsearch/non-attorney-practitioners.js
  shared/admin-tools/elasticsearch/test-elasticsearch.js
  shared/admin-tools/glue/lookup-user.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/workitems/getDocumentQCInboxForSectionInteractor.test.ts
  shared/src/business/useCases/workitems/getDocumentQCInboxForUserInteractor.test.ts
  shared/src/persistence/elasticsearch/getCaseInventoryReport.test.js
  shared/src/persistence/elasticsearch/getCasesByUserId.test.js
  shared/src/persistence/elasticsearch/getDocketEntriesServedWithinTimeframe.test.js
  shared/src/persistence/elasticsearch/getFirstSingleCaseRecord.test.js
  shared/src/persistence/elasticsearch/searchClient.js
  shared/src/persistence/elasticsearch/searchClient.test.constants.js
  shared/src/persistence/elasticsearch/searchClient.test.js
  web-api/delete-elasticsearch-index.js
  web-api/elasticsearch/client.js
  web-api/elasticsearch/elasticsearch-index-settings.js
  web-api/src/applicationContext.js
Labels: to staging

#2928 9746: draft docs missing doctype
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.js
  web-client/src/presenter/computeds/caseDetailEditHelper.js
  web-client/src/presenter/computeds/caseDetailEditHelper.test.js
Labels: to staging

#2939 9759 trial session status fix to test
  docs/aws.md
  package.json
  shared/src/business/dto/TrialSessionInfoDto.test.ts
  shared/src/business/dto/TrialSessionInfoDto.ts
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/trialSessions/TrialSession.getTrialSessionStatus.test.js
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/trialSessions/closeTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsForJudgeInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsInteractor.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFiler.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFilter.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/proxies/trialSessions/getTrialSessionsForJudgeProxy.js
  types/TEntity.d.ts
  web-api/dynamo-export.js
  web-api/migration-terraform/main/lambdas/migrations/0004-set-session-status.js
  web-api/migration-terraform/main/lambdas/migrations/0004-set-session-status.test.js
  web-api/migration-terraform/main/lambdas/migrationsToRun.js
  web-api/src/applicationContext.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/swagger.json
  web-client/integration-tests/journey/docketClerkViewsNewTrialSession.js
  web-client/integration-tests/journey/docketClerkViewsStandaloneRemoteTrialSession.js
  web-client/integration-tests/journey/docketClerkViewsTrialSessionWithNote.js
  web-client/integration-tests/journey/petitionsClerkViewsATrialSessionsEligibleCases.js
  web-client/integration-tests/journey/petitionsClerkViewsATrialSessionsEligibleCasesWithManuallyAddedCase.js
  web-client/integration-tests/journey/petitionsClerkViewsNewTrialSession.js
  web-client/integration-tests/journey/petitionsClerkViewsOpenTrialSession.js
  web-client/integration-tests/petitionsClerkSetsRemoteTrialSessionCalendar.test.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.js
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.js
  web-client/src/presenter/computeds/setForHearingModalHelper.js
  web-client/src/presenter/computeds/trialSessionHeaderHelper.js
  web-client/src/presenter/computeds/trialSessionHeaderHelper.test.js
  web-client/src/views/TrialSessionDetail/TrialSessionDetailHeader.jsx
Labels: Do Not Merge

#2952 9668: Auto-Generate Deadline - Order for Amended Petition and Filing Fee (OAPF)
  shared/src/business/entities/EntityConstants.js
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.js
  web-client/integration-tests/petitionsClerkCaseDeadlineFromOrderForAmendedPetitionAndFilingFee.test.js
Labels: to test

#2930 9741-add application package to practitioner document types map
  shared/src/business/entities/EntityConstants.js
Labels: to staging

#2956 DevEx-1116 - Log when response payload over 5mb
  aws/lambdas/LogsToElasticSearch_info/index-template.json
  web-api/src/logger.js
  web-api/src/logger.test.js
Labels: to test

#2953 Devex: Fix lint warnings
  shared/src/authorization/getUserPermissions.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/practitioners/getPractitionerDocumentsInteractor.test.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.ts
  shared/src/business/useCases/trialSessions/setNoticesForCalendaredTrialSessionInteractor.test.ts
  shared/src/business/useCases/updatePetitionerInformationInteractor.test.ts
  shared/src/business/utilities/DateHandler.js
  shared/src/business/utilities/abbreviateState.js
  shared/src/business/utilities/formatPhoneNumber.js
  shared/src/business/utilities/replaceBracketed.js
  shared/src/persistence/dynamodbClientService.ts
  shared/src/test/mockDocuments.js
  web-api/src/middleware/apiGatewayHelper.js
  web-client/integration-tests/externalUserOpinionSearch.test.js
  web-client/integration-tests/stampDispositionClerkOfTheCourtJourney.test.js
  web-client/src/presenter/actions/getDocumentEditUrlAsPathAction.js
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.js
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.test.js
Labels: to staging

#2951 Devex: Remove unnecessary timeouts
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatch.test.js
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatchCaseCaption.test.js
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatchMultipleFields.test.js
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatchPrimaryAndSecondaryContactName.test.js
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatchSecondaryContactName.test.js
  web-client/integration-tests-public/unauthedUserCaseSearchPartialMatchContactPrimaryName.test.js
  web-client/integration-tests-public/unauthedUserOrderSearchExactMatchDocumentTitle.test.js
  web-client/integration-tests-public/unauthedUserSearchesForCase.test.js
  web-client/integration-tests-public/unauthedUserSearchesForOrder.test.js
  web-client/integration-tests-public/unauthedUserSearchesForSealedCase.test.js
  web-client/integration-tests-public/unauthedUserSearchesForUnsealedCase.test.js
  web-client/integration-tests-public/unauthedUserSeesStrickenDocketEntry.test.js
  web-client/integration-tests-public/unauthedUserViewsHealthCheck.test.js
  web-client/integration-tests-public/unauthedUserViewsTodaysOpinions.test.js
  web-client/integration-tests-public/unauthedUserViewsTodaysOrders.test.js
  web-client/integration-tests-public/userTriesToViewUnsealedCaseWithSealedDocketEntry.test.js
  web-client/integration-tests/petitionsClerkBlockConsolidatedCasesJourney.test.js
  web-client/integration-tests/petitionsClerkCaseAdvancedSearch.test.js
  web-client/integration-tests/petitionsClerkCaseNotesJourney.test.js
  web-client/integration-tests/petitionsClerkCounselAssociationJourney.test.js
  web-client/integration-tests/petitionsClerkCreateNoticeJourney.test.js
  web-client/integration-tests/petitionsClerkCreateOrderJourney.test.js
  web-client/integration-tests/petitionsClerkCreatesEstateCaseWithLongAdditionalName.test.js
  web-client/integration-tests/petitionsClerkDocumentQCJourney.test.js
  web-client/integration-tests/petitionsClerkEditsPetitionPaymentFee.test.js
  web-client/integration-tests/petitionsClerkPrioritizesCase.test.js
  web-client/integration-tests/petitionsClerkQCPetitionStatistics.test.js
  web-client/integration-tests/petitionsClerkRemovesPetitionerDuringPetitionQc.test.js
  web-client/integration-tests/petitionsClerkSavesDocumentQCForLater.test.js
  web-client/integration-tests/petitionsClerkServesOrder.test.js
  web-client/integration-tests/petitionsClerkSetsRemoteTrialSessionCalendar.test.js
  web-client/integration-tests/petitionsClerkSetsTrialSessionCalendar.test.js
  web-client/integration-tests/petitionsClerkSignsDocumentJourney.test.js
  web-client/integration-tests/petitionsClerkVerifiesOffboardedJudgeJourney.test.js
  web-client/integration-tests/petitionsClerkViewsDraftDocuments.test.js
  web-client/integration-tests/practitionerCaseJourney.test.js
  web-client/integration-tests/practitionerDocumentationJourney.test.js
  web-client/integration-tests/privatePractitionerConsolidatedCasesWithStatisticsJourney.test.js
  web-client/integration-tests/privatePractitionerViewsPendingEmailJourney.test.js
  web-client/integration-tests/respondentCaseJourney.test.js
  web-client/integration-tests/scheduleATrialSession.test.js
  web-client/integration-tests/sentWorkItemsExpireAfterNDays.test.js
  web-client/integration-tests/signAndServeStipulatedDecision.test.js
  web-client/integration-tests/stampDispositionClerkOfTheCourtJourney.test.js
  web-client/integration-tests/stampDispositionJudgeJourney.test.js
  web-client/integration-tests/trialClerkWorkingCopy.test.js
  web-client/integration-tests/trialHearingsJourney.test.js
  web-client/integration-tests/trialSessionChangeToInPersonProceedingJourney.test.js
  web-client/integration-tests/trialSessionEligibleCasesJourney.test.js
  web-client/integration-tests/trialSessionMigrations.test.js
  web-client/integration-tests/v1ApiJourney.test.js
  web-client/integration-tests/v2ApiJourney.test.js
  web-client/integration-tests/verifyCheckReadyForTrial.test.js
  web-client/integration-tests/viewManageDeadlinesOfCase.test.js
Labels: to staging

#2926 devex: remove reindex setup from circle workflow
  .circleci/config.yml
  package.json
  scripts/dynamo/get-reindex-flag.sh
  scripts/dynamo/update-deploy-table-after-reindex.sh
  setup-for-reindex.sh
  web-api/migration-cron-terraform/bin/deploy-app.sh
  web-api/migration-cron-terraform/bin/destroy-app.sh
  web-api/migration-cron-terraform/main/lambdas/reindex-status.js
  web-api/migration-cron-terraform/main/lambdas/reindex-status.test.js
  web-api/migration-cron-terraform/main/reindex-status.tf
  web-api/migration-cron-terraform/main/variables.tf
  web-api/switch-colors-cron-terraform/bin/destroy-app.sh
Labels: to staging

#2958 9668: Auto-Generate Deadline - Order for Amended Petition and Filing Fee (OAPF)
  shared/src/business/entities/EntityConstants.js
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.js
  web-client/integration-tests/petitionsClerkCaseDeadlineFromOrderForAmendedPetitionAndFilingFee.test.js
Labels: to staging

#2967 Dependency Updates 12/26/2022
  docs/dependency-updates.md
  package-lock.json
  package.json
  reset-dependencies.sh
Labels: to staging

#2796 Devex 1071 enzyme replacement
  docs/running-locally.md
  enzyme.config.js
  image-compare-pdfs.js
  jest-browser.config.js
  package.json
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.js
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.test.js
  shared/src/business/utilities/documentGenerators/documentServiceEmail.js
  shared/src/business/utilities/documentGenerators/documentServiceEmail.test.js
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.js
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.test.js
  shared/src/business/utilities/emailGenerator/components/EmailHeader.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.test.jsx
  shared/src/business/utilities/emailGenerator/emailTemplates/DocumentService.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/PetitionService.test.js
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.js
  shared/src/business/utilities/pdfGenerator/components/AddressLabel.test.js
  shared/src/business/utilities/pdfGenerator/components/CompressedDocketHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/DatePrintedFooter.test.js
  shared/src/business/utilities/pdfGenerator/components/DatePrintedFooter.test.jsx
  shared/src/business/utilities/pdfGenerator/components/DateServedFooter.test.js
  shared/src/business/utilities/pdfGenerator/components/DocketHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/PageMetaHeaderDocket.test.js
  shared/src/business/utilities/pdfGenerator/components/PretrialMemorandum.test.js
  shared/src/business/utilities/pdfGenerator/components/PrimaryHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/ReportsHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/ReportsMetaHeader.test.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/AddressLabelCoverSheet.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.test.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/ChangeOfAddress.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/DocketRecord.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeOfTrialJudge.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeToInPersonProceeding.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeToRemoteProceeding.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfDocketChange.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfReceiptOfPetition.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfTrialIssued.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfTrialIssuedInPerson.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/Order.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PendingReport.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PractitionerCaseList.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/ReceiptOfFiling.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/StandingPretrialOrder.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/StandingPretrialOrderForSmallCase.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.test.js
  shared/test-pdf-expected-images/Bounced_Email_Alert.pdf.1.png
  shared/test-pdf-expected-images/Document_Service_Email.pdf.1.png
  shared/test-pdf-expected-images/Petition_Service_Email.pdf.1.png
  web-client/src/ustc-ui/DateInput/DatePickerComponent.jsx
  web-client/src/ustc-ui/DateInput/DatePickerComponent.test.js
  web-client/src/ustc-ui/DateInput/DatePickerComponentHelper.js
  web-client/src/ustc-ui/PdfPreview/PdfViewer.test.js
Labels: to staging

#2955 9759 Refactor Trial Session Status
  docs/aws.md
  package.json
  shared/src/business/dto/TrialSessionInfoDto.test.ts
  shared/src/business/dto/TrialSessionInfoDto.ts
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/entities/trialSessions/TrialSession.removeCaseFromCalendar.test.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/trialSessions/closeTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsForJudgeInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsInteractor.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.getTrialSessionStatus.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFiler.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.setPretrialMemorandumFilter.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/proxies/trialSessions/getTrialSessionsForJudgeProxy.js
  types/TEntity.d.ts
  web-api/dynamo-export.js
  web-api/migration-terraform/main/lambdas/migrations/0004-set-session-status.js
  web-api/migration-terraform/main/lambdas/migrations/0004-set-session-status.test.js
  web-api/migration-terraform/main/lambdas/migrationsToRun.js
  web-api/src/applicationContext.js
  web-api/src/lambdaWrapper.test.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/swagger.json
  web-client/integration-tests/journey/docketClerkViewsNewTrialSession.js
  web-client/integration-tests/journey/docketClerkViewsStandaloneRemoteTrialSession.js
  web-client/integration-tests/journey/docketClerkViewsTrialSessionWithNote.js
  web-client/integration-tests/journey/petitionsClerkViewsATrialSessionsEligibleCases.js
  web-client/integration-tests/journey/petitionsClerkViewsATrialSessionsEligibleCasesWithManuallyAddedCase.js
  web-client/integration-tests/journey/petitionsClerkViewsNewTrialSession.js
  web-client/integration-tests/journey/petitionsClerkViewsOpenTrialSession.js
  web-client/integration-tests/petitionsClerkSetsRemoteTrialSessionCalendar.test.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.js
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.js
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.js
  web-client/src/presenter/computeds/setForHearingModalHelper.js
  web-client/src/presenter/computeds/trialSessionHeaderHelper.js
  web-client/src/presenter/computeds/trialSessionHeaderHelper.test.js
  web-client/src/views/TrialSessionDetail/TrialSessionDetailHeader.jsx
Labels: Blue/Green Migration, to staging

#2879 Devex #1063 Setup glued judges // Ability to login as judge and chambers in lower environments
  docs/operations/production-like-data-sets.md
  shared/admin-tools/user/setup-glued-judges.js
  shared/admin-tools/user/setup-test-users.js
Labels: to staging
