Repository ustaxcourt/ef-cms, pull requests merged in 2022-06, with the labels that each got.

#2230 Dependency Updates May 31
  .circleci/config.yml
  Dockerfile
  docs/team-process.md
  package-lock.json
  package.json
  patches/s3rver+3.7.1.patch
  scripts/verify-terraform-version.sh
  webpack.config.client.js
  webpack.config.client.prod.js
Labels: to staging

#2235 9507: Revert to font-awesome v5
  cypress-readonly/integration/public/health-check.spec.js
  docs/team-process.md
  package-lock.json
  package.json
Labels: to staging

#2241 9488 - ADC Filtering to Test
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedMessages.test.js
  web-client/src/presenter/sequences/gotoMessagesSequence.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/presenter/utilities/processFormattedMessages.test.js
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/TableFilters/TableFilters.jsx
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: to test

#2243 9489 - added filters component to personal messages inbox
  web-client/src/ustc-ui/TableFilters/TableFilters.jsx
  web-client/src/views/Messages/MessagesIndividualInbox.jsx
  web-client/src/views/Messages/MessagesIndividualOutbox.jsx
Labels: to test

#2246 9331 - 508 Compliant PDF
  web-client/src/pdfs/how-to-use-search.pdf
Labels: to test

#2244 9488 - ADC Filtering
  docs/additional-resources/how-we-work.md
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedMessages.test.js
  web-client/src/presenter/sequences/gotoMessagesSequence.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/presenter/utilities/processFormattedMessages.test.js
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/TableFilters/TableFilters.jsx
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: to staging

#2239 Ustc 2142 irs super user suppression handling
  docs/environments.md
  docs/operations/bounced-email-notifications.md
  docs/operations/bounced-email-notifications.png
  iam/terraform/environment-specific/main/lambda.tf
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/email/handleBounceNotificationInteractor.js
  shared/src/business/useCases/email/handleBounceNotificationInteractor.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.jsx
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.test.jsx
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.js
  shared/src/dispatchers/slack/sendSlackNotification.js
  shared/src/dispatchers/slack/sendSlackNotification.test.js
  shared/src/persistence/dynamo/notifications/getDispatchNotification.js
  shared/src/persistence/dynamo/notifications/getDispatchNotification.test.js
  shared/src/persistence/dynamo/notifications/saveDispatchNotification.js
  shared/src/persistence/dynamo/notifications/saveDispatchNotification.test.js
  shared/src/test/mockBounceNotification.js
  web-api/src/applicationContext.js
  web-api/src/email/handleBounceNotificationsLambda.js
  web-api/switch-bounce-handler-colors.js
  web-api/terraform/api/handle-bounced-service-email.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/cognito-trigger.tf
  web-api/terraform/template/lambdas/handle-bounce-notification.js
  web-api/terraform/template/lambdas/handle-bounced-service-email.js
  web-api/terraform/template/locals.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/ses.tf
  web-api/terraform/template/variables.tf
  web-client/switch-colors.sh
  webpack.config.lambda.api.js
Labels: to test

#2262 9502 - adding some artillery scripts to allow load testing in the future
  .gitignore
  artillery/messages/create-token-ids.js
  artillery/messages/extract-user-ids.js
  artillery/messages/sections.csv
  artillery/messages/sendMessagesToEveryone.js
  artillery/read-messages.yml
  package.json
Labels: to staging

#2257 9508 - UX Feedback
  web-client/src/views/WhatToExpect.jsx
Labels: to test

#2263 USTC-2142 irs super user suppression handling
  docs/environments.md
  docs/operations/bounced-email-notifications.md
  docs/operations/bounced-email-notifications.png
  iam/terraform/environment-specific/main/lambda.tf
  setup-bounce-handler-deploy-file.sh
  setup-s3-deploy-files.sh
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/email/handleBounceNotificationInteractor.js
  shared/src/business/useCases/email/handleBounceNotificationInteractor.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.jsx
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.test.jsx
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.js
  shared/src/dispatchers/slack/sendSlackNotification.js
  shared/src/dispatchers/slack/sendSlackNotification.test.js
  shared/src/persistence/dynamo/notifications/getDispatchNotification.js
  shared/src/persistence/dynamo/notifications/getDispatchNotification.test.js
  shared/src/persistence/dynamo/notifications/saveDispatchNotification.js
  shared/src/persistence/dynamo/notifications/saveDispatchNotification.test.js
  shared/src/test/mockBounceNotification.js
  web-api/src/applicationContext.js
  web-api/src/email/handleBounceNotificationsLambda.js
  web-api/switch-bounce-handler-colors.js
  web-api/terraform/api/handle-bounced-service-email.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/cognito-trigger.tf
  web-api/terraform/template/lambdas/handle-bounce-notification.js
  web-api/terraform/template/lambdas/handle-bounced-service-email.js
  web-api/terraform/template/locals.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/ses.tf
  web-api/terraform/template/variables.tf
  web-client/switch-colors.sh
  webpack.config.lambda.api.js
Labels: to staging

#2251 9508 - Update Caseless Petitioner
  web-client/src/styles/custom.scss
  web-client/src/views/Dashboards/DashboardPetitioner.jsx
  web-client/src/views/Dashboards/FilingFeeOptions.jsx
  web-client/src/views/WhatToExpect.jsx
Labels: to staging

#2266 Update references to the primary branch
  docs/running-locally.md
Labels: to staging

#2273 9503 - Estimated End Date
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/entities/trialSessions/TrialSession.test.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  web-client/integration-tests/journey/docketClerkCreatesARemoteTrialSession.js
  web-client/integration-tests/journey/docketClerkCreatesATrialSession.js
  web-client/integration-tests/journey/docketClerkCreatesAnIncompleteTrialSessionBeforeCalendaring.js
  web-client/integration-tests/journey/docketClerkUnsealsCase.js
  web-client/integration-tests/trialSessionChangeToInPersonProceedingJourney.test.js
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.js
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.test.js
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.js
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.test.js
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.js
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.test.js
  web-client/src/presenter/actions/TrialSession/updateTrialSessionAction.js
  web-client/src/presenter/actions/TrialSession/updateTrialSessionAction.test.js
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.js
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.test.js
  web-client/src/presenter/actions/getComputedFormDateFactoryAction.js
  web-client/src/presenter/computeds/formattedTrialSessions.formatSession.test.js
  web-client/src/presenter/computeds/formattedTrialSessions.js
  web-client/src/presenter/computeds/formattedTrialSessions.test.js
  web-client/src/presenter/sequences/submitTrialSessionSequence.js
  web-client/src/presenter/sequences/updateTrialSessionSequence.js
  web-client/src/presenter/sequences/validateTrialSessionSequence.js
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/DateInput/DateInput.jsx
  web-client/src/ustc-ui/DateInput/DatePickerComponent.jsx
  web-client/src/utilities/preparedDateToISOString.js
  web-client/src/utilities/preparedDateToISOString.test.js
  web-client/src/views/TrialSessionDetail/TrialSessionDetailHeader.jsx
  web-client/src/views/TrialSessionDetail/TrialSessionInformation.jsx
  web-client/src/views/TrialSessions/SessionInformationForm.jsx
  web-client/src/views/TrialSessions/TrialSessionsTable.jsx
Labels: to test

#2272 Dependency updates for week of 6/14/22 to staging
  .circleci/config.yml
  docs/frontend.md
  docs/team-process.md
  package-lock.json
  package.json
  web-client/integration-tests/docketClerkVerifiesConsolidatedCases.test.js
  web-client/src/presenter/computeds/formattedWorkQueue.js
Labels: to staging

#2275 3569: Enable Creating Docket Entries on Consolidated Cases from the Lead Case
  cypress-smoketests/integration/court-issued-documents.cy.js
  cypress-smoketests/support/pages/advanced-search.js
  cypress-smoketests/support/pages/case-detail.js
  scripts/change-chief-judge.sh
  scripts/dynamo/setup-consolidated-cases-propagate-docket-entries.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/useCaseHelper/serveDocumentAndGetPaperServicePdf.js
  shared/src/business/useCaseHelper/serveDocumentAndGetPaperServicePdf.test.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.consolidatedCases.test.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.js
  shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.js
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.js
  shared/src/business/useCases/docketEntry/editPaperFilingInteractor.js
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.js
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.js
  shared/src/business/utilities/getFormattedCaseDetail.js
  shared/src/persistence/dynamo/documents/updateDocketEntryPendingServiceStatus.js
  shared/src/proxies/documents/fileAndServeCourtIssuedDocumentProxy.js
  shared/src/test/mockCase.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/docketClerkConsolidatesCases.test.js
  web-client/integration-tests/docketClerkVerifiesConsolidatedCases.test.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryForNoticeFromDraft.js
  web-client/integration-tests/journey/docketClerkConsolidatesCases.js
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.js
  web-client/integration-tests/journey/docketClerkServesDocument.js
  web-client/integration-tests/journey/docketClerkServesDocumentOnLeadCase.js
  web-client/integration-tests/journey/docketClerkUnconsolidatesLeadCase.js
  web-client/integration-tests/journey/petitionerVerifiesConsolidatedCases.js
  web-client/integration-tests/privatePractitionerConsolidatedCasesWithStatisticsJourney.test.js
  web-client/src/getConstants.js
  web-client/src/presenter/actions/CaseConsolidation/flipConsolidatedCaseAllCheckboxAction.js
  web-client/src/presenter/actions/CaseConsolidation/flipConsolidatedCaseAllCheckboxAction.test.js
  web-client/src/presenter/actions/CaseConsolidation/setupConsolidatedCasesAction.js
  web-client/src/presenter/actions/CaseConsolidation/setupConsolidatedCasesAction.test.js
  web-client/src/presenter/actions/CaseConsolidation/updateCaseCheckboxAction.js
  web-client/src/presenter/actions/CaseConsolidation/updateCaseCheckboxAction.test.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.test.js
  web-client/src/presenter/actions/getPaperServiceSuccessMessageAction.js
  web-client/src/presenter/actions/getPaperServiceSuccessMessageAction.test.js
  web-client/src/presenter/computeds/FeatureFlags/featureFlagHelper.js
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.js
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.test.js
  web-client/src/presenter/presenter.js
  web-client/src/presenter/sequences/consolidatedCaseCheckboxAllChangeSequence.js
  web-client/src/presenter/sequences/gotoAddCourtIssuedDocketEntrySequence.js
  web-client/src/presenter/sequences/openConfirmInitiateServiceModalSequence.js
  web-client/src/presenter/sequences/updateCaseCheckboxSequence.js
  web-client/src/styles/modals.scss
  web-client/src/views/ConfirmInitiateServiceModal.jsx
  web-client/src/views/ModalDialog.jsx
Labels: to test

#2285 9512 Add Pretrial Memorandum Column to Session Copy Page
  shared/src/business/entities/DocketEntry.getServedPartiesCode.test.js
  shared/src/business/entities/DocketEntry.js
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/EntityValidationConstants.js
  shared/src/business/entities/cases/PublicDocketEntry.test.js
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.js
  shared/src/business/utilities/documentGenerators/docketRecord.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/DocketRecord.test.js
  shared/src/persistence/elasticsearch/getReconciliationReport.js
  shared/src/persistence/elasticsearch/getReconciliationReport.test.js
  web-client/src/getConstants.js
  web-client/src/presenter/actions/EditDocketRecordEntry/setDocketEntryMetaFormForEditAction.test.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.js
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaTabService.jsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.jsx
Labels: to test

#2279 Devex 950 - Simplify running smoke tests locally
  package.json
  scripts/setup-cypress-variables.sh
Labels: to staging

#2283 9502 Consolidated and Lead case indicator on Messages screens
  shared/src/business/entities/Message.js
  shared/src/business/entities/Message.test.js
  shared/src/business/useCases/processStreamRecords/processCaseEntries.js
  shared/src/business/useCases/processStreamRecords/processCaseEntries.test.js
  shared/src/business/useCases/processStreamRecords/processMessageEntries.js
  shared/src/business/useCases/processStreamRecords/processMessageEntries.test.js
  shared/src/persistence/elasticsearch/bulkIndexRecords.js
  shared/src/persistence/elasticsearch/bulkIndexRecords.test.js
  shared/src/persistence/elasticsearch/getIndexNameForRecord.js
  shared/src/persistence/elasticsearch/getIndexNameForRecord.test.js
  shared/src/persistence/elasticsearch/helpers/formatDocketEntryResult.js
  shared/src/persistence/elasticsearch/helpers/formatDocketEntryResult.test.js
  shared/src/persistence/elasticsearch/helpers/formatMessageResult.js
  shared/src/persistence/elasticsearch/helpers/formatMessageResult.test.js
  shared/src/persistence/elasticsearch/helpers/searchClauses.js
  shared/src/persistence/elasticsearch/messages/getCompletedSectionInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getCompletedSectionInboxMessages.test.js
  shared/src/persistence/elasticsearch/messages/getCompletedUserInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getCompletedUserInboxMessages.test.js
  shared/src/persistence/elasticsearch/messages/getSectionInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getSectionInboxMessages.test.js
  shared/src/persistence/elasticsearch/messages/getSectionOutboxMessages.js
  shared/src/persistence/elasticsearch/messages/getSectionOutboxMessages.test.js
  shared/src/persistence/elasticsearch/messages/getUserInboxMessages.js
  shared/src/persistence/elasticsearch/messages/getUserInboxMessages.test.js
  shared/src/persistence/elasticsearch/messages/getUserOutboxMessages.js
  shared/src/persistence/elasticsearch/messages/getUserOutboxMessages.test.js
  shared/src/persistence/elasticsearch/searchClient.js
  shared/src/persistence/elasticsearch/searchClient.test.js
  web-api/elasticsearch/efcms-case-mappings.js
  web-api/elasticsearch/efcms-message-mappings.js
  web-client/integration-tests/docketClerkConsolidatedCaseMessagesJourney.test.js
  web-client/integration-tests/journey/createNewMessageOnCase.js
  web-client/integration-tests/journey/externalUserSearchesForOrder.js
  web-client/integration-tests/journey/petitionsClerkVerifiesCompletedMessageNotInInbox.js
  web-client/integration-tests/journey/petitionsClerkVerifiesConsolidatedCaseIndicatorSentMessagesBox.js
  web-client/integration-tests/journey/petitionsClerkVerifiesLeadCaseIndicatorSentMessagesBox.js
  web-client/integration-tests/messagesJourney.test.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/presenter/utilities/processFormattedMessages.test.js
  web-client/src/styles/icons.scss
  web-client/src/styles/tables.scss
  web-client/src/views/Messages/MessagesIndividualCompleted.jsx
  web-client/src/views/Messages/MessagesIndividualInbox.jsx
  web-client/src/views/Messages/MessagesIndividualOutbox.jsx
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInProgress.jsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.jsx
  web-client/src/views/WorkQueue/IndividualWorkQueueOutbox.jsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.jsx
Labels: to staging

#2298 9501 - Fixing numberOfPages bug
  shared/src/business/useCases/addCoversheetInteractor.js
  shared/src/business/useCases/addCoversheetInteractor.test.js
Labels: to test

#2286 Increase deploy resource_class to xlarge
  .circleci/config.yml
Labels: to staging

#2295 3569: Fix mistakes
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.consolidatedCases.test.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.js
  web-client/integration-tests/docketClerkConsolidatesCases.test.js
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/docketClerkAddsAndServesDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkServesDocumentOnLeadCase.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.test.js
Labels: to test

#2309 Bug 9522: Unable to download all cases on a trial session
  package-lock.json
  package.json
Labels: to test

#2297 Add documentation about axios forbidden error on Test Users Setup
  docs/additional-resources/troubleshooting.md
Labels: to staging

#2310 Bug 9522: Unable to download all cases on a trial session
  package-lock.json
  package.json
Labels: to staging

#2296 Admin script for re-serving documents that were served within a specified timeframe
  package.json
  shared/admin-tools/email/resend-service-email-to-irs-superuser.js
  shared/src/persistence/elasticsearch/getDocketEntriesServedWithinTimeframe.js
  shared/src/persistence/elasticsearch/getDocketEntriesServedWithinTimeframe.test.js
  web-api/src/applicationContext.js
Labels: to staging

#2308 9515: Online Cited Sources
  cypress-smoketests/support/pages/advanced-search.js
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/cases/PublicDocketEntry.js
  shared/src/tools/courtIssuedEventCodes.json
  web-client/integration-tests/docketClerkServedOrderOfAmendedPetition.test.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/clearCourtIssuedDocketEntryFormValuesAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/clearCourtIssuedDocketEntryFormValuesAction.test.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.js
  web-client/src/presenter/computeds/formattedDocketEntries.js
  web-client/src/presenter/computeds/formattedDocketEntries.test.js
Labels: to test

#2284 OpEx 1069: Elastic Search Replicas
  .circleci/config.yml
  docs/testing.md
  shared/admin-tools/elasticsearch/test-elasticsearch.js
  web-api/elasticsearch/elasticsearch-index-settings.js
  web-api/elasticsearch/elasticsearch-settings.js
Labels: to test

#2316 OpEx 1069: Elastic Search Replicas
  .circleci/config.yml
  docs/testing.md
  shared/admin-tools/elasticsearch/test-elasticsearch.js
  web-api/elasticsearch/elasticsearch-index-settings.js
  web-api/elasticsearch/elasticsearch-settings.js
Labels: to staging

#2319 9523 BUG: IRS and Private Practitioners search for unassociated sealed case by docket number throws error
  web-client/integration-tests/journey/practitionerSearchesForUnassociatedSealedCase.js
  web-client/integration-tests/practitionerCaseJourney.test.js
  web-client/integration-tests/respondentCaseJourney.test.js
  web-client/src/presenter/actions/getCaseAssociationAction.js
  web-client/src/presenter/actions/showSealedToPublicCaseAction.js
  web-client/src/presenter/actions/showSealedToPublicCaseAction.test.js
  web-client/src/presenter/computeds/sealedCaseDetailHelper.js
  web-client/src/presenter/computeds/sealedCaseDetailHelper.test.js
  web-client/src/presenter/sequences/submitCaseDocketNumberSearchSequence.js
  web-client/src/presenter/sequences/submitCaseSearchSequence.js
  web-client/src/presenter/sequences/submitCaseSearchSequence.test.js
  web-client/src/presenter/state.js
  web-client/src/views/AppComponent.jsx
  web-client/src/views/CaseDetail/SealedCaseDetail.jsx
Labels: to test

#2324 9520 extra large trial sessions
  shared/src/proxies/caseNote/getUserCaseNoteForCasesProxy.js
  web-api/src/app.js
  web-api/src/caseNote/getUserCaseNoteForCasesLambda.js
Labels: bug, to test

#2325 Bug 9522 - Adding Additional Tests
  .gitignore
  package-lock.json
  package.json
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/judgeViewsTrialSessionWorkingCopy.js
  web-client/integration-tests/judgeDownloadsAllCasesFromTrialSession.test.js
  web-client/src/presenter/actions/BatchDownload/displayDownloadLinkAction.js
Labels: to staging

#2331 DevEx - Speed up Scss Compile Times
  web-client/src/app.jsx
  web-client/src/appPublic.jsx
  web-client/src/index.scss
  web-client/src/uswds-required.scss
  web-client/src/uswds.scss
Labels: to test

#2327 Devex 1051: Don't re-create the ES Cluster if it isn't needed
  .circleci/config.yml
  scripts/verify-private-elasticsearch.sh
  web-api/disable-deploying-dynamo-stream-trigger.sh
  web-api/enable-deploying-dynamo-stream-trigger.sh
  web-api/migration-cron-terraform/bin/deploy-app.sh
  web-api/migration-cron-terraform/bin/destroy-app.sh
  web-api/migration-cron-terraform/main/lambdas/reindex-status.js
  web-api/migration-cron-terraform/main/lambdas/reindex-status.test.js
  web-api/migration-cron-terraform/main/reindex-status.tf
  web-api/migration-cron-terraform/main/variables.tf
  web-api/setup-elasticsearch-index.sh
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/main.tf
  web-api/terraform/template/outputs.tf
  web-api/terraform/template/variables.tf
Labels: to staging

#2333 9515 ocs
  cypress-smoketests/support/pages/advanced-search.js
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/cases/PublicDocketEntry.js
  shared/src/tools/courtIssuedEventCodes.json
  web-client/integration-tests/docketClerkAddsDocketEntryWithUnservableEventCode.test.js
  web-client/integration-tests/docketClerkServedOrderOfAmendedPetition.test.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntries.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromDraft.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrderOfDismissal.js
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrderWithDate.js
  web-client/integration-tests/journey/docketClerkAddsMiscellaneousPaperFiling.js
  web-client/integration-tests/journey/docketClerkAddsOSTDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkAddsOpinionToDocketEntry.js
  web-client/integration-tests/journey/docketClerkAddsOrderDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkAddsPaperFiledDocketEntryAndSavesForLater.js
  web-client/integration-tests/journey/docketClerkAddsPaperFiledPendingDocketEntryAndSavesForLater.js
  web-client/integration-tests/journey/docketClerkAddsPaperFiledPendingDocketEntryAndServes.js
  web-client/integration-tests/journey/docketClerkAddsPretrialMemorandumToCase.js
  web-client/integration-tests/journey/docketClerkAddsStipulatedDecisionDocketEntryFromOrder.js
  web-client/integration-tests/journey/docketClerkAddsTrackedDocketEntry.js
  web-client/integration-tests/journey/docketClerkAddsTranscriptDocketEntryFromOrder.js
  web-client/integration-tests/journey/petitionsClerkAddsDocketEntryFromOrder.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/clearCourtIssuedDocketEntryFormValuesAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/clearCourtIssuedDocketEntryFormValuesAction.test.js
  web-client/src/presenter/actions/DocketEntry/getDocketEntryAlertSuccessAction.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.js
  web-client/src/presenter/computeds/formattedDocketEntries.js
  web-client/src/presenter/computeds/formattedDocketEntries.test.js
Labels: to staging

#2328 9517: Text Additions to Support Online Cited Sources
  web-client/src/views/Public/SearchBoilerplateText.jsx
  web-client/src/views/Public/TodaysOpinions.jsx
Labels: to staging

#2323 9520: extra large trial sessions
  shared/src/proxies/caseNote/getUserCaseNoteForCasesProxy.js
  web-api/src/app.js
  web-api/src/caseNote/getUserCaseNoteForCasesLambda.js
Labels: bug, to staging

#2307 Devex 950 cleaner scripts
  package.json
  scripts/run-cypress.sh
  scripts/setup-cypress-variables.sh
Labels: to staging
