Repository ustaxcourt/ef-cms, pull requests merged in 2022-05, with the labels that each got.

#2135 9492: Bugfix related to message attachments
  web-client/integration-tests/journey/createNewMessageOnCase.js
  web-client/src/presenter/computeds/messageModalHelper.js
  web-client/src/presenter/computeds/messageModalHelper.test.js
Labels: bugfix

#2137 9492: Bugfix related to message attachments
  cypress-integration/integration/messages.spec.js
  cypress-integration/support/pages/case-detail.js
  cypress-integration/support/pages/document-qc.js
  web-client/integration-tests/docketClerkExternalDocumentQCWorkflow.test.js
  web-client/integration-tests/journey/createNewMessageOnCase.js
  web-client/src/presenter/computeds/messageModalHelper.js
  web-client/src/presenter/sequences/completeDocketEntryQCAndSendMessageSequence.js
  web-client/src/presenter/sequences/createMessageSequence.js
Labels: bugfix

#2146 9356 - Clinic letter on case for trial
  .gitignore
  package.json
  shared/src/business/entities/cases/Case.isPractitioner.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.js
  shared/src/business/useCases/trialSessions/setNoticesForCalendaredTrialSessionInteractor.js
  shared/src/business/useCases/trialSessions/setNoticesForCalendaredTrialSessionInteractor.standingPretrial.test.js
  shared/src/business/useCases/trialSessions/setNoticesForCalendaredTrialSessionInteractor.test.js
  web-api/storage/scripts/seedLocalDatabase.js
  web-client/integration-tests/journey/practitionerCreatesNewCase.js
  web-client/integration-tests/journey/userVerifiesLengthOfDocketEntry.js
  web-client/integration-tests/petitionsClerkFilesPetitionWithClinicLetterAttached.test.js
Labels: to staging

#2147 9483 - Change Chief Judge
  scripts/change-chief-judge.sh
  scripts/dynamo/setup-chief-judge-name-flag.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.js
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.test.js
  shared/src/business/useCases/users/getJudgeForUserChambersInteractor.js
  shared/src/business/useCases/users/getJudgeForUserChambersInteractor.test.js
  shared/src/proxies/getChiefJudgeNameForSigningProxy.js
  shared/src/sharedAppContext.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/changeChiefJudgeNameJourney.test.js
  web-client/integration-tests/docketClerkOpinionAdvancedSearch.test.js
  web-client/integration-tests/helpers.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.test.js
Labels: to test

#2108 Bug 9486 consolidated case list
  web-client/integration-tests/docketClerkVerifiesConsolidatedCases.test.js
  web-client/integration-tests/journey/docketClerkConsolidatesCaseThatCannotBeConsolidated.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedCases.js
  web-client/src/presenter/sequences/addCaseToTrialSessionSequence.js
  web-client/src/presenter/sequences/blockCaseFromTrialSequence.js
  web-client/src/presenter/sequences/prioritizeCaseSequence.js
  web-client/src/presenter/sequences/removeCaseFromTrialSequence.js
  web-client/src/presenter/sequences/sealCaseSequence.js
  web-client/src/presenter/sequences/setForHearingSequence.js
  web-client/src/presenter/sequences/submitUpdateCaseModalSequence.js
  web-client/src/presenter/sequences/unblockCaseFromTrialSequence.js
  web-client/src/presenter/sequences/unprioritizeCaseSequence.js
  web-client/src/presenter/sequences/unsealCaseSequence.js
Labels: bugfix, to staging

#2158 Devex refactor interactor calling interactor to test
  shared/src/business/entities/User.js
  shared/src/business/useCaseHelper/getJudgeInSectionHelper.js
  shared/src/business/useCaseHelper/getJudgeInSectionHelper.test.js
  shared/src/business/useCases/caseNote/deleteCaseNoteInteractor.js
  shared/src/business/useCases/caseNote/deleteUserCaseNoteInteractor.js
  shared/src/business/useCases/caseNote/deleteUserCaseNoteInteractor.test.js
  shared/src/business/useCases/caseNote/getUserCaseNoteForCasesInteractor.js
  shared/src/business/useCases/caseNote/getUserCaseNoteForCasesInteractor.test.js
  shared/src/business/useCases/caseNote/getUserCaseNoteInteractor.js
  shared/src/business/useCases/caseNote/getUserCaseNoteInteractor.test.js
  shared/src/business/useCases/caseNote/updateUserCaseNoteInteractor.js
  shared/src/business/useCases/caseNote/updateUserCaseNoteInteractor.test.js
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.test.js
  shared/src/business/useCases/trialSessions/getTrialSessionWorkingCopyInteractor.js
  shared/src/business/useCases/trialSessions/getTrialSessionWorkingCopyInteractor.test.js
  shared/src/business/useCases/users/getJudgeForUserChambersInteractor.js
  shared/src/business/useCases/users/getJudgeForUserChambersInteractor.test.js
  shared/src/business/useCases/users/getJudgeInSectionInteractor.js
  shared/src/business/useCases/users/getJudgeInSectionInteractor.test.js
  shared/src/proxies/users/getJudgeInSectionProxy.js
  web-api/src/app.js
  web-api/src/applicationContext.js
  web-api/src/users/getJudgeInSectionLambda.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/getJudgeForCurrentUserAction.js
  web-client/src/presenter/actions/getJudgeForCurrentUserAction.test.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.test.js
Labels: to test

#2150 9482: Addition of Document No. to Caption on Cover Sheets to staging
  shared/src/business/useCases/addCoversheetInteractor.js
  shared/src/business/useCases/addCoversheetInteractor.test.js
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.js
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.test.js
  shared/src/business/utilities/documentGenerators/coverSheet.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.test.js
  shared/test-pdf-expected-images/CourtIssuedDocumentCoverSheet.pdf.1.png
  shared/test-pdf-expected-images/CoverSheet.pdf.1.png
Labels: to staging

#2154 Cypress video compression experiment
  cypress-smoketests.json
Labels: to test

#2160 bugfix - adding fallbacks onto the entity for userNotes and calendaredCases
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/entities/trialSessions/TrialSession.test.js
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.js
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.test.js
Labels: to test

#2161 Dependency Updates for Week of May 2nd
  .circleci/config.yml
  Dockerfile
  docs/additional-resources/blue-green-migration.md
  docs/team-process.md
  jest-browser.config.js
  jest.config.js
  package-lock.json
  package.json
  shared/jest.config.js
  web-client/JsdomWithTextEncoderEnvironment.js
  web-client/jest-integration.config.js
  web-client/jest-unit.config.js
  web-client/jest.config.js
Labels: to staging

#2162 Health check beautification
  web-client/src/views/Health/HealthCheck.jsx
Labels: to staging

#2183 9490 - added unit test coverage for setSectionMessagesSortAction
  web-client/src/presenter/actions/setSectionMessagesSortAction.js
  web-client/src/presenter/actions/setSectionMessagesSortAction.test.js
Labels: to test

#2180 Docs consolidation
  docs/team-process.md
Labels: to test

#2181 Dependency updates week of 5/9
  cypress-readonly/integration/public/health-check.spec.js
  docs/team-process.md
  docs/teamcharter.md
  package-lock.json
  package.json
Labels: to staging

#2187 Docs Update
  docs/team-process.md
Labels: to staging

#2145 9483 - Chief Judge Transition
  scripts/change-chief-judge.sh
  scripts/dynamo/setup-chief-judge-name-flag.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.js
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.test.js
  shared/src/proxies/getChiefJudgeNameForSigningProxy.js
  shared/src/sharedAppContext.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/changeChiefJudgeNameJourney.test.js
  web-client/integration-tests/helpers.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.js
  web-client/src/presenter/actions/setSignatureNameForPdfSigningAction.test.js
Labels: to staging

#2205 9490 UX feedback
  web-client/src/app.jsx
  web-client/src/ustc-ui/SortableColumnHeaderButton/SortableColumnHeaderButton.jsx
Labels: to test

#2199 Devex 1064 - refactor formatted messages
  web-client/src/presenter/computeds/formattedCaseMessages.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedMessages.test.js
  web-client/src/presenter/computeds/recentMessagesHelper.js
  web-client/src/presenter/computeds/showSortableHeaders.js
  web-client/src/presenter/computeds/showSortableHeaders.test.js
  web-client/src/presenter/state.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/presenter/utilities/processFormattedMessages.test.js
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: to test

#2195 DevEx 1055: Tabs Icons are Passed in as Props
  web-client/src/ustc-ui/Tabs/Tabs.jsx
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.jsx
  web-client/src/views/PetitionQcScanBatchPreviewer.jsx
  web-client/src/views/ScanBatchPreviewer.jsx
Labels: to staging

#2219 9490 - speed up renders using memo
  scripts/create-messages.sh
  web-client/src/presenter/actions/resetCacheKeyAction.js
  web-client/src/presenter/actions/resetCacheKeyAction.test.js
  web-client/src/presenter/computeds/formattedMessages.js
  web-client/src/presenter/computeds/formattedWorkQueue.js
  web-client/src/presenter/sequences/gotoMessagesSequence.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/styles/tables.scss
  web-client/src/ustc-ui/SortableColumnHeaderButton/SortableColumnHeaderButton.jsx
  web-client/src/views/Messages/MessagesSectionCompleted.jsx
  web-client/src/views/Messages/MessagesSectionInbox.jsx
  web-client/src/views/Messages/MessagesSectionOutbox.jsx
Labels: to test

#2209 9506 - Display Index on other Notice Documents
  shared/src/business/useCaseHelper/service/createChangeItems.js
  shared/src/business/useCaseHelper/service/createChangeItems.test.js
  shared/src/business/useCases/updateContactInteractor.js
  shared/src/business/useCases/updateContactInteractor.test.js
Labels: to staging

#2213 Dependency updates puppeteer
  docs/team-process.md
  package-lock.json
  package.json
  shared/src/business/utilities/getChromiumBrowser.js
  shared/src/business/utilities/getChromiumBrowser.test.js
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  webpack.config.lambda.api.js
  webpack.config.lambda.js
Labels: to staging

#2227 Back merge staging into test
  docs/team-process.md
  package-lock.json
  package.json
  shared/src/business/useCaseHelper/trialSessions/serveGeneratedNoticesOnCase.js
  shared/src/business/useCases/trialSessions/addCaseToTrialSessionInteractor.test.js
  shared/src/business/useCases/trialSessions/setForHearingInteractor.test.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.js
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.js
  shared/src/business/utilities/getChromiumBrowser.js
  shared/src/business/utilities/getChromiumBrowser.test.js
  shared/src/test/mockTrial.js
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-client/integration-tests/adcClerkViewsSectionMessagesJourney.test.js
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/createNewMessageOnCase.js
  web-client/integration-tests/journey/docketClerkCreatesARemoteTrialSession.js
  web-client/integration-tests/journey/getUserMessageCount.js
  web-client/integration-tests/trialSessionChangeToInPersonProceedingJourney.test.js
  web-client/src/presenter/actions/setDefaultTableSortAction.js
  webpack.config.lambda.api.js
  webpack.config.lambda.js
Labels: to test
