Repository ustaxcourt/ef-cms, pull requests merged in 2022-10, with the labels that each got.

#2616 9610 hybrid case type counts to test
  web-client/src/presenter/computeds/trialSessionDetailsHelper.js
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
  web-client/src/views/TrialSessionDetail/TrialSessionDetail.jsx
Labels: to test

#2619 9633 BUG: Petitions Clerks and Docket Clerks receive validation error if they use the Calculate links when entering Statistics on a Petition
  cypress-integration/support/pages/create-paper-petition.js
  web-client/src/ustc-ui/DollarsInput/DollarsInput.jsx
Labels: to staging

#2614 9602: Dedicated Docket View - Orders to staging
  shared/src/business/entities/EntityConstants.js
  web-client/integration-tests-public/journey/unauthedUserViewsFilteredDocketRecord.js
  web-client/integration-tests-public/unauthedUserSearchesForCase.test.js
  web-client/integration-tests/docketClerkServesCourtIssuedDocumentForPaperCase.test.js
  web-client/integration-tests/docketRecordFilterJourney.test.js
  web-client/integration-tests/journey/docketClerkServesOrderWithPaperService.js
  web-client/src/applicationContextPublic.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.js
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.js
  web-client/src/presenter/computeds/formattedDocketEntries.js
  web-client/src/presenter/computeds/formattedDocketEntries.test.js
  web-client/src/presenter/state-public.js
  web-client/src/views/Public/PublicDocketRecordHeader.jsx
Labels: to staging

#2633 9610-fix for bottom border of hybrid trial session filter when not a …
  web-client/src/views/TrialSessionDetail/TrialSessionDetail.jsx
Labels: to test

#2640 9493 make endpoint async + update tests
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.test.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.ts
  web-api/src/app.js
  web-client/integration-tests/docketRecordJourney.test.js
  web-client/src/presenter/sequences/servePaperFiledDocumentSequence.js
Labels: to test

#2642 9511 printable trial session copy
  shared/src/business/utilities/htmlGenerator/icons.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.jsx
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.2.png
Labels: to test

#2627 Devex 1071 enzyme replacement to test
  Dockerfile-pdf-testing
  image-compare-pdfs.js
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.js
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.test.js
  shared/src/business/utilities/documentGenerators/documentServiceEmail.js
  shared/src/business/utilities/documentGenerators/documentServiceEmail.test.js
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.js
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.test.js
  shared/src/business/utilities/emailGenerator/components/EmailHeader.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/BouncedEmailAlert.test.jsx
  shared/src/business/utilities/emailGenerator/emailTemplates/DocumentService.test.js
  shared/src/business/utilities/emailGenerator/emailTemplates/PetitionService.test.js
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.js
  shared/src/business/utilities/pdfGenerator/components/AddressLabel.test.js
  shared/src/business/utilities/pdfGenerator/components/CompressedDocketHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/DatePrintedFooter.test.js
  shared/src/business/utilities/pdfGenerator/components/DatePrintedFooter.test.jsx
  shared/src/business/utilities/pdfGenerator/components/DateServedFooter.test.js
  shared/src/business/utilities/pdfGenerator/components/DocketHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/PageMetaHeaderDocket.test.js
  shared/src/business/utilities/pdfGenerator/components/PretrialMemorandum.test.js
  shared/src/business/utilities/pdfGenerator/components/PrimaryHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/ReportsHeader.test.js
  shared/src/business/utilities/pdfGenerator/components/ReportsMetaHeader.test.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/AddressLabelCoverSheet.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.test.jsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/ChangeOfAddress.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/DocketRecord.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeOfTrialJudge.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeToInPersonProceeding.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeToRemoteProceeding.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfDocketChange.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfReceiptOfPetition.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfTrialIssued.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfTrialIssuedInPerson.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/Order.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PendingReport.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PractitionerCaseList.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/ReceiptOfFiling.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/StandingPretrialOrder.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/StandingPretrialOrderForSmallCase.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.test.js
  shared/test-pdf-expected-images/Bounced_Email_Alert.pdf.1.png
  shared/test-pdf-expected-images/Document_Service_Email.pdf.1.png
  shared/test-pdf-expected-images/Petition_Service_Email.pdf.1.png
  update-pdf-images.sh
  web-client/src/ustc-ui/DateInput/DatePickerComponent.jsx
  web-client/src/ustc-ui/DateInput/DatePickerComponent.test.js
  web-client/src/ustc-ui/DateInput/DatePickerComponentHelper.js
  web-client/src/ustc-ui/PdfPreview/PdfViewer.test.js
Labels: to test

#2658 9600: Practitioner: Add Consolidated Card to Case Information Screen
  shared/src/authorization/authorizationClientService.js
  web-client/src/presenter/computeds/caseDetailHelper.showConsolidatedCasesCard.test.js
Labels: to test

#2651 9627: Adding a STIN from the Review Petition page creates a Docket Index number for the STIN
  shared/src/business/entities/cases/Case.addDocketEntry.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCaseHelper/initialFilingDocuments/updateInitialFilingDocuments.js
  shared/src/business/useCaseHelper/initialFilingDocuments/updateInitialFilingDocuments.test.js
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.js
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.test.js
Labels: bugfix, to test

#2617 Handle broken pdf-testing builds
  Dockerfile-pdf-testing
  docs/team-process.md
Labels: to staging

#2622 Integration Test Fix
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/docketClerkServesOrderWithPaperService.js
Labels: to staging

#2565 3572 eligible cases grouping
  shared/src/business/entities/cases/EligibleCase.js
  shared/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.test.ts
  shared/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.ts
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.test.js
  web-client/integration-tests/journey/petitionsClerkViewsAHybridTrialSessionsFilteredEligibleCases.js
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.js
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.js
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.test.js
  web-client/src/presenter/state.js
  web-client/src/presenter/utilities/processFormattedMessages.js
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
Labels: to staging

#2639 Decision to fork and maintain Cerebral as State Management Tool
  docs/architecture/decisions/0007-react-state-mangement.md
Labels: to staging

#2626 9633: Add test to cover commas added to DollarsInput
  cypress-integration/support/pages/create-paper-petition.js
  web-client/src/views/StartCaseInternal/StatisticsForm.jsx
Labels: to staging

#2660 9607: Add clerk filter to 'In Progress' tab
  web-client/src/presenter/computeds/formattedWorkQueue.js
  web-client/src/presenter/computeds/formattedWorkQueue.test.js
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.jsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.jsx
Labels: to test

#2612 9610 hybrid case type counts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.js
  web-client/src/presenter/computeds/trialSessionDetailsHelper.test.js
  web-client/src/styles/overrides.scss
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
  web-client/src/views/TrialSessionDetail/TrialSessionDetail.jsx
Labels: to staging

#2659 USTC 2631: Non-Attorney Practitioner Stats
  shared/admin-tools/elasticsearch/non-attorney-practitioners.js
Labels: to staging

#2610 9593 sort trial session
  esbuildHelper.mjs
  package.json
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.test.js
  web-api/dynamo-export.js
  web-client/src/applicationContext.js
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.js
  web-client/src/presenter/sequences/openCaseInventoryReportModalSequence.js
  web-client/src/styles/tables.scss
  web-client/src/views/TrialSessionDetail/AllCases.jsx
  web-client/src/views/TrialSessionDetail/EligibleCases.jsx
  web-client/src/views/TrialSessionDetail/InactiveCases.jsx
  web-client/src/views/TrialSessionDetail/OpenCases.jsx
Labels: to staging

#2661 9493 story to test
  Dockerfile-pdf-testing
  cypress-integration/support/pages/create-paper-petition.js
  docs/architecture/decisions/0007-react-state-mangement.md
  docs/team-process.md
  shared/src/business/useCaseHelper/initialFilingDocuments/updateInitialFilingDocuments.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.jsx
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  web-client/integration-tests/docketRecordJourney.test.js
  web-client/src/presenter/actions/CaseConsolidation/shouldSetupConsolidatedCasesAction.js
  web-client/src/presenter/actions/CaseConsolidation/shouldSetupConsolidatedCasesAction.test.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/submitCourtIssuedDocketEntryAction.js
  web-client/src/presenter/actions/CourtIssuedDocketEntry/submitCourtIssuedDocketEntryAction.test.js
  web-client/src/presenter/actions/DocketEntry/submitEditPaperFilingAction.js
  web-client/src/presenter/actions/DocketEntry/submitEditPaperFilingAction.test.js
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.js
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.test.js
  web-client/src/presenter/computeds/trialSessionDetailsHelper.js
  web-client/src/presenter/computeds/trialSessionDetailsHelper.test.js
  web-client/src/presenter/sequences/openConfirmInitiateServiceModalSequence.js
  web-client/src/presenter/sequences/openConfirmPaperServiceModalSequence.js
  web-client/src/presenter/sequences/openConfirmServeCourtIssuedDocumentSequence.js
  web-client/src/presenter/sequences/openConfirmServePaperFiledDocumentSequence.js
  web-client/src/presenter/sequences/saveCourtIssuedDocketEntrySequence.js
  web-client/src/presenter/sequences/submitCourtIssuedDocketEntrySequence.js
  web-client/src/presenter/sequences/submitPaperFilingSequence.js
  web-client/src/views/StartCaseInternal/StatisticsForm.jsx
Labels: to test

#2662 9627 stin docket record index
  shared/src/business/entities/cases/Case.addDocketEntry.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCaseHelper/initialFilingDocuments/updateInitialFilingDocuments.js
  shared/src/business/useCaseHelper/initialFilingDocuments/updateInitialFilingDocuments.test.js
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.js
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.test.js
Labels: to staging

#2668 9600 (and 9569) - Address UX Feedback #2
  web-client/src/styles/custom.scss
  web-client/src/views/CaseDetail/CaseInformation/ConsolidatedCases.jsx
Labels: to test

#2678 9587-fix styling issues for documentation table
  web-client/src/styles/tables.scss
  web-client/src/views/Practitioners/PractitionerDocumentation.jsx
Labels: to test

#2646 Dependency Updates Week of 10/10/2022
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#2686 9607: restrict new assignment filters to docket users only
  web-client/src/presenter/computeds/workQueueHelper.js
  web-client/src/styles/custom.scss
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.jsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.jsx
Labels: to test

#2468 Opex 1075 color switch gate
  .circleci/config.yml
  package.json
  web-api/switch-colors-cron-terraform/bin/create-bucket.sh
  web-api/switch-colors-cron-terraform/bin/create-dynamodb.sh
  web-api/switch-colors-cron-terraform/bin/deploy-app.sh
  web-api/switch-colors-cron-terraform/bin/destroy-app.sh
  web-api/switch-colors-cron-terraform/bin/policy.json
  web-api/switch-colors-cron-terraform/main/lambdas/switch-colors.js
  web-api/switch-colors-cron-terraform/main/main.tf
  web-api/switch-colors-cron-terraform/main/switch-colors.tf
  web-api/switch-colors-cron-terraform/main/variables.tf
  webpack.config.lambda.switch-colors-cron.js
Labels: to staging

#2710 9587 practitioner detail tabs to test
  shared/src/business/useCases/practitioners/getPractitionerDocumentDownloadUrlInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionerDocumentDownloadUrlInteractor.ts
  shared/src/persistence/dynamo/practitioners/getPractitionerDocumentByFileId.ts
  shared/src/persistence/s3/getDownloadPolicyUrl.js
  shared/src/proxies/getPractitionerDocumentDownloadUrlProxy.js
  web-api/src/app.js
  web-api/src/getPersistenceGateway.js
  web-api/src/practitioners/getPractitionerDocumentDownloadUrlLambda.js
  web-client/src/presenter/actions/openPractitionerDocumentDownloadUrlAction.js
  web-client/src/presenter/actions/openPractitionerDocumentDownloadUrlAction.test.js
  web-client/src/views/Practitioners/PractitionerDocumentation.jsx
Labels: to test

#2696 Devex 1100 swagger doc housekeeping
  web-api/src/swagger/swaggerLambda.js
  web-api/swagger.json
Labels: to staging

#2694 Dependency updates - week of 10/17/22
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#2711 9678: Use prod context to get the proper environment variable values
  .circleci/config.yml
Labels: to staging

#2718 9587-practitioner-detail-tabs
  shared/src/persistence/s3/getDownloadPolicyUrl.js
Labels: to test

#2721 9587 - fix an integration test
  web-client/src/presenter/actions/openCaseDocumentDownloadUrlAction.js
  web-client/src/presenter/actions/openCaseDocumentDownloadUrlAction.test.js
  web-client/src/presenter/actions/openPractitionerDocumentDownloadUrlAction.js
  web-client/src/presenter/actions/openPractitionerDocumentDownloadUrlAction.test.js
Labels: to test

#2719 Dependency Updates for Week of 10/24/2022
  docs/dependency-updates.md
  package-lock.json
  package.json
Labels: to staging

#2704 Bug 9660
  shared/src/business/useCaseHelper/consolidatedCases/formatPublicCase.test.ts
  shared/src/business/useCaseHelper/consolidatedCases/formatPublicCase.ts
  shared/src/business/useCases/addPetitionerToCaseInteractor.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.ts
  shared/src/business/useCases/public/getPublicCaseInteractor.test.ts
  shared/src/business/useCases/public/getPublicCaseInteractor.ts
  shared/src/test/mockCase.js
  shared/src/test/mockUsers.js
Labels: to staging

#2670 9600 Petitioner: Add Consolidated Card to Case Information Screen
  shared/src/authorization/authorizationClientService.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/caseDetailHelper.js
  web-client/src/presenter/computeds/caseDetailHelper.showConsolidatedCasesCard.test.js
  web-client/src/presenter/computeds/caseDetailHelper.showSealedCaseView.test.js
  web-client/src/styles/custom.scss
  web-client/src/views/CaseDetail/CaseInformation/ConsolidatedCases.jsx
  web-client/src/views/CaseDetail/CaseInformationExternal.jsx
Labels: to staging

#2669 9596 Petitioner: Add Consolidated Card to Case Information Screen
  web-client/src/presenter/computeds/caseDetailHelper.showConsolidatedCasesCard.test.js
Labels: to staging

#2736 9679 - Prevent Duplicate Work Items
  shared/src/business/entities/WorkItem.js
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.ts
  shared/src/errors/errors.js
  web-api/src/getPersistenceGateway.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/helpers.js
  web-client/integration-tests/journey/docketClerkCompletesDocketEntryQcAndSendsMessage.js
  web-client/integration-tests/journey/docketClerkTriesToCompleteSameEntry.js
  web-client/integration-tests/signAndServeStipulatedDecision.test.js
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/getConstants.js
  web-client/src/presenter/actions/CourtIssuedOrder/appendFormAndOverwriteOrderFileAction.test.js
  web-client/src/presenter/actions/confirmWorkItemAlreadyCompleteAction.js
  web-client/src/presenter/actions/confirmWorkItemAlreadyCompleteAction.test.js
  web-client/src/presenter/actions/getCompleteTrialSessionAlertSuccessAction.js
  web-client/src/presenter/actions/isWorkItemAlreadyCompletedAction.js
  web-client/src/presenter/actions/navigateToDocketQcAction.js
  web-client/src/presenter/actions/setFromPageAction.js
  web-client/src/presenter/actions/startDelayedLogoutAction.test.js
  web-client/src/presenter/presenter.js
  web-client/src/presenter/sequences/completeDocketEntryQCSequence.js
  web-client/src/presenter/sequences/confirmWorkItemAlreadyCompleteSequence.js
  web-client/src/presenter/sequences/gotoCaseDetailSequence.js
  web-client/src/presenter/sequences/gotoCompleteDocketEntryQCSequence.js
  web-client/src/presenter/sequences/gotoDocketEntryQcSequence.js
  web-client/src/presenter/sequences/openCompleteAndSendMessageModalSequence.js
  web-client/src/presenter/sequences/updateTrialSessionCompleteSequence.js
  web-client/src/router.js
  web-client/src/views/DocketEntryQc.jsx
  web-client/src/views/DocketEntryQc/WorkItemAlreadyCompletedModal.jsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.jsx
  web-client/src/views/ScanBatchPreviewer/ScanBatchModals.jsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.jsx
Labels: to test
