Repository ustaxcourt/ef-cms, pull requests merged in 2023-04, with the labels that each got.

#3403 9865 Pamphlet Host Page: to test
  cypress-integration/integration/date-picker-rejects-invalid-years.cy.js
  docs/dependency-updates.md
  esbuild.config.mjs
  esbuild.public.config.mjs
  esbuildHelper.mjs
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/public/getOpinionPamphletsInteractor.test.ts
  shared/src/business/useCases/public/getOpinionPamphletsInteractor.ts
  shared/src/persistence/elasticsearch/advancedDocumentSearch.test.ts
  shared/src/persistence/elasticsearch/advancedDocumentSearch.ts
  shared/src/proxies/public/getOpinionPamphletsProxy.ts
  web-api/src/app-public.js
  web-api/src/getUseCases.ts
  web-api/src/public-api/getOpinionPamphletsLambda.js
  web-api/swagger.json
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/Public/getOpinionPamphletsAction.test.ts
  web-client/src/presenter/actions/Public/getOpinionPamphletsAction.ts
  web-client/src/presenter/actions/Public/setOpinionPamphletsAction.test.ts
  web-client/src/presenter/actions/Public/setOpinionPamphletsAction.ts
  web-client/src/presenter/actions/shouldSaveToConsolidatedGroupAction.test.ts
  web-client/src/presenter/actions/shouldSaveToConsolidatedGroupAction.ts
  web-client/src/presenter/computeds/Public/opinionPamphletsHelper.test.ts
  web-client/src/presenter/computeds/Public/opinionPamphletsHelper.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryHelper.test.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/Public/gotoOpinionPamphletsSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/routerPublic.ts
  web-client/src/styles/tables.scss
  web-client/src/views/AppComponentPublic.tsx
  web-client/src/views/Public/OpinionPamphlets.tsx
Labels: to test

#3402 USTC-3401: Practitioner Stats
  .gitignore
  shared/admin-tools/elasticsearch/practitioner-stats.ts
Labels: to staging

#3410 9865 feedback
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/Public/opinionPamphletsHelper.test.ts
  web-client/src/presenter/computeds/Public/opinionPamphletsHelper.ts
  web-client/src/views/Public/OpinionPamphlets.tsx
Labels: to test

#3411 Added PID tracking to be able to kill dynamo after closing the api. I believe this was accidentally removed.
  run-local.sh
Labels: to staging

#3351 Like Console.log()... but Pink!
  shared/src/tools/pinkLog.ts
Labels: to staging

#3421 Dep updates 2023 04 06
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#3436 9987 to test (again)
  docs/additional-resources/README.md
  shared/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  shared/src/persistence/elasticsearch/getCaseInventoryReport.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesForSealedCaseByName.ts
  web-client/integration-tests-public/unauthedUserSearchesForSealedCase.test.ts
Labels: to test

#3426 Devex 1074: Reduce the number of unnecessary changes being deployed by Terraform
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/s3.tf
  web-client/terraform/common/frontend-public-www-redirect.tf
  web-client/terraform/ui/frontend-public.tf
  web-client/terraform/ui/frontend.tf
Labels: to staging

#3442 9968 New Docket Entry: NOTT - 30 Day Notice of Trial
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  shared/src/tools/courtIssuedEventCodes.json
  web-client/src/presenter/actions/getComputedFormDateFactoryAction.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.test.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.ts
  web-client/src/presenter/sequences/gotoEditDocketEntryMetaSequence.ts
Labels: to staging

#3446 9987: Filter `Closed - Dismissed` From Case Inventory Report
  docs/additional-resources/README.md
  shared/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  shared/src/persistence/elasticsearch/getCaseInventoryReport.ts
Labels: to staging

#3440 Enforce Reducing Typescript Errors
  .github/workflows/typescript-error-check.yml
  scripts/compareTypescriptErrors.ts
  scripts/jest-scripts.config.js
  tsconfig.json
  web-client/integration-tests/journey/createNewMessageOnCase.ts
Labels: to staging

#3459 9989 + 10000: New Trial Session Type - Hybrid S
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.test.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
  web-client/integration-tests/trialSessionHybridEligibleCasesJourney.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.test.ts
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.ts
Labels: to test

#3462 Devex 1163 - [Design Debt] Update Mid-Table Date Header Row on Trial Session Page
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#3469 9989 & 10000: New Trial Session Type - Hybrid S
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.test.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
  web-client/integration-tests/trialSessionHybridEligibleCasesJourney.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.test.ts
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.ts
Labels: to staging

#3472 9864: Redaction Acknowledgment for E-Filed Documents
  cypress/cypress-integration/integration/file-an-answer.cy.ts
  scripts/dynamo/setup-redaction-acknowledgement-enabled-flag.sh
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/DocketEntry.validate.test.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/EntityValidationConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/documentTitleJourney.test.ts
  web-client/integration-tests/journey/externalUserFilesDocumentForOwnedCase.ts
  web-client/integration-tests/journey/petitionerFilesADocumentForCase.ts
  web-client/integration-tests/journey/petitionerFilesANonstardardDDocumentForCase.ts
  web-client/integration-tests/journey/petitionerFilesApplicationToTakeDeposition.ts
  web-client/integration-tests/journey/petitionerFilesDocumentForCase.ts
  web-client/integration-tests/journey/practitionerFilesDocumentForOwnedCase.ts
  web-client/integration-tests/journey/respondentAddsAnswer.ts
  web-client/integration-tests/journey/respondentAddsMotionWithBrief.ts
  web-client/integration-tests/journey/respondentAddsStipulatedDecision.ts
  web-client/integration-tests/journey/respondentFilesDocumentForAssociatedCase.ts
  web-client/integration-tests/journey/respondentFilesFirstIRSDocumentOnCase.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.test.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/sequences/gotoFileDocumentSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/buttons.scss
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/Focus/Focus.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
  web-client/src/views/WarningNotification.tsx
Labels: to staging, Manual Deploy Step(s) Required

#3492 9994 Only assign work items if they are not completed.
  shared/src/business/entities/Correspondence.ts
  shared/src/business/entities/PrivatePractitioner.ts
  shared/src/business/entities/WorkItem.test.ts
  shared/src/business/entities/WorkItem.ts
  shared/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.test.ts
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
  shared/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.ts
  shared/src/business/useCaseHelper/service/createChangeItems.test.ts
  shared/src/business/useCaseHelper/service/createChangeItems.ts
  shared/src/business/useCaseHelper/workItems/updateAssociatedJudgeOnWorkItems.test.ts
  shared/src/business/useCaseHelper/workItems/updateAssociatedJudgeOnWorkItems.ts
  shared/src/business/useCaseHelper/workItems/updateCaseStatusOnWorkItems.test.ts
  shared/src/business/useCaseHelper/workItems/updateCaseStatusOnWorkItems.ts
  shared/src/business/useCaseHelper/workItems/updateCaseTitleOnWorkItems.test.ts
  shared/src/business/useCaseHelper/workItems/updateCaseTitleOnWorkItems.ts
  shared/src/business/useCaseHelper/workItems/updateDocketNumberSuffixOnWorkItems.test.ts
  shared/src/business/useCaseHelper/workItems/updateDocketNumberSuffixOnWorkItems.ts
  shared/src/business/useCaseHelper/workItems/updateTrialDateOnWorkItems.test.ts
  shared/src/business/useCaseHelper/workItems/updateTrialDateOnWorkItems.ts
  shared/src/business/useCaseHelper/workItems/updateTrialLocationOnWorkItems.js
  shared/src/business/useCaseHelper/workItems/updateTrialLocationOnWorkItems.test.js
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  shared/src/business/useCases/saveCaseDetailInternalEditInteractor.ts
  shared/src/business/useCases/updateContactInteractor.ts
  shared/src/business/utilities/getDocumentTitleWithAdditionalInfo.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCInboxForUser.test.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCInboxForUser.ts
  shared/src/persistence/dynamo/workitems/saveWorkItem.test.ts
  shared/src/persistence/dynamo/workitems/saveWorkItem.ts
  shared/src/test/mockCase.ts
  shared/src/test/mockDocuments.ts
  shared/src/test/mockWorkItem.ts
  types/TEntity.d.ts
  web-api/src/getUseCaseHelpers.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.test.ts
Labels: to staging

#3451 Remove unused inputs in the Date Range Picker
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
Labels: to staging

#3504 9723 custom case Inventory Report
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/EntityValidationConstants.ts
  shared/src/business/entities/JoiValidationConstants.ts
  shared/src/business/entities/customCaseInventorySearch/CustomCaseInventorySearch.test.ts
  shared/src/business/entities/customCaseInventorySearch/CustomCaseInventorySearch.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/caseInventoryReport/getCustomCaseInventoryReportInteractor.test.ts
  shared/src/business/useCases/caseInventoryReport/getCustomCaseInventoryReportInteractor.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.test.ts
  shared/src/business/useCases/validateCustomCaseInventorySearchFiltersInteractor.test.ts
  shared/src/business/useCases/validateCustomCaseInventorySearchFiltersInteractor.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/persistence/elasticsearch/getCasesByFilters.ts
  shared/src/proxies/reports/getCustomCaseInventoryReportProxy.ts
  web-api/elasticsearch/efcms-case-mappings.js
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/reports/getCustomCaseInventoryReportLambda.ts
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/clearOptionalCustomCaseInventoryFilterAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/clearOptionalCustomCaseInventoryFilterAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseInventoryReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseInventoryReportAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseInventoryFiltersAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseInventoryFiltersAction.ts
  web-client/src/presenter/actions/validateCustomInventoryFiltersAction.test.ts
  web-client/src/presenter/actions/validateCustomInventoryFiltersAction.ts
  web-client/src/presenter/computeds/customCaseInventoryReportHelper.test.ts
  web-client/src/presenter/computeds/customCaseInventoryReportHelper.ts
  web-client/src/presenter/customCaseInventoryReportState.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/clearOptionalCustomCaseInventoryFilterSequence.ts
  web-client/src/presenter/sequences/getCustomCaseInventoryReportSequence.ts
  web-client/src/presenter/sequences/gotoCustomCaseReportSequence.ts
  web-client/src/presenter/sequences/setCustomCaseInventoryReportFiltersSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/buttons.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/overrides.scss
  web-client/src/ustc-ui/Accordion/Accordion.test.tsx
  web-client/src/ustc-ui/Accordion/Accordion.tsx
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/ustc-ui/Select/SelectSearch.tsx
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/AppComponent.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/Header/ReportsMenu.tsx
Labels: to test, Manual Deploy Step(s) Required
