Repository ustaxcourt/ef-cms, pull requests merged in 2023-03, with the labels that each got.

#3183 9599/9597: Consolidated Group Display on My Cases Page
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.js
  shared/src/business/utilities/generateSelectedFilterList.js
  shared/src/business/utilities/generateSelectedFilterList.test.js
  shared/src/business/utilities/getFormattedCaseDetail.js
  shared/src/business/utilities/getFormattedCaseDetail.test.js
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.jsx
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.test.js
  web-client/integration-tests/journey/petitionsClerkVerifiesConsolidatedCaseIndicatorSentMessagesBox.js
  web-client/integration-tests/journey/petitionsClerkVerifiesLeadCaseIndicatorSentMessagesBox.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/preparePrintableFormattedCasesAction.test.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/preparePrintableFormattedCasesAction.ts
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.tsx
  web-client/src/views/CaseListRowExternal.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/TrialSessionDetail/AllCases.tsx
  web-client/src/views/TrialSessionDetail/EligibleCases.tsx
  web-client/src/views/TrialSessionDetail/InactiveCases.tsx
  web-client/src/views/TrialSessionDetail/OpenCases.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
Labels: to staging

#3178 9797 BUG: Checking/Unchecking the "Use Existing Address" checkboxes causes issues
  web-client/src/presenter/actions/CaseDetail/shouldUseContactPrimaryAddressAction.test.ts
  web-client/src/presenter/actions/CaseDetail/shouldUseContactPrimaryAddressAction.ts
  web-client/src/presenter/actions/CaseDetail/unsetAddressOnFormAction.test.ts
  web-client/src/presenter/actions/CaseDetail/unsetAddressOnFormAction.ts
  web-client/src/presenter/actions/CaseDetail/unsetContactSecondaryAddressOnFormAction.test.ts
  web-client/src/presenter/actions/CaseDetail/unsetContactSecondaryAddressOnFormAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/toggleUseContactPrimaryAddressSequence.ts
  web-client/src/views/StartCase/ContactSecondary.tsx
Labels: bugfix, to test

#3192 9818 Fixing console error during case creation
  web-client/src/presenter/actions/StartCaseInternal/getFormContactPrimaryAction.ts
  web-client/src/presenter/sequences/submitPetitionFromPaperSequence.ts
Labels: to test

#3187 9863 BUG (fix) - When adding a party to a case in a consolidated group, the cases listed in the Consolidated case card disappear from view
  cypress-integration/integration/consolidated-case.cy.js
  cypress-integration/integration/docket-clerk-views-consolidated-case.cy.js
  cypress-integration/integration/start-a-case-practitioner.cy.js
  web-client/src/presenter/sequences/CaseAssociation/associateIrsPractitionerWithCaseSequence.ts
  web-client/src/presenter/sequences/CaseAssociation/associatePrivatePractitionerWithCaseSequence.ts
  web-client/src/presenter/sequences/deleteCorrespondenceDocumentSequence.ts
Labels: bugfix

#3195 attempt to fix integration test
  web-client/integration-tests/docketClerkCaseInventoryReport.test.js
Labels: to staging

#3191 9797 BUG: Checking/Unchecking the "Use Existing Address" checkboxes causes issues
  web-client/src/presenter/actions/CaseDetail/shouldUseContactPrimaryAddressAction.test.ts
  web-client/src/presenter/actions/CaseDetail/shouldUseContactPrimaryAddressAction.ts
  web-client/src/presenter/actions/CaseDetail/unsetAddressOnFormAction.test.ts
  web-client/src/presenter/actions/CaseDetail/unsetAddressOnFormAction.ts
  web-client/src/presenter/actions/CaseDetail/unsetContactSecondaryAddressOnFormAction.test.ts
  web-client/src/presenter/actions/CaseDetail/unsetContactSecondaryAddressOnFormAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/toggleUseContactPrimaryAddressSequence.ts
  web-client/src/views/StartCase/ContactSecondary.tsx
Labels: bugfix, to staging

#3201 fix-cypress: update url for dynamodb local
  web-api/start-dynamo.sh
Labels: to staging

#3197 9767 Case Status History (Intermediate PR to Test)
  shared/src/business/entities/cases/Case.closeCase.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/entities/cases/Case.removeFromTrial.test.js
  shared/src/business/entities/cases/Case.reopenCase.test.js
  shared/src/business/entities/cases/Case.setCaseStatus.test.js
  shared/src/business/entities/cases/Case.setCaseStatus.test.ts
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.js
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.js
  shared/src/business/useCases/createCaseFromPaperInteractor.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.test.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/removeCaseFromTrialInteractor.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.test.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/tables.scss
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseStatusHistory.tsx
Labels: to test

#3203 9869: check isDirectlyAssociated instead of isAssociated to ensure th…
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.test.ts
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.ts
Labels: to test

#3202 9870 BUG: Incorrect Error message appears if a Petitions Clerk clicks create case before all required fields have been completed.
  web-client/src/presenter/actions/chooseStatisticValidationStrategyAction.test.ts
  web-client/src/presenter/actions/chooseStatisticValidationStrategyAction.ts
  web-client/src/presenter/sequences/calculatePenaltiesSequence.ts
Labels: bugfix

#3207 Bug 9869: Request access page error
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.test.ts
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.ts
  web-client/src/presenter/sequences/gotoRequestAccessSequence.test.ts
  web-client/src/presenter/sequences/gotoRequestAccessSequence.ts
Labels: to staging

#3166 DevEx - convert entity to ts
  .circleci/config.yml
  .github/workflows/client-integration.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  cypress-smoketests.config.js
  docs/additional-resources/old-readme.md
  docs/ci-cd.md
  run-integration-tests.sh
  run-local.sh
  shared/src/business/entities/CaseDeadline.js
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/entities/IrsPractitioner.js
  shared/src/business/entities/IrsPractitioner.ts
  shared/src/business/entities/OutboxItem.test.ts
  shared/src/business/entities/OutboxItem.ts
  shared/src/business/entities/PractitionerDocument.js
  shared/src/business/entities/PractitionerDocument.ts
  shared/src/business/entities/WorkItem.js
  shared/src/business/entities/WorkItem.ts
  shared/src/business/entities/orders/Order.js
  shared/src/business/entities/orders/Order.ts
  shared/src/business/entities/orders/OrderWithoutBody.js
  shared/src/business/entities/orders/OrderWithoutBody.ts
  shared/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  shared/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.ts
  shared/src/business/useCases/caseDeadline/validateCaseDeadlineInteractor.ts
  shared/src/business/useCases/practitioners/createPractitionerDocumentInteractor.ts
  shared/src/business/useCases/practitioners/editPractitionerDocumentInteractor.ts
  shared/src/business/useCases/users/getIrsPractitionersBySearchKeyInteractor.ts
  shared/src/business/useCases/workitems/assignWorkItemsInteractor.ts
  shared/src/persistence/dynamo/caseDeadlines/createCaseDeadline.ts
  shared/src/persistence/dynamo/practitioners/createPractitionerDocument.ts
  shared/src/persistence/dynamo/practitioners/editPractitionerDocument.ts
  shared/src/persistence/dynamo/practitioners/getPractitionerDocuments.ts
  shared/src/persistence/dynamo/workitems/createSectionOutboxRecords.ts
  shared/src/persistence/dynamo/workitems/createUserOutboxRecord.ts
  shared/src/persistence/dynamo/workitems/deleteWorkItem.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCServedForUser.ts
  shared/src/persistence/dynamo/workitems/saveWorkItem.ts
  shared/src/persistence/dynamo/workitems/saveWorkItemForDocketClerkFilingExternalDocument.ts
  types/TEntity.d.ts
  wait-for-dynamo.sh
  wait-until-services.sh
  wait-until.sh
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/pa11y/helpers.js
  web-client/pa11y/pa11y-ci.web-client-1.config.js
  web-client/pa11y/pa11y-ci.web-client-2.config.js
  web-client/pa11y/pa11y-ci.web-client-3.config.js
  web-client/pa11y/pa11y-ci.web-client-4.config.js
  web-client/pa11y/pa11y-docketclerk.js
  web-client/pa11y/pa11y-petitioner.js
Labels: to staging

#3189 Dependency Updates for the week of 02/27/23
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#3204 DevEx - Adding Abstract JoiValidationEntity
  shared/src/business/entities/JoiValidationEntity.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/useCaseHelper/trialSessions/createTrialSessionAndWorkingCopy.test.js
Labels: to staging

#3211 9870 Bugfix: Incorrect Error message appears if a Petitions Clerk clicks create case before all required fields have been completed.
  web-client/src/presenter/actions/chooseStatisticValidationStrategyAction.test.ts
  web-client/src/presenter/actions/chooseStatisticValidationStrategyAction.ts
  web-client/src/presenter/sequences/calculatePenaltiesSequence.ts
Labels: bugfix

#3217 1109: Design debt
  web-client/src/views/CaseDetail/MessagesCompleted.tsx
  web-client/src/views/DocketRecord/DocumentViewer.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.tsx
Labels: to staging

#3231 9819 intermediate to test
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfReceiptOfPetition.jsx
  shared/test-pdf-expected-images/Notice_Receipt_Petition_E_Access.pdf.1.png
Labels: to test

#3152 9818: E-Access: Add E-Mail Fields to Petitions Entry/Edit UI
  scripts/dynamo/setup-e-consent-fields-enabled-feature-flag.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/contacts/ContactFactory.js
  shared/src/business/entities/contacts/Petitioner.js
  shared/src/business/entities/contacts/Petitioner.test.js
  shared/src/business/useCases/updatePetitionerInformationInteractor.test.ts
  shared/src/business/useCases/updatePetitionerInformationInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/eConsentJourney.test.js
  web-client/src/presenter/actions/StartCaseInternal/setDefaultStartCaseInternalFormAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setDefaultStartCaseInternalFormAction.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.ts
  web-client/src/presenter/computeds/contactsHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
  web-client/src/presenter/computeds/partiesInformationHelper.test.ts
  web-client/src/presenter/computeds/partiesInformationHelper.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.test.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.ts
  web-client/src/presenter/computeds/startCaseInternalContactsHelper.test.ts
  web-client/src/presenter/computeds/startCaseInternalContactsHelper.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/gotoPetitionQcSequence.ts
  web-client/src/presenter/sequences/gotoReviewSavedPetitionSequence.ts
  web-client/src/presenter/sequences/gotoStartCaseWizardSequence.ts
  web-client/src/presenter/sequences/submitPetitionFromPaperSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
  web-client/src/views/CaseDetailEdit/CaseDetailEdit.tsx
  web-client/src/views/CaseDetailEdit/PartyInformation.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCaseInternal/Parties.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
Labels: to staging, Manual Deploy Step(s) Required

#3210 9819 Dynamic NOTR
  docs/testing.md
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
  shared/src/business/utilities/documentGenerators/noticeOfReceiptOfPetition.test.js
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfReceiptOfPetition.jsx
  shared/test-pdf-expected-images/Notice_Receipt_Petition_E_Access.pdf.1.png
  web-client/src/presenter/sequences/gotoReviewSavedPetitionSequence.test.ts
  web-client/src/presenter/sequences/gotoReviewSavedPetitionSequence.ts
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/StartCase/Contacts.tsx
Labels: to staging

#3247 9868 BUG: Jumpy checkboxes to test attempt #3
  web-client/pa11y/pa11y-docketclerk.js
  web-client/pa11y/pa11y-petitionsclerk.js
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDetailEdit/PartyInformation.tsx
  web-client/src/views/PaperFiling/Inclusions.tsx
  web-client/src/views/StartCaseInternal/Parties.tsx
Labels: to test

#3243 Dependencies 3/7/23
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: dependencies, to staging

#3228 9782 Calendar: Display Trial Session Dates and Session Type on Swing Session Menu
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.ts
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging

#3263 9868: jumpy checkboxes alternative
  web-client/src/styles/overrides.scss
Labels: to test

#3269 9783 Document QC: Reorder Inbox Work Items
  web-client/src/presenter/computeds/formattedWorkQueue.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
Labels: to test

#3270 Update UX-Documentation.md
  docs/wiki/UX-Documentation.md
Labels: to staging

#3265 Fix overloaded cases endpoint
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
Labels: to staging

#3259 9614: Move Document QC Inbox query to Dynamo
  docs/additional-resources/blue-green-migration.md
  docs/migrations.md
  docs/terraform.md
  docs/wiki/UX-Documentation.md
  package.json
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  shared/src/business/useCases/getReconciliationReportInteractor.ts
  shared/src/persistence/dynamo/dynamoTypes.ts
  shared/src/persistence/dynamo/workitems/createSectionOutboxRecords.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCInboxForUser.test.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCInboxForUser.ts
  shared/src/persistence/dynamo/workitems/getDocumentQCServedForSection.ts
  shared/src/persistence/dynamo/workitems/saveWorkItem.ts
  shared/src/persistence/dynamodbClientService.ts
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForUser.js
  shared/src/persistence/elasticsearch/workitems/getDocumentQCInboxForUser.test.js
  types/TEntity.d.ts
  web-api/create-dynamo-tables.js
  web-api/run-local-migration.ts
  web-api/src/getPersistenceGateway.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/terraform/template/dynamo-table/dynamo-migration.tf
  web-api/workflow-terraform/migration/main/lambdas/migrations/0003-update-trial-session-working-copy-status.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0003-update-trial-session-working-copy-status.test.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0004-remove-closedDate-for-open-cases.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0004-remove-closedDate-for-open-cases.test.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0004-set-session-status.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0004-set-session-status.test.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0006-reformat-sortable-docket-number.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0006-reformat-sortable-docket-number.test.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.js
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/docketClerkConsolidatedCaseWorkItemsJourney.test.js
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedGroupInformationForDocumentQC.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedLeadCaseIndicatorDocumentQCSection.js
Labels: Blue/Green Migration

#3199 9767 Case Status History
  shared/src/business/entities/cases/Case.closeCase.test.ts
  shared/src/business/entities/cases/Case.removeFromTrial.test.ts
  shared/src/business/entities/cases/Case.reopenCase.test.ts
  shared/src/business/entities/cases/Case.setCaseStatus.test.ts
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.test.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/trialSessions/deleteTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/removeCaseFromTrialInteractor.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.test.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/tables.scss
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseStatusHistory.tsx
Labels: to staging

#3300 9868 BUG: jumpy checkboxes
  web-client/pa11y/pa11y-docketclerk.js
  web-client/pa11y/pa11y-petitionsclerk.js
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDetailEdit/PartyInformation.tsx
  web-client/src/views/PaperFiling/Inclusions.tsx
  web-client/src/views/StartCaseInternal/Parties.tsx
Labels: to staging

#3307 OpEx: admin script to toggle dynamo streams on/off
  shared/admin-tools/dynamodb/toggle-streams.sh
Labels: to staging

#3313 Devex 1135: Delete all code associated with FILE_IN_CONSOLIDATED permission
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentForConsolidatedInteractor.test.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentForConsolidatedInteractor.ts
  shared/src/business/useCases/externalDocument/uploadExternalDocumentsInteractor.test.ts
  shared/src/business/useCases/externalDocument/uploadExternalDocumentsInteractor.ts
  shared/src/proxies/documents/fileExternalDocumentForConsolidatedProxy.ts
  web-api/src/app.js
  web-api/src/documents/fileExternalDocumentToConsolidatedCasesLambda.js
  web-api/src/getUseCases.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/FileDocument/canFileInConsolidatedCasesAction.test.ts
  web-client/src/presenter/actions/FileDocument/canFileInConsolidatedCasesAction.ts
  web-client/src/presenter/actions/FileDocument/setSelectedCasesForConsolidatedCaseDocumentSubmissionAction.test.ts
  web-client/src/presenter/actions/FileDocument/setSelectedCasesForConsolidatedCaseDocumentSubmissionAction.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsForConsolidatedAction.test.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsForConsolidatedAction.ts
  web-client/src/presenter/actions/clearPartyPrimaryAction.test.ts
  web-client/src/presenter/actions/clearPartyPrimaryAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/completeDocumentSelectSequence.ts
  web-client/src/presenter/sequences/gotoFileDocumentSequence.ts
  web-client/src/presenter/sequences/setSelectedCasesForConsolidatedCaseDocumentSubmissionSequence.ts
  web-client/src/presenter/sequences/submitExternalDocumentSequence.ts
  web-client/src/views/FileDocument/CheckConsolidatedCasesModal.tsx
  web-client/src/views/FileDocument/SelectDocumentType.tsx
Labels: to staging

#3329 BUG 9699 to test
  docs/aws.md
  shared/src/business/utilities/documentGenerators/addressLabelCoverSheet.test.ts
  shared/src/business/utilities/pdfGenerator/components/AddressLabel.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/AddressLabelCoverSheet.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfReceiptOfPetition.tsx
  shared/test-pdf-expected-images/Address_Label_Cover_Sheet.pdf.1.png
Labels: to test

#3295 Dependency updates 3-20-2023
  .circleci/config.yml
  Dockerfile
  docs/additional-resources/blue-green-migration.md
  docs/additional-resources/environment-switcher.md
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  tsconfig.json
Labels: dependencies, to staging

#3337 9872 Chambers: Remove Ability to Edit Trial Session
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.ts
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#3311 9806 Bugfix - When associating a swing session, the associated trial session does not indicate that it is a part of a swing session
  shared/src/business/useCaseHelper/trialSessions/associateSwingTrialSessions.test.ts
  shared/src/business/useCaseHelper/trialSessions/associateSwingTrialSessions.ts
  shared/src/business/useCases/trialSessions/createTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/createTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/setTrialSessionAsSwingSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/proxies/trialSessions/setTrialSessionAsSwingSessionProxy.ts
  web-api/src/app.js
  web-api/src/getUseCaseHelpers.ts
  web-api/src/getUseCases.ts
  web-api/src/trialSessions/setTrialSessionAsSwingSessionLambda.js
  web-api/swagger.json
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.test.ts
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.ts
Labels: to staging

#3345 9872 Chambers: Remove Ability to Edit Trial Session
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/trialSessionDetailsHelper.ts
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to staging

#3350 9975 BUG: Petitions "Served" QC Boxes Sorting in Reverse Order
  web-client/src/presenter/computeds/formattedWorkQueue.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
Labels: bugfix

#3353 Opex-1151 - Intermediate branch to Test
  package.json
  scripts/pr-to-test.sh
Labels: to test

#3361 9983: Unable to file non-standard H documents that point to an iteration type document
  web-client/src/views/FileDocument/NonstandardForm.tsx
Labels: bugfix

#3379 9828 Penalty/Deficiencies: Remove Positive Value Validation intermediate to test
  web-client/src/presenter/actions/checkForNegativeValueAction.test.ts
  web-client/src/presenter/actions/checkForNegativeValueAction.ts
Labels: to test

#3380 9828 Penalty/Deficiencies: Remove Positive Value Validation
  shared/src/business/entities/Penalty.test.ts
  shared/src/business/entities/Penalty.ts
  shared/src/business/entities/Statistic.test.ts
  shared/src/business/entities/Statistic.ts
  web-client/integration-tests/journey/petitionsClerkAddsDeficiencyStatisticToCase.js
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/checkForNegativeValueAction.test.ts
  web-client/src/presenter/actions/checkForNegativeValueAction.ts
  web-client/src/presenter/actions/clearConfirmationTextAction.test.ts
  web-client/src/presenter/actions/clearConfirmationTextAction.ts
  web-client/src/presenter/actions/clearConfirmationTextCalculatePenaltiesModalAction.test.ts
  web-client/src/presenter/actions/clearConfirmationTextForCalculatePenaltiesModalAction.ts
  web-client/src/presenter/actions/clearConfirmationTextStatisticsAction.test.ts
  web-client/src/presenter/actions/clearConfirmationTextStatisticsAction.ts
  web-client/src/presenter/actions/setNegativeValueConfirmationTextAction.test.ts
  web-client/src/presenter/actions/setNegativeValueConfirmationTextAction.ts
  web-client/src/presenter/actions/unsetNegativeValueConfirmationTextAction.test.ts
  web-client/src/presenter/actions/unsetNegativeValueConfirmationTextAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/calculatePenaltiesSequence.ts
  web-client/src/presenter/sequences/cancelAddStatisticSequence.ts
  web-client/src/presenter/sequences/checkForNegativeValueSequence.ts
  web-client/src/presenter/sequences/gotoAddDeficiencyStatisticsSequence.ts
  web-client/src/presenter/sequences/gotoEditDeficiencyStatisticSequence.ts
  web-client/src/presenter/sequences/gotoStartCaseWizardSequence.ts
  web-client/src/presenter/sequences/showCalculatePenaltiesModalSequence.ts
  web-client/src/presenter/sequences/submitAddDeficiencyStatisticsSequence.ts
  web-client/src/presenter/sequences/submitEditDeficiencyStatisticSequence.ts
  web-client/src/presenter/sequences/submitPetitionFromPaperSequence.ts
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/DollarsInput/DollarsInput.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/CaseDetail/DeficiencyStatisticsForm.tsx
  web-client/src/views/StartCaseInternal/CalculatePenaltiesModal.tsx
  web-client/src/views/StartCaseInternal/StatisticsForm.tsx
Labels: to staging

#3356 Dependency updates 27 03 23
  docs/dependency-updates.md
  package-lock.json
  package.json
Labels: to staging
