Repository ustaxcourt/ef-cms, pull requests merged in 2023-09, with the labels that each got.

#3845 10116: DNS Failover
  .circleci/config.yml
  docs/additional-resources/healthCheck.md
  docs/additional-resources/troubleshooting.md
  iam/terraform/account-specific/main/circle-ci.tf
  iam/terraform/environment-specific/main/lambda.tf
  package-lock.json
  package.json
  run-api.sh
  run-local.sh
  shared/admin-tools/user/add-user.ts
  shared/admin-tools/user/admin.ts
  shared/src/business/useCases/health/getCachedHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getCachedHealthCheckInteractor.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.ts
  shared/src/business/useCases/health/healthCheck.drawio
  shared/src/business/useCases/health/setHealthCheckCacheInteractor.test.ts
  shared/src/business/useCases/health/setHealthCheckCacheInteractor.ts
  shared/src/proxies/requests.ts
  web-api/src/app-public.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/health/getCachedHealthCheckLambda.ts
  web-api/src/health/setHealthCheckCacheLambda.ts
  web-api/src/persistence/dynamo/deployTable/getStoredApplicationHealth.ts
  web-api/src/persistence/dynamo/deployTable/setStoredApplicationHealth.ts
  web-api/src/persistence/dynamodbClientService.test.ts
  web-api/src/persistence/dynamodbClientService.ts
  web-api/src/persistence/ses/getSesStatus.test.ts
  web-api/src/persistence/ses/getSesStatus.ts
  web-api/switch-health-check-domain.ts
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/api/cron.tf
  web-api/terraform/api/failover.tf
  web-api/terraform/api/outputs.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/failover.tf
  web-api/terraform/template/lambdas/cron.js
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
  web-client/switch-colors.sh
  web-client/terraform/main/main.tf
  web-client/terraform/main/outputs.tf
  web-client/terraform/main/variables.tf
Labels: to staging, Needs Environment Specific, Needs Account Specific

#3905 Dependency Updates - Last Week of August 2023
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
Labels: dependencies, to staging

#3922 10110 - Remove Attachments from Messages - to test
  shared/src/business/useCases/messages/createMessageInteractor.test.ts
  shared/src/business/useCases/messages/createMessageInteractor.ts
  shared/src/business/useCases/messages/forwardMessageInteractor.ts
  shared/src/business/useCases/messages/replyToMessageInteractor.test.ts
  shared/src/business/useCases/messages/replyToMessageInteractor.ts
  shared/src/proxies/messages/createMessageProxy.ts
  shared/src/proxies/messages/forwardMessageProxy.ts
  shared/src/proxies/messages/replyToMessageProxy.ts
  web-client/integration-tests/correspondenceJourney.test.ts
  web-client/integration-tests/docketClerkServesCourtIssuedDocumentOnLeadCaseFromMessageDetail.test.ts
  web-client/integration-tests/docketClerkServesPaperFiledDocumentOnLeadCaseFromMessageDetail.test.ts
  web-client/integration-tests/journey/createNewMessageOnCase.ts
  web-client/integration-tests/journey/docketClerkCreatesMessageWithCorrespondence.ts
  web-client/integration-tests/journey/petitionsClerkCreatesMessageToChambers.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewMessageOnCaseWithMaxAttachments.ts
  web-client/integration-tests/journey/petitionsClerkForwardsMessageWithAttachment.ts
  web-client/integration-tests/journey/userSendsMessage.ts
  web-client/integration-tests/messagesJourney.test.ts
  web-client/src/presenter/actions/CaseDetail/forwardMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/forwardMessageAction.ts
  web-client/src/presenter/actions/CaseDetail/replyToMessageAction.ts
  web-client/src/presenter/actions/WorkItem/setCreateMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setCreateMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/WorkItem/setForwardMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setForwardMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/WorkItem/setReplyToMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setReplyToMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
  web-client/src/presenter/computeds/messageModalHelper.test.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/styles/forms.scss
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/ForwardMessageModalDialog.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
  web-client/src/views/Messages/ReplyToMessageModalDialog.tsx
Labels: to test

#3931 10144 flaky cypress test
  cypress/cypress-integration/support/pages/document-qc.ts
  cypress/cypress-smoketests/integration/court-issued-documents.cy.ts
Labels: to staging

#3946 10141 case status ready bug
  shared/src/business/useCases/checkForReadyForTrialCasesInteractor.test.ts
  shared/src/business/useCases/checkForReadyForTrialCasesInteractor.ts
  web-api/src/persistence/elasticsearch/getReadyForTrialCases.test.ts
  web-api/src/persistence/elasticsearch/getReadyForTrialCases.ts
  web-client/integration-tests/verifyCheckReadyForTrial.test.ts
Labels: to staging

#3949 3948 judge chambers update
  scripts/data-import/judge/judge_users.csv
  shared/admin-tools/user/add-user.ts
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to test

#3912 10114 story
  package-lock.json
  package.json
  scripts/dynamo/setup-use-change-of-address-lambda-flag.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/Practitioner.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCaseHelper/coverSheets/removeCoversheet.ts
  shared/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.ts
  shared/src/business/useCases/addCoverToPdf.ts
  shared/src/business/useCases/generateCoverSheetData.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.ts
  shared/src/business/useCases/users/generateChangeOfAddress.ts
  shared/src/business/useCases/users/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  shared/src/business/useCases/users/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.ts
  web-api/src/applicationContext.ts
  web-api/src/errors/errors.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/createChangeOfAddressJob.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/setChangeOfAddressCaseAsDone.ts
  web-api/terraform/api/change-of-address.tf
  web-api/terraform/api/sqs.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/template/cognito.tf
  web-api/terraform/template/lambdas/pdf-generation.js
  web-client/integration-tests/journey/practitionerUpdatesAddress.ts
  web-client/src/presenter/actions/CaseWorksheet/updateSubmittedCavCaseDetailAction.ts
  web-client/src/presenter/actions/userContactUpdateProgressAction.test.ts
  web-client/src/presenter/actions/userContactUpdateProgressAction.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/UserContactEditProgress.tsx
Labels: to staging, Manual Deploy Step(s) Required

#3958 10065 Bug: When there are 6 lines in the address area of a NOTR and a RPT is indicated, the Address info is not formatted correctly
  shared/src/business/utilities/documentGenerators/noticeOfReceiptOfPetition.test.ts
  shared/src/business/utilities/htmlGenerator/documents/notice-of-receipt-of-petition.scss
  shared/test-pdf-expected-images/Notice_Receipt_Petition.pdf.1.png
  shared/test-pdf-expected-images/Notice_Receipt_Petition_E_Access.pdf.1.png
  shared/test-pdf-expected-images/Notice_Receipt_Petition_E_Access_Long_Address.pdf.1.png
  shared/test-pdf-expected-images/Notice_Receipt_Petition_Long_Address.pdf.1.png
Labels: to staging

#3942 10110 - Ability to Remove Message Attachments
  shared/src/business/useCases/messages/createMessageInteractor.test.ts
  shared/src/business/useCases/messages/createMessageInteractor.ts
  shared/src/business/useCases/messages/forwardMessageInteractor.ts
  shared/src/business/useCases/messages/replyToMessageInteractor.test.ts
  shared/src/business/useCases/messages/replyToMessageInteractor.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/business/utilities/getFormattedCaseDetail.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/proxies/messages/createMessageProxy.ts
  shared/src/proxies/messages/forwardMessageProxy.ts
  shared/src/proxies/messages/replyToMessageProxy.ts
  web-client/integration-tests/correspondenceJourney.test.ts
  web-client/integration-tests/docketClerkServesCourtIssuedDocumentOnLeadCaseFromMessageDetail.test.ts
  web-client/integration-tests/docketClerkServesPaperFiledDocumentOnLeadCaseFromMessageDetail.test.ts
  web-client/integration-tests/journey/createNewMessageOnCase.ts
  web-client/integration-tests/journey/docketClerkCreatesMessageWithCorrespondence.ts
  web-client/integration-tests/journey/petitionsClerkCreatesMessageToChambers.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewMessageOnCaseWithMaxAttachments.ts
  web-client/integration-tests/journey/petitionsClerkForwardsMessageWithAttachment.ts
  web-client/integration-tests/journey/userSendsMessage.ts
  web-client/integration-tests/messagesJourney.test.ts
  web-client/src/presenter/actions/CaseDetail/createMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/createMessageAction.ts
  web-client/src/presenter/actions/CaseDetail/forwardMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/forwardMessageAction.ts
  web-client/src/presenter/actions/CaseDetail/replyToMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/replyToMessageAction.ts
  web-client/src/presenter/actions/WorkItem/setCreateMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setCreateMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/WorkItem/setForwardMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setForwardMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/WorkItem/setReplyToMessageModalDialogModalStateAction.test.ts
  web-client/src/presenter/actions/WorkItem/setReplyToMessageModalDialogModalStateAction.ts
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAfterQCAction.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
  web-client/src/presenter/computeds/messageModalHelper.test.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/styles/forms.scss
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/ForwardMessageModalDialog.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
  web-client/src/views/Messages/ReplyToMessageModalDialog.tsx
Labels: to staging

#3953 3948 judge chambers update
  scripts/data-import/judge/judge_users.csv
  shared/admin-tools/user/add-user.ts
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to staging

#3965 Devex 1136: Automated Glue Jobs
  .circleci/config.yml
  docs/operations/production-like-data-sets.md
  iam/terraform/account-specific/main/circle-ci.tf
  iam/terraform/environment-specific/main/glue-job-status.tf
  iam/terraform/environment-specific/main/migration.tf
  iam/terraform/environment-specific/main/reindex-status.tf
  iam/terraform/environment-specific/main/wait-for-workflow.tf
  package-lock.json
  package.json
  scripts/circleci/approve-pending-job.ts
  scripts/circleci/cancel-workflow.ts
  scripts/delete-all-persistence.sh
  scripts/glue/glue-job-status.ts
  scripts/glue/start-glue-job.ts
  scripts/helpers/dynamodb-table-exists.sh
  scripts/helpers/opensearch-domain-exists.sh
  scripts/jest-scripts.config.ts
  scripts/setup-deploy-table-for-glue-job.sh
  scripts/sync-s3-buckets-with-timeout.sh
  setup-for-blue-green-migration.sh
  shared/admin-tools/aws/deployTableHelper.ts
  shared/admin-tools/aws/glueHelper.ts
  shared/admin-tools/aws/migrationWaitHelper.ts
  shared/admin-tools/aws/sqsHelper.ts
  shared/admin-tools/circleci/circleci-helper.ts
  shared/admin-tools/dynamodb/fix-race-condition-served-in-drafts.ts
  shared/admin-tools/dynamodb/import-case-status-changes-from-csv.ts
  shared/admin-tools/elasticsearch/practitioner-stats.ts
  shared/admin-tools/glue/GLUE_JOBS.md
  shared/admin-tools/glue/glue_flow.drawio
  shared/admin-tools/glue/glue_flow.drawio.png
  shared/admin-tools/user/admin.ts
  shared/admin-tools/user/rotate-environment-secrets.ts
  shared/admin-tools/user/setup-glued-judges.ts
  shared/admin-tools/user/verifyAdminUserDisabled.test.ts
  tsconfig.json
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-api/workflow-terraform/glue-cron/bin/deploy-app.sh
  web-api/workflow-terraform/glue-cron/bin/deploy-init.sh
  web-api/workflow-terraform/glue-cron/bin/destroy-app.sh
  web-api/workflow-terraform/glue-cron/bin/disable.sh
  web-api/workflow-terraform/glue-cron/bin/enable.sh
  web-api/workflow-terraform/glue-cron/main/glue-job-status.tf
  web-api/workflow-terraform/glue-cron/main/lambdas/glue-job-status.js
  web-api/workflow-terraform/glue-cron/main/lambdas/glue-job-status.test.js
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/glue-cron/main/variables.tf
  web-api/workflow-terraform/wait-for-workflow-cron/bin/deploy-app.sh
  web-api/workflow-terraform/wait-for-workflow-cron/bin/deploy-init.sh
  web-api/workflow-terraform/wait-for-workflow-cron/bin/destroy-app.sh
  web-api/workflow-terraform/wait-for-workflow-cron/bin/disable.sh
  web-api/workflow-terraform/wait-for-workflow-cron/bin/enable.sh
  web-api/workflow-terraform/wait-for-workflow-cron/main/lambdas/wait-for-workflow.js
  web-api/workflow-terraform/wait-for-workflow-cron/main/lambdas/wait-for-workflow.test.js
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/variables.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/wait-for-workflow.tf
  webpack.config.lambda.glue-cron.js
  webpack.config.lambda.wait-for-workflow.js
Labels: Needs Environment Specific, Needs Account Specific

#3994 10054 generate ea documents to test
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.ts
  web-client/src/presenter/actions/FileDocument/setIsExternalConsolidatedCaseGroupEnabledValueAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.ts
  web-client/src/presenter/computeds/allowExternalConsolidatedGroupFilingHelper.test.ts
  web-client/src/presenter/computeds/allowExternalConsolidatedGroupFilingHelper.ts
  web-client/src/presenter/sequences/completeDocumentSelectSequence.ts
  web-client/src/presenter/sequences/gotoRequestAccessSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/FileDocument/FileDocument.tsx
  web-client/src/views/RequestAccess/RequestAccess.tsx
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
Labels: to test

#3992 hotfix: fix paginator on Judge Activity Report
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
Labels: to staging

#4005 Devex 1214: Changing paginator page scrolls to the top of the table
  web-client/src/presenter/utilities/focusPaginatorTop.test.ts
  web-client/src/presenter/utilities/focusPaginatorTop.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3995 Dependency Updates Week of Sept 18 2023
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  docs/testing.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/src/presenter/state.ts
  web-client/terraform/main/main.tf
Labels: to staging, Manual Deploy Step(s) Required

#4007 10054: Upload progress fixes
  web-client/src/presenter/actions/FileDocument/setDocumentFileForAutoGeneratedEntryOfAppearanceAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDocumentFileForAutoGeneratedEntryOfAppearanceAction.ts
  web-client/src/presenter/sequences/submitCaseAssociationRequestSequence.ts
Labels: to test

#4011 9788: Add Icons to Printable Version of Trial Session Information Screen
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.test.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/htmlGenerator/cards.scss
  shared/src/business/utilities/htmlGenerator/documents/notice-of-docket-change.scss
  shared/src/business/utilities/htmlGenerator/documents/printable-working-copy-list.scss
  shared/src/business/utilities/htmlGenerator/documents/trial-calendar.scss
  shared/src/business/utilities/htmlGenerator/index-main.scss
  shared/src/business/utilities/htmlGenerator/shared.scss
  shared/src/business/utilities/htmlGenerator/tables.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfDocketChange.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Trial_Calendar.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Session_Notes.pdf.1.png
  web-api/src/applicationContext.ts
  web-api/src/persistence/dynamo/trialSessions/getCalendaredCasesForTrialSession.ts
Labels: to test

#4020 9788: UX Feedback
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/htmlGenerator/documents/printable-working-copy-list.scss
  shared/src/business/utilities/htmlGenerator/documents/trial-calendar.scss
  shared/src/business/utilities/htmlGenerator/shared.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Trial_Calendar.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Session_Notes.pdf.1.png
Labels: to test

#4003 design debt: fix mispelling
  shared/src/business/entities/EntityConstants.ts
Labels: to staging
