Repository ustaxcourt/ef-cms, pull requests merged in 2023-06, with the labels that each got.

#3601 9598 sealed cases feedback to test
  shared/src/business/useCaseHelper/caseAssociation/associateIrsPractitionerToCase.ts
  shared/src/business/useCaseHelper/consolidatedCases/formatConsolidatedCaseCoversheetData.ts
  shared/src/business/useCases/caseAssociationRequest/submitCaseAssociationRequestInteractor.ts
  shared/src/business/useCases/generateCoverSheetData.test.ts
  shared/src/business/useCases/generateCoverSheetData.ts
  shared/src/business/useCases/generateDocketRecordPdfInteractor.test.ts
  shared/src/business/useCases/generateDocketRecordPdfInteractor.ts
  shared/src/proxies/documents/submitCaseAssociationRequestProxy.ts
  shared/src/proxies/generateDocketRecordPdfProxy.ts
  web-api/src/cases/generateDocketRecordPdfLambda.ts
  web-client/integration-tests/externalUserFilesDocumentAcrossConsolidatedCases.test.ts
  web-client/src/presenter/actions/FileDocument/submitRespondentCaseAssociationRequestAction.test.ts
  web-client/src/presenter/actions/FileDocument/submitRespondentCaseAssociationRequestAction.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsAction.test.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsAction.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.test.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.ts
  web-client/src/presenter/computeds/externalConsolidatedCaseGroupHelper.test.ts
  web-client/src/presenter/computeds/externalConsolidatedCaseGroupHelper.ts
  web-client/src/views/CaseDetail/CaseInformation/ConsolidatedCases.tsx
  web-client/src/views/FileDocument/ExternalConsolidatedGroupCards.tsx
Labels: to test

#3609 DD1181-update-docket-record-page-column-header
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: to test

#3580 DX - 1172 Disable past dates for creating or editing trial sessions
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/ustc-ui/DateInput/DateInput.tsx
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging, design debt

#3616 Checkboxes, USWDS style
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/styles/overrides.scss
  web-client/src/ustc-ui/DateInput/DateInput.tsx
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
Labels: to test

#3564 9980 jar progress description
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.test.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  shared/src/proxies/reports/getCasesByStatusAndByJudgeProxy.ts
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/reports/getCasesByStatusAndByJudgeLambda.ts
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrder.ts
  web-client/integration-tests/journey/docketClerkUpdatesCaseStatusTo.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/integration-tests/judgeActivityReportJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/presenter/sequences/JudgeActivityReport/submitJudgeActivityReportSequence.ts
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to staging

#3615 Checkboxes, USWDS style
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/styles/overrides.scss
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
Labels: to staging

#3614 DX - 1173 session copy notes design
  web-client/src/styles/tables.scss
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
Labels: to staging, design debt

#3619 Dependency Updates - Week of May 29, 2023
  package-lock.json
  package.json
Labels: dependencies, to staging

#3623 10046: Updated OAP/OAPF
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/amended-petition-form.pdf._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/amended-petition-form.pdf._S3rver_object.md5
Labels: to test

#3610 Devex: remove jsdocs as a requirement.
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/ustc-story-template.md
  docs/code-review.md
  package-lock.json
  package.json
  scripts/compareTypescriptErrors.ts
  sequenceAudit.js
  web-client/jsdoc.conf.json
Labels: to staging

#3630 10018-Story to test
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/ustc-story-template.md
  docs/code-review.md
  package-lock.json
  package.json
  scripts/compareTypescriptErrors.ts
  sequenceAudit.js
  shared/src/business/entities/DocketEntry.isServed.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/cases/Case.archiveDocketEntry.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/archiveDraftDocumentInteractor.ts
  shared/src/business/useCases/docketEntry/updateDocketEntryMetaInteractor.test.ts
  shared/src/business/useCases/docketEntry/updateDocketEntryMetaInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-client/integration-tests/journey/petitionsDeletesOrderFromCase.ts
  web-client/jsdoc.conf.json
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/archiveDraftDocumentAction.test.ts
  web-client/src/presenter/actions/archiveDraftDocumentAction.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerAction.test.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerAction.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerDocketEntryIdAction.test.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerDocketEntryIdAction.ts
  web-client/src/presenter/actions/setArchiveDraftDocumentAction.ts
  web-client/src/presenter/actions/setShowModalFactoryAction.ts
  web-client/src/presenter/computeds/documentViewerHelper.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.test.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
  web-client/src/presenter/computeds/getShowNotServedForDocument.test.ts
  web-client/src/presenter/computeds/getShowNotServedForDocument.ts
  web-client/src/presenter/computeds/messageDocumentHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/DocketEntry/closeModalAndRefetchCase.ts
  web-client/src/presenter/sequences/archiveDraftDocumentSequence.ts
  web-client/src/presenter/sequences/caseDetailPrimaryTabChangeSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
  web-client/src/views/DraftDocuments/DocketEntryHasAlreadyBeenServedModal.tsx
  web-client/src/views/DraftDocuments/DraftDocuments.tsx
  web-client/src/views/ModalDialog.tsx
Labels: to test

#3638 10046: Updated OAP/OAPF
  docs/code-review.md
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/amended-petition-form.pdf._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/amended-petition-form.pdf._S3rver_object.md5
Labels: to staging

#3648 Bugfix 10061 Document title spacing issue
  shared/src/business/utilities/getDescriptionDisplay.test.ts
  shared/src/business/utilities/getDescriptionDisplay.ts
  shared/src/business/utilities/getFormattedCaseDetail.formatDocketEntry.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-client/integration-tests-public/journey/unauthedUserViewsCaseDetail.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardB.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardC.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardD.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardE.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardF.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardG.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryNonstandardH.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
  web-client/src/views/Public/PublicFilingsAndProceedings.tsx
Labels: bugfix

#3647 9866 Visibility Change for Practitioner-Filed Briefs
  package.json
  scripts/dynamo/set-document-policy-change-date.sh
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.getDocketEntriesFiledByPractitioner.test.ts
  shared/src/business/entities/cases/PublicCase.isPrivateDocument.test.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/entities/cases/PublicDocketEntry.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.test.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests-public/unauthedUserViewsPractitionerFiledBriefOnCase.test.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.test.ts
  web-client/src/presenter/actions/FileDocument/defaultSecondaryDocumentAction.test.ts
  web-client/src/presenter/actions/setMessageDetailViewerDocumentToDisplayAction.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getShowDocumentViewerLink.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
Labels: to staging, Manual Deploy Step(s) Required

#3650 2023 06 09 test backmerge staging
  package.json
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/workflow-terraform/migration/main/lambdas/migrations/0000-validate-all-items.test.js
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.test.ts
  web-client/src/presenter/actions/clearViewerDocumentToDisplayAction.ts
Labels: to test

#3626 9785 add consolidation icons to deadlines report intermediate to test
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/persistence/dynamo/caseDeadlines/createCaseDeadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: Blue/Green Migration, to test

#3652 9784: Consolidation: Add Icons/Count to Pending Report
  shared/src/business/useCases/pendingItems/generatePrintablePendingReportInteractor.test.ts
  shared/src/business/useCases/pendingItems/generatePrintablePendingReportInteractor.ts
  shared/src/business/utilities/documentGenerators/pendingReport.test.ts
  shared/src/business/utilities/htmlGenerator/icons.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/PendingReport.tsx
  shared/src/persistence/elasticsearch/fetchPendingItems.ts
  shared/test-pdf-expected-images/Pending_Report.pdf.1.png
  web-client/src/presenter/computeds/blockedCasesReportHelper.ts
  web-client/src/presenter/computeds/formattedPendingItems.test.ts
  web-client/src/presenter/computeds/formattedPendingItems.ts
  web-client/src/presenter/computeds/utilities/addConsolidatedProperties.test.ts
  web-client/src/presenter/computeds/utilities/addConsolidatedProperties.ts
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
Labels: to staging

#3657 10018-Prevent deletion of served documents
  shared/src/business/entities/DocketEntry.isServed.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/cases/Case.archiveDocketEntry.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/archiveDraftDocumentInteractor.ts
  shared/src/business/useCases/docketEntry/updateDocketEntryMetaInteractor.test.ts
  shared/src/business/useCases/docketEntry/updateDocketEntryMetaInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-client/integration-tests/docketClerkAttemptsToDeleteADraftThatHasAlreadyBeenServed.test.ts
  web-client/integration-tests/journey/petitionsDeletesOrderFromCase.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/archiveDraftDocumentAction.test.ts
  web-client/src/presenter/actions/archiveDraftDocumentAction.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerAction.test.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerAction.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerDocketEntryIdAction.test.ts
  web-client/src/presenter/actions/clearDraftDocumentViewerDocketEntryIdAction.ts
  web-client/src/presenter/actions/setArchiveDraftDocumentAction.ts
  web-client/src/presenter/actions/setShowModalFactoryAction.ts
  web-client/src/presenter/computeds/documentViewerHelper.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.test.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
  web-client/src/presenter/computeds/getShowNotServedForDocument.test.ts
  web-client/src/presenter/computeds/getShowNotServedForDocument.ts
  web-client/src/presenter/computeds/messageDocumentHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/DocketEntry/closeModalAndRefetchCase.ts
  web-client/src/presenter/sequences/archiveDraftDocumentSequence.ts
  web-client/src/presenter/sequences/caseDetailPrimaryTabChangeSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
  web-client/src/views/DraftDocuments/DocketEntryHasAlreadyBeenServedModal.tsx
  web-client/src/views/DraftDocuments/DraftDocuments.tsx
  web-client/src/views/ModalDialog.tsx
Labels: to staging

#3665 add documentation to troubleshooting.md to handle failing Practitione…
  docs/additional-resources/troubleshooting.md
Labels: to staging

#3668 Dependency Updates 06 12 23
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#3678 9785 add consolidation icons to deadlines report
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/useCaseHelper/autoGenerateDeadline.test.ts
  shared/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/persistence/dynamo/caseDeadlines/createCaseDeadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/presenter/computeds/setForHearingModalHelper.ts
  web-client/src/presenter/computeds/statisticsHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/providers/socket.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: Blue/Green Migration, to test

#3627 9785:add consolidation icons to deadlines report
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/useCaseHelper/autoGenerateDeadline.test.ts
  shared/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/persistence/dynamo/caseDeadlines/createCaseDeadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlineFromFormAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/presenter/computeds/setForHearingModalHelper.ts
  web-client/src/presenter/computeds/statisticsHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/providers/socket.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: Blue/Green Migration, to staging

#3684 10043 DevOps User: DLQ Alert to DevOps
  iam/terraform/account-specific/main/service-emails-alarms.tf
Labels: to staging, Manual Deploy Step(s) Required

#3681 10072 BUG: Petitioner Service info and email address are not updating appropriately on cases
  .circleci/config.yml
  cypress/cypress-smoketests/integration/user-post-authentication.cy.ts
  cypress/cypress-smoketests/support/pages/case-detail.ts
  cypress/cypress-smoketests/support/pages/login.ts
  cypress/cypress-smoketests/support/pages/petitioner-dashboard.ts
  iam/terraform/environment-specific/main/update-petitioner-cases-lambda-role.tf
  shared/src/persistence/dynamo/users/createNewPetitionerUser.test.ts
  shared/src/persistence/dynamo/users/createNewPetitionerUser.ts
  shared/src/persistence/dynamo/users/createOrUpdatePractitionerUser.test.ts
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/locals.tf
  web-api/terraform/template/variables.tf
Labels: to staging, Manual Deploy Step(s) Required

#3688 Dep Updates 2023-06-19
  .circleci/config.yml
  .vscode/launch.json
  Dockerfile
  docs/dependency-updates.md
  docs/environments.md
  package-lock.json
  package.json
  scripts/restart-experimental-environment.sh
  scripts/verify-terraform-version.sh
  shared/admin-tools/user/admin.ts
  shared/admin-tools/user/setup-admin.ts
  shared/admin-tools/user/setup-test-users.sh
  shared/admin-tools/user/setup-test-users.ts
  shared/admin-tools/util.ts
  shared/src/business/entities/JoiValidationConstants.ts
  shared/src/business/entities/PractitionerDocument.ts
  shared/src/business/entities/PublicUser.ts
  shared/src/business/entities/User.ts
  shared/src/business/entities/deadlines/DeadlineSearch.ts
  shared/src/business/entities/judgeActivityReport/JudgeActivityReportSearch.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/utilities/getChromiumBrowser.ts
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
Labels: to staging

#3700 10064 coming soon bugfix intermediate branch to test 1687881658
  cypress/cypress-integration/support/pages/public/advanced-search.ts
  scripts/dynamo/delete-order-and-opinion-search-feature-flags.sh
  scripts/dynamo/setup-add-docket-numbers-to-orders-flag.sh
  scripts/dynamo/setup-external-opinion-search-flag.sh
  scripts/dynamo/setup-external-order-search-flag.sh
  scripts/dynamo/setup-internal-opinion-search-flag.sh
  scripts/dynamo/setup-internal-order-search-flag.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/opinionSearch.test.ts
  web-client/integration-tests/opinionSearchFeatureFlag.test.ts
  web-client/integration-tests/orderSearch.test.ts
  web-client/integration-tests/orderSearchFeatureFlag.test.ts
  web-client/src/presenter/computeds/FeatureFlags/featureFlagHelper.test.ts
  web-client/src/presenter/computeds/FeatureFlags/featureFlagHelper.ts
  web-client/src/presenter/sequences/Public/gotoPublicSearchSequence.ts
  web-client/src/presenter/sequences/Public/submitPublicOpinionAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/Public/submitPublicOrderAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/gotoAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/submitOpinionAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/submitOrderAdvancedSearchSequence.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/Public/PublicSearch.tsx
Labels: bugfix

#3699 9769 - Custom Case Report Enhancements with PO Feedback
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to test

#3695 10043 DevOps User: DLQ Alert to DevOps Take 2
  iam/terraform/account-specific/main/service-emails-alarms.tf
  web-api/terraform/main/main.tf
Labels: to staging

#3703 10052: add showDateHint to DateRangePickerComponent
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3701 10070 Remove DSC as Document Option intermediate branch to test 1687898248
  shared/src/tools/Event Codes - External Filings - Internal Document List.csv
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
Labels: to test

#3702 10064 coming soon bugfix
  cypress/cypress-integration/support/pages/public/advanced-search.ts
  scripts/dynamo/delete-order-and-opinion-search-feature-flags.sh
  scripts/dynamo/setup-add-docket-numbers-to-orders-flag.sh
  scripts/dynamo/setup-external-opinion-search-flag.sh
  scripts/dynamo/setup-external-order-search-flag.sh
  scripts/dynamo/setup-internal-opinion-search-flag.sh
  scripts/dynamo/setup-internal-order-search-flag.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/featureFlag/getFeatureFlagValueInteractor.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/opinionSearch.test.ts
  web-client/integration-tests/opinionSearchFeatureFlag.test.ts
  web-client/integration-tests/orderSearch.test.ts
  web-client/integration-tests/orderSearchFeatureFlag.test.ts
  web-client/src/presenter/computeds/FeatureFlags/featureFlagHelper.test.ts
  web-client/src/presenter/computeds/FeatureFlags/featureFlagHelper.ts
  web-client/src/presenter/sequences/Public/gotoPublicSearchSequence.ts
  web-client/src/presenter/sequences/Public/submitPublicOpinionAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/Public/submitPublicOrderAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/gotoAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/submitOpinionAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/submitOrderAdvancedSearchSequence.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/Public/PublicSearch.tsx
Labels: bugfix, to staging, Manual Deploy Step(s) Required
