Repository ustaxcourt/ef-cms, pull requests merged in 2023-02, with the labels that each got.

#3029 DevEx - Convert DocketEntry to typescript
  shared/src/business/dto/TrialSessionInfoDto.ts
  shared/src/business/entities/DocketEntry.js
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/JoiValidationDecorator.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/useCases/addCoverToPdf.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/docketEntry/updateCourtIssuedDocketEntryInteractor.ts
  shared/src/business/useCases/generateCoverSheetData.ts
  shared/src/business/useCases/getReconciliationReportInteractor.ts
  shared/src/business/useCases/trialSessions/canSetTrialSessionAsCalendaredInteractor.test.ts
  shared/src/business/useCases/trialSessions/canSetTrialSessionAsCalendaredInteractor.ts
  shared/src/business/useCases/trialSessions/createTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/createTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/generateNoticeOfChangeOfTrialJudgeInteractor.ts
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.ts
  shared/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsForJudgeInteractor.ts
  shared/src/business/useCases/trialSessions/getTrialSessionsInteractor.ts
  shared/src/business/useCases/trialSessions/validateTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/validateTrialSessionInteractor.ts
  shared/src/persistence/dynamo/trialSessions/addCaseToHearing.ts
  shared/src/persistence/dynamo/trialSessions/createTrialSession.ts
  shared/src/persistence/dynamo/trialSessions/getTrialSessions.ts
  shared/src/persistence/dynamo/trialSessions/updateCaseHearing.ts
  shared/src/persistence/dynamo/trialSessions/updateTrialSession.ts
  types/TEntity.d.ts
  web-api/storage/scripts/seedLocalDatabase.js
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/pa11y/helpers.js
  web-client/pa11y/pa11y-ci.web-client-1.config.js
  web-client/pa11y/pa11y-ci.web-client-2.config.js
  web-client/pa11y/pa11y-ci.web-client-3.config.js
  web-client/pa11y/pa11y-ci.web-client-4.config.js
Labels: to staging

#3054 devex-1063: fixing a few issues with the setup glued judges script
  shared/admin-tools/user/setup-glued-judges.js
Labels: to staging

#3103 Dependency Updates 2/10/2023
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  scripts/verify-terraform-version.sh
Labels: to staging

#3102 Bug 9781 practitioner not updating
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.test.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.ts
  shared/src/persistence/dynamo/users/updatePractitionerUser.test.ts
  shared/src/persistence/dynamo/users/updatePractitionerUser.ts
Labels: to test

#3105 9595: Visibility Across Consolidated Case Group
  cypress-integration/integration/start-a-case-practitioner.cy.js
  shared/src/business/entities/cases/Case.isPetitionerPartOfGroup.test.js
  shared/src/business/entities/cases/Case.isUserPartOfGroup.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCaseHelper/consolidatedCases/formatAndSortConsolidatedCases.js
  shared/src/business/useCaseHelper/consolidatedCases/formatAndSortConsolidatedCases.test.js
  shared/src/business/useCaseHelper/consolidatedCases/getUnassociatedLeadCase.js
  shared/src/business/useCaseHelper/consolidatedCases/getUnassociatedLeadCase.test.js
  shared/src/business/useCaseHelper/consolidatedCases/processUserAssociatedCases.js
  shared/src/business/useCaseHelper/consolidatedCases/processUserAssociatedCases.test.js
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/persistence/dynamo/users/getCasesForUser.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/consolidatedGroupAccessJourney.test.js
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/integration-tests/petitionerAccessesAssociatedConsolidatedGroupCase.test.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/getCaseAssociationAction.test.ts
  web-client/src/presenter/actions/getCaseAssociationAction.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: to test

#3056 devex-1082: add more metrics for segments
  aws/lambdas/LogsToElasticSearch_info/index-template.json
  scripts/dynamo/delete-dynamo-table.sh
  setup-for-blue-green-migration.sh
  shared/admin-tools/dynamodb/read-segment.js
  shared/src/business/utilities/DateHandler.js
  shared/src/business/utilities/DateHandler.test.js
  web-api/elasticsearch/client.js
  web-api/migration-cron-terraform/main/lambdas/reindex-status.js
  web-api/migration-cron-terraform/main/reindex-status.tf
  web-api/migration-terraform/main/lambdas/migration-segments.js
  web-api/migration-terraform/main/lambdas/migration-segments.test.js
  web-api/migration-terraform/main/migration-segments.tf
  web-api/migration-terraform/main/migration.tf
  web-api/switch-colors-cron-terraform/main/switch-colors.tf
Labels: to staging

#3117 1101 - Test backmerge
  docs/aws.md
  docs/team-process.md
  scripts/change-chief-judge.sh
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/cases/Case.isSealedCase.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/generateDocketRecordPdfInteractor.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.js
  shared/src/business/utilities/setConsolidationFlagsForDisplay.test.js
  shared/src/persistence/dynamo/workitems/createSectionOutboxRecords.ts
  shared/src/persistence/dynamo/workitems/createUserOutboxRecord.ts
  shared/src/persistence/dynamo/workitems/saveWorkItemForDocketClerkFilingExternalDocument.ts
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.2.png
  types/TEntity.d.ts
  web-api/src/applicationContext.js
  web-api/src/getPersistenceGateway.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/swagger.json
  web-client/integration-tests/docketClerkConsolidatedCaseWorkItemsJourney.test.js
  web-client/integration-tests/docketClerkConsolidatesCases.test.js
  web-client/integration-tests/docketClerkServesCourtIssuedDocumentOnLeadCaseFromMessageDetail.test.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
  web-client/src/presenter/computeds/caseDetailHelper.ts
  web-client/src/presenter/computeds/caseInformationHelper.ts
  web-client/src/presenter/computeds/draftDocumentViewerHelper.test.ts
  web-client/src/presenter/computeds/formattedEligibleCasesHelper.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.js
  web-client/src/presenter/computeds/formattedTrialSessionDetailsForFilteredEligibleCases.test.js
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test

#3114 1109-Design Debt: Change column header to Title Case
  web-client/src/views/DocketRecord/DocumentViewer.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.tsx
Labels: to test

#3140 dep-updates - for all node 16
  .github/workflows/api.yml
  .github/workflows/build-ts-api.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
Labels: to staging

#3120 Devex 1101
  shared/src/business/entities/cases/Case.isSealedCase.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/generateDocketRecordPdfInteractor.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-api/src/applicationContext.js
  web-client/integration-tests-public/journey/unauthedUserViewsCaseDetailForSealedCase.js
  web-client/integration-tests/journey/associatedUserViewsCaseDetailForSealedCase.js
  web-client/integration-tests/journey/docketClerkSealsCase.js
  web-client/integration-tests/journey/docketClerkUnsealsCase.js
  web-client/integration-tests/journey/petitionerSearchesForUnassociatedSealedCase.js
  web-client/integration-tests/journey/practitionerSearchesForUnassociatedSealedCase.js
  web-client/integration-tests/journey/unassociatedUserViewsCaseDetailForSealedCase.js
  web-client/integration-tests/journey/unassociatedUserViewsCaseDetailForUnsealedCase.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
  web-client/src/presenter/computeds/caseDetailHelper.ts
  web-client/src/presenter/computeds/caseInformationHelper.ts
  web-client/src/presenter/computeds/sealedCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/sealedCaseDetailHelper.ts
Labels: to staging

#3145 9595: feedback to `test`
  shared/src/business/entities/cases/Case.isUserPartOfGroup.test.js
  shared/src/business/entities/cases/Case.js
Labels: to test

#3163 9845: fix live migration
  web-api/migration-terraform/main/lambdas/migration.js
  web-api/migration-terraform/main/lambdas/migration.test.js
Labels: to staging

#3148 opex: lower socket timeout for s3
  web-api/src/applicationContext.js
Labels: to staging

#3155 9595: Visibility Across Consolidated Case Group
  cypress-integration/integration/start-a-case-practitioner.cy.js
  shared/src/business/entities/cases/Case.isPetitionerPartOfGroup.test.js
  shared/src/business/entities/cases/Case.isUserPartOfGroup.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCaseHelper/consolidatedCases/formatAndSortConsolidatedCases.js
  shared/src/business/useCaseHelper/consolidatedCases/formatAndSortConsolidatedCases.test.js
  shared/src/business/useCaseHelper/consolidatedCases/getUnassociatedLeadCase.js
  shared/src/business/useCaseHelper/consolidatedCases/getUnassociatedLeadCase.test.js
  shared/src/business/useCaseHelper/consolidatedCases/processUserAssociatedCases.js
  shared/src/business/useCaseHelper/consolidatedCases/processUserAssociatedCases.test.js
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/persistence/dynamo/users/getCasesForUser.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/consolidatedGroupAccessJourney.test.js
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/integration-tests/petitionerAccessesAssociatedConsolidatedGroupCase.test.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/getCaseAssociationAction.test.ts
  web-client/src/presenter/actions/getCaseAssociationAction.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: to staging

#3169 9818 Story to Test
  scripts/dynamo/setup-e-consent-fields-enabled-feature-flag.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/contacts/ContactFactory.js
  shared/src/business/entities/contacts/Petitioner.js
  shared/src/business/entities/contacts/Petitioner.test.js
  shared/src/business/useCases/updatePetitionerInformationInteractor.test.ts
  shared/src/business/useCases/updatePetitionerInformationInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/eConsentJourney.test.js
  web-client/src/presenter/actions/StartCaseInternal/setDefaultStartCaseInternalFormAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setDefaultStartCaseInternalFormAction.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.ts
  web-client/src/presenter/computeds/contactsHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
  web-client/src/presenter/computeds/partiesInformationHelper.test.ts
  web-client/src/presenter/computeds/partiesInformationHelper.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.test.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.ts
  web-client/src/presenter/computeds/startCaseInternalContactsHelper.test.ts
  web-client/src/presenter/computeds/startCaseInternalContactsHelper.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/gotoPetitionQcSequence.ts
  web-client/src/presenter/sequences/gotoReviewSavedPetitionSequence.ts
  web-client/src/presenter/sequences/gotoStartCaseWizardSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
  web-client/src/views/CaseDetailEdit/CaseDetailEdit.tsx
  web-client/src/views/CaseDetailEdit/PartyInformation.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCaseInternal/Parties.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
Labels: Manual Deploy Step(s) Required

#3158 env switcher - SOURCE_TABLE and SOURCE_TABLE_VERSION are different things
  scripts/env/env-for-circle.sh
  scripts/env/environments/00-common
  scripts/env/from-file.sh
  scripts/env/set-env.zsh
Labels: to staging

#3180 DevEx: env switcher - fixing broken ES endpoint environment variable
  scripts/env/environments/00-common
Labels: to staging

#3173 1109 base - Design Debt
  web-client/src/views/CaseDetail/MessagesCompleted.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test
