Repository ustaxcourt/ef-cms, pull requests merged in 2023-07, with the labels that each got.

#3712 DD1181: change column header in DocumentView component from 'Index' t…
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: to test

#3717 9998 full run for all judges intermediate branch to test 1687755209
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
Labels: to test

#3722 9998 full run for all judges intermediate branch to test
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  web-client/src/presenter/judgeActivityReportState.ts
Labels: to test

#3718 10075 BUG: Multi-docketing UI appears when serving Simultaneous e-filings in Lead case
  shared/src/business/entities/DocketEntry.isAutoServed.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.test.ts
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.ts
Labels: bugfix

#3713 DD1181: change column header in DocumentView component from 'Index' t…
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: to staging

#3706 update team charter 2023
  README.md
  docs/additional-resources/DAWSON-team-charter.md
  docs/additional-resources/how-we-work.md
Labels: to staging

#3708 Devex 1188: Transition ExternalDocumentFactory and related entities to ES6
  shared/jest-shared.config.ts
  shared/src/business/entities/ReconciliationReportEntry.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/entities/docketEntry/DocketEntryFactory.ts
  shared/src/business/entities/externalDocument/ExternalDocumentBase.ts
  shared/src/business/entities/externalDocument/ExternalDocumentFactory.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardA.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardA.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardB.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardB.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardC.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardC.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardD.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardD.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardE.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardE.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardF.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardF.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardG.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardG.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardH.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardH.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardI.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardI.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardJ.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentNonStandardJ.ts
  shared/src/business/entities/externalDocument/ExternalDocumentStandard.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentStandard.ts
  shared/src/persistence/s3/getDownloadPolicyUrl.test.ts
Labels: to staging

#3686 10052 public search date range
  shared/src/business/entities/cases/CaseSearch.test.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/useCases/caseAdvancedSearchInteractor.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.ts
  shared/src/business/utilities/aggregateCommonQueryParams.test.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  shared/src/persistence/elasticsearch/caseAdvancedSearch.ts
  shared/src/persistence/elasticsearch/casePublicSearch.ts
  web-api/src/applicationContext.ts
  web-client/integration-tests/journey/irsSuperuserAdvancedSearchForCase.ts
  web-client/integration-tests/journey/petitionsClerkAdvancedSearchForCase.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultCaseSearchDatesAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultCaseSearchDatesAction.ts
  web-client/src/presenter/actions/AdvancedSearch/validateCaseAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Public/submitPublicCaseAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/submitCaseAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/updateCaseAdvancedSearchByNameFormValueSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to staging

#3727 10070 remove dsc as document option - with PO feedback
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/internalFilingEvents.json
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/internalTypesHelper.test.ts
  web-client/src/presenter/computeds/internalTypesHelper.ts
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
Labels: to test

#3728 9998 - Async endpoint conversion - Intermediate
  shared/src/business/useCases/judgeActivityReport/getOpinionsFiledByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getOpinionsFiledByJudgeInteractor.ts
  shared/src/business/useCases/judgeActivityReport/getOrdersFiledByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getOrdersFiledByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getCasesClosedByJudge.test.ts
  shared/src/persistence/elasticsearch/getCasesClosedByJudge.ts
  shared/src/proxies/reports/getOpinionsFiledByJudgeProxy.ts
  shared/src/proxies/reports/getOrdersFiledByJudgeProxy.ts
  web-api/src/app.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/src/presenter/actions/JudgeActivityReport/getCasesClosedByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getOpinionsForJudgeActivityReportAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getOpinionsForJudgeActivityReportAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/getOrdersIssuedForJudgeActivityReportAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getOrdersIssuedForJudgeActivityReportAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/getTrialSessionsForJudgeActivityReportAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportOrdersAndOpinionsDataAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportOrdersAndOpinionsDataAction.ts
  web-client/src/presenter/judgeActivityReportState.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/JudgeActivityReport/fetchOrdersAndOpinionsForJudgesCompleteSequence.ts
  web-client/src/presenter/sequences/JudgeActivityReport/submitJudgeActivityReportSequence.ts
  web-client/src/providers/socketRouter.ts
Labels: to test

#3735 10070 Remove DSC as Document Option for E-Filing/Paper Filing
  shared/src/business/entities/EntityConstants.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/internalTypesHelper.test.ts
  web-client/src/presenter/computeds/internalTypesHelper.ts
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
Labels: to staging

#3754 1191: remove optional time text
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to test

#3749 Dependency Updates July Week 2
  .circleci/config.yml
  Dockerfile
  docs/terraform.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/src/business/useCases/getCasesForUserInteractor.ts
  web-client/integration-tests/judgeActivityReportJourney.test.ts
Labels: to staging

#3752 9998 - UX - Progress Spinner for Async Calls + Case closed Aggregation
  shared/src/business/useCases/judgeActivityReport/getCasesClosedByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesClosedByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getCasesClosedByJudge.test.ts
  shared/src/persistence/elasticsearch/getCasesClosedByJudge.ts
  shared/src/persistence/elasticsearch/searchClient.test.constants.ts
  shared/src/persistence/elasticsearch/searchClient.ts
  shared/src/proxies/reports/getCasesClosedByJudgeProxy.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/src/presenter/judgeActivityReportState.ts
  web-client/src/presenter/sequences/JudgeActivityReport/fetchOrdersAndOpinionsForJudgesCompleteSequence.ts
Labels: to test

#3756 Devex: typescript-ify the check-secrets script
  package-lock.json
  package.json
  shared/admin-tools/user/list-users-with-expired-credentials.js
  shared/admin-tools/user/list-users-with-expired-credentials.test.ts
  shared/admin-tools/user/list-users-with-expired-credentials.ts
  shared/admin-tools/user/rotate-environment-secrets.ts
Labels: to staging

#3765 1191: remove optional time text
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging

#3745 10075 Bug: Multi-docketing UI appears when serving Simultaneous e-filings in Lead case
  shared/src/business/entities/DocketEntry.isAutoServed.test.ts
  shared/src/business/useCases/addCoversheetInteractor.test.ts
  shared/src/business/useCases/addCoversheetInteractor.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.test.ts
  shared/src/business/useCases/document/serveExternallyFiledDocumentInteractor.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/getDocketNumbersForConsolidatedServiceAction.test.ts
  web-client/src/presenter/actions/getDocketNumbersForConsolidatedServiceAction.ts
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.test.ts
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.ts
Labels: bugfix, to staging

#3767 10069: BUG: East-West domain failover mechanism not triggering
  .circleci/config.yml
  docs/aws.md
  docs/terraform.md
  shared/src/business/useCases/health/getHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.ts
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
  web-client/src/presenter/actions/getHealthCheckAction.test.ts
  web-client/terraform/main/main.tf
  web-client/terraform/main/outputs.tf
Labels: to test

#3774 10069: Caching SES health
  package-lock.json
  package.json
  shared/src/persistence/ses/getSesStatus.test.ts
  shared/src/persistence/ses/getSesStatus.ts
  web-client/terraform/main/main.tf
Labels: to test

#3763 Dep Updates - July 2023 Week 3
  cypress/cypress-smoketests/support/pages/advanced-search.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  shared/src/business/utilities/generateHTMLTemplateForPDF/generateHTMLTemplateForPDF.test.ts
Labels: to staging

#3776 9998 CAV/Submitted Cases Feedback
  shared/src/business/entities/judgeActivityReport/JudgeActivityReportSearch.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.test.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  shared/src/proxies/reports/getCasesByStatusAndByJudgeProxy.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setCavAndSubmittedCasesAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setCavAndSubmittedCasesAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/presenter/judgeActivityReportState.ts
  web-client/src/presenter/sequences/JudgeActivityReport/getCavAndSubmittedCasesForJudgesSequence.ts
  web-client/src/presenter/sequences/JudgeActivityReport/submitJudgeActivityReportSequence.ts
  web-client/src/styles/overrides.scss
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3783 10076: Extend Visibility Changes to Amended/Supplemental/Redacted Briefs
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/PublicCase.isPrivateDocument.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/entities/cases/PublicDocketEntry.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/persistence/s3/getPublicDownloadPolicyUrl.ts
  web-api/src/app-public.ts
  web-api/storage/fixtures/seed/caseWithAmendedAndRedactedBriefs.json
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/index.ts
  web-client/integration-tests-public/unauthedAmendedAndRedactedBriefVisibilityJourney.test.ts
  web-client/integration-tests/amendedAndRedactedBriefVisibilityJourney.test.ts
  web-client/integration-tests/helpers.ts
  web-client/jest-unit.config.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseInventoryFiltersAction.test.ts
  web-client/src/presenter/actions/getAllFeatureFlagsAction.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/state.ts
Labels: to staging

#3778 Dependencies Week of July 24
  .circleci/config.yml
  Dockerfile
  docs/backend.md
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  stylelint.config.js
  web-client/integration-tests/verifyCheckReadyForTrial.test.ts
Labels: to staging
