Repository ustaxcourt/ef-cms, pull requests merged in 2023-08, with the labels that each got.

#3785 10069: health checks sans failover
  .circleci/config.yml
  docs/aws.md
  docs/terraform.md
  package-lock.json
  package.json
  shared/src/business/useCases/health/getHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.ts
  shared/src/persistence/ses/getSesStatus.test.ts
  shared/src/persistence/ses/getSesStatus.ts
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
  web-client/src/presenter/actions/getHealthCheckAction.test.ts
  web-client/terraform/main/main.tf
  web-client/terraform/main/outputs.tf
Labels: to staging

#3786 flakey test: docketClerkCaseInventoryReport
  web-client/integration-tests/docketClerkCaseInventoryReport.test.ts
Labels: to test

#3795 10116 health check stability
  iam/terraform/environment-specific/main/lambda.tf
  run-api.sh
  run-local.sh
  shared/src/business/useCases/health/getCachedHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getCachedHealthCheckInteractor.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.test.ts
  shared/src/business/useCases/health/getHealthCheckInteractor.ts
  shared/src/business/useCases/health/setHealthCheckCacheInteractor.test.ts
  shared/src/business/useCases/health/setHealthCheckCacheInteractor.ts
  shared/src/persistence/dynamo/deployTable/getStoredApplicationHealth.ts
  shared/src/persistence/dynamo/deployTable/setStoredApplicationHealth.ts
  shared/src/persistence/dynamodbClientService.test.ts
  shared/src/persistence/dynamodbClientService.ts
  shared/src/persistence/ses/getSesStatus.test.ts
  shared/src/persistence/ses/getSesStatus.ts
  shared/src/proxies/health/getCachedHealthCheckProxy.ts
  web-api/src/app-public.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/health/getCachedHealthCheckLambda.ts
  web-api/src/health/setHealthCheckCacheLambda.ts
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/api/cron.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/template/lambdas/cron.js
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-client/terraform/main/main.tf
Labels: to test

#3796 9998 - Judge Activity Report - DOD (Tests + Spinner)
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/test/mockCase.ts
  tsconfig.json
  web-api/storage/fixtures/seed/cav-submitted-cases.ts
  web-api/storage/fixtures/seed/index.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/src/presenter/actions/JudgeActivityReport/checkJudgeActivityReportOpinionsAndOrdersIsSetAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/checkJudgeActivityReportOpinionsAndOrdersIsSetAction.ts
  web-client/src/presenter/sequences/JudgeActivityReport/submitJudgeActivityReportSequence.ts
Labels: to test

#3797 De flakeify docket clerk case inventory report
  web-client/integration-tests/docketClerkCaseInventoryReport.test.ts
Labels: to staging

#3787 Absolute Imports to all areas of application
  package-lock.json
  package.json
  shared/src/business/entities/Batch.ts
  tsconfig.json
  web-api/jest-unit.config.ts
  web-api/src/applicationContext.ts
  webpack.config.lambda.js
  webpack.config.lambda.rotate-info-indices.js
Labels: to staging

#3808 allow ts-node to be run in our projects with the paths property
  package-lock.json
  package.json
  tsconfig.json
Labels: to staging

#3809 Dep updates 2023 08 03
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  patches/s3rver+3.7.1.patch
Labels: to staging

#3810 Fix typescript count
  scripts/compareTypescriptErrors.ts
Labels: to staging

#3807 Default variable to empty string when there is no health check id.
  web-client/terraform/main/outputs.tf
Labels: to staging

#3813 Introduce SSO to Environment Switcher; deprecating IAM Users and keys
  docs/additional-resources/environment-switcher.md
  iam/terraform/account-specific/bin/deploy-init.sh
  iam/terraform/account-specific/main/dawson-dev.tf
  iam/terraform/account-specific/main/variables.tf
  package.json
  scripts/env/assume-role.zsh
  scripts/env/aws-accounts/example.env
  scripts/env/environments/example.env
  scripts/env/set-env.zsh
  scripts/env/unset-env.zsh
  shared/admin-tools/user/list-users-with-expired-credentials.test.ts
  shared/admin-tools/user/list-users-with-expired-credentials.ts
Labels: Manual Deploy Step(s) Required

#3707 Resolve race condition undrafting
  package-lock.json
  package.json
  shared/admin-tools/dynamodb/fix-race-condition-served-in-drafts.test.ts
  shared/admin-tools/dynamodb/fix-race-condition-served-in-drafts.ts
  shared/src/business/entities/DocketEntry.setAsServed.test.ts
  shared/src/business/entities/DocketEntry.ts
Labels: to staging

#3856 10081: Add Judge Selection as Field For Adding SPTO/SPOS Docket Entries
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/judgeActivityReport/getOpinionsFiledByJudgeInteractor.ts
  shared/src/business/useCases/judgeActivityReport/getOrdersFiledByJudgeInteractor.ts
  shared/src/business/useCases/opinionAdvancedSearchInteractor.ts
  shared/src/business/useCases/orderAdvancedSearchInteractor.ts
  shared/src/business/useCases/public/getTodaysOpinionsInteractor.ts
  shared/src/business/useCases/public/getTodaysOrdersInteractor.ts
  shared/src/business/useCases/public/opinionPublicSearchInteractor.ts
  shared/src/business/useCases/public/orderPublicSearchInteractor.ts
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.ts
  shared/src/tools/courtIssuedEventCodes.json
  tsconfig.json
  web-api/elasticsearch/index-types.ts
  web-api/src/applicationContext.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearch.test.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearch.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearchHelpers/getJudgeFilterForOpinionSearch.test.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearchHelpers/getJudgeFilterForOpinionSearch.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearchHelpers/getJudgeFilterForOrderSearch.test.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearchHelpers/getJudgeFilterForOrderSearch.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearchHelpers/getSealedQuery.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/2b26cc62-e79b-4811-a8f5-57c71d4431d8._S3rver_metadata.json
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/2b26cc62-e79b-4811-a8f5-57c71d4431d8._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/2b26cc62-e79b-4811-a8f5-57c71d4431d8._S3rver_object.md5
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0011-add-filed-by-role.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0011-add-filed-by-role.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0012-remove-signed-judge-on-spos-spto.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0012-remove-signed-judge-on-spos-spto.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/sptoSposRequiresJudgeJourney.test.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
  web-client/src/presenter/computeds/Public/todaysOrdersHelper.test.ts
  web-client/src/presenter/computeds/Public/todaysOrdersHelper.ts
Labels: Blue/Green Migration

#3877 9998 - Refactor fetching of CAV and Submitted Cases - to test
  .github/workflows/backmerge-PR.yml
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/pages/start-a-case.ts
  package-lock.json
  package.json
  scripts/elasticsearch/ready-cluster-for-migration.helpers.test.ts
  scripts/elasticsearch/ready-cluster-for-migration.helpers.ts
  scripts/elasticsearch/ready-cluster-for-migration.ts
  scripts/jest-scripts.config.ts
  setup-for-blue-green-migration.sh
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/business/useCases/opinionAdvancedSearchInteractor.ts
  shared/src/test/mockCase.ts
  tsconfig.json
  web-api/elasticsearch/index-types.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearch.ts
  web-api/src/persistence/elasticsearch/fetchEventCodesCountForJudges.test.ts
  web-api/src/persistence/elasticsearch/getCasesByEventCodes.test.ts
  web-api/src/persistence/elasticsearch/getCasesByEventCodes.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.test.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  web-api/src/persistence/elasticsearch/helpers/searchQueryForAggregation.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0007-update-corporate-disclosure-document.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0008-add-assignee-id-gsi2pk-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0009-add-trial-location-field-to-work-item.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0010-add-lead-docket-number-to-case-deadline.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0011-add-filed-by-role.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0011-add-filed-by-role.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/docketClerkServesCourtIssuedDocument.test.ts
  web-client/integration-tests/journey/consolidation/createConsolidatedGroup.ts
  web-client/integration-tests/journey/docketClerkChecksDocketEntryEditLink.ts
  web-client/integration-tests/journey/docketClerkNavigatesToEditDocketEntryMeta.ts
  web-client/integration-tests/journey/docketClerkServesDocument.ts
  web-client/integration-tests/journey/docketClerkViewsCaseDetailAfterServingCourtIssuedDocument.ts
  web-client/integration-tests/judgeActivityReportJourney.test.ts
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3898 9998 - DOD - to test
  shared/src/business/useCases/judgeActivityReport/addDocumentTypeToEventCodeAggregation.test.ts
  shared/src/business/useCases/judgeActivityReport/addDocumentTypeToEventCodeAggregation.ts
  shared/src/business/useCases/judgeActivityReport/getCountOfOpinionsFiledByJudgesInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCountOfOpinionsFiledByJudgesInteractor.ts
  shared/src/business/useCases/judgeActivityReport/getCountOfOrdersFiledByJudgesInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCountOfOrdersFiledByJudgesInteractor.ts
  web-api/src/persistence/elasticsearch/fetchEventCodesCountForJudges.test.ts
  web-api/src/persistence/elasticsearch/fetchEventCodesCountForJudges.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.test.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3899 10135 cypress search flaky test
  .github/ISSUE_TEMPLATE/flaky-test.md
  cypress/cypress-smoketests/support/pages/advanced-search.ts
  package.json
Labels: to staging

#3895 DepUpdate: Update NPM Packages;
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging, Manual Deploy Step(s) Required

#3901 Fix test deploy step temp solution
  .circleci/config.yml
Labels: to test
