Repository ustaxcourt/ef-cms, pull requests merged in 2023-10, with the labels that each got.

#4000 Devex: added a "build-and-deploy-empty" workflow for deploying an environment with empty persistence
  .circleci/config.yml
  shared/admin-tools/user/setup-glued-judges.ts
Labels: to staging

#4010 Devex 1214: Changing paginator page scrolls to the top of the table
  web-client/src/presenter/utilities/focusPaginatorTop.test.ts
  web-client/src/presenter/utilities/focusPaginatorTop.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to staging

#3990 devex: Remove duplicate test setup
  web-client/integration-tests/helpers.ts
Labels: to staging

#4040 9788 UX feedback - to test
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.test.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Trial_Calendar_No_Lead_Case.pdf.1.png
Labels: to test

#4044 10136 bugfix
  web-client/integration-tests/practitionerDashboard.test.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.test.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
Labels: to test

#3987 9995 refactor
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCaseHelper/getJudgeForUserHelper.test.ts
  shared/src/business/useCaseHelper/getJudgeForUserHelper.ts
  shared/src/business/useCases/caseWorksheet/getCaseWorksheetsForJudgeInteractor.test.ts
  shared/src/business/useCases/caseWorksheet/getCaseWorksheetsForJudgeInteractor.ts
  shared/src/business/useCases/caseWorksheet/updateCaseWorksheetInteractor.test.ts
  shared/src/business/useCases/caseWorksheet/updateCaseWorksheetInteractor.ts
  shared/src/business/useCases/users/updateUserPendingEmailInteractor.test.ts
  shared/src/test/mockUsers.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/src/lambdas/caseWorksheet/getCaseWorksheetsForJudgeLambda.ts
  web-client/src/styles/custom.scss
Labels: to staging

#4047 10039: default case count to 1 per UX feedback
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
Labels: to test

#4032 Devex fix test serve case to irs
  cypress/cypress-smoketests/integration/case-creation.cy.ts
  cypress/cypress-smoketests/integration/court-issued-documents.cy.ts
  cypress/cypress-smoketests/integration/create-trial-session.cy.ts
  cypress/cypress-smoketests/integration/search.cy.ts
  cypress/cypress-smoketests/integration/user-post-authentication.cy.ts
  cypress/cypress-smoketests/support/pages/case-detail.ts
  cypress/cypress-smoketests/support/pages/create-paper-case-local.ts
  cypress/cypress-smoketests/support/pages/create-paper-case.ts
  cypress/cypress-smoketests/support/pages/environment-specific-factory.ts
Labels: to staging

#4045 9788 - Add Consolidation Icons to Printable Copy of Trial Session Information
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.test.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/htmlGenerator/cards.scss
  shared/src/business/utilities/htmlGenerator/documents/notice-of-docket-change.scss
  shared/src/business/utilities/htmlGenerator/documents/printable-working-copy-list.scss
  shared/src/business/utilities/htmlGenerator/documents/trial-calendar.scss
  shared/src/business/utilities/htmlGenerator/index-main.scss
  shared/src/business/utilities/htmlGenerator/shared.scss
  shared/src/business/utilities/htmlGenerator/tables.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfDocketChange.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Trial_Calendar.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Lead_Case.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Session_Notes.pdf.1.png
  web-api/src/persistence/dynamo/trialSessions/getCalendaredCasesForTrialSession.ts
  web-client/src/presenter/actions/TrialSession/getCalendaredCasesForTrialSessionAction.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
Labels: to staging

#4057 10136 - DOD
  shared/src/business/entities/UserCase.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/proxies/getCasesForUserProxy.ts
  web-api/src/persistence/dynamo/cases/getCaseMetadataWithCounsel.ts
  web-api/src/persistence/dynamo/cases/getCasesMetadataByLeadDocketNumber.ts
  web-api/src/persistence/dynamo/helpers/aggregateCaseItems.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.ts
  web-client/src/presenter/actions/Dashboard/getOpenAndClosedCasesForUserAction.ts
  web-client/src/presenter/actions/setCasesAction.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
  web-client/src/presenter/state.ts
Labels: to test

#4056 10136 Bug: The My Cases page is not displaying the correct Open/Closed Cases count if a party is associated with a Consolidated Group
  shared/src/business/entities/UserCase.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/proxies/getCasesForUserProxy.ts
  web-api/src/persistence/dynamo/cases/getCaseMetadataWithCounsel.ts
  web-api/src/persistence/dynamo/cases/getCasesMetadataByLeadDocketNumber.ts
  web-api/src/persistence/dynamo/helpers/aggregateCaseItems.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.ts
  web-client/integration-tests/practitionerDashboard.test.ts
  web-client/src/presenter/actions/Dashboard/getOpenAndClosedCasesForUserAction.ts
  web-client/src/presenter/actions/setCasesAction.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.test.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
  web-client/src/presenter/state.ts
Labels: to staging

#4061 Design Debt 1159: Session Copy page - implement new sort arrows
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/toggleWorkingCopySortAction.test.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/toggleWorkingCopySortAction.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.test.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.ts
  web-client/src/presenter/computeds/sortableColumnHelper.test.ts
  web-client/src/presenter/computeds/sortableColumnHelper.ts
  web-client/src/presenter/sequences/sortTableSequence.ts
  web-client/src/presenter/sequences/toggleWorkingCopySortSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/SortableColumnHeaderButton/SortableColumnHeaderButton.tsx
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/Practitioners/PractitionerDocumentation.tsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.tsx
Labels: to test

#4065 10161: Activity Report/Judge Dashboard: Remove Decision Doc Criteria
  scripts/run-once-scripts/open-search-playground.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/business/utilities/calculateDaysElapsedSinceLastStatusChange.test.ts
  shared/src/business/utilities/calculateDaysElapsedSinceLastStatusChange.ts
  shared/src/proxies/reports/getCasesByStatusAndByJudgeProxy.ts
  shared/src/test/mockCase.ts
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUtilities.ts
  web-api/src/lambdas/reports/getCasesByStatusAndByJudgeLambda.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersWithServedEventCodes.test.ts
  web-api/src/persistence/elasticsearch/getDocketNumbersWithServedEventCodes.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/swagger.json
  web-api/workflow-terraform/migration/main/lambdas/migrations/0012-remove-signed-judge-on-spos-spto.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0014-default-case-status-history.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0014-default-case-status-history.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseWorksheet/getSubmittedAndCavCasesForCurrentJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setCavAndSubmittedCasesAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setCavAndSubmittedCasesAction.ts
  web-client/src/presenter/actions/getJudgeForCurrentUserAction.ts
  web-client/src/presenter/actions/passAlongJudgeUserAction.test.ts
  web-client/src/presenter/actions/passAlongJudgeUserAction.ts
  web-client/src/presenter/actions/setJudgeUserAction.test.ts
  web-client/src/presenter/actions/setJudgeUserAction.ts
  web-client/src/presenter/computeds/CaseWorksheets/caseWorksheetsHelper.test.ts
  web-client/src/presenter/computeds/CaseWorksheets/caseWorksheetsHelper.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/presenter/judgeActivityReportState.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/JudgeActivityReport/getCavAndSubmittedCasesForJudgesSequence.ts
  web-client/src/presenter/sequences/gotoDashboardSequence.test.ts
  web-client/src/presenter/sequences/gotoDashboardSequence.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: Blue/Green Migration, to test

#4067 10160: increase NOTT reminder window by four days
  shared/src/business/entities/trialSessions/TrialSession.noticeOfTrialReminder.test.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
Labels: to staging

#4058 Dep updates 2023 10 02
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4063 10136: DOD - don't use formatCase, add types to computed
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
Labels: to staging

#4076 10159: New Case Status: Submitted - Rule 122
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/judgeActivityReportJourney.test.ts
  web-client/src/presenter/actions/CaseDetail/validateUpdateCaseModalAction.ts
  web-client/src/presenter/actions/CaseWorksheet/getSubmittedAndCavCasesForCurrentJudgeAction.test.ts
  web-client/src/presenter/actions/CaseWorksheet/getSubmittedAndCavCasesForCurrentJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/computeds/CaseWorksheets/caseWorksheetsHelper.test.ts
  web-client/src/presenter/computeds/CaseWorksheets/caseWorksheetsHelper.ts
Labels: to staging

#4080 10170: BUG: Format consolidated member cases for external users
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.test.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
Labels: bugfix, to test

#4081 10170: BUG: Format consolidated member cases for external users
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.test.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
Labels: bugfix, to staging

#4079 10158: Flakey test: `court-issued-documents.cy.ts`
  cypress/cypress-smoketests/support/pages/create-electronic-petition.ts
Labels: to staging

#4082 10039: add `isSeniorJudge` to CSV_HEADERS
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.ts
Labels: to staging

#4053 Bug refactor idle timer logic to testing
  web-client/src/views/IdleActivityMonitor.tsx
Labels: to test

#4085 Flakey test: Calling cy.intercept before making request
  cypress/cypress-integration/integration/file-a-petition.cy.ts
  cypress/cypress-smoketests/support/pages/create-electronic-petition.ts
Labels: to staging

#4097 10177: BUG: If a practitioner previews their uploaded EA doc, the Redaction acknowledgement checkbox disappears
  web-client/integration-tests/journey/respondentRequestsAccessToCase.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
Labels: to test

#4094 Devex 1187 - Fix Joi validation mismatch
  shared/src/business/entities/JoiValidationEntity.ts
  shared/src/business/entities/UserCase.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeD.test.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeD.ts
  shared/src/business/entities/caseWorksheet/CaseWorksheet.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
Labels: to test

#4099 1183 Design Debt: ADC user - Messages filter dropdown options are not listed alphabetically
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test, design debt

#4103 10177 edge case + remove REDACTION_ACKNOWLEDGEMENT_ENABLED feature flag
  scripts/dynamo/remove-redaction-acknowledgement-enabled-flag.sh
  scripts/dynamo/setup-redaction-acknowledgement-enabled-flag.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/helpers.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.test.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.ts
  web-client/src/presenter/actions/navigateToRequestAccessReviewAction.test.ts
  web-client/src/presenter/actions/navigateToRequestAccessReviewAction.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
Labels: to test

#4101 DX1209 - Calendar note character limit - addendum
  web-client/src/views/CaseDetail/AddEditCalendarNoteModal.tsx
Labels: to test, design debt

#4090 1159 - Implement New Sort Arrows
  web-client/src/presenter/actions/TrialSessionWorkingCopy/toggleWorkingCopySortAction.test.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/toggleWorkingCopySortAction.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.test.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.ts
  web-client/src/presenter/computeds/sortableColumnHelper.test.ts
  web-client/src/presenter/computeds/sortableColumnHelper.ts
  web-client/src/presenter/sequences/sortTableSequence.ts
  web-client/src/presenter/sequences/toggleWorkingCopySortSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/SortableColumnHeaderButton/SortableColumnHeaderButton.tsx
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/Practitioners/PractitionerDocumentation.tsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.tsx
Labels: to staging, design debt

#4092 10144 - addressing es lint issues
  cypress/cypress-integration/integration/docket-clerk-edits-court-issued-document.cy.ts
  cypress/cypress-integration/support/pages/document-qc.ts
Labels: to staging

#4066 10165: Private Practitioners have the option to file Entry of Appearance documents across a consolidated group if they are associated with at least one other case in the group
  scripts/dynamo/delete-order-and-opinion-search-feature-flags.sh
  scripts/dynamo/delete-stamp-disposition-feature-flag.sh
  scripts/dynamo/remove-consolidated-cases-group-access-petitioner-flag.sh
  scripts/dynamo/setup-consolidated-cases-group-access-petitioner-flag.sh
  scripts/run-once-scripts/delete-pdfjs-express-viewer-flag.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/User.ts
  shared/src/business/useCaseHelper/caseAssociation/associateIrsPractitionerToCase.test.ts
  shared/src/business/useCaseHelper/caseAssociation/associateIrsPractitionerToCase.ts
  shared/src/business/useCases/caseAssociationRequest/submitCaseAssociationRequestInteractor.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.ts
  shared/src/proxies/documents/submitCaseAssociationRequestProxy.ts
  shared/src/test/mockUsers.ts
  web-api/swagger.json
  web-client/integration-tests/docketClerkConsolidatesCases.test.ts
  web-client/integration-tests/docketClerkExternalDocumentQCWorkflow.test.ts
  web-client/integration-tests/externalUserFilesDocumentAcrossConsolidatedCases.test.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.ts
  web-client/integration-tests/journey/irsPractitionerRequestAccessToFileAcrossConsolidatedCasesGroup.ts
  web-client/integration-tests/journey/petitionsClerkAddsRespondentsToCase.ts
  web-client/integration-tests/journey/practitionerFilesDocumentForOwnedCase.ts
  web-client/integration-tests/modifyRespondentContactInfo.test.ts
  web-client/integration-tests/orderSearchJourneyCaseCaption.test.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.ts
  web-client/src/presenter/actions/FileDocument/submitCaseAssociationRequestAction.test.ts
  web-client/src/presenter/actions/FileDocument/submitCaseAssociationRequestAction.ts
  web-client/src/presenter/actions/FileDocument/submitRespondentCaseAssociationRequestAction.test.ts
  web-client/src/presenter/actions/FileDocument/submitRespondentCaseAssociationRequestAction.ts
  web-client/src/presenter/actions/getCaseAssociationAction.test.ts
  web-client/src/presenter/actions/getCaseAssociationAction.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.ts
  web-client/src/presenter/computeds/allowExternalConsolidatedGroupFilingHelper.test.ts
  web-client/src/presenter/computeds/allowExternalConsolidatedGroupFilingHelper.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/requestAccessHelper.ts
  web-client/src/presenter/sequences/gotoFileDocumentSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/FileDocument/FileDocument.tsx
  web-client/src/views/RequestAccess/RequestAccess.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
Labels: to staging, Manual Deploy Step(s) Required

#4102 DX1184 - Increase width of Completed By Select Input
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
Labels: to test, design debt

#4098 10177: BUG: If a practitioner previews their uploaded EA doc, the Redaction acknowledgement checkbox disappears
  scripts/dynamo/remove-redaction-acknowledgement-enabled-flag.sh
  scripts/dynamo/setup-redaction-acknowledgement-enabled-flag.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/journey/respondentRequestsAccessToCase.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.test.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.ts
  web-client/src/presenter/actions/navigateToRequestAccessReviewAction.test.ts
  web-client/src/presenter/actions/navigateToRequestAccessReviewAction.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
Labels: to staging

#4109 10152 - Petitioner: Remove Default 'Surviving Spouse' Designation From Caption
  .cognito/config.json
  .gitignore
  cypress/cypress-integration/integration/docket-clerk-edits-court-issued-document.cy.ts
  cypress/cypress-integration/support/pages/document-qc.ts
  package-lock.json
  package.json
  scripts/dynamo/remove-redaction-acknowledgement-enabled-flag.sh
  shared/src/business/entities/cases/Case.getCaseCaption.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/useCases/auth/authenticateUserInteractor.ts
  shared/src/proxies/auth/changePasswordLocalProxy.ts
  shared/src/proxies/auth/confirmSignUpLocalProxy.ts
  shared/src/proxies/createUserInteractorLocalProxy.ts
  tsconfig.json
  web-api/src/cognitoLocalWrapper.test.ts
  web-api/src/cognitoLocalWrapper.ts
  web-api/src/persistence/cognito/confirmAuthCodeCognitoLocal.ts
  web-api/src/persistence/dynamo/users/createNewPetitionerUser.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.test.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.ts
  web-client/src/presenter/actions/authenticateUserAction.test.ts
  web-client/src/presenter/actions/authenticateUserAction.ts
  web-client/src/presenter/actions/changePasswordLocalAction.test.ts
  web-client/src/presenter/actions/changePasswordLocalAction.ts
  web-client/src/presenter/actions/confirmSignUpLocalAction.test.ts
  web-client/src/presenter/actions/createNewAccountAction.test.ts
  web-client/src/presenter/actions/createNewAccountAction.ts
  web-client/src/presenter/computeds/contactsHelper.test.ts
  web-client/src/presenter/computeds/contactsHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/sequences/createNewAccountLocalSequence.ts
  web-client/src/presenter/sequences/goToCreateAccountLocalSequence.ts
  web-client/src/presenter/sequences/gotoChangePasswordLocalSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/ChangePasswordLocal.tsx
  web-client/src/views/CreateNewAccountLocal.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
Labels: to test

#4106 DX1184 - Increase width of Completed By Select Input
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
Labels: to staging, design debt

#4100 1183 Design Debt: ADC user - Messages filter dropdown options are not listed alphabetically
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to staging, design debt

#4107 Devex 1209 - Remove character limit in calendar note
  shared/src/business/entities/notes/CalendarNote.test.ts
  shared/src/business/entities/notes/CalendarNote.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/useCases/validateCalendarNoteInteractor.test.ts
  web-client/src/views/CaseDetail/AddEditCalendarNoteModal.tsx
Labels: to staging, design debt

#4113 Design Debt 1203 - Case/Order/Opinion results table column header labels
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: to test

#4117 10158 story
  cypress/cypress-integration/integration/consolidated-case.cy.ts
  cypress/cypress-integration/integration/trial-session-working-copy.cy.ts
  cypress/cypress-integration/support/pages/create-paper-petition.ts
  cypress/cypress-integration/support/pages/document-qc.ts
  cypress/cypress-integration/support/pages/start-a-case.ts
  cypress/cypress-smoketests/integration/court-issued-documents.cy.ts
  cypress/cypress-smoketests/integration/create-trial-session.cy.ts
  cypress/cypress-smoketests/support/pages/advanced-search.ts
  cypress/cypress-smoketests/support/pages/case-detail.ts
  cypress/cypress-smoketests/support/pages/create-electronic-petition.ts
  cypress/cypress-smoketests/support/pages/petitioner-dashboard.ts
  docs/flaky-tests.md
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
Labels: to staging

#4104 10152 story
  shared/src/business/entities/cases/Case.getCaseCaption.test.ts
  shared/src/business/entities/cases/Case.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.test.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.ts
  web-client/src/presenter/computeds/contactsHelper.test.ts
  web-client/src/presenter/computeds/contactsHelper.ts
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
Labels: to staging

#4122 Design Debt 1203 - Change Case/Order/Opinion Table Headers
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: to staging

#4126 10182 Integration test error output and stack trace
  web-client/integration-tests/helpers.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/setAlertFromExceptionAction.ts
  web-client/src/providers/httpClient.ts
Labels: to staging

#4130 10169: BUG: Numbered/Bulleted list formatting on Order Generator not displaying appropriately on Preview or after Save
  shared/src/business/utilities/htmlGenerator/documents/order.scss
Labels: to test

#4134 10169: BUG
  shared/src/business/utilities/htmlGenerator/documents/order.scss
Labels: to test

#4133 Dependency Updates - October 23, 2023
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
Labels: dependencies

#4132 devex: updated node/npm version refs in running-locally.md
  docs/running-locally.md
Labels: to staging

#4137 Devex 1187: CaseDeadline
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/useCases/caseDeadline/validateCaseDeadlineInteractor.test.ts
  shared/src/business/useCases/caseDeadline/validateCaseDeadlineInteractor.ts
  shared/src/test/mockCaseDeadline.ts
  web-api/src/persistence/dynamo/caseDeadlines/createCaseDeadline.ts
  web-client/integration-tests/journey/petitionsClerkCreatesACaseDeadline.ts
  web-client/integration-tests/journey/petitionsClerkEditsCaseDeadline.ts
  web-client/src/presenter/state.ts
Labels: to staging
