Repository ustaxcourt/ef-cms, pull requests merged in 2023-05, with the labels that each got.

#3514 9858 + 3898 + 9874: UX Feedback and Testing
  shared/src/business/useCases/caseAssociationRequest/submitCaseAssociationRequestInteractor.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  shared/src/business/useCases/generatePrintableFilingReceiptInteractor.ts
  shared/src/proxies/documents/submitCaseAssociationRequestProxy.ts
  shared/src/proxies/generatePrintableFilingReceiptProxy.ts
  web-client/integration-tests/externalUserFilesDocumentAcrossConsolidatedCases.test.ts
  web-client/integration-tests/fixtures/consolidated-case-group-for-external-multidocketing.ts
  web-client/integration-tests/journey/practitionerRequestAccessToFileAcrossConsolidatedCasesGroup.ts
  web-client/src/presenter/actions/FileDocument/submitCaseAssociationRequestAction.ts
  web-client/src/styles/cards.scss
  web-client/src/views/FileDocument/ExternalConsolidatedGroupCards.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
Labels: to test

#3467 Design Debt [1163] - Update Mid-Table Date Header Row on Trial Session Page
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to staging

#3503 Dependency updates week of 2023 04 24
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#3533 Node18 - Updatable Version in Terraform
  package-lock.json
  package.json
  scripts/dynamo/get-current-node-version.sh
  scripts/dynamo/get-deploying-node-version.sh
  scripts/dynamo/setup-node-version-state.sh
  web-api/terraform/api/api-async.tf
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/api/cognito-trigger.tf
  web-api/terraform/api/cron.tf
  web-api/terraform/api/handle-bounced-service-email.tf
  web-api/terraform/api/layers.tf
  web-api/terraform/api/maintenance_notify.tf
  web-api/terraform/api/seal-in-lower-environment.tf
  web-api/terraform/api/send-emails-lambda.tf
  web-api/terraform/api/set-trial-session-lambda.tf
  web-api/terraform/api/streams.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/api/websockets.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/lambdas/public-api-authorizer.js
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
  webpack.config.lambda.migration-cron.js
  webpack.config.lambda.migration.js
  webpack.config.lambda.reindex-cron.js
  webpack.config.lambda.rotate-info-indices.js
  webpack.config.lambda.switch-colors-cron.js
Labels: Manual Deploy Step(s) Required

#3527 Update terraform docs
  docs/terraform.md
Labels: to staging

#3561 9723 custom case front end intermediate to test
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/EntityValidationConstants.ts
  shared/src/business/entities/JoiValidationEntity.ts
  shared/src/business/entities/customCaseInventorySearch/CustomCaseInventorySearch.test.ts
  shared/src/business/entities/customCaseInventorySearch/CustomCaseInventorySearch.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/caseInventoryReport/getCustomCaseInventoryReportInteractor.test.ts
  shared/src/business/useCases/caseInventoryReport/getCustomCaseInventoryReportInteractor.ts
  shared/src/business/useCases/validateCustomCaseInventorySearchFiltersInteractor.test.ts
  shared/src/business/useCases/validateCustomCaseInventorySearchFiltersInteractor.ts
  shared/src/business/utilities/DateHandler.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/business/utilities/formatNumber.test.ts
  shared/src/business/utilities/formatNumber.ts
  shared/src/persistence/elasticsearch/getCasesByFilters.ts
  shared/src/persistence/elasticsearch/searchClient.ts
  shared/src/proxies/reports/getCustomCaseInventoryReportProxy.ts
  web-api/src/applicationContext.ts
  web-api/src/getUtilities.ts
  web-client/integration-tests/docketClerkAddsAutomaticBlockCaseToTrial.test.ts
  web-client/integration-tests/docketClerkMultiDocketsCourtIssuedDocumentForPaperCase.test.ts
  web-client/integration-tests/docketClerkRunsCustomCaseInventoryReport.test.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.ts
  web-client/integration-tests/petitionsClerkBlockCase.test.ts
  web-client/integration-tests/petitionsClerkBlockConsolidatedCasesJourney.test.ts
  web-client/integration-tests/petitionsClerkFiltersBlockedCaseReport.test.ts
  web-client/integration-tests/petitionsClerkPrioritizesCase.test.ts
  web-client/integration-tests/petitionsClerkSetsRemoteTrialSessionCalendar.test.ts
  web-client/integration-tests/petitionsClerkSetsTrialSessionCalendar.test.ts
  web-client/integration-tests/petitionsClerkViewsDraftDocuments.test.ts
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseInventoryReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseInventoryReportAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseInventoryFiltersAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseInventoryFiltersAction.ts
  web-client/src/presenter/actions/resetCustomCaseInventoryReportStateAction.test.ts
  web-client/src/presenter/actions/resetCustomCaseInventoryReportStateAction.ts
  web-client/src/presenter/actions/validateCustomInventoryFiltersAction.test.ts
  web-client/src/presenter/actions/validateCustomInventoryFiltersAction.ts
  web-client/src/presenter/computeds/customCaseInventoryReportHelper.test.ts
  web-client/src/presenter/computeds/customCaseInventoryReportHelper.ts
  web-client/src/presenter/customCaseInventoryReportState.ts
  web-client/src/presenter/sequences/getCustomCaseInventoryReportSequence.ts
  web-client/src/presenter/sequences/gotoCustomCaseReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: Blue/Green Migration, to test

#3559 9980: Reporting: Judge Activity Report - Progress Description
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.test.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  shared/src/proxies/reports/getCasesByStatusAndByJudgeProxy.ts
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/reports/getCasesByStatusAndByJudgeLambda.ts
  web-client/integration-tests/judgeActivityReportJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/presenter/sequences/JudgeActivityReport/submitJudgeActivityReportSequence.ts
  web-client/src/views/Header/ReportsMenu.tsx
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3566 9980 jar progress description intermediate branch to test
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
  web-client/src/views/JudgeActivityReport/JudgeActivityReport.tsx
Labels: to test

#3572 Devex 1147 uswds v3 upgrade
  docs/wiki/UX-Documentation.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  stylelint.config.js
  web-client/src/app.tsx
  web-client/src/appPublic.tsx
  web-client/src/index.scss
  web-client/src/styles/_index.scss
  web-client/src/styles/buttons.scss
  web-client/src/styles/cards.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/styles/icons.scss
  web-client/src/styles/menus.scss
  web-client/src/styles/modals.scss
  web-client/src/styles/nav.scss
  web-client/src/styles/overrides.scss
  web-client/src/styles/print.scss
  web-client/src/styles/progress.scss
  web-client/src/styles/public.scss
  web-client/src/styles/tables.scss
  web-client/src/styles/tabs.scss
  web-client/src/styles/typography.scss
  web-client/src/ustc-ui/DateInput/DatePickerComponent.tsx
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/uswds-required.scss
  web-client/src/uswds.scss
  web-client/src/uswds/_index.scss
  web-client/src/variables/_index.scss
  web-client/src/variables/variables.scss
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
  web-client/src/views/Footer.tsx
  web-client/src/views/Header/DocumentQCMenu.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Header/HeaderPublic.tsx
  web-client/src/views/Header/MessagesMenu.tsx
  web-client/src/views/Header/ReportsMenu.tsx
  web-client/src/views/StartCaseInternal/OrdersNeededSummary.tsx
  web-client/src/views/UsaBanner.tsx
  web-client/src/views/WarningNotification.tsx
Labels: to staging

#3571 devex: Add debugging for integration tests as well as unit tests.
  .gitignore
  .vscode/launch.json
Labels: to staging

#3568 Devex 1166 messaging consistency
  web-client/src/views/StartCase/FilePetitionSuccess.tsx
Labels: to staging

#3575 Dependency Updates for the week of 05/15/23 🚀🚀🚀
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
Labels: to staging, Manual Deploy Step(s) Required

#3583 devex: Make typescript error count log be accurate.
  scripts/compareTypescriptErrors.ts
Labels: to staging

#3587 9980 jar progress description intermediate branch to test
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.test.ts
  shared/src/business/useCases/judgeActivityReport/getCasesByStatusAndByJudgeInteractor.ts
  shared/src/persistence/elasticsearch/getDocketNumbersByStatusAndByJudge.ts
  web-client/integration-tests/journey/docketClerkAddsDocketEntryFromOrder.ts
  web-client/integration-tests/journey/docketClerkUpdatesCaseStatusTo.ts
  web-client/integration-tests/journey/viewJudgeActivityReportResults.ts
  web-client/integration-tests/judgeActivityReportJourney.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/getSubmittedAndCavCasesByJudgeAction.test.ts
  web-client/src/presenter/actions/JudgeActivityReport/setJudgeActivityReportDataAction.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.test.ts
  web-client/src/presenter/computeds/JudgeActivityReport/judgeActivityReportHelper.ts
Labels: to test

#3586 9866 Visibility Change for Practitioner-Filed Briefs
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.getDocketEntriesFiledByPractitioner.test.ts
  shared/src/business/entities/cases/PublicCase.isPrivateDocument.test.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/entities/cases/PublicDocketEntry.test.ts
  shared/src/business/entities/cases/PublicDocketEntry.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.test.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.test.ts
  web-client/src/presenter/actions/FileDocument/defaultSecondaryDocumentAction.test.ts
  web-client/src/presenter/actions/setMessageDetailViewerDocumentToDisplayAction.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getShowDocumentViewerLink.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
Labels: to test

#3593 10034 to test
  shared/src/business/dto/cases/ConsolidatedCaseDTO.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/useCaseHelper/caseAssociation/associateIrsPractitionerToCase.ts
  shared/src/business/useCaseHelper/caseAssociation/associatePrivatePractitionerToCase.test.ts
  shared/src/business/useCaseHelper/caseAssociation/associatePrivatePractitionerToCase.ts
  shared/src/business/useCases/caseAssociationRequest/submitCaseAssociationRequestInteractor.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  web-client/integration-tests/externalUserFilesDocumentAcrossConsolidatedCases.test.ts
  web-client/integration-tests/journey/irsPractitionerRequestAccessToFileAcrossConsolidatedCasesGroup.ts
  web-client/integration-tests/permissions.test.ts
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.test.ts
  web-client/src/presenter/actions/CaseAssociationRequest/canRequestAccessAction.ts
  web-client/src/presenter/actions/CaseConsolidation/getConsolidatedCasesByCaseAction.test.ts
  web-client/src/presenter/actions/CaseConsolidation/setConsolidatedCasesForCaseAction.ts
  web-client/src/presenter/actions/FileDocument/getFileExternalDocumentAlertSuccessAction.test.ts
  web-client/src/presenter/actions/FileDocument/getFileExternalDocumentAlertSuccessAction.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.ts
  web-client/src/presenter/actions/FileDocument/setIsExternalConsolidatedCaseGroupEnabledValueAction.test.ts
  web-client/src/presenter/actions/FileDocument/setIsExternalConsolidatedCaseGroupEnabledValueAction.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsAction.test.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsAction.ts
  web-client/src/presenter/computeds/externalConsolidatedCaseGroupHelper.ts
  web-client/src/views/FileDocument/FileDocument.tsx
  web-client/src/views/RequestAccess/RequestAccess.tsx
Labels: to test

#3591 DX-1173 session copy notes design
  web-client/src/styles/tables.scss
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
Labels: to staging, design debt

#3560 DevEx - 1170 separate pdf lambda
  iam/terraform/environment-specific/main/cognito-post-authentication.tf
  iam/terraform/environment-specific/main/update-petitioner-cases-lambda-role.tf
  package-lock.json
  package.json
  scripts/dynamo/get-current-use-layers.sh
  scripts/dynamo/get-deploying-use-layers.sh
  scripts/dynamo/setup-use-external-pdf-generation-flag.sh
  scripts/dynamo/setup-use-layers-state.sh
  shared/jest-shared.config.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.test.ts
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.ts
  shared/src/business/useCases/generatePdfFromHtmlInteractor.ts
  shared/src/business/utilities/documentGenerators/generateAndVerifyPdfDiff.ts
  shared/src/business/utilities/getChromiumBrowser.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/terraform/api/api-async.tf
  web-api/terraform/api/api-public.tf
  web-api/terraform/api/api.tf
  web-api/terraform/api/cognito-trigger.tf
  web-api/terraform/api/cron.tf
  web-api/terraform/api/handle-bounced-service-email.tf
  web-api/terraform/api/maintenance_notify.tf
  web-api/terraform/api/pdf-generation.tf
  web-api/terraform/api/seal-in-lower-environment.tf
  web-api/terraform/api/send-emails-lambda.tf
  web-api/terraform/api/set-trial-session-lambda.tf
  web-api/terraform/api/streams.tf
  web-api/terraform/api/variables.tf
  web-api/terraform/api/websockets.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/cognito-trigger.tf
  web-api/terraform/template/lambdas/pdf-generation.js
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
  web-client/integration-tests/helpers.ts
  webpack.config.lambda.api.js
  webpack.config.lambda.js
  webpack.config.lambda.migration-cron.js
  webpack.config.lambda.migration.js
  webpack.config.lambda.reindex-cron.js
  webpack.config.lambda.rotate-info-indices.js
  webpack.config.lambda.switch-colors-cron.js
Labels: to staging, Manual Deploy Step(s) Required

#3598 Dep updates 5/22/23
  package-lock.json
  package.json
Labels: to staging

#3596 doc-qc-styling: fix vertical alignment of checkboxes
  web-client/src/styles/overrides.scss
Labels: to staging
