Repository ustaxcourt/ef-cms, pull requests merged in 2023-12, with the labels that each got.

#4345 10194 export pending report
  package-lock.json
  package.json
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/DateHandler.formats.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/proxies/pendingItems/exportPendingReportProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.test.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/pendingItems/exportPendingReportLambda.ts
  web-api/src/persistence/elasticsearch/fetchPendingItems.test.ts
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/exportPendingReportAction.test.ts
  web-client/src/presenter/actions/exportPendingReportAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/exportPendingReportSequence.ts
  web-client/src/views/PendingReport/PendingReport.tsx
Labels: to test

#4272 10117 Story: My Cases - Filing Fee Status Display
  cypress/cypress-integration/integration/irs-practitioner-dashboard.cy.ts
  cypress/cypress-integration/integration/irs-practitioner-views-case-detail.cy.ts
  cypress/cypress-integration/integration/petitioner-dashboard.cy.ts
  cypress/cypress-integration/integration/private-practitioner-dashboard.cy.ts
  scripts/run-once-scripts/cleanup-usercase-records.ts
  set-tokens.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/UserCase.test.ts
  shared/src/business/entities/UserCase.ts
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/cases/getUserCaseMappingsByDocketNumber.ts
  web-api/src/persistence/dynamo/cases/updateUserCaseMapping.test.ts
  web-api/src/persistence/dynamo/cases/updateUserCaseMapping.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/workflow-terraform/migration/main/lambdas/migrations/0012-remove-signed-judge-on-spos-spto.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0012-remove-signed-judge-on-spos-spto.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0013-consolidated-cases-gsi1pk.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0013-consolidated-cases-gsi1pk.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0013-default-case-status-history.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0013-default-case-status-history.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
  web-client/src/presenter/computeds/caseDetailHelper.ts
  web-client/src/presenter/computeds/dashboardExternalHelper.test.ts
  web-client/src/presenter/computeds/dashboardExternalHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDetail/CaseInformationExternal.tsx
  web-client/src/views/CaseListRowExternal.tsx
  web-client/src/views/CaseListTable.tsx
Labels: Manual Deploy Step(s) Required

#4354 10195 - petition submission flow text changes
  docs/entities/PublicCase.md
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/StartCase/FilePetitionSuccess.tsx
  web-client/src/views/StartCase/SpousePermissionConfirmModal.tsx
  web-client/src/views/StartCase/StartCaseStep1.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
  web-client/src/views/StartCase/StartCaseStep4.tsx
  web-client/src/views/StartCase/StartCaseStep5.tsx
Labels: to staging

#4362 devex: fix smoketests if practitioner does not have any cases
  cypress/helpers/auth/login-as-helpers.ts
  web-client/src/views/CaseListTable.tsx
  web-client/src/views/CaseSearchBox.tsx
Labels: to staging

#4352 10150: display intervenor as filing party
  shared/src/business/entities/DocketEntry.generateFiledBy.test.ts
  shared/src/business/entities/DocketEntry.ts
Labels: to test

#4325 Dependency Updates 2023-11-28
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4319 Devex 1198: prevent a migration from having the same source and destination table
  setup-for-blue-green-migration.sh
Labels: to staging

#4332 10197: BUG - User cannot update their contact information
  cypress/cypress-integration/integration/practitioners-with-no-cases.cy.ts
  cypress/cypress-integration/support/helpers.ts
  shared/src/business/entities/User.test.ts
  shared/src/business/entities/User.ts
  shared/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  shared/src/business/useCases/users/generateChangeOfAddress.ts
  shared/src/business/useCases/users/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.ts
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.test.ts
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.ts
  web-client/src/presenter/actions/setUserAction.test.ts
  web-client/src/presenter/sequences/userContactUpdateCompleteSequence.ts
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/UserContactEditForm.tsx
Labels: to staging

#4382 10194: showNoPendingItems bug
  package-lock.json
  package.json
  web-client/src/presenter/computeds/pendingReportListHelper.test.ts
  web-client/src/presenter/computeds/pendingReportListHelper.ts
Labels: to test

#4375 Devex 1238: refactor case creation entities
  shared/src/business/entities/cases/CaseExternalIncomplete.test.ts
  shared/src/business/entities/cases/CaseExternalIncomplete.ts
  shared/src/business/entities/cases/ElectronicPetition.test.ts
  shared/src/business/entities/cases/ElectronicPetition.ts
  shared/src/business/entities/cases/ElectronicPetitionForCorporationContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForEstateWithoutExecutorContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForInternationalContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForMinorWithoutGuardianContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPartnershipTaxMattersPartnerContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPetitionerAndDeceasedSpouseContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPetitionerAndSpouseContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionInformationFactory.test.ts
  shared/src/business/entities/cases/ElectronicPetitionInformationFactory.ts
  shared/src/business/entities/cases/PaperPetition.test.ts
  shared/src/business/entities/cases/PaperPetition.ts
  shared/src/business/entities/contacts/ContactFactory.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/startCase/validateStartCaseWizardInteractor.ts
  shared/src/business/useCases/validatePetitionFromPaperInteractor.ts
  shared/src/business/useCases/validatePetitionInteractor.ts
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderDesignatingPlaceOfTrialCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForCdsCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForDiscCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesPetitionPaymentFeeOptions.ts
Labels: to staging

#4397 10211: Bug: Cerebral debounce
  web-client/src/presenter/sequences/submitCaseAssociationRequestSequence.ts
  web-client/src/presenter/utilities/debounceSequenceDecorator.test.ts
  web-client/src/presenter/utilities/debounceSequenceDecorator.ts
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
Labels: to test

#4377 1137 devex - Address feedback
  cypress/cypress-integration/integration/docket-clerk-multi-docket-draft-order.cy.ts
  web-client/integration-tests/docketClerkCreatesOrderWithAddedDocketEntries.test.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrderWithAddedDocketNumbers.ts
  web-client/integration-tests/journey/docketClerkEditsOrderAndChecksAddedDocketNumbers.ts
  web-client/src/presenter/actions/skipSigningOrderAction.test.ts
  web-client/src/presenter/actions/skipSigningOrderAction.ts
  web-client/src/presenter/sequences/openEditOrderTitleModalSequence.ts
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.tsx
  web-client/src/views/ConsolidatedCasesCheckboxes.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/CreateOrder/CreateOrderChooseTypeModal.tsx
  web-client/src/views/CreateOrder/EditOrderTitleModal.tsx
  web-client/src/views/DocketRecord/DraftDocumentViewer.tsx
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
  web-client/src/views/SignOrder.tsx
Labels: to test

#4398 10185: IRS Calendar Admin Lookup
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  shared/src/business/entities/trialSessions/IrsCalendarAdministratorInfo.test.ts
  shared/src/business/entities/trialSessions/IrsCalendarAdministratorInfo.ts
  shared/src/business/entities/trialSessions/NewTrialSession.ts
  shared/src/business/entities/trialSessions/TrialSession.IrsCalendarAdministratorInfo.test.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/useCases/getAllUsersByRoleInteractor.test.ts
  shared/src/business/useCases/getAllUsersByRoleInteractor.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/proxies/users/getAllUsersByRoleProxy.ts
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/users/getAllUsersByRoleLambda.ts
  web-api/src/persistence/elasticsearch/users/getAllUsersByRole.test.ts
  web-api/src/persistence/elasticsearch/users/getAllUsersByRole.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/getIrsPractitionerUsersAction.test.ts
  web-client/src/presenter/actions/TrialSession/getIrsPractitionerUsersAction.ts
  web-client/src/presenter/actions/TrialSession/setIrsPractitionerUsersAction.test.ts
  web-client/src/presenter/actions/TrialSession/setIrsPractitionerUsersAction.ts
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.ts
  web-client/src/presenter/sequences/gotoAddTrialSessionSequence.ts
  web-client/src/presenter/sequences/gotoEditTrialSessionSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/Utils/documentTypeSelectHelper.test.ts
  web-client/src/ustc-ui/Utils/documentTypeSelectHelper.ts
  web-client/src/views/TrialSessionWorkingCopy/SessionAssignments.tsx
  web-client/src/views/TrialSessions/SessionAssignmentsForm.tsx
Labels: to test

#4370 Dep updates dec 5 2023
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  cypress/cypress-integration/integration/message-count-on-header.cy.ts
  cypress/helpers/auth/login-as-helpers.ts
  cypress/helpers/retry.ts
  docker-to-ecr.sh
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4405 Devex 1211 intermediate branch to test 1702316593
  web-api/terraform/template/cognito.tf
  web-client/src/views/CaseDetail/CaseInformation/CaseInformationInternal.tsx
  web-client/src/views/CaseDetail/CaseNotes.tsx
Labels: to test

#4390 10194: Export pending report
  cypress/cypress-integration/integration/pending-report.cy.ts
  package-lock.json
  package.json
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/DateHandler.formats.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/proxies/pendingItems/exportPendingReportProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.test.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/pendingItems/exportPendingReportLambda.ts
  web-api/src/persistence/elasticsearch/fetchPendingItems.test.ts
  web-api/swagger.json
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/PendingItems/setPendingItemsAction.test.ts
  web-client/src/presenter/actions/PendingItems/setPendingItemsAction.ts
  web-client/src/presenter/actions/exportPendingReportAction.test.ts
  web-client/src/presenter/actions/exportPendingReportAction.ts
  web-client/src/presenter/computeds/pendingReportListHelper.test.ts
  web-client/src/presenter/computeds/pendingReportListHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/exportPendingReportSequence.ts
  web-client/src/presenter/utilities/downloadCsv.test.ts
  web-client/src/presenter/utilities/downloadCsv.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/views/Header/ReportsMenu.tsx
  web-client/src/views/PendingReport/PendingReport.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
  web-client/src/views/PendingReport/SimplePdfPreviewPage.tsx
Labels: to staging

#4401 9739 fix permissions for lambda
  iam/terraform/environment-specific/main/cognito-post-authentication.tf
  iam/terraform/environment-specific/main/update-petitioner-cases-lambda-role.tf
Labels: to staging

#4413 10176: Handle Feedback
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  cypress/cypress-integration/integration/message-count-on-header.cy.ts
  cypress/cypress-integration/integration/pending-report.cy.ts
  cypress/helpers/auth/login-as-helpers.ts
  cypress/helpers/retry.ts
  docker-to-ecr.sh
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/cognito-post-authentication.tf
  iam/terraform/environment-specific/main/main.tf
  iam/terraform/environment-specific/main/update-petitioner-cases-lambda-role.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  shared/src/business/useCases/pendingMotion/validateDocketEntryWorksheetInteractor.ts
  web-api/runtimes/puppeteer/package-lock.json
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.test.ts
  web-api/src/getUseCases.ts
  web-api/src/persistence/dynamo/pendingMotion/updateDocketEntryWorksheet.ts
  web-api/swagger.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/src/applicationContext.ts
  web-client/src/presenter/computeds/PendingMotions/addEditDocketEntryWorksheetModalHelper.ts
  web-client/src/presenter/computeds/PendingMotions/pendingMotionsHelper.ts
  web-client/src/presenter/utilities/downloadCsv.test.ts
  web-client/src/presenter/utilities/downloadCsv.ts
  web-client/terraform/main/main.tf
Labels: to test

#4367 10150: display intervenor as filing party
  shared/src/business/entities/DocketEntry.generateFiledBy.test.ts
  shared/src/business/entities/DocketEntry.ts
Labels: to staging

#4396 Design Debt #1211: Fix alignment/placement of icon links in cards
  web-client/src/views/CaseDetail/CaseInformation/CaseInformationInternal.tsx
  web-client/src/views/CaseDetail/CaseNotes.tsx
Labels: to staging

#4411 10184 story
  cypress/cypress-smoketests/integration/search.cy.ts
  shared/src/tools/courtIssuedEventCodes.json
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
Labels: to staging

#4412 10211: Bug: Multiple auto-generated EAs
  web-client/src/presenter/sequences/submitCaseAssociationRequestSequence.ts
  web-client/src/presenter/utilities/debounceSequenceDecorator.test.ts
  web-client/src/presenter/utilities/debounceSequenceDecorator.ts
Labels: to staging

#4418 10200 trial session date remote nott
  shared/src/business/utilities/pdfGenerator/documentTemplates/ThirtyDayNoticeOfTrial.tsx
  shared/test-pdf-expected-images/Thirty_Day_Notice_Of_Trial_Remote.pdf.1.png
  shared/test-pdf-expected-images/Thirty_Day_Notice_Of_Trial_Standalone_Remote.pdf.1.png
  web-client/src/presenter/computeds/serveThirtyDayNoticeModalHelper.ts
Labels: to staging

#4317 1137 devex
  cypress/cypress-integration/integration/docket-clerk-creates-draft-orders-for-lead-case.cy.ts
  cypress/helpers/create-order.ts
  cypress/helpers/search-by-docket-number-in-header.ts
  shared/src/business/utilities/getSelectedConsolidatedCasesToMultiDocketOn.test.ts
  shared/src/business/utilities/getSelectedConsolidatedCasesToMultiDocketOn.ts
  web-client/integration-tests/docketClerkCreatesOrderWithAddedDocketEntries.test.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrderWithAddedDocketNumbers.ts
  web-client/integration-tests/journey/docketClerkEditsOrderAndChecksAddedDocketNumbers.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.test.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.ts
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfFromUrlAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.ts
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.test.ts
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.ts
  web-client/src/presenter/actions/setAddedDocketNumbersAction.test.ts
  web-client/src/presenter/actions/setAddedDocketNumbersAction.ts
  web-client/src/presenter/actions/setRedirectUrlAction.ts
  web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.test.ts
  web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.ts
  web-client/src/presenter/actions/skipSigningOrderAction.test.ts
  web-client/src/presenter/actions/skipSigningOrderAction.ts
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.test.ts
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.ts
  web-client/src/presenter/computeds/createOrderHelper.test.ts
  web-client/src/presenter/computeds/createOrderHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoCreateOrderSequence.ts
  web-client/src/presenter/sequences/gotoEditOrderSequence.ts
  web-client/src/presenter/sequences/submitUpdateAddDocketNumbersToOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.tsx
  web-client/src/views/ConsolidatedCasesCheckboxes.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/CreateOrder/CreateOrderChooseTypeModal.tsx
  web-client/src/views/CreateOrder/EditOrderTitleModal.tsx
  web-client/src/views/DocketRecord/DraftDocumentViewer.tsx
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
  web-client/src/views/SignOrder.tsx
Labels: to staging

#4404 Fix ExcludeMethods Type
  shared/src/business/entities/IrsPractitioner.ts
  shared/src/business/entities/NewPractitioner.ts
  shared/src/business/entities/Practitioner.ts
  shared/src/business/entities/PrivatePractitioner.ts
  shared/src/business/entities/PublicUser.ts
  shared/src/business/entities/User.ts
  shared/src/business/entities/WorkItem.ts
  shared/src/business/useCases/practitioners/createPractitionerUserInteractor.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.test.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.locking.test.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.ts
  shared/src/business/useCases/practitioners/validateAddPractitionerInteractor.test.ts
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.test.ts
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.ts
  shared/src/test/mockUsers.ts
  types/TEntity.d.ts
  web-api/src/persistence/dynamo/cases/updatePractitionerOnCase.ts
  web-api/src/persistence/dynamo/users/createNewPractitionerUser.ts
  web-api/src/persistence/dynamo/users/getPractitionerByBarNumber.ts
  web-client/src/presenter/actions/Navigation/toggleMenuAction.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/UserContactEdit.tsx
  web-client/src/views/UserContactEditForm.tsx
Labels: to staging

#4403 Devex best practices cypress
  cypress/cypress-integration/integration/assign-a-work-item-to-self.cy.ts
  cypress/cypress-integration/integration/chambers-user-clicks-document-qc-link.cy.ts
  cypress/cypress-integration/integration/check-not-found-error.cy.ts
  cypress/helpers/auth/login-as-helpers.ts
  web-client/src/views/BigHeader.tsx
  web-client/src/views/Error.tsx
  web-client/src/views/TrialSessions/TrialSessionsSummary.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.tsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.tsx
Labels: to staging

#4422 Fix staging styling
  docs/dependency-updates.md
  package-lock.json
  package.json
Labels: to staging

#4423 10176: Handle Mike feedback
  cypress/cypress-integration/integration/assign-a-work-item-to-self.cy.ts
  cypress/cypress-integration/integration/chambers-user-clicks-document-qc-link.cy.ts
  cypress/cypress-integration/integration/check-not-found-error.cy.ts
  cypress/helpers/auth/login-as-helpers.ts
  shared/src/business/entities/IrsPractitioner.ts
  shared/src/business/entities/NewPractitioner.ts
  shared/src/business/entities/Practitioner.ts
  shared/src/business/entities/PrivatePractitioner.ts
  shared/src/business/entities/PublicUser.ts
  shared/src/business/entities/User.ts
  shared/src/business/entities/WorkItem.ts
  shared/src/business/entities/docketEntryWorksheet/DocketEntryWorksheet.test.ts
  shared/src/business/entities/docketEntryWorksheet/DocketEntryWorksheet.ts
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  shared/src/business/useCases/pendingMotion/updateDocketEntryWorksheetInteractor.test.ts
  shared/src/business/useCases/pendingMotion/validateDocketEntryWorksheetInteractor.test.ts
  shared/src/business/useCases/practitioners/createPractitionerUserInteractor.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.test.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.locking.test.ts
  shared/src/business/useCases/practitioners/updatePractitionerUserInteractor.ts
  shared/src/business/useCases/practitioners/validateAddPractitionerInteractor.test.ts
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.test.ts
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.ts
  shared/src/test/mockUsers.ts
  types/TEntity.d.ts
  web-api/bulkImportPractitionerUsers.ts
  web-api/src/persistence/dynamo/cases/updatePractitionerOnCase.ts
  web-api/src/persistence/dynamo/users/createNewPractitionerUser.ts
  web-api/src/persistence/dynamo/users/getPractitionerByBarNumber.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/Navigation/toggleMenuAction.ts
  web-client/src/presenter/computeds/PendingMotions/pendingMotionsHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/BigHeader.tsx
  web-client/src/views/Error.tsx
  web-client/src/views/PendingMotion/AddEditDocketEntryWorksheetModal.tsx
  web-client/src/views/PendingMotion/PendingMotion.tsx
  web-client/src/views/TrialSessions/TrialSessionsSummary.tsx
  web-client/src/views/UserContactEdit.tsx
  web-client/src/views/UserContactEditForm.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.tsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.tsx
Labels: to test

#4430 fix noce generation
  shared/src/business/useCases/users/setUserEmailFromPendingEmailInteractor.ts
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.ts
  web-api/src/applicationContext.ts
  web-api/src/persistence/messages/sendUpdatePetitionerCasesMessage.ts
Labels: to staging

#4399 DevEx 1231: Only index a record into ES if it was modified after a specific timestamp
  web-api/bulkImportPractitionerUsers.ts
  web-api/seed-dynamo.ts
  web-api/src/lambdas/streams/processStreamRecordsLambda.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/terraform/api/variables.tf
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/variables.tf
Labels: to staging

#4436 Devex 1237 intermediate branch to test 1702913328
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailPendingReportList.tsx
Labels: to test

#4435 10204: Bug: Stamp formatting
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.test.ts
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.ts
  shared/src/business/utilities/documentGenerators/coverSheet.test.ts
  shared/src/business/utilities/htmlGenerator/utils.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.tsx
  shared/test-pdf-expected-images/StampedCoverSheet.pdf.1.png
Labels: to test

#4438 10151 - Case Search Filter Updates
  cypress/cypress-integration/support/pages/public/advanced-search.ts
  cypress/cypress-readonly/integration/public/advanced-search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/useCases/caseAdvancedSearchInteractor.ts
  shared/src/proxies/caseAdvancedSearchProxy.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to test

#4442 10151 story - UX feedback
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to test

#4424 add usa-layout-grid to sass entrypoint
  docs/dependency-updates.md
  package-lock.json
  package.json
  web-client/src/uswds/_index.scss
Labels: to staging

#4441 10216: rework PublicCase.isPrivateDocument and accompanying tests
  shared/src/business/entities/cases/PublicCase.isPrivateDocument.test.ts
  shared/src/business/entities/cases/PublicCase.ts
Labels: to test

#4445 10204: Bug: Stamp formatting
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.test.ts
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.ts
  shared/src/business/utilities/documentGenerators/coverSheet.test.ts
  shared/src/business/utilities/htmlGenerator/utils.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.tsx
  shared/test-pdf-expected-images/StampedCoverSheet.pdf.1.png
Labels: to staging

#4433 Devex 1237: Tracked Items > Pending Report Changes (Design Debt)
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailPendingReportList.tsx
Labels: to staging

#4450 10229: Bug: Printable practitioner case list
  cypress/cypress-smoketests/integration/search.cy.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.test.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/cases/getDocketNumbersByUser.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.test.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.ts
  web-client/integration-tests/helpers.ts
  web-client/src/views/Practitioners/PractitionerDetails.tsx
Labels: to test

#4455 10222 bug intermediate branch to test 1703182794
  web-client/src/views/CaseListRowExternal.tsx
  web-client/src/views/CaseListTable.tsx
Labels: to test

#4449 10151 - DOD - Public Case Search refactor
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/caseAdvancedSearchInteractor.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.test.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatch.test.ts
  web-client/src/presenter/actions/AdvancedSearch/setAdvancedSearchResultsAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
Labels: to test

#4431 10205 - Auto-generate Entry of Appearance - Practitioner Flow
  cypress/cypress-integration/integration/petitions-clerk-files-external-document.cy.ts
  cypress/cypress-integration/integration/practitioner-request-access-to-case.cy.ts
  cypress/cypress-integration/integration/stamp-order.cy.ts
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  cypress/helpers/addIntervenorToCase.ts
  cypress/helpers/petitioner-creates-electronic-case.ts
  cypress/helpers/petitionsclerk-creates-paper-case.ts
  cypress/helpers/select-redaction-acknowledgement.ts
  cypress/helpers/select-typeahead-input.ts
  shared/src/business/entities/cases/PublicContact.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.test.ts
  web-client/integration-tests/journey/docketClerkEditsServiceIndicatorToNoneForPetitioner.ts
  web-client/integration-tests/journey/petitionsClerkAddsPractitionerToSecondaryContact.ts
  web-client/integration-tests/permissions.test.ts
  web-client/integration-tests/practitionerCaseJourney.test.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.ts
  web-client/src/presenter/computeds/requestAccessHelper.test.ts
  web-client/src/presenter/computeds/requestAccessHelper.ts
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/CaseDetail/AddPrivatePractitionerModal.tsx
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/RequestAccess/PartiesRepresenting.tsx
  web-client/src/views/RequestAccess/RequestAccess.tsx
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
  web-client/src/views/ServiceIndicatorRadios.tsx
  web-client/src/views/TrialSessionDetail/EligibleCases.tsx
Labels: to staging

#4437 Fix flaky test when selecting status of matter
  cypress/cypress-integration/integration/pending-motions-table-judge-and-chamber-dashboard.cy.ts
  web-client/src/views/PendingMotion/AddEditDocketEntryWorksheetModal.tsx
Labels: to staging

#4448 10222 - bug
  web-client/src/views/CaseListRowExternal.tsx
  web-client/src/views/CaseListTable.tsx
Labels: to staging

#4454 10229: Bug: Printable case list
  cypress/cypress-smoketests/integration/search.cy.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.test.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/cases/getDocketNumbersByUser.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.test.ts
  web-api/src/persistence/dynamo/users/getCasesForUser.ts
  web-client/integration-tests/helpers.ts
  web-client/src/views/Practitioners/PractitionerDetails.tsx
Labels: to staging

#4444 10151 - Case Search: Search Filter Updates
  cypress/cypress-integration/support/pages/public/advanced-search.ts
  cypress/cypress-readonly/integration/public/advanced-search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/useCases/caseAdvancedSearchInteractor.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.test.ts
  shared/src/business/useCases/public/casePublicSearchInteractor.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  shared/src/proxies/caseAdvancedSearchProxy.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/integration-tests-public/unauthedUserCaseSearchExactMatch.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/setAdvancedSearchResultsAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to staging

#4407 10185: IRS Calendar Administrator Lookup
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/entities/JoiValidationConstants.test.ts
  shared/src/business/entities/JoiValidationEntity.ts
  shared/src/business/entities/externalDocument/externalDocumentHelpers.test.ts
  shared/src/business/entities/judgeActivityReport/JudgeActivityReportSearch.ts
  shared/src/business/entities/notes/CalendarNote.ts
  shared/src/business/entities/trialSessions/IrsCalendarAdministratorInfo.test.ts
  shared/src/business/entities/trialSessions/IrsCalendarAdministratorInfo.ts
  shared/src/business/entities/trialSessions/NewTrialSession.ts
  shared/src/business/entities/trialSessions/TrialSession.IrsCalendarAdministratorInfo.test.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.ts
  shared/src/business/useCaseHelper/getJudgeForUserHelper.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/editDocketEntry/completeDocketEntryQCInteractor.ts
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  shared/src/business/useCases/generatePrintableFilingReceiptInteractor.ts
  shared/src/business/useCases/getAllUsersByRoleInteractor.test.ts
  shared/src/business/useCases/getAllUsersByRoleInteractor.ts
  shared/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/business/useCases/updateCaseDetailsInteractor.ts
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.test.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/business/utilities/pdfGenerator/components/SessionAssignmentsSection.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/src/proxies/users/getAllUsersByRoleProxy.ts
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes_Using_New_Calendar_Props.pdf.1.png
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/users/getAllUsersByRoleLambda.ts
  web-api/src/persistence/elasticsearch/users/getAllUsersByRole.test.ts
  web-api/src/persistence/elasticsearch/users/getAllUsersByRole.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/getIrsPractitionerUsersAction.test.ts
  web-client/src/presenter/actions/TrialSession/getIrsPractitionerUsersAction.ts
  web-client/src/presenter/actions/TrialSession/setIrsPractitionerUsersAction.test.ts
  web-client/src/presenter/actions/TrialSession/setIrsPractitionerUsersAction.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionDetailsOnFormAction.ts
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.ts
  web-client/src/presenter/sequences/gotoAddTrialSessionSequence.ts
  web-client/src/presenter/sequences/gotoEditTrialSessionSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/Utils/documentTypeSelectHelper.test.ts
  web-client/src/ustc-ui/Utils/documentTypeSelectHelper.ts
  web-client/src/views/TrialSessionWorkingCopy/SessionAssignments.tsx
  web-client/src/views/TrialSessions/SessionAssignmentsForm.tsx
Labels: to staging
