Repository ustaxcourt/ef-cms, pull requests merged in 2023-11, with the labels that each got.

#4144 Devex 1187: Batch
  shared/src/business/entities/Batch.test.ts
  shared/src/business/entities/Batch.ts
  shared/src/business/entities/joiValidationEntity/JoiValidationEntity_New.test.ts
  shared/src/business/entities/joiValidationEntity/TestCaseEntity.ts
  shared/src/business/entities/joiValidationEntity/helper.ts
Labels: to staging

#4145 Devex 1187: OutboxItem
  shared/src/business/entities/OutboxItem.test.ts
  shared/src/business/entities/OutboxItem.ts
  web-api/src/persistence/dynamo/dynamoTypes.ts
  web-api/src/persistence/dynamo/workitems/createSectionOutboxRecords.ts
Labels: to staging

#4149 Devex 1187: Correspondence
  shared/src/business/entities/Correspondence.test.ts
  shared/src/business/entities/Correspondence.ts
Labels: to staging

#4146 Devex 1187: AddPrivatePractitioner
  shared/src/business/entities/caseAssociation/AddPrivatePractitioner.test.ts
  shared/src/business/entities/caseAssociation/AddPrivatePractitioner.ts
  shared/src/business/useCases/caseAssociation/validateAddPrivatePractitionerInteractor.ts
Labels: to staging

#4150 Devex 1187: Message
  shared/src/business/entities/Message.test.ts
  shared/src/business/entities/Message.ts
  shared/src/business/entities/MessageResult.ts
  shared/src/business/entities/NewMessage.test.ts
  shared/src/business/entities/NewMessage.ts
  shared/src/business/useCases/messages/createMessageInteractor.ts
  shared/src/business/useCases/messages/forwardMessageInteractor.ts
  shared/src/business/useCases/messages/replyToMessageInteractor.ts
  shared/src/business/useCases/messages/validateCreateMessageInteractor.test.ts
  shared/src/business/useCases/messages/validateCreateMessageInteractor.ts
  web-api/src/persistence/dynamo/messages/createMessage.test.ts
  web-api/src/persistence/dynamo/messages/createMessage.ts
  web-api/src/persistence/dynamo/messages/updateMessage.test.ts
  web-api/src/persistence/dynamo/messages/updateMessage.ts
  web-client/integration-tests/caseServicesSupervisorJourney.test.ts
  web-client/integration-tests/journey/createNewMessageOnCase.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewMessageOnCaseWithMaxAttachments.ts
  web-client/integration-tests/messagesJourney.test.ts
  web-client/integration-tests/messagesTableJourney.test.ts
  web-client/src/presenter/actions/setAlertFromExceptionAction.test.ts
  web-client/src/presenter/actions/validateCreateMessageAction.test.ts
  web-client/src/presenter/actions/validateCreateMessageAction.ts
Labels: to staging

#4151 Devex 1187: AddIrsPractitioner
  shared/src/business/entities/caseAssociation/AddIrsPractitioner.test.ts
  shared/src/business/entities/caseAssociation/AddIrsPractitioner.ts
  shared/src/business/useCases/caseAssociation/validateAddIrsPractitionerInteractor.test.ts
  shared/src/business/useCases/caseAssociation/validateAddIrsPractitionerInteractor.ts
  web-client/src/presenter/actions/CaseAssociation/validateAddIrsPractitionerAction.ts
Labels: to staging

#4152 Devex 1187: Penalty
  shared/src/business/entities/Penalty.test.ts
  shared/src/business/entities/Penalty.ts
  shared/src/business/useCases/validatePenaltiesInteractor.test.ts
  shared/src/business/useCases/validatePenaltiesInteractor.ts
Labels: to staging

#4158 10191: critical bug: consolidated case practitioner association
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
  web-client/integration-tests/journey/docketClerkConsolidatesCases.ts
  web-client/integration-tests/practitionerAssociationJourney.test.ts
Labels: bugfix, to staging

#4136 10186 get calendared cases overloaded to test
  shared/src/business/entities/cases/CalendaredCase.test.ts
  shared/src/business/entities/cases/CalendaredCase.ts
  shared/src/business/entities/cases/EligibleCase.test.ts
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/test/mockComplexCase.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/dynamo/trialSessions/getCalendaredCasesForTrialSession.ts
  web-client/src/presenter/errors/ActionError.ts
  web-client/src/presenter/errors/ErrorFactory.ts
Labels: to test

#4142 10169: BUG: Numbered/Bulleted list formatting on Order Generator not displaying appropriately on Preview or after Save
  shared/src/business/utilities/htmlGenerator/documents/order.scss
Labels: to staging

#4168 10186: add status to CalendaredCase
  shared/src/business/entities/cases/CalendaredCase.test.ts
  shared/src/business/entities/cases/CalendaredCase.ts
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.test.ts
Labels: bugfix, to test

#4155 Devex 1187 UpdateUserEmail
  shared/src/business/entities/UpdateUserEmail.test.ts
  shared/src/business/entities/UpdateUserEmail.ts
  shared/src/business/useCases/validatePetitionerInteractor.test.ts
  shared/src/business/useCases/validatePetitionerInteractor.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.test.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.ts
  web-client/src/presenter/actions/validateChangeLoginAndServiceEmailAction.ts
Labels: to staging

#4169 10186: get calendared cases overloaded
  shared/src/business/entities/cases/CalendaredCase.test.ts
  shared/src/business/entities/cases/CalendaredCase.ts
  shared/src/business/entities/cases/EligibleCase.test.ts
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/getCalendaredCasesForTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.test.ts
  shared/src/business/useCases/trialSessions/getEligibleCasesForTrialSessionInteractor.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/test/mockComplexCase.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/dynamo/trialSessions/getCalendaredCasesForTrialSession.ts
  web-client/src/presenter/errors/ActionError.ts
  web-client/src/presenter/errors/ErrorFactory.ts
Labels: bugfix, to staging

#4182 devex-1187: HearingNote
  shared/src/business/entities/notes/HearingNote.test.ts
  shared/src/business/entities/notes/HearingNote.ts
Labels: to staging

#4179 OpEx: run setup-test-users and setup-glued-judges after data finishes gluing
  .circleci/config.yml
  shared/admin-tools/dynamodb/toggle-streams.sh
  shared/admin-tools/user/setup-glued-judges.ts
Labels: to staging

#4180 devex: changed the update-judge-isSeniorJudge script to eliminate the manual pre-work
  scripts/judge/update-judge-isSeniorJudge.ts
Labels: to staging

#4183 devex-1187: EligibleCase
  shared/src/business/entities/cases/EligibleCase.ts
Labels: to staging

#4184 Devex 1187 TrialSession, NewTrialSession
  shared/src/business/entities/trialSessions/NewTrialSession.ts
  shared/src/business/entities/trialSessions/TrialSession.test.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  web-client/integration-tests/journey/docketClerkCreatesARemoteTrialSession.ts
  web-client/integration-tests/journey/docketClerkCreatesATrialSession.ts
  web-client/integration-tests/journey/docketClerkCreatesAnIncompleteTrialSessionBeforeCalendaring.ts
Labels: to staging

#4185 devex-1187: Contact
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/entities/cases/CaseExternalForInternationalContacts.test.ts
  shared/src/business/entities/cases/CaseExternalInformationFactory.test.ts
  shared/src/business/entities/contacts/Contact.ts
  shared/src/business/entities/contacts/NextFriendForIncompetentPersonContact.ts
  shared/src/business/entities/contacts/NextFriendForMinorContact.ts
  shared/src/business/entities/contacts/PartnershipAsTaxMattersPartnerContact.ts
  shared/src/business/entities/contacts/PartnershipBBAContact.ts
  shared/src/business/entities/contacts/PartnershipOtherThanTaxMattersContact.ts
  shared/src/business/entities/contacts/PetitionerConservatorContact.ts
  shared/src/business/entities/contacts/PetitionerCorporationContact.ts
  shared/src/business/entities/contacts/PetitionerCustodianContact.ts
  shared/src/business/entities/contacts/PetitionerDeceasedSpouseContact.ts
  shared/src/business/entities/contacts/PetitionerEstateWithExecutorPrimaryContact.ts
  shared/src/business/entities/contacts/PetitionerGuardianContact.ts
  shared/src/business/entities/contacts/PetitionerIntermediaryContact.ts
  shared/src/business/entities/contacts/PetitionerPrimaryContact.ts
  shared/src/business/entities/contacts/PetitionerSpouseContact.ts
  shared/src/business/entities/contacts/PetitionerTrustContact.ts
  shared/src/business/entities/contacts/SurvivingSpouseContact.ts
  shared/src/business/useCases/validateAddPetitionerInteractor.test.ts
  shared/src/business/useCases/validatePetitionerInteractor.test.ts
Labels: to staging

#4186 Devex 1187: DeadlineSearch
  shared/src/business/entities/deadlines/DeadlineSearch.ts
Labels: to staging

#4189 Devex 1187: JudgeActivityReportSearch
  shared/src/business/entities/judgeActivityReport/JudgeActivityReportSearch.ts
Labels: to staging

#4190 Devex 1187: Order, OrderWithoutBody
  shared/src/business/entities/orders/Order.test.ts
  shared/src/business/entities/orders/Order.ts
  shared/src/business/entities/orders/OrderWithoutBody.ts
  shared/src/business/useCases/courtIssuedOrder/validateOrderWithoutBodyInteractor.test.ts
  web-client/integration-tests/journey/chambersUserAddsOrderToCase.ts
  web-client/integration-tests/journey/chambersUserSkipSigningOrder.ts
  web-client/integration-tests/journey/petitionsClerkAddsGenericOrderToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsNoticeToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsOrderToCase.ts
Labels: to staging

#4193 Devex 1187: UserCaseNote, PublicContact,TrialSessionWorkingCopy
  shared/src/business/entities/cases/PublicContact.ts
  shared/src/business/entities/notes/UserCaseNote.test.ts
  shared/src/business/entities/notes/UserCaseNote.ts
  shared/src/business/entities/trialSessions/TrialSessionWorkingCopy.ts
Labels: to staging

#4160 Devex 1187 Stamp and Scan entities
  shared/src/business/entities/Scan.test.ts
  shared/src/business/entities/Scan.ts
  shared/src/business/entities/Stamp.test.ts
  shared/src/business/entities/Stamp.ts
  shared/src/business/useCases/stampMotion/validateStampInteractor.test.ts
Labels: to staging

#4187 Devex 1187: EditPetitionerCounsel
  shared/src/business/entities/caseAssociation/EditPetitionerCounsel.test.ts
  shared/src/business/entities/caseAssociation/EditPetitionerCounsel.ts
  web-client/integration-tests/journey/petitionsClerkEditsPractitionerOnCase.ts
Labels: to staging

#4188 Devex 1187: CustomCaseInventorySearch
  shared/src/business/entities/EntityValidationConstants.ts
  shared/src/business/entities/customCaseInventorySearch/CustomCaseInventorySearch.ts
Labels: to staging

#4211 Remove sensitive logs
  cypress/support/cognito-login.ts
Labels: to staging

#4161 Devex 1187 PublicUser, ReconciliationReportEntry
  shared/src/business/entities/PublicUser.ts
  shared/src/business/entities/ReconciliationReportEntry.ts
Labels: to staging

#4159 Devex 1187: Statistic
  shared/src/business/dto/cases/ConsolidatedCaseSummary.ts
  shared/src/business/entities/Statistic.test.ts
  shared/src/business/entities/Statistic.ts
  shared/src/business/useCases/validateAddDeficiencyStatisticsInteractor.test.ts
  shared/src/business/useCases/validateAddDeficiencyStatisticsInteractor.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-client/integration-tests/journey/petitionsClerkAddsDeficiencyStatisticToCase.ts
  web-client/src/presenter/actions/validatePetitionFromPaperAction.ts
Labels: to staging

#4216 10011 custom account creation UI - intermediate branch to test 1699576585
  shared/src/business/dto/cases/ConsolidatedCaseSummary.ts
  shared/src/business/entities/PublicUser.ts
  shared/src/business/entities/ReconciliationReportEntry.ts
  shared/src/business/entities/Statistic.test.ts
  shared/src/business/entities/Statistic.ts
  shared/src/business/entities/documents/PublicDocumentSearchResult.test.ts
  shared/src/business/entities/documents/PublicDocumentSearchResult.ts
  shared/src/business/useCases/users/createUserCognitoInteractor.test.ts
  shared/src/business/useCases/users/createUserCognitoInteractor.ts
  shared/src/business/useCases/validateAddDeficiencyStatisticsInteractor.test.ts
  shared/src/business/useCases/validateAddDeficiencyStatisticsInteractor.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/terraform/template/cognito.tf
  web-client/integration-tests/journey/petitionsClerkAddsDeficiencyStatisticToCase.ts
  web-client/src/presenter/actions/createNewPetitionerUserAction.ts
  web-client/src/presenter/actions/validatePetitionFromPaperAction.ts
Labels: to test

#4203 DX-1204 - My Cases Column Header
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
  web-client/src/views/CaseListTable.tsx
Labels: to test

#4215 Devex 1149
  iam/terraform/account-specific/bin/create-bucket.sh
  iam/terraform/account-specific/bin/create-dynamodb.sh
  iam/terraform/account-specific/bin/deploy-init.sh
Labels: to staging

#4204 Dependency updates 2023-11-07
  .circleci/config.yml
  Dockerfile
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4220 1204 design debt
  web-client/src/presenter/computeds/Dashboard/externalUserCasesHelper.ts
  web-client/src/views/CaseListTable.tsx
Labels: to staging

#4221 Updating PDF Testing Documents for M1 Users
  docs/testing.md
Labels: to staging

#4240 10011 to test again
  docs/testing.md
  web-api/terraform/template/cognito.tf
  web-client/integration-tests-cognito-local/petitionerCreatesAccount.test.ts
  web-client/src/presenter/actions/Public/cognitoResendVerificationLinkAction.ts
  web-client/src/presenter/actions/createConfirmLinkLocalAction.test.ts
  web-client/src/presenter/actions/createConfirmLinkLocalAction.ts
  web-client/src/presenter/computeds/headerPublicHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Public/goToCreatePetitionerAccountSequence.ts
  web-client/src/views/Public/CreatePetitionerAccount/VerificationSent.tsx
Labels: to test

#4236 10188 Bug Feedback: Add placeholder text to date input
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/StampMotion/ApplyStamp.tsx
Labels: to test

#4234 10180 Story: Judge/CA Dashboard: New Value for Status of Matter LOV
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/caseWorksheet/CaseWorksheet.ts
  shared/src/test/mockCaseWorksheet.ts
  web-client/integration-tests/caseWorksheetsJourney.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/CaseWorksheet/updateCaseWorksheetAction.test.ts
Labels: to staging

#4247 Design Debt 1208 - remove exclamation from hints app-wide
  web-client/src/ustc-ui/Hint/Hint.tsx
  web-client/src/views/CaseDetail/PaperServiceConfirmModal.tsx
  web-client/src/views/CaseDetail/UnblockFromTrialModal.tsx
  web-client/src/views/ConfirmInitiateServiceModal.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/FileDocument/SelectDocumentType.tsx
  web-client/src/views/PaperFiling/PaperFiling.tsx
Labels: to staging

#4228 Devex: Cypress post auth
  cypress/cypress-smoketests/integration/user-post-authentication.cy.ts
  cypress/cypress-smoketests/support/pages/case-detail.ts
  package-lock.json
  package.json
  shared/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-client/integration-tests/journey/admissionsClerkMigratesPractitionerWithoutEmail.ts
  web-client/integration-tests/trialClerkWorkingCopy.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
  web-client/src/views/CaseDetail/NoMatchingEmailFoundModal.tsx
Labels: to staging

#4198 Rewriting Flaky Test in Cypress
  .github/workflows/e2e-cypress.yml
  cypress.config.ts
  cypress/cypress-integration/integration/respondent-modifies-contact-info.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/setup/petitioner-creates-a-case.ts
  cypress/cypress-integration/support/setup/petitionsclerk-adds-respondent-to-case.ts
  cypress/cypress-integration/support/setup/petitionsclerk-serves-petition.ts
  cypress/cypress-integration/support/setup/respondent-modifies-contact-info.ts
  split-tests-cypress.ts
  web-client/integration-tests/modifyRespondentContactInfo.test.ts
  web-client/pa11y/pa11y-docketclerk.js
  web-client/src/ustc-ui/Modal/ConfirmModal.tsx
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/CaseDetail/CaseDetail.tsx
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.tsx
  web-client/src/views/CaseDetail/PartiesInformation.tsx
  web-client/src/views/CaseDetail/RespondentCounsel.tsx
  web-client/src/views/CaseDetail/RespondentSearch.tsx
  web-client/src/views/CaseDetailEdit/CaseDetailEdit.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.tsx
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/IRSNotice.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/StartCase/Address.tsx
  web-client/src/views/StartCase/CaseTypeSelect.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCase/FilePetitionSuccess.tsx
  web-client/src/views/StartCase/ProcedureType.tsx
  web-client/src/views/StartCase/StartCaseStep1.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
  web-client/src/views/StartCase/StartCaseStep4.tsx
  web-client/src/views/StartCase/StartCaseStep5.tsx
  web-client/src/views/StartCase/StateSelect.tsx
  web-client/src/views/StartCase/TrialCity.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
  web-client/src/views/SuccessNotification.tsx
  web-client/src/views/UserContactEdit.tsx
  web-client/src/views/UserContactEditProgress.tsx
Labels: to staging

#4206 fix rm in Dockerfile - to staging
  Dockerfile
Labels: to staging

#4255 2023 11 14 test backmerge staging 2
  .github/workflows/e2e-cypress.yml
  Dockerfile
  cypress.config.ts
  cypress/cypress-integration/integration/respondent-modifies-contact-info.cy.ts
  cypress/cypress-integration/integration/stamp-order.cy.ts
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/setup/petitioner-creates-a-case.ts
  cypress/cypress-integration/support/setup/petitionsclerk-adds-respondent-to-case.ts
  cypress/cypress-integration/support/setup/petitionsclerk-serves-petition.ts
  cypress/cypress-integration/support/setup/respondent-modifies-contact-info.ts
  cypress/support/cognito-login.ts
  set-tokens.sh
  shared/admin-tools/user/rotate-environment-secrets.ts
  split-tests-cypress.ts
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/CaseDetail/CaseDetail.tsx
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.tsx
  web-client/src/views/CaseDetail/PartiesInformation.tsx
  web-client/src/views/CaseDetail/RespondentCounsel.tsx
  web-client/src/views/CaseDetail/RespondentSearch.tsx
  web-client/src/views/CaseDetailEdit/CaseDetailEdit.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.tsx
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/IRSNotice.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/StartCase/Address.tsx
  web-client/src/views/StartCase/CaseTypeSelect.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCase/FilePetitionSuccess.tsx
  web-client/src/views/StartCase/ProcedureType.tsx
  web-client/src/views/StartCase/StartCaseStep1.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
  web-client/src/views/StartCase/StartCaseStep5.tsx
  web-client/src/views/StartCase/StateSelect.tsx
  web-client/src/views/StartCase/TrialCity.tsx
  web-client/src/views/SuccessNotification.tsx
  web-client/src/views/UserContactEdit.tsx
  web-client/src/views/UserContactEditProgress.tsx
Labels: to test

#4248 DD 1212: Case Messages - the +/- icons are being obscured by long content
  docs/terraform.md
  web-client/src/views/Messages/MessageDetail.tsx
Labels: to test

#4261 10172 story to test
  shared/src/business/entities/customCaseReportSearch/CustomCaseReportSearch.test.ts
  shared/src/business/entities/customCaseReportSearch/CustomCaseReportSearch.ts
  web-client/integration-tests/docketClerkRunsCustomCaseReport.test.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to test

#4258 DD 1161: set 'new' as default trial sessions tab after session creation
  cypress/cypress-smoketests/support/pages/trial-sessions.ts
  web-client/src/presenter/actions/TrialSession/navigateToTrialSessionsAction.test.ts
  web-client/src/presenter/actions/TrialSession/navigateToTrialSessionsAction.ts
  web-client/src/presenter/actions/setTabAction.ts
  web-client/src/presenter/sequences/submitTrialSessionSequence.ts
Labels: to test

#4269 10192 story
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.ts
Labels: to test

#4256 10188 Bug: The status report portion of the Stamp Order does not display in the Stamp Preview
  cypress/cypress-integration/integration/assign-a-work-item-to-self.cy.ts
  cypress/cypress-integration/integration/consolidated-case.cy.ts
  cypress/cypress-integration/integration/private-practitioner-mobile.cy.ts
  cypress/cypress-integration/integration/respondent-modifies-contact-info.cy.ts
  cypress/cypress-integration/integration/stamp-order.cy.ts
  cypress/cypress-integration/support/pages/create-paper-petition.ts
  cypress/cypress-integration/support/pages/document-qc.ts
  cypress/cypress-integration/support/pages/start-a-case.ts
  cypress/cypress-integration/support/setup/petitionsclerk-serves-petition.ts
  cypress/cypress-smoketests/support/commands.ts
  cypress/cypress-smoketests/support/pages/advanced-search.ts
  cypress/cypress-smoketests/support/pages/case-detail.ts
  cypress/cypress-smoketests/support/pages/create-electronic-petition.ts
  cypress/cypress-smoketests/support/pages/petitioner-dashboard.ts
  shared/src/business/entities/Stamp.test.ts
  shared/src/business/entities/Stamp.ts
  shared/src/business/useCases/generateCoverSheetData.test.ts
  shared/src/business/useCases/generateCoverSheetData.ts
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.test.ts
  shared/src/business/useCases/stampMotion/setDocumentTitleFromStampDataInteractor.ts
  shared/src/business/utilities/documentGenerators/coverSheet.test.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/CoverSheet.tsx
  shared/src/test/mockStamp.ts
  shared/test-pdf-expected-images/StampedCoverSheet.pdf.1.png
  web-client/pa11y/pa11y-docketclerk.js
  web-client/pa11y/pa11y-judge.js
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineFormAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineFormAction.ts
  web-client/src/presenter/actions/StampMotion/clearOptionalFieldsStampFormAction.test.ts
  web-client/src/presenter/actions/StampMotion/clearOptionalFieldsStampFormAction.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/CaseDetail/CaseDetailHeaderMenu.tsx
  web-client/src/views/CaseDetail/DeleteCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseSearchBox.tsx
  web-client/src/views/CaseWorksheet/CaseWorksheets.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.tsx
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/FilingPartiesForm.tsx
  web-client/src/views/PaperFiling/PaperFiling.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/StampMotion/ApplyStamp.tsx
  web-client/src/views/StartCaseInternal/StatisticsForm.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.tsx
Labels: to staging

#4270 10192 - Add ptm back for trial session working copy
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.ts
Labels: to staging

#4264 DD: Case Messages - the +/- icons are being obscured by long content
  docs/terraform.md
  web-client/src/views/Messages/MessageDetail.tsx
Labels: to staging

#4260 Dependency Updates Week of 11/13/23
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4276 add testMatch argument to test:client:unit and update docs
  docs/ci-cd.md
  package.json
Labels: to staging

#4278 10011 - Account Creation UI - intermediate branch to test
  shared/src/business/entities/NewPetitionerUser.ts
  web-api/terraform/template/cognito.tf
  web-client/src/presenter/computeds/headerPublicHelper.test.ts
  web-client/src/presenter/computeds/headerPublicHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/views/Header/HeaderPublic.tsx
  web-client/src/views/Public/CreatePetitionerAccount/CreatePetitionerAccountInfo.tsx
Labels: to test

#4281 9739 lock and wait to test
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/proxies/requests.ts
Labels: to test

#4284 10174 - Consolidate how trial location is added to case status
  shared/src/business/utilities/caseStatusWithTrialInformation.test.ts
  shared/src/business/utilities/caseStatusWithTrialInformation.ts
  shared/src/business/utilities/formatPendingItem.test.ts
  shared/src/business/utilities/formatPendingItem.ts
  web-api/src/applicationContext.ts
  web-api/src/getUtilities.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/computeds/recentMessagesHelper.test.ts
  web-client/src/presenter/computeds/recentMessagesHelper.ts
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.tsx
Labels: to test

#4285 devex: remove deprecated config
  cypress-smoketests-readonly-public.config.ts
  cypress-smoketests-readonly.config.ts
  cypress-smoketests.config.ts
Labels: to staging

#4291 Template Generator Types to test
  cypress-smoketests-readonly-public.config.ts
  cypress-smoketests-readonly.config.ts
  cypress-smoketests.config.ts
  docs/ci-cd.md
  package.json
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.test.ts
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.ts
  shared/src/business/useCaseHelper/service/sendIrsSuperuserPetitionEmail.test.ts
  shared/src/business/useCaseHelper/service/sendIrsSuperuserPetitionEmail.ts
  shared/src/business/useCaseHelper/service/sendServedPartiesEmails.test.ts
  shared/src/business/useCaseHelper/service/sendServedPartiesEmails.ts
  shared/src/business/useCases/email/handleBounceNotificationInteractor.ts
  shared/src/business/utilities/documentGenerators/addressLabelCoverSheet.ts
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.ts
  shared/src/business/utilities/documentGenerators/changeOfAddress.ts
  shared/src/business/utilities/documentGenerators/coverSheet.ts
  shared/src/business/utilities/documentGenerators/docketRecord.ts
  shared/src/business/utilities/documentGenerators/documentServiceEmail.ts
  shared/src/business/utilities/documentGenerators/entryOfAppearance.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeOfTrialJudge.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToInPersonProceeding.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToRemoteProceeding.ts
  shared/src/business/utilities/documentGenerators/noticeOfDocketChange.ts
  shared/src/business/utilities/documentGenerators/noticeOfReceiptOfPetition.ts
  shared/src/business/utilities/documentGenerators/noticeOfTrialIssued.ts
  shared/src/business/utilities/documentGenerators/noticeOfTrialIssuedInPerson.ts
  shared/src/business/utilities/documentGenerators/order.ts
  shared/src/business/utilities/documentGenerators/pendingReport.ts
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.ts
  shared/src/business/utilities/documentGenerators/practitionerCaseList.ts
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.ts
  shared/src/business/utilities/documentGenerators/receiptOfFiling.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrder.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.ts
  shared/src/business/utilities/documentGenerators/thirtyDayNoticeOfTrial.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.test.ts
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.ts
Labels: to test

#4292 10183 Alphabetize trial session planning by city
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.tsx
  shared/src/proxies/trialSessions/runTrialSessionPlanningReportProxy.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
Labels: to test

#4298 Fix advanced-search.cy.ts. Switch to data-testId
  cypress/cypress-readonly/integration/public/advanced-search.cy.ts
  web-client/src/views/Public/PublicCaseDetailHeader.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to staging

#4302 Backmerge staging to test 11-22-23
  cypress/cypress-readonly/integration/public/advanced-search.cy.ts
  web-client/src/views/Public/PublicCaseDetailHeader.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to test

#4290 DD 1161 to test
  web-client/integration-tests/journey/docketClerkViewsTrialSessionsTab.ts
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.test.ts
  web-client/src/presenter/actions/TrialSession/createTrialSessionAction.ts
  web-client/src/presenter/actions/TrialSession/navigateToTrialSessionsAction.test.ts
  web-client/src/presenter/actions/TrialSession/navigateToTrialSessionsAction.ts
  web-client/src/presenter/actions/TrialSession/setActiveTrialSessionsTabAction.test.ts
  web-client/src/presenter/actions/TrialSession/setActiveTrialSessionsTabAction.ts
  web-client/src/presenter/sequences/submitTrialSessionSequence.ts
Labels: to test

#4218 Devex 1187: CourtIssuedDocument
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentBase.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentBase.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentConstants.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeA.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeA.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeB.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeB.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeC.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeC.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeF.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeF.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeG.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeG.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.ts
  shared/src/business/useCases/courtIssuedDocument/validateCourtIssuedDocketEntryInteractor.test.ts
  shared/src/business/useCases/courtIssuedDocument/validateCourtIssuedDocketEntryInteractor.ts
  web-client/integration-tests/journey/docketClerkConvertsAnOrderToAnOpinion.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeC.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeD.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeE.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeF.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeG.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeH.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryMetaCourtIssued.ts
  web-client/src/presenter/state.ts
Labels: to staging

#4295 force break test to verify videos
  .github/workflows/e2e-cypress.yml
Labels: to staging

#4297 devex - Store cypress videos from circle correctly
  .circleci/config.yml
Labels: to staging

#4305 10196 - story
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/useCases/getPaperServicePdfUrlInteractor.ts
  web-client/src/presenter/computeds/trialSessionHeaderHelper.test.ts
  web-client/src/presenter/computeds/trialSessionHeaderHelper.ts
Labels: to staging

#4299 Devex 1205: Get Sassy
  package-lock.json
  package.json
  shared/src/business/utilities/generateHTMLTemplateForPDF/generateHTMLTemplateForPDF.ts
  shared/src/business/utilities/htmlGenerator/cards.scss
  shared/src/business/utilities/htmlGenerator/fonts.scss
  web-api/cognito/style.css
  web-client/src/styles/_index.scss
  web-client/src/styles/buttons.scss
  web-client/src/styles/cards.scss
  web-client/src/styles/icons.scss
  web-client/src/styles/menus.scss
  web-client/src/styles/modals.scss
  web-client/src/styles/nav.scss
  web-client/src/styles/print.scss
  web-client/src/styles/progress.scss
  web-client/src/styles/public.scss
  web-client/src/styles/tabs.scss
  web-client/src/styles/typography.scss
Labels: to test

#4224 Devex 1187: Case Association Request Documents
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentBase.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeA.test.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeA.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeB.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeC.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestDocumentTypeD.ts
  shared/src/business/entities/caseAssociation/CaseAssociationRequestFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/entities/externalDocument/SupportingDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/SupportingDocumentInformationFactory.ts
  web-client/integration-tests/journey/practitionerRequestsAccessToCaseAutoGenerated.ts
  web-client/integration-tests/journey/practitionerRequestsAccessToCaseManual.ts
  web-client/integration-tests/journey/practitionerRequestsPendingAccessToCase.ts
  web-client/integration-tests/journey/respondentRequestsAccessToCase.ts
Labels: to staging

#4226 Devex 1187: CaseExternalIncomplete
  shared/src/business/entities/cases/CaseExternal.test.ts
  shared/src/business/entities/cases/CaseExternal.ts
  shared/src/business/entities/cases/CaseExternalIncomplete.test.ts
  shared/src/business/entities/cases/CaseExternalIncomplete.ts
  shared/src/business/entities/cases/CaseExternalInformationFactory.test.ts
  shared/src/business/entities/cases/CaseExternalInformationFactory.ts
  shared/src/business/useCases/validatePetitionInteractor.ts
Labels: to staging

#4283 10140: Bug Fix Display Message count and Notes Icon
  cypress/cypress-integration/integration/judges-notes-icon.cy.ts
  cypress/cypress-integration/integration/message-count-on-header.cy.ts
  cypress/cypress-integration/support/pages/document-qc.ts
  web-client/src/presenter/sequences/gotoBlockedCasesReportSequence.ts
  web-client/src/presenter/sequences/gotoCaseDeadlineReportSequence.ts
  web-client/src/presenter/sequences/gotoDashboardSequence.ts
  web-client/src/presenter/sequences/gotoMessageDetailSequence.ts
  web-client/src/presenter/sequences/gotoPendingReportSequence.ts
  web-client/src/router.ts
  web-client/src/views/CaseDetail/CaseDetailSubnavTabs.tsx
  web-client/src/views/CaseDetail/CaseNotes.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/TrialSessionWorkingCopy/AddEditUserCaseNoteModal.tsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.tsx
Labels: to staging

#4287 PDF Template Generator Types
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.test.ts
  shared/src/business/useCaseHelper/generatePdfFromHtmlHelper.ts
  shared/src/business/useCaseHelper/service/sendIrsSuperuserPetitionEmail.test.ts
  shared/src/business/useCaseHelper/service/sendIrsSuperuserPetitionEmail.ts
  shared/src/business/useCaseHelper/service/sendServedPartiesEmails.test.ts
  shared/src/business/useCaseHelper/service/sendServedPartiesEmails.ts
  shared/src/business/useCases/email/handleBounceNotificationInteractor.ts
  shared/src/business/utilities/documentGenerators/addressLabelCoverSheet.ts
  shared/src/business/utilities/documentGenerators/bouncedEmailAlert.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.ts
  shared/src/business/utilities/documentGenerators/changeOfAddress.ts
  shared/src/business/utilities/documentGenerators/coverSheet.ts
  shared/src/business/utilities/documentGenerators/docketRecord.ts
  shared/src/business/utilities/documentGenerators/documentServiceEmail.ts
  shared/src/business/utilities/documentGenerators/entryOfAppearance.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeOfTrialJudge.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToInPersonProceeding.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToRemoteProceeding.ts
  shared/src/business/utilities/documentGenerators/noticeOfDocketChange.ts
  shared/src/business/utilities/documentGenerators/noticeOfReceiptOfPetition.ts
  shared/src/business/utilities/documentGenerators/noticeOfTrialIssued.ts
  shared/src/business/utilities/documentGenerators/noticeOfTrialIssuedInPerson.ts
  shared/src/business/utilities/documentGenerators/order.ts
  shared/src/business/utilities/documentGenerators/pendingReport.ts
  shared/src/business/utilities/documentGenerators/petitionServiceEmail.ts
  shared/src/business/utilities/documentGenerators/practitionerCaseList.ts
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.ts
  shared/src/business/utilities/documentGenerators/receiptOfFiling.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrder.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.ts
  shared/src/business/utilities/documentGenerators/thirtyDayNoticeOfTrial.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.test.ts
  shared/src/business/utilities/generateHTMLTemplateForPDF/reactTemplateGenerator.ts
Labels: to staging

#4300 10077: Bug: edit petition validation
  shared/src/business/entities/cases/PetitionIncomplete.test.ts
  shared/src/business/entities/cases/PetitionIncomplete.ts
  shared/src/business/test/createCaseFromPaperInteractor.e2e.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/validatePetitionFromPaperInteractor.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkEditsPetitionInQCIRSNotice.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderDesignatingPlaceOfTrialCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForCdsCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForDiscCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesPetitionPaymentFeeOptions.ts
  web-client/src/presenter/actions/validateCaseDetailAction.test.ts
  web-client/src/presenter/actions/validateCaseDetailAction.ts
Labels: to test

#4313 Delete backmerge-PR.yml
  .github/workflows/backmerge-PR.yml
Labels: to staging

#4314 Devex - 1137 Refactor Derived State
  shared/src/business/utilities/getSelectedConsolidatedCasesToMultiDocketOn.test.ts
  shared/src/business/utilities/getSelectedConsolidatedCasesToMultiDocketOn.ts
  web-client/integration-tests/journey/docketClerkEditsOrderAndChecksAddedDocketNumbers.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.test.ts
  web-client/src/presenter/actions/CaseConsolidation/loadConsolidatedCasesForAddDocketNumbersModalAction.ts
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfFromUrlAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.ts
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.test.ts
  web-client/src/presenter/actions/saveSelectedDocketNumbersAction.ts
  web-client/src/presenter/actions/setAddedDocketNumbersAction.test.ts
  web-client/src/presenter/actions/setAddedDocketNumbersAction.ts
  web-client/src/presenter/actions/setRedirectUrlAction.ts
  web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.test.ts
  web-client/src/presenter/actions/setSelectedConsolidatedCasesToMultiDocketOnAction.ts
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.test.ts
  web-client/src/presenter/computeds/addDocketNumbersModalHelper.ts
  web-client/src/presenter/computeds/createOrderHelper.test.ts
  web-client/src/presenter/computeds/createOrderHelper.ts
  web-client/src/presenter/sequences/gotoCreateOrderSequence.ts
  web-client/src/presenter/sequences/gotoEditOrderSequence.ts
  web-client/src/presenter/sequences/openEditOrderTitleModalSequence.ts
  web-client/src/presenter/sequences/submitUpdateAddDocketNumbersToOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to test

#4303 10183 story
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  shared/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.tsx
  shared/src/proxies/trialSessions/runTrialSessionPlanningReportProxy.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
  web-api/bulkImportPractitionerUsers.ts
  web-api/src/persistence/elasticsearch/fetchPendingItems.test.ts
Labels: to staging

#4315 10077: Bug: deficiency statistics validation
  shared/src/business/entities/cases/CaseInternal.test.ts
  shared/src/business/entities/cases/CaseInternal.ts
  shared/src/business/test/createCaseFromPaperInteractor.e2e.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  web-client/integration-tests/journey/petitionsClerkEditsPetitionInQCIRSNotice.ts
  web-client/src/presenter/actions/validateCaseDetailAction.test.ts
  web-client/src/presenter/actions/validateCaseDetailAction.ts
Labels: to staging

#4336 10176 dashboard pending motions style fix
  cypress/cypress-integration/integration/pending-motions-table-judge-and-chamber-dashboard.cy.ts
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  shared/src/proxies/pendingItems/updateDocketEntryWorksheetProxy.ts
  web-api/src/app.ts
  web-api/swagger.json
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesForCurrentJudgeAction.test.ts
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesForCurrentJudgeAction.ts
  web-client/src/views/Dashboards/DashboardChambers.tsx
  web-client/src/views/PendingMotion/PendingMotion.tsx
  web-client/src/views/WorkQueue/RecentMessages.tsx
Labels: to test

#4326 10195 text changes - petition submission flow
  docs/entities/PublicCase.md
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/StartCase/FilePetitionSuccess.tsx
  web-client/src/views/StartCase/SpousePermissionConfirmModal.tsx
  web-client/src/views/StartCase/StartCaseStep1.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep3.tsx
  web-client/src/views/StartCase/StartCaseStep4.tsx
  web-client/src/views/StartCase/StartCaseStep5.tsx
Labels: to test

#4333 Devex 1238 - refactor case creation entities
  shared/src/business/entities/cases/CaseExternalIncomplete.test.ts
  shared/src/business/entities/cases/CaseExternalIncomplete.ts
  shared/src/business/entities/cases/ElectronicPetition.test.ts
  shared/src/business/entities/cases/ElectronicPetition.ts
  shared/src/business/entities/cases/ElectronicPetitionForCorporationContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForEstateWithoutExecutorContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForInternationalContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForMinorWithoutGuardianContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPartnershipTaxMattersPartnerContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPetitionerAndDeceasedSpouseContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionForPetitionerAndSpouseContacts.test.ts
  shared/src/business/entities/cases/ElectronicPetitionInformationFactory.test.ts
  shared/src/business/entities/cases/ElectronicPetitionInformationFactory.ts
  shared/src/business/entities/cases/PaperPetition.test.ts
  shared/src/business/entities/cases/PaperPetition.ts
  shared/src/business/entities/contacts/ContactFactory.test.ts
  shared/src/business/test/createCaseInteractor.e2e.test.ts
  shared/src/business/test/fileExternalDocumentInteractor.e2e.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/startCase/validateStartCaseWizardInteractor.ts
  shared/src/business/useCases/validatePetitionFromPaperInteractor.ts
  shared/src/business/useCases/validatePetitionInteractor.ts
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderDesignatingPlaceOfTrialCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForCdsCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesOrderForDiscCheckbox.ts
  web-client/integration-tests/journey/petitionsClerkVerifiesPetitionPaymentFeeOptions.ts
Labels: to test

#4340 Devex aws sdk v3 documentclient to test
  cypress/cypress-smoketests/support/wait-for-noce.ts
  package.json
  scripts/run-once-scripts/archive-unwanted-outbox-records.js
  shared/admin-tools/elasticsearch/find-deadlines.js
  shared/admin-tools/glue/become-user.ts
  shared/admin-tools/util.ts
  shared/src/business/test/createMockDocumentClient.ts
  web-api/configure-dynamo-stream.js
  web-api/jest-unit.config.ts
  web-api/src/applicationContext.ts
  web-api/src/fallbackHandler.test.ts
  web-api/src/fallbackHandler.ts
  web-api/src/getDynamoEndpoints.test.ts
  web-api/src/getDynamoEndpoints.ts
  web-api/src/lambdas/streams/processStreamRecordsLambda.ts
  web-api/src/lambdas/v1/getCaseLambda.test.ts
  web-api/src/lambdas/v1/getDocumentDownloadUrlLambda.test.ts
  web-api/src/lambdas/v2/getCaseLambda.test.ts
  web-api/src/lambdas/v2/getDocumentDownloadUrlLambda.test.ts
  web-api/src/persistence/dynamo/caseDeadlines/deleteCaseDeadline.test.ts
  web-api/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.test.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCasesByLeadDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCasesMetadataByLeadDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/updatePractitionerOnCase.test.ts
  web-api/src/persistence/dynamo/correspondence/updateCaseCorrespondence.test.ts
  web-api/src/persistence/dynamo/locks/acquireLock.test.ts
  web-api/src/persistence/dynamo/locks/acquireLock.ts
  web-api/src/persistence/dynamo/messages/getMessageThreadByParentId.test.ts
  web-api/src/persistence/dynamo/messages/getMessagesByDocketNumber.test.ts
  web-api/src/persistence/dynamo/messages/markMessageThreadRepliedTo.test.ts
  web-api/src/persistence/dynamo/messages/setMessageAsRead.test.ts
  web-api/src/persistence/dynamo/messages/updateMessage.test.ts
  web-api/src/persistence/dynamo/notifications/getDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/saveDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/saveUserConnection.test.ts
  web-api/src/persistence/dynamo/trialSessions/getTrialSessionById.test.ts
  web-api/src/persistence/dynamo/trialSessions/getTrialSessions.test.ts
  web-api/src/persistence/dynamo/trialSessions/updateCaseHearing.test.ts
  web-api/src/persistence/dynamo/trialSessions/updateTrialSession.test.ts
  web-api/src/persistence/dynamo/trialSessions/updateTrialSessionWorkingCopy.test.ts
  web-api/src/persistence/dynamo/users/createOrUpdatePractitionerUser.test.ts
  web-api/src/persistence/dynamo/users/createOrUpdateUser.test.ts
  web-api/src/persistence/dynamo/users/createPetitionerUserRecords.test.ts
  web-api/src/persistence/dynamo/workitems/deleteWorkItem.test.ts
  web-api/src/persistence/dynamo/workitems/getDocumentQCServedForSection.test.ts
  web-api/src/persistence/dynamo/workitems/getDocumentQCServedForUser.test.ts
  web-api/src/persistence/dynamo/workitems/putWorkItemInOutbox.test.ts
  web-api/src/persistence/dynamo/workitems/putWorkItemInUsersOutbox.test.ts
  web-api/src/persistence/dynamo/workitems/saveWorkItemForDocketClerkFilingExternalDocument.test.ts
  web-api/src/persistence/dynamo/workitems/setPriorityOnAllWorkItems.test.ts
  web-api/src/persistence/dynamodbClientService.test.ts
  web-api/src/persistence/dynamodbClientService.ts
  web-client/integration-tests/helpers.ts
Labels: to test

#4341 10197: Remove Guard and Pass user from websocket message
  cypress/cypress-integration/integration/practitioners-with-no-cases.cy.ts
  cypress/cypress-integration/support/helpers.ts
  shared/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.test.ts
  shared/src/business/useCases/users/verifyUserPendingEmailInteractor.ts
  web-client/src/presenter/actions/setUserAction.test.ts
  web-client/src/presenter/actions/setUserAction.ts
Labels: to test
