Repository ustaxcourt/ef-cms, pull requests merged in 2023-01, with the labels that each got.

#2987 9719 icon bug test
  shared/src/business/entities/DocketEntry.getServedPartiesCode.test.js
  shared/src/business/entities/DocketEntry.js
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.test.ts
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.ts
  web-client/integration-tests/docketClerkConsolidatedCaseWorkItemsJourney.test.js
  web-client/integration-tests/journey/docketClerkAddsAnUnservableDocument.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedLeadCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/practitionerFilesDocumentForOwnedCase.js
  web-client/src/presenter/actions/EditDocketRecordEntry/setDocketEntryMetaFormForEditAction.test.js
  web-client/src/presenter/computeds/formattedTrialSessions.formatSession.test.js
Labels: to test

#2989 9749: rearrange trial status options in dropdown
  docs/ci-cd.md
  shared/src/business/entities/EntityConstants.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.trialStatus.test.js
Labels: to test

#2985 9775 BUG Fix: Docket record sort dropdown is not displaying label for external mobile users
  web-client/integration-tests/petitionerWithRepresentationChangesEmail.test.js
  web-client/src/presenter/computeds/docketRecordHelper.js
  web-client/src/presenter/computeds/docketRecordHelper.test.js
  web-client/src/styles/tabs.scss
  web-client/src/views/DocketRecord/DocketRecordHeader.jsx
Labels: to test

#2988 DevEx - Refactor TrialSession to TypeScript
  shared/src/business/entities/JoiValidationDecorator.ts
  shared/src/business/entities/trialSessions/TrialSession.js
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/utilities/DateHandler.js
  shared/src/persistence/dynamo/trialSessions/getTrialSessions.ts
  tsconfig.json
Labels: to staging

#2970 Devex: Address 504 errors
  web-api/src/applicationContext.js
  web-api/src/getDynamoEndpoints.js
Labels: to staging

#2973 Devex 1078: Sortable docket number should use 4-digit year
  docs/additional-resources/blue-green-migration.md
  shared/src/business/entities/CaseDeadline.test.js
  shared/src/business/entities/cases/Case.getSortableDocketNumber.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/test/mockCase.js
  web-api/migration-terraform/main/lambdas/migrations/0006-reformat-sortable-docket-number.js
  web-api/migration-terraform/main/lambdas/migrations/0006-reformat-sortable-docket-number.test.js
  web-api/migration-terraform/main/lambdas/migrationsToRun.js
  web-api/src/v1/getCaseLambda.test.js
  web-api/src/v2/getCaseLambda.test.js
Labels: Blue/Green Migration, to staging

#2986 9669 Additional Case Status Category - Closed (Dismissed)
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/cases/Case.canConsolidate.test.js
  shared/src/business/entities/cases/Case.closeCase.test.js
  shared/src/business/entities/cases/Case.isClosed.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/entities/cases/Case.reopenCase.test.js
  shared/src/business/entities/cases/Case.setCaseStatus.test.js
  shared/src/business/entities/cases/Case.shouldGenerateNotices.test.js
  shared/src/business/entities/cases/Case.test.js
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.js
  shared/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.js
  shared/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.js
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  shared/src/business/useCases/trialSessions/batchDownloadTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  shared/src/tools/courtIssuedEventCodes.json
  web-api/migration-terraform/main/lambdas/migrations/0001-remove-has-sealed-documents.js
  web-api/migration-terraform/main/lambdas/migrations/0001-remove-has-sealed-documents.test.js
  web-api/migration-terraform/main/lambdas/migrations/0002-default-sealed-to.js
  web-api/migration-terraform/main/lambdas/migrations/0002-default-sealed-to.test.js
  web-api/migration-terraform/main/lambdas/migrations/0004-remove-closedDate-for-open-cases.js
  web-api/migration-terraform/main/lambdas/migrations/0004-remove-closedDate-for-open-cases.test.js
  web-api/migration-terraform/main/lambdas/migrationsToRun.js
  web-api/src/applicationContext.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-api/storage/scripts/seedLocalDatabase.js
  web-client/integration-tests/caseStatusClosedDismissedJourney.test.js
  web-client/integration-tests/docketClerkEditsACalendaredTrialSession.test.js
  web-client/integration-tests/externalUserViewsOpenAndClosedCases.test.js
  web-client/integration-tests/journey/docketClerkUpdatesCaseStatusTo.js
  web-client/integration-tests/journey/docketClerkUpdatesCaseStatusToClosed.js
  web-client/integration-tests/journey/docketClerkViewsCaseDetailAfterServingCourtIssuedDocument.js
  web-client/integration-tests/petitionerWithRepresentationChangesEmail.test.js
  web-client/integration-tests/trialSessionChangeToRemoteProceedingJourney.test.js
  web-client/src/applicationContext.js
  web-client/src/getConstants.js
  web-client/src/presenter/computeds/caseInventoryReportHelper.js
  web-client/src/presenter/computeds/caseInventoryReportHelper.test.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.js
Labels: to staging

#2996 BUG-9776: Swing Session Icon Missing On Trial Sessions Views
  shared/src/business/dto/TrialSessionInfoDto.ts
  types/TEntity.d.ts
  web-client/integration-tests/docketClerkCreatesATrial.test.js
  web-client/integration-tests/journey/docketClerkCreatesATrialSession.js
  web-client/integration-tests/journey/docketClerkViewsTrialSessionList.js
  web-client/integration-tests/trialSessionChangeToRemoteProceedingJourney.test.js
Labels: to test

#2994 9775 BUG Fix: Docket record sort dropdown is not displaying label for external mobile users
  web-client/src/presenter/computeds/docketRecordHelper.js
  web-client/src/presenter/computeds/docketRecordHelper.test.js
  web-client/src/styles/tabs.scss
  web-client/src/views/DocketRecord/DocketRecordHeader.jsx
Labels: to staging

#2997 9749: rearrange trial status options
  docs/ci-cd.md
  shared/src/business/entities/EntityConstants.js
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.trialStatus.test.js
Labels: to staging

#2980 9719 icon bug
  shared/src/business/entities/DocketEntry.getServedPartiesCode.test.js
  shared/src/business/entities/DocketEntry.js
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.test.ts
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.ts
  web-client/integration-tests/docketClerkConsolidatedCaseWorkItemsJourney.test.js
  web-client/integration-tests/journey/docketClerkAddsAnUnservableDocument.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/docketClerkVerifiesConsolidatedLeadCaseIndicatorDocumentQCSection.js
  web-client/integration-tests/journey/practitionerFilesDocumentForOwnedCase.js
  web-client/src/presenter/actions/EditDocketRecordEntry/setDocketEntryMetaFormForEditAction.test.js
Labels: to staging

#3015 Devex 1112 actual - fix
  cypress-smoketests/integration/case-creation.cy.js
  cypress-smoketests/integration/change-address.cy.js
  web-client/src/presenter/computeds/formattedTrialSessions.formatSession.test.js
Labels: to test

#2992 DevEx - Remove Duplicate Test action runs
  .github/workflows/api.yml
  .github/workflows/build-ts-api.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-client/integration-tests/petitionsClerkCounselAssociationElectronicServiceJourney.test.js
Labels: to staging

#2981 minor version updates
  package-lock.json
Labels: to staging

#3009 BUG 9776: Swing session icon missing
  shared/src/business/dto/TrialSessionInfoDto.ts
  types/TEntity.d.ts
  web-client/integration-tests/docketClerkCreatesATrial.test.js
  web-client/integration-tests/journey/docketClerkCreatesATrialSession.js
  web-client/integration-tests/journey/docketClerkViewsTrialSessionList.js
Labels: to staging

#3019 Devex 1082 long running glue jobs
  aws/lambdas/LogsToElasticSearch_info/index-template.json
  web-api/migration-terraform/main/lambdas/migration-segments.js
  web-api/migration-terraform/main/lambdas/migration-segments.test.js
Labels: to staging

#3003 IntegrationTestFix: Increase Timout of two long running tests. Remove unused setTimeout in BeforeAll
  web-client/integration-tests/journey/petitionsClerkSetsATrialSessionsSchedule.js
  web-client/integration-tests/trialSessionChangeToRemoteProceedingJourney.test.js
Labels: to staging

#3007 devex-1094: add typescript to coverage in jest.config files
  scripts/jest-scripts.config.js
  shared/jest.config.js
  web-api/jest.config.js
  web-client/jest-unit.config.js
  web-client/jest.config.js
Labels: to staging

#3023 9772 E-Filing: Remove M123 As E-Filing Option
  docs/entities/PublicCase.md
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/externalFilingEvents.json
  web-client/integration-tests/externalUserFilesDocumentForLegacyCase.test.js
  web-client/integration-tests/journey/userTriesToFileAnUnavailableDocumentType.js
Labels: to staging

#3001 9594 consolidated visibility for petitioner
  .github/workflows/client-integration.yml
  .github/workflows/e2e-pa11y.yml
  cypress-smoketests.config.js
  cypress.config.js
  run-local.sh
  scripts/dynamo/setup-consolidated-cases-group-access-petitioner-flag.sh
  scripts/run-cypress.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.js
  shared/src/business/entities/cases/Case.isPetitionerPartOfGroup.test.js
  shared/src/business/entities/cases/Case.js
  shared/src/business/test/createTestApplicationContext.js
  shared/src/business/useCases/caseAssociation/deleteCounselFromCaseInteractor.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCasesByCaseInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/persistence/dynamo/users/createNewPractitionerUser.ts
  tsconfig.json
  types/TEntity.d.ts
  web-api/src/v1/getCaseLambda.test.js
  web-api/src/v1/getDocumentDownloadUrlLambda.test.js
  web-api/src/v2/getCaseLambda.test.js
  web-api/src/v2/getDocumentDownloadUrlLambda.test.js
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/streams-local.js
  web-client/integration-tests/docketClerkConsolidatesCases.test.js
  web-client/integration-tests/fixtures/consolidated-cases.ts
  web-client/integration-tests/helpers.js
  web-client/integration-tests/petitionerAccessesAssociatedConsolidatedGroupCase.test.js
  web-client/integration-tests/utils/database.js
  web-client/pa11y/pa11y-docketclerk.js
  web-client/pa11y/pa11y-petitioner.js
  web-client/src/applicationContext.js
  web-client/src/presenter/actions/getCaseAssociationAction.js
  web-client/src/presenter/actions/getCaseAssociationAction.test.js
  web-client/src/presenter/actions/setCaseAssociationAction.js
  web-client/src/presenter/actions/setCaseAssociationAction.test.js
  web-client/src/presenter/computeds/caseDetailHeaderHelper.js
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.js
  web-client/src/presenter/sequences/gotoCaseDetailSequence.js
Labels: to staging

#3033 DEP UPDATES Week of 1-16-23
  .circleci/config.yml
  .github/workflows/api.yml
  .github/workflows/build-ts-api.yml
  .github/workflows/client-integration.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  Dockerfile-local
  docs/dependency-updates.md
  docs/running-locally.md
  package-lock.json
  package.json
  reset-dependencies.sh
  web-api/runtimes/puppeteer/build.sh
Labels: to staging

#3038 Admin script: monthly paper vs electronic stats
  shared/admin-tools/elasticsearch/get-petition-counts.js
Labels: to staging

#3055 9664: Feedback
  shared/src/business/entities/Penalty.js
  shared/src/business/entities/Penalty.test.js
  shared/src/business/entities/Statistic.test.js
  shared/src/business/useCases/caseStatistics/addDeficiencyStatisticInteractor.ts
  shared/src/business/useCases/caseStatistics/updateDeficiencyStatisticInteractor.ts
  shared/src/business/useCases/validatePenaltiesInteractor.test.ts
  web-client/integration-tests/journey/petitionsClerkAddsDeficiencyStatisticToCase.js
  web-client/integration-tests/journey/petitionsClerkEditsDeficiencyStatistic.js
  web-client/src/presenter/actions/addPenaltyInputAction.js
  web-client/src/presenter/actions/calculatePenaltiesAction.js
  web-client/src/presenter/actions/calculatePenaltiesAction.test.js
  web-client/src/presenter/actions/refreshStatisticsAction.js
  web-client/src/presenter/actions/setDefaultPenaltiesAction.js
  web-client/src/presenter/actions/setStatisticIndexAction.js
  web-client/src/presenter/actions/setupItemizedPenaltiesModalStateAction.test.js
  web-client/src/presenter/actions/validatePenaltiesAction.js
  web-client/src/presenter/actions/validatePenaltiesAction.test.js
  web-client/src/presenter/computeds/statisticsFormHelper.js
  web-client/src/presenter/computeds/statisticsFormHelper.test.js
  web-client/src/views/CaseDetail/DeficiencyStatisticsForm.jsx
  web-client/src/views/StartCaseInternal/CalculatePenaltiesModal.jsx
Labels: to test
