Repository ustaxcourt/ef-cms, pull requests merged in 2024-01, with the labels that each got.

#4467 10231: if migrating, only create indices on destination domain
  web-api/setup-elasticsearch-index.sh
Labels: to staging

#4483 10210 bugfix
  web-client/src/styles/custom.scss
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to test

#4457 Dependency Updates
  .circleci/config.yml
  .eslintrc.js
  Dockerfile
  docs/additional-resources/blue-green-migration.md
  docs/dependency-updates.md
  docs/temp/opensearch_upgrade_deploy_instructions.md
  iam/terraform/account-specific/bin/deploy-opensearch-info.sh
  iam/terraform/account-specific/main/elasticsearch.tf
  iam/terraform/account-specific/main/lambda-es-role.tf
  iam/terraform/account-specific/main/lambda-logs-to-elasticsearch.tf
  iam/terraform/account-specific/main/lambda-rotate-info-indices.tf
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/terraform/bin/init.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/bin/deploy-opensearch-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/elasticsearch/elasticsearch.tf
  web-api/terraform/template/elasticsearch/outputs.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging, Manual Deploy Step(s) Required

#4502 Merge staging into test
  .circleci/config.yml
  .eslintrc.js
  Dockerfile
  docs/additional-resources/blue-green-migration.md
  docs/dependency-updates.md
  docs/temp/opensearch_upgrade_deploy_instructions.md
  iam/terraform/account-specific/bin/deploy-opensearch-info.sh
  iam/terraform/account-specific/main/elasticsearch.tf
  iam/terraform/account-specific/main/lambda-es-role.tf
  iam/terraform/account-specific/main/lambda-logs-to-elasticsearch.tf
  iam/terraform/account-specific/main/lambda-rotate-info-indices.tf
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/terraform/bin/init.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/bin/deploy-opensearch-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/elasticsearch/elasticsearch.tf
  web-api/terraform/template/elasticsearch/outputs.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: Manual Deploy Step(s) Required

#4508 10232: adding debug logging
  shared/src/business/useCases/getCasesForUserInteractor.ts
Labels: to test

#4511 10232: perform batchGet in parallel; keep timestamps in comment
  shared/src/business/useCases/getCasesForUserInteractor.ts
  web-api/src/persistence/dynamodbClientService.ts
Labels: to test

#4510 10214: Include docketNumber suffix for pending motion table
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.test.ts
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
Labels: to test

#4520 10232: better granularity on timing
  shared/src/business/useCases/getCasesForUserInteractor.ts
Labels: to test

#4458 design-debt-1207
  web-client/src/styles/cards.scss
Labels: to staging

#4523 10197 debug users with pending email
  web-api/elasticsearch/efcms-user-mappings.ts
Labels: to test

#4515 DX-1234 Correspondence Column header
  web-client/src/views/Correspondence/Correspondence.tsx
Labels: to test

#4528 10232 cases endpoint 504s intermediate branch to test 1704739480
  shared/src/business/useCases/getCasesForUserInteractor.ts
  web-api/src/persistence/dynamodbClientService.ts
Labels: to test

#4527 1235 UX Feedback
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to test

#4526 1242 design debt
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.ts
Labels: to test

#4459 10221-bug:
  web-client/src/presenter/actions/FileDocument/setDocumentFileForAutoGeneratedEntryOfAppearanceAction.ts
Labels: to staging

#4489 10210 bugfix
  web-client/src/styles/custom.scss
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging

#4535 10214: Speed up the interactor
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.test.ts
  shared/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/cases/getCaseMetadataByDocketNumber.ts
  web-api/src/persistence/dynamo/cases/getConsolidatedCasesCount.ts
  web-api/src/persistence/dynamo/cases/getDocketEntryOnCase.ts
Labels: to test

#4516 DX-1234 Correspondence Column header
  web-client/src/views/Correspondence/Correspondence.tsx
Labels: to staging

#4519 DX-1235 - Removed bold texts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
Labels: to staging

#4539 9583: Allow sorting messages for Internal/Court users
  cypress/cypress-integration/integration/messages.cy.ts
  cypress/helpers/retry.ts
  cypress/helpers/sort-message-column-header.ts
  web-client/integration-tests/adcClerkViewsMessagesJourney.test.ts
  web-client/integration-tests/messagesTableJourney.test.ts
  web-client/src/presenter/actions/setDefaultTableSortAction.test.ts
  web-client/src/presenter/actions/setDefaultTableSortAction.ts
  web-client/src/presenter/computeds/showSortableHeaders.test.ts
  web-client/src/presenter/computeds/showSortableHeaders.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/CaseDetail/CaseDetailHeaderMenu.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Messages/CompleteMessageModalDialog.tsx
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/MessageDetail.tsx
  web-client/src/views/Messages/Messages.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
Labels: Do Not Merge, to test

#4543 10202 bugfix (ux feedback + dod)
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/state/trialSessionState.ts
Labels: to test

#4545 10238: Re-Enable EA Generation on Cases w/ Paper Service for Private Practitioners - TO TEST
  cypress/cypress-integration/integration/practitioner-request-access-to-case.cy.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.ts
  web-client/src/presenter/computeds/requestAccessHelper.test.ts
  web-client/src/presenter/computeds/requestAccessHelper.ts
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
Labels: to test

#4548 Dx1243 petitions qc error message
  shared/src/business/entities/cases/CaseQC.test.ts
  shared/src/business/entities/cases/CaseQC.ts
  web-client/integration-tests/docketClerkEditsPetitionPaymentFee.test.ts
Labels: to test

#4549 10224 bug
  shared/src/business/useCaseHelper/consolidatedCases/formatPublicCase.test.ts
  shared/src/business/useCases/createCaseInteractor.test.ts
  shared/src/business/useCases/saveCaseDetailInternalEditInteractor.test.ts
  shared/src/business/useCases/updatePetitionerInformationInteractor.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.test.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-api/workflow-terraform/migration/bin/deploy-init.sh
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/actions/getUsersInSectionAction.ts
  web-client/src/presenter/sequences/gotoCustomCaseReportSequence.ts
Labels: to test

#4522 DX-1242 - design debt
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.ts
Labels: to staging

#4557 debug github action
  .github/workflows/typescript-untouched-files-check.yml
Labels: to staging

#4530 10232 cases endpoint 504s
  shared/src/business/useCases/getCasesForUserInteractor.test.ts
  shared/src/business/useCases/getCasesForUserInteractor.ts
  web-api/src/persistence/dynamodbClientService.ts
Labels: to staging

#4531 10203: Add "ATP" event code;
  shared/src/business/entities/DocketEntry.setAsServed.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/useCaseHelper/serveDocumentAndGetPaperServicePdf.test.ts
  shared/src/business/useCaseHelper/serveDocumentAndGetPaperServicePdf.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.test.ts
  shared/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  shared/src/tools/internalFilingEvents.json
Labels: to staging

#4544 Update Team Charter 2024
  docs/additional-resources/DAWSON-team-charter.md
Labels: to staging

#4537 devex: Update linter for no floating promises.
  .eslintrc.js
  package.json
  shared/src/business/useCaseHelper/email/sendEmailVerificationLink.test.ts
  shared/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  shared/src/business/useCases/pdf/validatePdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/createTrialSessionInteractor.ts
  shared/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  shared/src/business/useCases/validateCaseDetailInteractor.ts
  shared/src/business/utilities/createSignedDocumentsForInspection.ts
  shared/src/business/utilities/sleep.test.ts
  tsconfig.json
  web-api/src/app-local.ts
  web-api/src/logger.test.ts
  web-api/src/persistence/s3/zipS3Files.ts
  web-api/storage/fixtures/create-random-cases.ts
  web-api/storage/fixtures/get-diffs.ts
  web-api/storage/fixtures/validate-seed.ts
  web-api/storage/scripts/cases/createOrder.ts
  web-api/storage/scripts/loadTest/loadTestPdfGeneration.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesForOpinionByDocketNumber.ts
  web-client/integration-tests/helpers.ts
  web-client/src/app.tsx
  web-client/src/index.ts
  web-client/src/presenter/actions/persistPublicAppStateAction.ts
  web-client/src/presenter/actions/validateCaseDetailsAction.ts
  web-client/src/providers/socket.ts
  webpack.config.lambda.api.ts
Labels: to staging

#4541 devex-1187: increase petitioner additional name character count
  shared/src/business/entities/contacts/Petitioner.test.ts
  shared/src/business/entities/contacts/Petitioner.ts
Labels: to staging

#4547 10238: Re-Enable EA Generation on Cases w/ Paper Service for Private Practitioners
  cypress/cypress-integration/integration/practitioner-request-access-to-case.cy.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.test.ts
  web-client/src/presenter/actions/setDefaultGenerationTypeAction.ts
  web-client/src/presenter/computeds/requestAccessHelper.test.ts
  web-client/src/presenter/computeds/requestAccessHelper.ts
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
Labels: to staging

#4540 10202 bugfix
  shared/src/business/dto/trialSessions/TrialSessionInfoDTO.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.test.ts
  shared/src/business/useCases/trialSessions/generateTrialCalendarPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.test.ts
  shared/src/business/utilities/documentGenerators/trialCalendar.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.test.ts
  shared/src/business/utilities/getFormattedTrialSessionDetails.ts
  shared/src/business/utilities/htmlGenerator/utils.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Trial_Calendar.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.2.png
  web-client/src/presenter/actions/TrialSession/canSetTrialSessionToCalendarAction.ts
  web-client/src/presenter/actions/TrialSession/getTrialSessionDetailsAction.ts
  web-client/src/presenter/actions/TrialSession/mergeCaseOrderIntoCalendaredCasesAction.ts
  web-client/src/presenter/actions/TrialSession/mergeCaseOrderIntoEligibleCasesAction.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/trialSessionHeaderHelper.ts
  web-client/src/presenter/state/trialSessionState.ts
Labels: to staging

#4461 10224-bug
  web-api/elasticsearch/efcms-case-mappings.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.test.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/actions/getUsersInSectionAction.ts
  web-client/src/presenter/sequences/gotoCustomCaseReportSequence.ts
Labels: elasticsearch, to staging

#4550 Design debt 1243 - Clarifying a Petitions QC Error Message
  shared/src/business/entities/cases/CaseQC.test.ts
  shared/src/business/entities/cases/CaseQC.ts
  web-client/integration-tests/docketClerkEditsPetitionPaymentFee.test.ts
Labels: to staging

#4551 Update DOD template
  .github/ISSUE_TEMPLATE/ustc-story-template.md
Labels: to staging

#4570 Backmerge staging into test
  .github/ISSUE_TEMPLATE/ustc-story-template.md
Labels: to test

#4565 Devex - fix lint error
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
Labels: to test

#4571 Devex fix lint error
  shared/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
Labels: to staging

#4554 Devex improving smoke tests again
  cypress/cypress-smoketests/integration/change-address.cy.ts
  cypress/helpers/auth/login-as-helpers.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
  web-client/src/views/EditPetitionerCounsel.tsx
Labels: to staging

#4542 Dependency updates - Week of 01/08/24
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  package-lock.json
  package.json
  web-api/workflow-terraform/glue-cron/main/glue-job-status.tf
  web-api/workflow-terraform/migration-cron/main/migration-status.tf
  web-api/workflow-terraform/reindex-cron/main/reindex-status.tf
  web-api/workflow-terraform/switch-colors-cron/main/switch-colors.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/wait-for-workflow.tf
Labels: to staging

#4576 10218 Add ATP to petitions flow
  cypress/cypress-integration/integration/petitions-clerk-creates-a-case.cy.ts
  cypress/cypress-integration/support/pages/create-paper-petition.ts
  cypress/helpers/create-and-serve-paper-petition.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/PaperPetition.test.ts
  shared/src/business/entities/cases/PaperPetition.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/filePetitionFromPaperInteractor.test.ts
  shared/src/business/useCases/filePetitionFromPaperInteractor.ts
  shared/src/business/useCases/uploadDocumentAndMakeSafeInteractor.ts
  shared/src/proxies/createCaseFromPaperProxy.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.test.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.ts
  web-client/src/presenter/actions/saveCaseDetailInternalEditAction.ts
  web-client/src/presenter/actions/unsetDocumentSelectedForPreviewAction.ts
  web-client/src/presenter/computeds/petitionQcHelper.test.ts
  web-client/src/presenter/computeds/petitionQcHelper.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.test.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.ts
  web-client/src/presenter/computeds/scanHelper.test.ts
  web-client/src/presenter/computeds/scanHelper.ts
  web-client/src/views/CaseDetailEdit/Attachments.tsx
  web-client/src/views/CaseDetailEdit/IRSNoticeCaseReview.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/PDFPreviewButton.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
Labels: to test

#4582 9583: Sorting messages
  cypress/cypress-integration/integration/messages.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/helpers/retry.ts
  cypress/helpers/sort-message-column-header.ts
  cypress/support/commands/keepAliases.ts
  web-client/integration-tests/adcClerkViewsMessagesJourney.test.ts
  web-client/integration-tests/messagesTableJourney.test.ts
  web-client/src/presenter/actions/setDefaultTableSortAction.test.ts
  web-client/src/presenter/actions/setDefaultTableSortAction.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/computeds/showSortableHeaders.test.ts
  web-client/src/presenter/computeds/showSortableHeaders.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/CaseDetail/CaseDetailHeaderMenu.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Messages/CompleteMessageModalDialog.tsx
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/MessageDetail.tsx
  web-client/src/views/Messages/Messages.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
Labels: to staging

#4577 Design Debt 1219 - Move Submission Buttons on some forms
  web-client/src/views/Correspondence/AddCorrespondenceDocument.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
Labels: to staging

#4587 Fix tsconfig and Github Action
  tsconfig.json
Labels: to staging

#4593 Dx1219 fix move submission controls
  web-client/src/views/Correspondence/AddCorrespondenceDocument.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
Labels: to staging

#4546 devex 1044: add terraform script that defines opensearch snapshot repository
  iam/terraform/account-specific/bin/deploy-init.sh
  iam/terraform/account-specific/bin/deploy-opensearch-info.sh
  iam/terraform/account-specific/main/cognito.tf
  iam/terraform/account-specific/main/elasticsearch.tf
  iam/terraform/account-specific/main/main.tf
  iam/terraform/account-specific/main/s3.tf
  iam/terraform/account-specific/main/variables.tf
Labels: to staging, Manual Deploy Step(s) Required, Needs Account Specific

#4599 10250: To Test
  cypress/cypress-integration/integration/judge-draft-order-notice.cy.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-client/src/presenter/actions/removeSignatureAction.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.test.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.ts
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
Labels: to test

#4578 Dependency Updates - Week of Jan 15, 2024
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesAction.ts
  web-client/terraform/main/main.tf
Labels: to staging

#4604 10255: Fix modal bugs TO TEST
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.test.ts
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.ts
  web-client/src/presenter/actions/setCreateOrderSelectedCasesAction.test.ts
  web-client/src/presenter/actions/setCreateOrderSelectedCasesAction.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.test.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.ts
  web-client/src/presenter/sequences/submitUpdateAddDocketNumbersToOrderSequence.ts
  web-client/src/presenter/state.ts
Labels: bugfix, to test

#4610 9584: Court User - Filtering Messages
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  cypress/cypress-integration/integration/messages.cy.ts
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/account-specific/main/s3.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesAction.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/terraform/main/main.tf
Labels: to test

#4614 9584: Remove Filters on the Individual Completed section;
  cypress/cypress-integration/integration/messages.cy.ts
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
Labels: to test

#4602 10250: BUG: Removing a Judge's signature from a draft Order causes issues with some functionality
  cypress/cypress-integration/integration/judge-draft-order-notice.cy.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  web-api/src/persistence/elasticsearch/caseDeadlines/getCaseDeadlinesByDateRange.test.ts
  web-client/src/presenter/actions/removeSignatureAction.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.test.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.ts
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
Labels: bugfix, to staging
