Repository ustaxcourt/ef-cms, pull requests merged in 2024-11, with the labels that each got.

#5435 10363: AWS Batch
  .circleci/config.yml
  cypress-smoketests.config.ts
  cypress/deployed-and-local/integration/aws-batch-docket-entries-download/aws-batch-docket-entries-download.cy.ts
  cypress/helpers/cypressTasks/dynamo/dynamo-helpers.ts
  cypress/local-only/support/database.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/dynamo/setup-aws-batch-zipper-minimum-count.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/src/persistence/batch/getBatchClient.ts
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/modules/batch/batch.tf
  web-api/terraform/modules/batch/docker-image/Dockerfile
  web-api/terraform/modules/batch/docker-image/check-env-variables.sh
  web-api/terraform/modules/batch/docker-image/deploy-to-ecr.sh
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
  web-api/terraform/modules/batch/docker-image/tsconfig.json
  web-api/terraform/modules/batch/variables.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/elastic-container-registry/batch-elastic-container-registry.tf
  web-api/terraform/modules/elastic-container-registry/variables.tf
  web-api/terraform/modules/lambda-role/lambda-role.tf
  web-client/src/presenter/actions/BatchDownload/resetBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/BatchDownload/setBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.ts
  web-client/src/presenter/sequences/batchDownloadDocketEntriesSequence.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to staging, Manual Deploy Step(s) Required, Needs Account Specific

#5492 10480 Story: M112 and M116 Motion Issues
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/DocketEntryFactory.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/entities/externalDocument/SecondaryDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/SecondaryDocumentInformationFactory.ts
  shared/src/tools/Event Codes - External Filings - Internal Document List.csv
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
  web-client/src/presenter/actions/FileDocument/refreshExternalDocumentTitleFromEventCodeAction.ts
  web-client/src/presenter/actions/FileDocument/setSupportingDocumentScenarioAction.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.ts
  web-client/src/presenter/computeds/editDocketEntryMetaHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.ts
Labels: to staging

#5498 10412 Design Debt: Message Table Improvements
  cypress/deployed-and-local/integration/documentQC/complete-docket-qc.cy.ts
  cypress/local-only/tests/integration/messages/messages.cy.ts
  web-client/src/styles/tables.scss
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/Messages/MessageColumns.test.ts
  web-client/src/views/Messages/MessageColumns.ts
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to staging

#5506 10363: AWS Batch Piggyback
  .circleci/config.yml
Labels: to staging

#5508 10363: Fix cypress test for AWS Batch
  cypress/helpers/cypressTasks/dynamo/dynamo-helpers.ts
Labels: to staging

#5504 10460: Handle UX Feedback
  cypress/readonly/integration/public/trial-sessions.cy.ts
  package-lock.json
  web-api/terraform/applyables/blue/blue.tf
  web-client/src/presenter/computeds/Public/publicTrialSessionsHelper.ts
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsDataRow.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsTable.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessions.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsRemoteProceedingsCard.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsTable.tsx
Labels: Do Not Merge, to test

#5507 Dep updates 2024 10 28
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
Labels: to staging, Review Please

#5512 10460: Create custom select for Public Mobile view
  cypress/local-only/tests/integration/public/trialSessions/trial-sessions.cy.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionHelper.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionsHelper.ts
  web-client/src/ustc-ui/Select/Selects.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsFilters.tsx
Labels: to test

#5514 Devex: fix cross-account role assumption
  .circleci/config.yml
  scripts/migration/set-migration-complete-marker.sh
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/account-specific/variables.tf
  web-api/terraform/bin/deploy-account-specific.sh
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/ci-cd/variables.tf
  web-api/terraform/modules/rds/restore.tf
Labels: to staging, Needs Account Specific

#5524 10363: Fix Cypress Cache issue
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/business/useCases/featureFlag/getAllFeatureFlagsInteractor.ts
Labels: Do Not Merge, to test

#5521 10275 back to test
  package-lock.json
  package.json
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.ts
  shared/src/test/mockCasesReadyForTrial.json
  shared/src/test/mockReadyForTrialCases.json
  shared/src/test/mockSpecialTrialSessions.json
  shared/src/test/mockTrialSessions.json
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/getDataForCalendaring.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/getDataForCalendaring.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-api/src/persistence/elasticsearch/getSuggestedCalendarCases.test.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.test.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.test.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermModalAction.test.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermModalAction.ts
  web-client/src/presenter/actions/downloadXlsxAction.test.ts
  web-client/src/presenter/utilities/downloadXlsx.test.ts
Labels: to test

#5496 10535/10432 Story
  web-client/src/presenter/actions/TrialSession/trialSessionQueryParamsAction.test.ts
  web-client/src/presenter/actions/TrialSession/trialSessionQueryParamsAction.ts
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/presenter/state.ts
Labels: to staging

#5517 10391: give the restore postgres script a title that's not copypasta
  .circleci/config.yml
Labels: to staging

#5528 OpEx: Postgres Quality-of-Life Improvements
  .circleci/config.yml
  check-env-variables.sh
  docs/postgres/connect-to-deployed-db.md
  scripts/helpers/prior-confirmation.sh
  scripts/helpers/suppress-output.sh
  scripts/postgres/connect.sh
  scripts/postgres/generate-token.sh
  scripts/postgres/get-read-only-endpoint.sh
  scripts/postgres/get-read-write-endpoint.sh
Labels: to staging

#5529 10461 Story: Public Trial Session Details - Addressing UX Feedback
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionDetailsInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionDetailsInteractor.ts
  web-client/src/presenter/actions/Public/TrialSessions/getPublicTrialSessionDetailsAction.test.ts
  web-client/src/presenter/actions/Public/TrialSessions/setPublicTrialSessionDetailsAction.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionDetailsHelper.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionDetailsHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Icon/CaseIcons.tsx
  web-client/src/ustc-ui/Icon/ConsolidatedCaseIcon.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionDetails.tsx
  web-client/src/views/TrialSessionDetails/AllCases.tsx
  web-client/src/views/TrialSessionDetails/EligibleCases.tsx
  web-client/src/views/TrialSessionDetails/InactiveCases.tsx
  web-client/src/views/TrialSessionDetails/OpenCases.tsx
  web-client/src/views/TrialSessionDetails/TrialSessionDetailsHeader.tsx
  web-client/src/views/TrialSessionDetails/TrialSessionInformation.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test, Review Please

#5530 OpEx: fix terraform build errors
  .circleci/config.yml
  docs/postgres/deployment.md
  scripts/env/env-for-circle.sh
  scripts/env/environments/00-common
  scripts/postgres/generate-token.sh
  scripts/postgres/get-host.sh
  scripts/postgres/get-read-only-endpoint.sh
  scripts/postgres/get-read-write-endpoint.sh
  web-api/terraform/modules/batch/batch.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
Labels: to staging, Needs Account Specific

#5525 10363: Fix Cypress Cache issue STG
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/business/useCases/featureFlag/getAllFeatureFlagsInteractor.ts
Labels: to staging

#5522 10492 dxox updates to test
  types/TEntity.d.ts
  web-api/src/business/useCases/caseNote/updateUserCaseNoteInteractor.test.ts
  web-api/src/business/useCases/caseNote/updateUserCaseNoteInteractor.ts
  web-api/src/persistence/postgres/userCaseNotes/mocks.jest.ts
  web-api/src/persistence/postgres/userCaseNotes/updateUserCaseNote.ts
  web-api/src/persistence/postgres/userCaseNotes/upsertUserCaseNote.ts
Labels: to test

#5532 10525: Full Spectrum Docket Sorting TO TEST
  cypress/local-only/tests/integration/caseDetail/consolidated-case.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/getFormattedCaseDetail.formatDocketEntry.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/proxies/generateDocketRecordPdfProxy.ts
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.test.ts
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.ts
  web-client/src/presenter/actions/clearDocketRecordTableSortAction.test.ts
  web-client/src/presenter/actions/clearDocketRecordTableSortAction.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.test.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.test.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/sortTableSequence.ts
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/Messages/MessageColumns.test.ts
  web-client/src/views/Messages/MessageColumns.ts
  web-client/src/views/Messages/MessageTable.tsx
Labels: to test

#5536 10275 test
  cypress/local-only/tests/integration/trialSession/run-suggested-calendar-generator.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/DateHandler.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/proxies/trialSessions/generateSuggestedTrialSessionCalendarProxy.ts
  shared/src/test/mockTrialSessions.json
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-client/src/presenter/actions/TrialSession/formatAlertWarningForTermGeneratorAction.tsx
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.test.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.ts
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/sequences/TrialSessions/submitCreateTermModalSequence.ts
  web-client/src/views/SuccessNotification.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test

#5534 10461 Story: Addressing UX Feedback Round 2
  web-client/src/ustc-ui/Icon/CaseIcons.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionDetails.tsx
  web-client/src/views/TrialSessionDetails/AllCases.tsx
  web-client/src/views/TrialSessionDetails/InactiveCases.tsx
  web-client/src/views/TrialSessionDetails/OpenCases.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5527 Dependency Updates 2024-11-11
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
Labels: dependencies, to staging, Review Please

#5538 10461 Story: Add flex-column back in
  web-client/src/presenter/computeds/Public/publicTrialSessionHelper.test.ts
  web-client/src/views/Public/TrialSessions/PublicTrialSessionDetails.tsx
Labels: to test, Review Please

#5469 No App Context Experiment
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/proxies/customCaseReport/createCsvCustomCaseReportFileProxy.ts
  shared/src/proxies/reports/getCustomCaseReportProxy.ts
  shared/src/test/mockFactory.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/reports/createCsvCustomCaseReportFileLambda.ts
  web-api/src/lambdas/reports/getCustomCaseReportLambda.ts
  web-api/src/notifications/mocks.jest.ts
  web-api/src/notifications/notificationClient/getNotificationClient.ts
  web-api/src/notifications/notificationClient/getNotificationGateway.ts
  web-api/src/notifications/notificationClient/notificationGateway.mocks.jest.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.test.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-api/src/persistence/elasticsearch/mocks.jest.ts
  web-api/src/persistence/elasticsearch/searchClient/getSearchClient.ts
  web-api/src/persistence/elasticsearch/searchClient/mocks.jest.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/actions/validateCustomCaseReportFiltersAction.test.ts
  web-client/src/presenter/actions/validateCustomCaseReportFiltersAction.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to staging, Review Please

#5543 10461 Story: UX updates and coordinating with 10460
  shared/src/business/entities/cases/Case.sortByDocketNumber.test.ts
  shared/src/business/entities/cases/Case.ts
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionDetailsInteractor.ts
  web-client/src/presenter/actions/Public/TrialSessions/getPublicTrialSessionDetailsAction.test.ts
  web-client/src/presenter/actions/Public/TrialSessions/setPublicTrialSessionDetailsAction.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionDetailsHelper.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionDetailsHelper.ts
  web-client/src/routerPublic.ts
  web-client/src/views/AppComponentPublic.tsx
  web-client/src/views/Public/TrialSessions/PublicMobileTrialSessionsDataRow.tsx
  web-client/src/views/Public/TrialSessions/PublicMobileTrialSessionsTable.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionDetails.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessions.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsRemoteProceedingsCard.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsTable.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsTable.tsx
Labels: to test, Review Please

#5549 10525: Fix Unit Test
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.test.ts
Labels: to test

#5553 Bugfix: fix broken validation in EditCorrespondenceDocument
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
Labels: to staging, Review Please

#5554 Bugfix: fix broken validation in EditCorrespondenceDocument
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
Labels: to test, Review Please

#5550 10534 design debt intermediate branch to test 1731599532
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself.cy.ts
  tmp.md
  web-client/src/presenter/computeds/filePetitionHelper.test.ts
  web-client/src/presenter/computeds/filePetitionHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
  web-client/src/views/DocketRecord/DocumentViewer.tsx
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
  web-client/src/views/JudgeActivityReport/SubmittedAndCav.tsx
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/StartCase/Address.tsx
  web-client/src/views/StartCase/AddressUpdated.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopySessionList.tsx
  web-client/src/views/TrialSessions/InPersonProceedingForm.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
Labels: to test

#5546 Parallelize smoke tests in circle deploys
  .circleci/config.yml
  scripts/run-cypress.sh
Labels: to staging, Review Please

#5542 10460 story
  cypress/local-only/support/pages/public/advanced-search.ts
  cypress/local-only/tests/integration/public/trialSessions/trial-sessions.cy.ts
  shared/src/proxies/trialSessions/getPublicTrialSessionsProxy.ts
  shared/src/proxies/users/getPublicUsersInSectionProxy.ts
  web-api/src/app-public.ts
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionsInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionsInteractor.ts
  web-api/src/business/useCases/user/getUsersInSectionInteractor.ts
  web-api/src/lambdas/trialSessions/getPublicTrialSessionsLambda.ts
  web-client/src/appPublic.tsx
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/TrialSession/setTimeStampAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTimeStampAction.ts
  web-client/src/presenter/actions/resetPublicTrialSessionDataAction.test.ts
  web-client/src/presenter/actions/resetPublicTrialSessionDataAction.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionHelper.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionsHelper.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Public/gotoPublicTrialSessionsSequence.ts
  web-client/src/presenter/sequences/displayProgressSpinnerSequence.ts
  web-client/src/presenter/sequences/resetPublicTrialSessionDataSequence.ts
  web-client/src/presenter/sequences/updateFormValueSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/presenter/test.cerebral.ts
  web-client/src/routerPublic.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/public.scss
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/ustc-ui/Select/Selects.tsx
  web-client/src/views/AppComponentPublic.tsx
  web-client/src/views/Header/HeaderPublic.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsDataRow.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsTable.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessions.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsRemoteProceedingsCard.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsTable.tsx
Labels: to staging

#5555 OpEx: Stale Cases Report
  scripts/reports/stale-cases.ts
Labels: to staging

#5558 10534:Fixed Swing session casing for test
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5560 10275 calendar generator
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/JoiValidationConstants.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/constraints.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/WarningNotification.tsx
Labels: to test

#5566 [Addendum to 10408] Rm judge edit perms from trial session info page to test
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
Labels: to test, Review Please

#5569 10556 Bug: Filter Off-The-Record Docket Entries for Non-Internal Users
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-client/integration-tests/caseJourney.test.ts
  web-client/integration-tests/petitionerFilesADocument.test.ts
Labels: to test, Review Please

#5570 10556 bug to IRS
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-client/integration-tests/caseJourney.test.ts
  web-client/integration-tests/petitionerFilesADocument.test.ts
Labels: to irs

#5568 10525 test feedback
  shared/src/proxies/public/generatePublicDocketRecordPdfProxy.ts
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.ts
  web-client/src/appPublic.tsx
  web-client/src/presenter/actions/Public/generatePublicDocketRecordPdfUrlAction.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
  web-client/src/views/Public/PublicDocketRecordHeader.tsx
Labels: to test

#5572 10547 design debt intermediate branch to test 1732118400
  web-client/src/styles/custom.scss
  web-client/src/views/TrialSessionDetails/TrialSessionInformation.tsx
  web-client/src/views/TrialSessionWorkingCopy/SessionAssignments.tsx
  web-client/src/views/TrialSessionWorkingCopy/SessionNotes.tsx
  web-client/src/views/TrialSessionWorkingCopy/TrialSessionWorkingCopy.tsx
Labels: to test, Review Please

#5577 10553: Process to update contact info fails if DAWSON is also updating other contact info at the same time TO TEST
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/setChangeOfAddressCaseAsDone.ts
Labels: to test

#5579 10525: Update dropdown in mobile view;
  cypress/local-only/tests/integration/caseDetail/docketRecord/docketRecordSort.cy.ts
  web-client/src/presenter/state-public.ts
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/DocketRecord/DocketRecordSort.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
  web-client/src/views/Public/PublicDocketRecordHeader.tsx
Labels: to test

#5567 Load legacy pdfjs for outdated browsers
  web-client/src/applicationContext.ts
Labels: to test, Review Please

#5580 Type Websocket Messages - TO TEST
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  web-api/src/business/useCases/docketEntry/editPaperFilingInteractor.ts
  web-api/src/business/useCases/user/generateChangeOfAddress.ts
  web-api/src/notifications/sendNotificationToUser.test.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/notifications/sendNotificationToUserTypes.ts
  web-client/src/providers/socketRouter.ts
Labels: to test

#5486 10408: Add Special Session Copy Notes to Trial Sessions Page
  shared/src/business/entities/trialSessions/SpecialTrialSessions.ts
  shared/src/proxies/trialSessions/getBulkSpecialTrialSessionCopyNotesProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/getBulkTrialSessionCopyNotesInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getBulkTrialSessionCopyNotesInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/trialSessions/getBulkTrialSessionCopyNotesLambda.ts
  web-api/src/persistence/dynamo/trialSessions/getBulkTrialSessionWorkingCopies.test.ts
  web-api/src/persistence/dynamo/trialSessions/getBulkTrialSessionWorkingCopies.ts
  web-api/src/persistence/dynamo/trialSessions/getTrialSessionWorkingCopy.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/getBulkSpecialTrialSessionCopyNotesAction.test.ts
  web-client/src/presenter/actions/TrialSession/getBulkSpecialTrialSessionCopyNotesAction.ts
  web-client/src/presenter/actions/TrialSession/setBulkSpecialTrialSessionCopyNotesAction.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/presenter/state/trialSessionsPageState.ts
  web-client/src/views/TrialSessions/TrialSessions.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to staging

#5561 [ticket-#-pending for 10408] Remove Judge Edit permissions for Trial Session Info Page
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
Labels: to staging

#5573 10556 Bug: Filter Off-The-Record Docket Entries for Non-Internal Users
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-client/integration-tests/caseJourney.test.ts
  web-client/integration-tests/petitionerFilesADocument.test.ts
Labels: to staging, Review Please

#5589 10293 to Test Fix: Reset Paginator Page State on Filter Update
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to test, Review Please

#5596 10489 story to test
  shared/src/business/utilities/replaceBracketed.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.test.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.ts
Labels: to test

#5595 10553: Use latest user info from persistence;
  web-api/src/business/useCases/user/updateAssociatedCaseWorker.test.ts
  web-api/src/business/useCases/user/updateAssociatedCaseWorker.ts
Labels: to test

#5586 Dependency Updates for 11/22/2024
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
Labels: to staging

#5574 OpEx: Practitioners' email address, as defined in each of their cases
  scripts/reports/practitioners-email-in-cases.ts
Labels: to staging

#5597 10489: test
  cypress/local-only/tests/integration/statusReportOrder/status-report-order-description-fields.cy.ts
  web-client/src/presenter/sequences/gotoAddCourtIssuedDocketEntrySequence.ts
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
  web-client/src/views/StatusReportOrder.tsx
Labels: to test

#5599 10553: Add retry when entity is locked;
  web-api/src/business/useCaseHelper/acquireLock.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.ts
Labels: Do Not Merge, to test

#5604 Revert "5577" changes
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
Labels: to test
