Repository ustaxcourt/ef-cms, pull requests merged in 2024-04, with the labels that each got.

#4817 10260 fix async/sync put requests
  web-api/terraform/api/api-async.tf
Labels: to test

#4816 10307 - move issue to next page and adjust spacing
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.test.ts
  shared/src/business/utilities/pdfGenerator/components/PretrialMemorandum.tsx
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.2.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.3.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.4.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.5.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.6.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.7.png
Labels: to test

#4814 Dependency Updates - First Week of April 2024
  .circleci/config.yml
  .github/workflows/api.yml
  .github/workflows/build-ts-api.yml
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  .github/workflows/typescript-error-check.yml
  .github/workflows/typescript-untouched-files-check.yml
  Dockerfile
  docs/ci-cd.md
  docs/dependency-updates.md
  docs/flaky-tests.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/Dockerfile
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: dependencies, to staging

#4812 dd10283 - change country dropdown to radio
  cypress/cypress-smoketests/integration/change-address.cy.ts
  web-client/pa11y/pa11y-petitioner.js
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/StartCase/Country.tsx
  web-client/src/views/StartCase/InternationalAddress.tsx
  web-client/src/views/StyleGuide/Forms.tsx
Labels: to staging

#4830 DevEx - fix cognito pool UUID issues
  shared/admin-tools/user/admin.ts
  shared/src/business/entities/JoiValidationConstants.ts
Labels: to staging

#4821 devex: switch 9000 to 9001 for local
  docker-compose.yml
  docker-run.sh
  docs/additional-resources/old-readme.md
  package.json
  run-api.sh
  run-integration-tests.sh
  run-local.sh
  scripts/run-cypress.sh
  setup-local-env.sh
  web-client/integration-tests/v1ApiJourney.test.ts
  web-client/integration-tests/v2ApiJourney.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/isPrintPreviewPreparedAction.test.ts
Labels: to staging

#4822 10260: Fix 504 when uploading large PDF files;
  cypress/cypress-integration/integration/assign-a-work-item-to-self.cy.ts
  cypress/cypress-smoketests/integration/complete-docket-qc.cy.ts
  cypress/support/commands.ts
  shared/src/proxies/courtIssuedOrder/appendAmendedPetitionFormProxy.ts
  shared/src/proxies/courtIssuedOrder/fileCourtIssuedOrderProxy.ts
  shared/src/proxies/documents/addCoversheetProxy.ts
  shared/src/proxies/documents/updateDocketEntryMetaProxy.ts
  shared/src/proxies/documents/validatePdfProxy.ts
  shared/src/proxies/editDocketEntry/completeDocketEntryQCProxy.ts
  shared/src/proxies/polling/startPollingForResultsProxy.test.ts
  shared/src/proxies/polling/startPollingForResultsProxy.ts
  shared/src/proxies/requests.test.ts
  shared/src/proxies/requests.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.test.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/lambdas/polling/startPollingForResultsLambda.ts
  web-api/src/middleware/apiGatewayHelper.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.test.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.test.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.ts
  web-api/terraform/api/api-async.tf
  web-client/integration-tests/caseServicesSupervisorJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueOutbox.tsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.tsx
Labels: infrastructure, to staging

#4829 10276 story intermediate branch to test 1712777781
  cypress/cypress-smoketests/integration/admissions-clerk-grants-e-access.cy.ts
  cypress/cypress-smoketests/integration/admissions-clerk-updates-practitioner-email.cy.ts
  docs/additional-resources/importing-practitioner-users.md
  docs/additional-resources/update-practitioner-user-endpoint.md
  docs/wiki/Glossary.md
  docs/wiki/Practitioner-Database.md
  scripts/reports/practitioner-stats.ts
  scripts/user/create-and-enable-smoketest-user-helpers.ts
  scripts/user/setup-test-users.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/IrsPractitioner.test.ts
  shared/src/business/entities/NewPractitioner.test.ts
  shared/src/business/entities/Practitioner.test.ts
  shared/src/business/entities/Practitioner.ts
  shared/src/business/entities/PrivatePractitioner.test.ts
  shared/src/business/useCases/getUserInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.ts
  shared/src/business/useCases/practitioners/validateAddPractitionerInteractor.test.ts
  shared/src/business/useCases/practitioners/validatePractitionerInteractor.test.ts
  shared/src/business/useCases/users/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  shared/src/business/useCases/users/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  shared/src/business/useCases/users/updateUserContactInformationInteractor.test.ts
  shared/src/business/useCases/users/updateUserPendingEmailInteractor.test.ts
  shared/src/business/utilities/createPractitionerUser.test.ts
  shared/src/test/mockUsers.ts
  web-api/bulkImportPractitionerUsers.helpers.js
  web-api/bulkImportPractitionerUsers.helpers.test.ts
  web-api/run-local-migration.ts
  web-api/setup-cognito-users.sh
  web-api/src/business/useCases/practitioner/createPractitionerUserInteractor.test.ts
  web-api/src/business/useCases/user/updateAssociatedCaseWorker.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-api/workflow-terraform/migration/main/lambdas/migration-segments.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0002-change-employer-to-practice-type.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0002-change-employer-to-practice-type.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/journey/admissionsClerkAddsNewPractitioner.ts
  web-client/integration-tests/journey/admissionsClerkMigratesPractitionerWithoutEmail.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/Public/getTodaysOrdersAction.test.ts
  web-client/src/presenter/actions/validateAddPractitionerAction.ts
  web-client/src/presenter/actions/validatePractitionerAction.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/getAllIrsPractitionersForSelectHelper.ts
  web-client/src/presenter/computeds/createPractitionerUserHelper.test.ts
  web-client/src/presenter/computeds/createPractitionerUserHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/state-public.ts
  web-client/src/views/Practitioners/PractitionerDetails.tsx
  web-client/src/views/Practitioners/PractitionerForm.tsx
Labels: to test

#4839 Fix Cypress Test
  cypress/cypress-smoketests/integration/complete-docket-qc.cy.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
Labels: to staging

#4844 10276 story to test
  scripts/dynamo/set-local-migration-complete-marker.ts
  scripts/dynamo/set-migration-complete-marker.sh
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.test.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.ts
  web-api/workflow-terraform/migration/main/lambdas/migration.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migration.ts
  web-api/workflow-terraform/reindex-cron/main/lambdas/reindex-status.ts
Labels: to test

#4819 10149 E-Filing: Modify Confirmation Banner When Multi-docketing
  docs/running-locally.md
  shared/src/business/entities/EntityConstants.ts
Labels: to staging

#4806 10270: do not run email verification smoketest when emails are disabled
  cypress/cypress-smoketests/integration/verify-email-receipt.cy.ts
Labels: to staging

#4846 Opex: non-attorney stats refresh
  scripts/reports/non-attorney-practitioners-constants.ts
  scripts/reports/non-attorney-practitioners.ts
  web-api/elasticsearch/efcms-user-mappings.ts
Labels: Mappings Change(s)

#4843 Dependency updates 2024-04-17
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4859 Return stringified version of the json response;
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/middleware/apiGatewayHelper.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.test.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.ts
Labels: to test

#4421 ustc #4372: allow full ISO date + end date for reconciliation report
  docs/api/v2.yaml
  shared/src/business/useCases/getReconciliationReportInteractor.test.ts
  shared/src/business/useCases/getReconciliationReportInteractor.ts
  shared/src/business/utilities/DateHandler.test.ts
  shared/src/business/utilities/DateHandler.ts
  web-api/src/lambdas/v2/getReconciliationReportLambda.ts
  web-client/integration-tests/v2ApiJourney.test.ts
Labels: to staging, to merge

#4866 Onboarding Documentation Update
  docs/running-locally.md
Labels: to staging, to merge

#4867 4485 v2 api changes 2
  docs/api/v2.yaml
  web-api/src/lambdas/v2/marshallers/marshallDocketEntry.test.ts
  web-api/src/lambdas/v2/marshallers/marshallDocketEntry.ts
Labels: to staging, to merge, Review Please

#4863 10358/10359/10360 - BUGFIXES
  cypress/cypress-smoketests/integration/order-gets-unserved.cy.ts
  cypress/cypress-smoketests/integration/order-signature-disappears.cy.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.test.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/middleware/apiGatewayHelper.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.test.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.test.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.ts
  web-client/src/views/DocketRecord/DraftDocumentViewerDocument.tsx
Labels: bugfix, to staging, to merge

#4869 Dependency updates 2024-04-26
  .circleci/config.yml
  Dockerfile
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: dependencies

#4770 10249 fix pre epoch cases intermediate branch to test 1710967520
  cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts
  shared/src/business/entities/customCaseReportSearch/CustomCaseReportSearch.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/customCaseReportState.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to test

#4809 10068 permissions intermediate branch to test 1711998176
  cypress/cypress-integration/integration/batch-download-documents.cy.ts
  shared/src/authorization/authorizationClientService.ts
Labels: to test
