Repository ustaxcourt/ef-cms, pull requests merged in 2024-10, with the labels that each got.

#5406 10466 to test
  shared/src/business/entities/EmailConfirmationForm.test.ts
  shared/src/business/entities/EmailConfirmationForm.ts
  shared/src/business/useCases/validatePetitionerInteractor.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.test.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.ts
  web-client/src/presenter/actions/validateChangeLoginAndServiceEmailAction.ts
  web-client/src/presenter/computeds/createPractitionerUserHelper.ts
  web-client/src/presenter/computeds/validateEmailFormHelper.test.ts
  web-client/src/presenter/computeds/validateEmailFormHelper.ts
  web-client/src/presenter/sequences/gotoChangeLoginAndServiceEmailSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/ChangeLoginAndServiceEmail.tsx
  web-client/src/views/Practitioners/PractitionerForm.tsx
  web-client/src/views/Practitioners/PractitionerLoginServiceEmailForm.tsx
Labels: to test, Review Please

#5405 10313 Bug: Change Email Verification Link Does Not Expire
  shared/src/business/entities/User.ts
  web-api/src/business/useCases/auth/changePasswordInteractor.ts
  web-api/src/business/useCases/practitioner/updatePractitionerUserInteractor.ts
  web-api/src/business/useCases/user/updateUserPendingEmailInteractor.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
Labels: to test

#5414 10409 story intermediate branch to test 1727803033
  .eslintrc.js
  10409_validation_delete_me.md
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5413 10275 to test
  docs/running-locally.md
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/JoiValidationConstants.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/entities/trialSessions/GeneratedSuggestedTermForm.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/proxies/trialSessions/generateSuggestedTrialSessionCalendarProxy.ts
  shared/src/test/mockCase.ts
  web-api/src/app.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-api/src/getUtilities.ts
  web-api/src/lambdas/trialSessions/generateSuggestedTrialSessionCalendarLambda.ts
  web-api/src/persistence/dynamo/trialSessions/getEligibleCasesForTrialSession.ts
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermModalAction.ts
  web-client/src/presenter/actions/downloadXlsxAction.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/TrialSessions/openCreateTermModalSequence.ts
  web-client/src/presenter/sequences/TrialSessions/submitCreateTermModalSequence.ts
  web-client/src/presenter/utilities/downloadCsv.test.ts
  web-client/src/presenter/utilities/downloadCsv.ts
  web-client/src/presenter/utilities/downloadXlsx.ts
  web-client/src/styles/modals.scss
  web-client/src/styles/overrides.scss
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/views/CreateTermModal.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test

#5417 10313 Bug: Email Verification Link Does Not Expire (1-line update to switch expiration from 1 hour to 24 hours)
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
Labels: to test

#5398 10261 Story: Practitioner Case List
  cypress/local-only/tests/accessibility/practitionerDetails/admissions-clerk.cy.ts
  cypress/local-only/tests/integration/advancedSearch/practitioner-information.cy.ts
  shared/src/business/entities/User.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.test.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  shared/src/business/useCases/getPractitionerCasesInteractor.test.ts
  shared/src/business/useCases/getPractitionerCasesInteractor.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/proxies/practitioners/getPractitionerCasesProxy.ts
  web-api/src/app.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/cases/getPractitionerCasesLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.test.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.ts
  web-client/src/presenter/actions/setPractitionerClosedCasesPageAction.ts
  web-client/src/presenter/actions/setPractitionerOpenCasesPageAction.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.test.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/setPractitionerClosedCasesPageSequence.ts
  web-client/src/presenter/sequences/setPractitionerOpenCasesPageSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/tables.scss
  web-client/src/views/Practitioners/PractitionerCaseIcons.tsx
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerDetails.tsx
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to test

#5422 10409 story intermediate branch to test 1727894337
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormCourtIssued.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
  web-client/src/views/FileDocument/CompleteDocumentTypeSection.tsx
  web-client/src/views/FileDocument/CompleteDocumentTypeSectionRemainder.tsx
  web-client/src/views/PaperFiling/PrimaryDocumentForm.tsx
  web-client/src/views/TrialSessions/SessionAssignmentsForm.tsx
Labels: to test

#5426 File validation bug: Make correct file type check case insensitive
  web-client/src/views/FileHandlingHelpers/fileValidation.test.ts
  web-client/src/views/FileHandlingHelpers/fileValidation.ts
Labels: to test

#5421 10261 Story: Practitioner Case List - Pagination Fix
  web-client/src/presenter/actions/setPractitionerClosedCasesPageAction.ts
  web-client/src/presenter/actions/setPractitionerOpenCasesPageAction.ts
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to test

#5424 File validation bug: Make correct file type check case insensitive
  web-client/src/views/FileHandlingHelpers/fileValidation.test.ts
  web-client/src/views/FileHandlingHelpers/fileValidation.ts
Labels: to staging

#5391 Bugfix: Do not attempt to sign user out if clientNeedsToRefresh is true
  web-client/src/presenter/sequences/signOutUserInitiatedSequence.ts
Labels: to staging

#5305 Make explicit unified logger
  web-api/src/app-public.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/createLogger.ts
  web-api/src/gateways/worker/workerLocal.ts
  web-api/src/genericHandler.ts
  web-api/src/lambdas/cases/sealInLowerEnvironmentLambda.ts
  web-api/src/lambdas/cognitoAuthorizer/cognito-authorizer.test.ts
  web-api/src/lambdas/cognitoAuthorizer/createAuthorizer.ts
  web-api/src/lambdas/cognitoAuthorizer/websocket-authorizer.test.ts
  web-api/src/lambdas/cognitoAuthorizer/worker-handler.ts
  web-api/src/lambdas/migration/migration-segments.ts
  web-api/src/lambdas/migration/migration.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
  web-api/src/logger.test.ts
  web-api/src/logger.ts
  web-api/src/middleware/userIdLimiter.ts
  web-api/src/utilities/logger/getLogger.ts
  web-api/storage/scripts/createUsers.ts
Labels: to staging, Review Please

#5428 10391 dynamo migrations kysely aurora rds tokens intermediate branch to test 1727989027
  docs/postgres/deployment.md
  web-api/src/database-types.ts
  web-api/src/persistence/postgres/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/postgres/cases/upsertCase.ts
  web-api/src/persistence/postgres/cases/upsertCases.ts
  web-api/src/persistence/postgres/messages/createMessage.ts
  web-api/src/persistence/postgres/messages/getCompletedSectionInboxMessages.ts
  web-api/src/persistence/postgres/messages/getCompletedUserInboxMessages.ts
  web-api/src/persistence/postgres/messages/getMessageById.ts
  web-api/src/persistence/postgres/messages/getMessageThreadByParentId.ts
  web-api/src/persistence/postgres/messages/getMessagesByDocketNumber.ts
  web-api/src/persistence/postgres/messages/getSectionInboxMessages.ts
  web-api/src/persistence/postgres/messages/getSectionOutboxMessages.ts
  web-api/src/persistence/postgres/messages/getUserInboxMessages.ts
  web-api/src/persistence/postgres/messages/getUserOutboxMessages.ts
  web-api/src/persistence/postgres/messages/markMessageThreadRepliedTo.ts
  web-api/src/persistence/postgres/messages/setMessageAsRead.ts
  web-api/src/persistence/postgres/messages/updateMessage.ts
  web-api/src/persistence/postgres/messages/upsertMessages.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0001-init.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0002-init-indexes.ts
  web-api/src/persistence/postgres/utils/seed/seed.ts
Labels: to test

#5427 Opex: Judge carousel
  scripts/circleci/judge/judge_users.csv
Labels: to staging

#5403 #10512: attach mail from domain to identity
  docs/architecture/email.md
  web-api/terraform/modules/everything-else-deprecated/ses.tf
Labels: to staging

#5416 Dependency updates 10-02-2024
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5338 Opex: additional logging for automated glue jobs
  .circleci/config.yml
  scripts/migration/set-migration-complete-marker.sh
Labels: to staging

#5432 10275 to test, again
  cypress/local-only/tests/integration/trialSession/run-suggested-calendar-generator.cy.ts
  scripts/run-once-scripts/temp-get-special-trial-sessions.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/DateHandler.formats.test.ts
  shared/src/business/utilities/DateHandler.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/test/mockCasesReadyForTrial.json
  shared/src/test/mockSpecialTrialSessions.json
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.getPreviousTwoTerms.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.getSpecialSessionsInTerm.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-api/src/persistence/elasticsearch/getReadyForTrialCases.test.ts
  web-api/src/persistence/elasticsearch/getReadyForTrialCases.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.ts
  web-client/src/presenter/sequences/TrialSessions/submitCreateTermModalSequence.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test

#5433 10409 story intermediate branch to test 1728319369
  web-client/src/styles/tables.scss
  web-client/src/styles/tabs.scss
  web-client/src/styles/utility-classes.scss
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5434 10409 story intermediate branch to test 1728330518
  web-client/src/styles/custom.scss
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5438 10487 story intermediate branch to test 1728427842
  shared/src/business/utilities/DateHandler.ts
  web-api/src/business/useCases/judgeActivityReport/getTrialSessionsForJudgeActivityReportInteractor.test.ts
  web-api/src/business/useCases/judgeActivityReport/getTrialSessionsForJudgeActivityReportInteractor.ts
Labels: to test

#5440 10409 UX feedback
  web-client/src/styles/utility-classes.scss
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test

#5437 10363: AWS Batch - TO TEST
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/dynamo/setup-aws-batch-zipper-minimum-count.sh
  scripts/setup-all-env-configuration.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/src/gateways/worker/workerRouter.ts
  web-api/src/persistence/batch/getBatchClient.ts
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/modules/batch/batch.tf
  web-api/terraform/modules/batch/docker-image/Dockerfile
  web-api/terraform/modules/batch/docker-image/check-env-variables.sh
  web-api/terraform/modules/batch/docker-image/deploy-to-ecr.sh
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/batch/docker-image/src/testScript.ts
  web-api/terraform/modules/batch/docker-image/suppress-output.sh
  web-api/terraform/modules/batch/docker-image/tsconfig.json
  web-api/terraform/modules/batch/variables.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/elastic-container-registry/batch-elastic-container-registry.tf
  web-api/terraform/modules/elastic-container-registry/variables.tf
  web-api/terraform/modules/lambda-role/lambda-role.tf
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.ts
  web-client/src/providers/socketRouter.ts
Labels: to test, Needs Account Specific

#5442 10275 story
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-api/src/persistence/elasticsearch/getSuggestedCalendarCases.ts
Labels: to test

#5444 10363: Save Docket Entry keys in S3
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/terraform/modules/batch/docker-image/Dockerfile
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
Labels: to test

#5445 10363 aws batch
  web-api/terraform/modules/batch/batch.tf
Labels: to test

#5423 10395: Improve textarea elements
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/CaseDetail/AddEditCalendarNoteModal.tsx
  web-client/src/views/CaseDetail/BlockFromTrialModal.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/PrioritizeCaseModal.tsx
  web-client/src/views/CaseDetail/RemoveFromTrialSessionModal.tsx
  web-client/src/views/CaseDetailEdit/CaseInfo.tsx
  web-client/src/views/CaseDetailEdit/RemovePetitionerModal.tsx
  web-client/src/views/CaseDetailEdit/UpdateCaseModalDialog.tsx
  web-client/src/views/CaseWorksheet/AddEditCaseWorksheetModal.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedNonstandardForm.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
  web-client/src/views/FilingPartiesForm.tsx
  web-client/src/views/Messages/CompleteMessageModalDialog.tsx
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/ForwardMessageModalDialog.tsx
  web-client/src/views/Messages/ReplyToMessageModalDialog.tsx
  web-client/src/views/PaperFiling/PrimaryDocumentForm.tsx
  web-client/src/views/PendingMotion/AddEditDocketEntryWorksheetModal.tsx
  web-client/src/views/StampMotion/ApplyStamp.tsx
  web-client/src/views/StartCaseInternal/CaseInformation.tsx
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StatusReportOrder.tsx
  web-client/src/views/TrialSessions/AddTrialSession.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
Labels: to test

#5450 10395 Design Debt: Textarea improvement (update BindedTextarea)
  web-client/src/ustc-ui/BindedTextarea/BindedTextarea.tsx
  web-client/src/views/CaseDetail/AddEditCalendarNoteModal.tsx
  web-client/src/views/CaseWorksheet/AddEditCaseWorksheetModal.tsx
  web-client/src/views/PendingMotion/AddEditDocketEntryWorksheetModal.tsx
Labels: to test

#5430 10261 Story: Practitioner Case List (Updates based on UX feedback)
  shared/src/business/useCases/getPractitionerCasesInteractor.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/tabs.scss
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to test

#5448 10519 Bug: 30 Day NOTT Location Display Issue
  web-api/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.test.ts
  web-api/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.ts
Labels: to test

#5452 10363 test
  web-api/terraform/modules/batch/batch.tf
  web-client/src/presenter/actions/BatchDownload/resetBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/BatchDownload/setBatchDownloadProgressAction.ts
  web-client/src/presenter/sequences/batchDownloadDocketEntriesSequence.ts
Labels: to test

#5456 10363 test
  web-api/terraform/modules/batch/batch.tf
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
Labels: to test

#5457 10275 to test
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/assignSessionsToWeeks.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.getCitiesFromPreviousTwoTerms.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
Labels: to test

#5458 10483: test
  web-client/src/views/DocketRecord/DocketRecord.tsx
Labels: to test

#5464 10363: Add more logs & refactor;
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
Labels: to test

#5459 10466 to test
  shared/src/business/entities/EmailConfirmationForm.test.ts
  shared/src/business/entities/EmailConfirmationForm.ts
  shared/src/business/entities/contacts/Contact.ts
  web-client/src/presenter/actions/validateEmailConfirmationFormAction.test.ts
  web-client/src/presenter/actions/validateEmailConfirmationFormAction.ts
  web-client/src/presenter/computeds/validateEmailFormHelper.test.ts
  web-client/src/presenter/computeds/validateEmailFormHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/validateEmailConfirmationFormSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/ChangeLoginAndServiceEmail.tsx
  web-client/src/views/Practitioners/PractitionerLoginServiceEmailForm.tsx
Labels: to test, Review Please

#5463 10261 Story: Practitioner Case List -- UX Updates (Show multiple pages in pagination, and fix sort)
  shared/src/business/entities/cases/Case.sortByDocketNumber.test.ts
  shared/src/business/entities/cases/Case.ts
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to test, Review Please

#5453 Devex custom case no appcontext
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/proxies/customCaseReport/createCsvCustomCaseReportFileProxy.ts
  shared/src/proxies/reports/getCustomCaseReportProxy.ts
  shared/src/test/mockFactory.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/reports/createCsvCustomCaseReportFileLambda.ts
  web-api/src/lambdas/reports/getCustomCaseReportLambda.ts
  web-api/src/notifications/mocks.jest.ts
  web-api/src/notifications/notificationClient/getNotificationClient.ts
  web-api/src/notifications/notificationClient/getNotificationGateway.ts
  web-api/src/notifications/notificationClient/notificationGateway.mocks.jest.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.test.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-api/src/persistence/elasticsearch/mocks.jest.ts
  web-api/src/persistence/elasticsearch/searchClient/getSearchClient.ts
  web-api/src/persistence/elasticsearch/searchClient/mocks.jest.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/actions/validateCustomCaseReportFiltersAction.test.ts
  web-client/src/presenter/actions/validateCustomCaseReportFiltersAction.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to test, Review Please

#5468 10483: Display Empty Message to Public Users;
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/state-public.ts
  web-client/src/views/Public/PublicDocketRecord.tsx
  web-client/src/views/Public/PublicFilingsAndProceedings.tsx
Labels: to test

#5470 10261 Story: Practitioner Case List (Slight update to spacing and letting icons be accessible via VoiceOver)
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerDetails.tsx
Labels: to test, Review Please

#5465 10518-bug: Override problematic default Quill styles
  web-client/src/styles/_index.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/quill.scss
Labels: to test

#5407 10395: Improve textarea elements
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/BindedTextarea/BindedTextarea.tsx
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/CaseDetail/AddEditCalendarNoteModal.tsx
  web-client/src/views/CaseDetail/BlockFromTrialModal.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/PrioritizeCaseModal.tsx
  web-client/src/views/CaseDetail/RemoveFromTrialSessionModal.tsx
  web-client/src/views/CaseDetailEdit/CaseInfo.tsx
  web-client/src/views/CaseDetailEdit/RemovePetitionerModal.tsx
  web-client/src/views/CaseDetailEdit/UpdateCaseModalDialog.tsx
  web-client/src/views/CaseWorksheet/AddEditCaseWorksheetModal.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedNonstandardForm.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
  web-client/src/views/FilingPartiesForm.tsx
  web-client/src/views/Messages/CompleteMessageModalDialog.tsx
  web-client/src/views/Messages/CreateMessageModalDialog.tsx
  web-client/src/views/Messages/ForwardMessageModalDialog.tsx
  web-client/src/views/Messages/ReplyToMessageModalDialog.tsx
  web-client/src/views/PaperFiling/PrimaryDocumentForm.tsx
  web-client/src/views/PendingMotion/AddEditDocketEntryWorksheetModal.tsx
  web-client/src/views/StampMotion/ApplyStamp.tsx
  web-client/src/views/StartCaseInternal/CaseInformation.tsx
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StatusReportOrder.tsx
  web-client/src/views/TrialSessions/AddTrialSession.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
Labels: to staging, Review Please

#5439 10487 story
  shared/src/business/utilities/DateHandler.ts
  web-api/src/business/useCases/judgeActivityReport/getTrialSessionsForJudgeActivityReportInteractor.test.ts
  web-api/src/business/useCases/judgeActivityReport/getTrialSessionsForJudgeActivityReportInteractor.ts
Labels: to staging, Review Please

#5462 10519 Bug: 30 Day NOTT Location Display Issue
  web-api/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.test.ts
  web-api/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.ts
Labels: to staging

#5466 10074 Bug: Update Add Practitioner and IRS radio button validation
  web-client/src/presenter/actions/validateAddPractitionerAction.ts
  web-client/src/presenter/sequences/submitAddPractitionerSequence.ts
  web-client/src/views/IRSNotice.tsx
Labels: to test, Review Please

#5471 Dependency Updates
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: dependencies, to staging

#5461 10483 story
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/state-public.ts
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
  web-client/src/views/Public/PublicFilingsAndProceedings.tsx
Labels: to staging

#5476 Add missing dep for AWS Batch;
  package-lock.json
  package.json
Labels: to test

#5467 10313 Bug: Change Email Verification Link Does Not Expire
  cypress/deployed-and-local/integration/myAccount/petitioner-updates-email.cy.ts
  cypress/helpers/authentication/login-as-helpers.ts
  shared/src/business/entities/User.ts
  web-api/src/business/useCaseHelper/email/sendEmailVerificationLink.ts
  web-api/src/business/useCases/auth/changePasswordInteractor.ts
  web-api/src/business/useCases/practitioner/updatePractitionerUserInteractor.ts
  web-api/src/business/useCases/user/updateUserPendingEmailInteractor.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
  web-client/src/presenter/actions/updateUserPendingEmailAction.ts
  web-client/src/presenter/actions/verifyUserPendingEmailAction.test.tsx
  web-client/src/presenter/actions/verifyUserPendingEmailAction.tsx
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/resendVerifyPendingUserEmailSequence.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Icon/WarningIcon.tsx
  web-client/src/views/AppComponent.tsx
  web-client/src/views/ChangeLoginAndServiceEmail.tsx
  web-client/src/views/MyAccount/VerifyNewEmailModal.tsx
  web-client/src/views/VerifyEmailWarningNotification.tsx
Labels: to staging, Review Please

#5475 10261 Story: Update to sealed icon hover text
  shared/src/business/utilities/getSealedDocketEntryTooltip.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/views/Practitioners/PractitionerCaseIcons.tsx
Labels: to test, Review Please

#5479 10313 Bug: Actually use TOKEN_EXPIRATION_TIME_HOURS 🤦
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
Labels: to test

#5477 10518 Bug: Override problematic default Quill styles
  web-client/src/styles/_index.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/quill.scss
Labels: to staging, Review Please

#5472 10480 Story: M112 and M116 Motion Issues
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/DocketEntryFactory.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/entities/externalDocument/SecondaryDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/SecondaryDocumentInformationFactory.ts
  shared/src/tools/Event Codes - External Filings - Internal Document List.csv
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
  web-client/src/presenter/actions/FileDocument/refreshExternalDocumentTitleFromEventCodeAction.ts
  web-client/src/presenter/actions/FileDocument/setSupportingDocumentScenarioAction.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.ts
  web-client/src/presenter/computeds/editDocketEntryMetaHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.ts
Labels: to test, Review Please

#5484 10466: revert
  shared/src/business/entities/UpdateUserEmail.test.ts
  shared/src/business/entities/UpdateUserEmail.ts
  shared/src/business/useCases/validatePetitionerInteractor.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.test.ts
  shared/src/business/useCases/validateUpdateUserEmailInteractor.ts
  web-client/src/presenter/actions/validateChangeLoginAndServiceEmailAction.ts
  web-client/src/presenter/actions/validateEmailConfirmationFormAction.test.ts
  web-client/src/presenter/actions/validateEmailConfirmationFormAction.ts
  web-client/src/presenter/computeds/createPractitionerUserHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoChangeLoginAndServiceEmailSequence.ts
  web-client/src/presenter/sequences/validateEmailConfirmationFormSequence.ts
  web-client/src/views/ChangeLoginAndServiceEmail.tsx
  web-client/src/views/Practitioners/PractitionerForm.tsx
  web-client/src/views/Practitioners/PractitionerLoginServiceEmailForm.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCaseInternal/PaperPetitionEmail.tsx
Labels: to test

#5397 10261 Story: Practitioner Case List
  cypress/local-only/tests/accessibility/practitionerDetails/admissions-clerk.cy.ts
  cypress/local-only/tests/integration/advancedSearch/practitioner-information.cy.ts
  shared/src/business/entities/User.ts
  shared/src/business/entities/cases/Case.sortByDocketNumber.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.test.ts
  shared/src/business/useCases/generatePractitionerCaseListPdfInteractor.ts
  shared/src/business/useCases/getPractitionerCasesInteractor.test.ts
  shared/src/business/useCases/getPractitionerCasesInteractor.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/business/utilities/getSealedDocketEntryTooltip.ts
  shared/src/proxies/practitioners/getPractitionerCasesProxy.ts
  web-api/src/app.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/cases/getPractitionerCasesLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.test.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.ts
  web-client/src/presenter/actions/setPractitionerClosedCasesPageAction.ts
  web-client/src/presenter/actions/setPractitionerOpenCasesPageAction.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.test.ts
  web-client/src/presenter/computeds/practitionerInformationHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/setPractitionerClosedCasesPageSequence.ts
  web-client/src/presenter/sequences/setPractitionerOpenCasesPageSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/tables.scss
  web-client/src/styles/tabs.scss
  web-client/src/views/Practitioners/PractitionerCaseIcons.tsx
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerDetails.tsx
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to staging

#5485 Dep updates 2024 10 24
  .circleci/config.yml
  Dockerfile
  docs/additional-resources/blue-green-migration.md
  docs/dependency-updates.md
  docs/testing.md
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/src/utilities/cookieFormatting.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5489 10460: Trial Sessions Page: Public View
  shared/src/proxies/trialSessions/getPublicTrialSessionsProxy.ts
  shared/src/proxies/users/getPublicUsersInSectionProxy.ts
  web-api/src/app-public.ts
  web-api/src/business/useCases/trialSessions/getPublicTrialSessionsInteractor.ts
  web-api/src/business/useCases/user/getUsersInSectionInteractor.ts
  web-api/src/lambdas/trialSessions/getPublicTrialSessionsLambda.ts
  web-client/src/appPublic.tsx
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/TrialSession/setTimeStampAction.ts
  web-client/src/presenter/actions/resetPublicTrialSessionDataAction.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionHelper.test.ts
  web-client/src/presenter/computeds/Public/publicTrialSessionsHelper.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Public/gotoPublicTrialSessionsSequence.ts
  web-client/src/presenter/sequences/displayProgressSpinnerSequence.ts
  web-client/src/presenter/sequences/resetPublicTrialSessionDataSequence.ts
  web-client/src/presenter/sequences/updateFormValueSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/routerPublic.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponentPublic.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsDataRow.tsx
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsTable.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessions.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsRemoteProceedingsCard.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsTable.tsx
Labels: to test

#5490 10460: Disable links to session details until 10461 is complete;
  web-client/src/views/Public/TrialsSessions/PublicMobileTrialSessionsDataRow.tsx
  web-client/src/views/Public/TrialsSessions/PublicTrialSessionsTable.tsx
Labels: to test

#5487 10412 Design Debt: Message Table Updates
  cypress/deployed-and-local/integration/documentQC/complete-docket-qc.cy.ts
  cypress/local-only/tests/integration/messages/messages.cy.ts
  web-client/src/styles/tables.scss
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/Messages/MessageColumns.test.ts
  web-client/src/views/Messages/MessageColumns.ts
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to test

#5495 10412 Design Debt: Improving Messages Table -- UX Updates
  web-client/src/views/Messages/MessageTable.tsx
Labels: to test

#5497 10535/10432: Test
  web-client/src/presenter/actions/TrialSession/trialSessionQueryParamsAction.test.ts
  web-client/src/presenter/actions/TrialSession/trialSessionQueryParamsAction.ts
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/presenter/state.ts
Labels: to test

#5500 10535 story intermediate branch to test 1730389024
  web-client/src/presenter/computeds/trialSessionsHelper.ts
Labels: to test

#5501 10363: Handle PR Feedback
  cypress-smoketests.config.ts
  cypress/deployed-and-local/integration/aws-batch-docket-entries-download/aws-batch-docket-entries-download.cy.ts
  cypress/helpers/cypressTasks/dynamo/dynamo-helpers.ts
  cypress/local-only/support/database.ts
  docs/dependency-updates.md
  package-lock.json
  scripts/dynamo/setup-aws-batch-zipper-minimum-count.sh
  scripts/setup-all-env-configuration.sh
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/src/gateways/worker/workerRouter.ts
  web-api/terraform/modules/batch/docker-image/Dockerfile
  web-api/terraform/modules/batch/docker-image/check-env-variables.sh
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
  web-api/terraform/modules/batch/docker-image/suppress-output.sh
  web-api/terraform/modules/batch/variables.tf
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to test

#5499 10466 to test
  shared/src/business/entities/contacts/Contact.ts
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCaseInternal/EConsent.tsx
Labels: to test
