Repository ustaxcourt/ef-cms, pull requests merged in 2024-12, with the labels that each got.

#5611 10549 design debt intermediate branch to test 1733153071
  web-client/src/styles/typography.scss
Labels: to test, Review Please

#5613 10565 bug intermediate branch to test 1733166294
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/unauthedUserCaseSearchPartialMatchContactPrimaryName.test.ts
  web-client/src/presenter/actions/AdvancedSearch/setAdvancedSearchResultsAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: to test, Review Please

#5612 10553 bug test
  web-api/elasticsearch/efcms-case-mappings.ts
  web-api/src/business/useCases/auth/changePasswordInteractor.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/elasticsearch/getCasesByEmailTotal.ts
Labels: to test

#5593 10293 To Test - Repaginate Case Inventory Report
  docs/architecture/email.md
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/proxies/reports/getCaseInventoryReportProxy.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/caseInventoryReport/getCaseInventoryReportInteractor.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.ts
  web-client/integration-tests/docketClerkCaseInventoryReport.test.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCaseInventoryReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCaseInventoryReportAction.ts
  web-client/src/presenter/computeds/caseInventoryReportHelper.test.ts
  web-client/src/presenter/computeds/caseInventoryReportHelper.ts
  web-client/src/presenter/sequences/getCaseInventoryReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to test

#5616 10549 design debt intermediate branch to test 1733237164
  web-client/src/styles/typography.scss
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
Labels: to test, Review Please

#5617 10492 dxox intermediate branch to test 1733243644
  run-local.sh
  scripts/run-once-scripts/postgres-migration/batch-delete-dynamo-items.ts
  scripts/run-once-scripts/postgres-migration/delete-case-notes
  scripts/run-once-scripts/postgres-migration/delete-messages.ts
Labels: to test

#5619 10565 bugfix (hotfix)
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/unauthedUserCaseSearchPartialMatchContactPrimaryName.test.ts
  web-client/src/presenter/actions/AdvancedSearch/setAdvancedSearchResultsAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: bugfix

#5614 10565 bug
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/unauthedUserCaseSearchPartialMatchContactPrimaryName.test.ts
  web-client/src/presenter/actions/AdvancedSearch/setAdvancedSearchResultsAction.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicCaseAdvancedSearchAction.ts
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: to staging, Review Please

#5625 10285 design debt intermediate branch to test 1733326984
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: to test, Review Please

#5598 Dependency-Updates-11-26-2024
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
Labels: to staging

#5575 10554: Fix disappearing messages bug
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/clerk-of-court-stamp-order.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/judge-stamp-order.cy.ts
  web-api/src/business/useCases/messages/replyToMessageInteractor.test.ts
  web-api/src/business/useCases/messages/replyToMessageInteractor.ts
  web-api/src/persistence/postgres/messages/createMessageAsReply.ts
  web-api/src/persistence/postgres/messages/getMessagesByDocketNumber.ts
  web-api/src/persistence/postgres/messages/mocks.jest.ts
  web-client/integration-tests/stampDispositionClerkOfTheCourtJourney.test.ts
  web-client/integration-tests/stampDispositionJudgeJourney.test.ts
  web-client/src/presenter/sequences/gotoApplyStampSequence.ts
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/Messages/MessageDocument.tsx
Labels: to staging, Review Please

#5605 OpEx: Congressional Budget Justification reports for 2024
  scripts/helpers/generate-csv.test.ts
  scripts/helpers/generate-csv.ts
  scripts/reports/cases-closed-in-year.ts
  scripts/reports/closed-dates.ts
  scripts/reports/count-event-codes-by-year.ts
  scripts/reports/event-codes-by-year.ts
  scripts/reports/stale-cases.ts
  web-api/elasticsearch/efcms-case-mappings.ts
Labels: to staging, Mappings Change(s), Review Please

#5587 10557: Add action into the PublicDocketEntry entity.
  shared/src/business/entities/cases/PublicDocketEntry.test.ts
  shared/src/business/entities/cases/PublicDocketEntry.ts
Labels: to staging

#5571 Type Notifications to Users
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  web-api/src/business/useCases/docketEntry/editPaperFilingInteractor.ts
  web-api/src/business/useCases/user/generateChangeOfAddress.ts
  web-api/src/notifications/sendNotificationToUser.test.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/notifications/sendNotificationToUserTypes.ts
  web-client/src/providers/socketRouter.ts
Labels: to staging, Review Please

#5623 10553 bug test
  shared/src/proxies/users/verifyUserPendingEmailProxy.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.locking.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
  web-client/src/presenter/actions/setAlertInfoAction.ts
  web-client/src/presenter/actions/setInitialVerifyAlertMessageAction.ts
  web-client/src/presenter/actions/verifyUserPendingEmailAction.tsx
  web-client/src/presenter/sequences/gotoVerifyEmailSequence.ts
  web-client/src/views/Login/Login.tsx
Labels: Do Not Merge, to test

#5585 10525: Full Spectrum Docket Sorting
  cypress/helpers/caseDetail/docketRecord/paperFiling/create-and-save-for-later-paper-filing.ts
  cypress/helpers/caseDetail/docketRecord/paperFiling/create-and-serve-paper-filing.ts
  cypress/helpers/caseDetail/docketRecord/paperFiling/fill-paper-filing-form.ts
  cypress/helpers/fileAPetition/create-and-serve-paper-petition.ts
  cypress/local-only/tests/integration/caseDetail/consolidated-case.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/clerk-of-court-stamp-order.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/judge-stamp-order.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/docket-record-sort.cy.ts
  cypress/local-only/tests/integration/judgeActivityReport/judge-activity-report.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/getFormattedCaseDetail.formatDocketEntry.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/proxies/generateDocketRecordPdfProxy.ts
  shared/src/proxies/public/generatePublicDocketRecordPdfProxy.ts
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.test.ts
  web-api/src/business/useCases/generateDocketRecordPdfInteractor.ts
  web-client/src/appPublic.tsx
  web-client/src/presenter/actions/Public/generatePublicDocketRecordPdfUrlAction.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.test.ts
  web-client/src/presenter/actions/generateDocketRecordPdfUrlAction.ts
  web-client/src/presenter/actions/setDefaultDocketEntriesTableSortAction.test.ts
  web-client/src/presenter/actions/setDefaultDocketEntriesTableSortAction.ts
  web-client/src/presenter/actions/setDefaultMessagePageTableSortAction.test.ts
  web-client/src/presenter/actions/setDefaultMessagePageTableSortAction.ts
  web-client/src/presenter/actions/setDefaultTableSortAction.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.test.ts
  web-client/src/presenter/actions/setTableSortConfigurationAction.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/gotoMessagesSequence.ts
  web-client/src/presenter/sequences/sortTableSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/Table/SortableColumn.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/DocketRecord/DocketRecordSort.tsx
  web-client/src/views/Messages/MessageColumns.test.ts
  web-client/src/views/Messages/MessageColumns.ts
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
  web-client/src/views/Public/PublicDocketRecordHeader.tsx
Labels: to staging

#5631 10553: Use title to check if request timed out;
  web-api/src/business/useCases/user/queueEmailUpdateAssociatedCasesWorker.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
  web-api/src/gateways/worker/workerRouter.ts
  web-api/src/getUseCases.ts
  web-client/src/presenter/actions/verifyUserPendingEmailAction.tsx
  web-client/src/presenter/errors/GatewayTimeoutError.ts
Labels: Do Not Merge, to test

#5606 Devex: Wrapper for node:utils parseArgs
  scripts/jest-scripts.config.ts
  scripts/reports/reportUtils.md
  scripts/reports/reportUtils.test.ts
  scripts/reports/reportUtils.ts
  scripts/template.ts
Labels: to staging, Review Please

#5639 Remove chromium from Dockerfile (to test)
  .circleci/config.yml
  Dockerfile
Labels: to test, Manual Deploy Step(s) Required

#5640 Remove chromium from Dockerfile
  .circleci/config.yml
  Dockerfile
Labels: to staging, Manual Deploy Step(s) Required

#5635 10504 dxox update: fix process streams
  web-api/src/business/useCases/processStreamRecords/processCaseCorrespondenceEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processCaseCorrespondenceEntries.ts
  web-api/src/business/useCases/processStreamRecords/processCaseWorksheetEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processCaseWorksheetEntries.ts
Labels: to test, Review Please

#5641 BugFix: Fix hanging Node.js scripts by adding explicit exit signals
  web-api/src/persistence/postgres/utils/migrate/migrate.ts
  web-api/src/persistence/postgres/utils/seed/seed.ts
Labels: bugfix, Review Please

#5630 10293 to test: use unique React key in PendingReportList.tsx
  shared/src/business/utilities/formatPendingItem.test.ts
  shared/src/business/utilities/formatPendingItem.ts
  web-client/integration-tests/petitionsClerkVerifiesOffboardedJudgeJourney.test.ts
  web-client/src/presenter/actions/PendingItems/setPendingItemsAction.test.ts
  web-client/src/presenter/actions/PendingItems/setPendingItemsAction.ts
  web-client/src/presenter/computeds/formattedPendingItems.test.ts
  web-client/src/presenter/computeds/formattedPendingItems.ts
  web-client/src/presenter/computeds/pendingReportHelper.test.ts
  web-client/src/presenter/computeds/pendingReportHelper.ts
  web-client/src/presenter/computeds/pendingReportListHelper.test.ts
  web-client/src/presenter/computeds/pendingReportListHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/state/pendingReportState.ts
  web-client/src/views/PendingReport/PendingReport.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
Labels: to test

#5643 10491 Work Items: Fix processWorkItemEntries
  shared/src/business/useCases/saveCaseDetailInternalEditInteractor.test.ts
  shared/src/business/useCases/saveCaseDetailInternalEditInteractor.ts
  shared/src/business/useCases/updateContactInteractor.test.ts
  shared/src/business/useCases/updateContactInteractor.ts
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
  web-api/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.test.ts
  web-api/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.ts
  web-api/src/business/useCaseHelper/service/createChangeItems.test.ts
  web-api/src/business/useCaseHelper/service/createChangeItems.ts
  web-api/src/business/useCases/createCaseFromPaperInteractor.ts
  web-api/src/business/useCases/createCaseInteractor.test.ts
  web-api/src/business/useCases/createCaseInteractor.ts
  web-api/src/business/useCases/docketEntry/addPaperFilingInteractor.test.ts
  web-api/src/business/useCases/docketEntry/addPaperFilingInteractor.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.ts
  web-api/src/business/useCases/docketEntry/editPaperFilingInteractor.test.ts
  web-api/src/business/useCases/docketEntry/editPaperFilingInteractor.ts
  web-api/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.test.ts
  web-api/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.ts
  web-api/src/business/useCases/docketEntry/updateCourtIssuedDocketEntryInteractor.test.ts
  web-api/src/business/useCases/docketEntry/updateCourtIssuedDocketEntryInteractor.ts
  web-api/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  web-api/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processWorkItemEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processWorkItemEntries.ts
  web-api/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  web-api/src/business/useCases/user/updatePetitionerInformationInteractor.createWorkItemForChange.test.ts
  web-api/src/business/useCases/workItems/assignWorkItemsInteractor.test.ts
  web-api/src/business/useCases/workItems/assignWorkItemsInteractor.ts
  web-api/src/business/useCases/workItems/completeWorkItemInteractor.ts
  web-api/src/business/useCases/workItems/setWorkItemAsReadInteractor.test.ts
  web-api/src/business/useCases/workItems/setWorkItemAsReadInteractor.ts
  web-api/src/persistence/postgres/workitems/mocks.jest.ts
  web-api/src/persistence/postgres/workitems/saveWorkItem.ts
  web-api/src/persistence/postgres/workitems/upsertWorkItems.ts
  web-client/integration-tests/sentWorkItemsExpireAfterNDays.test.ts
  web-client/integration-tests/servedWorkItemsExpireAfter7Days.test.ts
Labels: to test

#5649 10489 feedback to test
  cypress/local-only/tests/integration/statusReportOrder/status-report-order-description-fields.cy.ts
  web-api/src/persistence/postgres/utils/migrate/migrate.ts
  web-api/src/persistence/postgres/utils/seed/seed.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.test.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.ts
Labels: to test

#5518 10492 dxox
  scripts/run-once-scripts/postgres-migration/batch-delete-dynamo-items.ts
  scripts/run-once-scripts/postgres-migration/delete-case-notes.ts
  scripts/run-once-scripts/postgres-migration/delete-messages.ts
  types/TEntity.d.ts
  web-api/src/business/useCases/caseNote/deleteUserCaseNoteInteractor.test.ts
  web-api/src/business/useCases/caseNote/deleteUserCaseNoteInteractor.ts
  web-api/src/business/useCases/caseNote/getUserCaseNoteForCasesInteractor.test.ts
  web-api/src/business/useCases/caseNote/getUserCaseNoteForCasesInteractor.ts
  web-api/src/business/useCases/caseNote/getUserCaseNoteInteractor.test.ts
  web-api/src/business/useCases/caseNote/getUserCaseNoteInteractor.ts
  web-api/src/business/useCases/caseNote/updateUserCaseNoteInteractor.test.ts
  web-api/src/business/useCases/caseNote/updateUserCaseNoteInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.test.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processStreamUtilities.ts
  web-api/src/business/useCases/processStreamRecords/processUserCaseNoteEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processUserCaseNoteEntries.ts
  web-api/src/database-types.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/userCaseNotes/deleteUserCaseNote.test.ts
  web-api/src/persistence/dynamo/userCaseNotes/deleteUserCaseNote.ts
  web-api/src/persistence/dynamo/userCaseNotes/getUserCaseNote.test.ts
  web-api/src/persistence/dynamo/userCaseNotes/getUserCaseNote.ts
  web-api/src/persistence/dynamo/userCaseNotes/getUserCaseNoteForCases.test.ts
  web-api/src/persistence/dynamo/userCaseNotes/getUserCaseNoteForCases.ts
  web-api/src/persistence/dynamo/userCaseNotes/updateUserCaseNote.test.ts
  web-api/src/persistence/dynamo/userCaseNotes/updateUserCaseNote.ts
  web-api/src/persistence/postgres/userCaseNotes/deleteUserCaseNote.ts
  web-api/src/persistence/postgres/userCaseNotes/getUserCaseNote.ts
  web-api/src/persistence/postgres/userCaseNotes/getUserCaseNoteForCases.ts
  web-api/src/persistence/postgres/userCaseNotes/mocks.jest.ts
  web-api/src/persistence/postgres/userCaseNotes/upsertUserCaseNote.ts
  web-api/src/persistence/postgres/userCaseNotes/upsertUserCaseNotes.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0003-add-user-case-notes.ts
  web-api/storage/fixtures/seed/efcms-local.json
Labels: to staging

#5648 10553: Process to update contact info fails if DAWSON is also updating other contact info at the same time
  shared/src/business/entities/factories/UserFactory.test.ts
  shared/src/business/entities/factories/UserFactory.ts
  shared/src/proxies/users/verifyUserPendingEmailProxy.ts
  web-api/elasticsearch/efcms-case-mappings.ts
  web-api/src/business/useCases/auth/changePasswordInteractor.test.ts
  web-api/src/business/useCases/auth/changePasswordInteractor.ts
  web-api/src/business/useCases/user/queueEmailUpdateAssociatedCasesWorker.test.ts
  web-api/src/business/useCases/user/queueEmailUpdateAssociatedCasesWorker.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.locking.test.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.test.ts
  web-api/src/business/useCases/user/verifyUserPendingEmailInteractor.ts
  web-api/src/gateways/worker/workerRouter.test.ts
  web-api/src/gateways/worker/workerRouter.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/persistence/dynamo/users/getUserByIdOnceAllUpdatesComplete.test.ts
  web-api/src/persistence/dynamo/users/getUserByIdOnceAllUpdatesComplete.ts
  web-api/src/persistence/elasticsearch/caseAdvancedSearch.test.ts
  web-api/src/persistence/elasticsearch/getCasesByEmailTotal.test.ts
  web-api/src/persistence/elasticsearch/getCasesByEmailTotal.ts
  web-client/src/presenter/actions/setAlertInfoAction.test.ts
  web-client/src/presenter/actions/setAlertInfoAction.ts
  web-client/src/presenter/actions/setInitialVerifyAlertMessageAction.test.ts
  web-client/src/presenter/actions/setInitialVerifyAlertMessageAction.ts
  web-client/src/presenter/actions/verifyUserPendingEmailAction.test.tsx
  web-client/src/presenter/actions/verifyUserPendingEmailAction.tsx
  web-client/src/presenter/errors/GatewayTimeoutError.ts
  web-client/src/presenter/sequences/gotoVerifyEmailSequence.ts
  web-client/src/views/Login/Login.tsx
Labels: to staging, Mappings Change(s), Review Please

#5653 Fix format of response object in our logs
  web-api/src/logger.test.ts
  web-api/src/logger.ts
Labels: to test, Review Please

#5650 10554 One-time script for cleaning up attachments on corrupted messages
  scripts/env/environments/00-common
  scripts/run-once-scripts/cleanup-corrupt-messages.ts
Labels: to staging, Manual Deploy Step(s) Required

#5634 10434: Trial Sessions Planning Report View - TO TEST
  cypress/local-only/tests/accessibility/trialSessionPlanningReport/trial-session-planning-report-view.cy.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.test.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.tsx
  shared/src/business/utilities/trialSessionPlanningReport/trialSessionPlanningReportDataTypes.ts
  shared/src/proxies/trialSessions/getTrialSessionPlanningReportProxy.ts
  shared/src/proxies/trialSessions/runTrialSessionPlanningReportProxy.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/trialSessions/getTrialSessionPlanningReportLambda.ts
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/getTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/getTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/TrialSession/runTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/runTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportViewAction.test.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportViewAction.ts
  web-client/src/presenter/actions/setupTrialSessionPlanningReportViewDataAction.test.ts
  web-client/src/presenter/actions/setupTrialSessionPlanningReportViewDataAction.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.test.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.ts
  web-client/src/presenter/computeds/trialSessionPlanningReportViewHelper.test.ts
  web-client/src/presenter/computeds/trialSessionPlanningReportViewHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoTrialSessionPlanningReportSequence.ts
  web-client/src/presenter/sequences/gotoTrialSessionPlanningReportViewSequence.ts
  web-client/src/presenter/sequences/navigateToTrialSessionPlanningReportViewSequence.ts
  web-client/src/presenter/sequences/runTrialSessionPlanningReportSequence.ts
  web-client/src/presenter/sequences/validateTrialSessionPlanningSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponent.tsx
  web-client/src/views/TrialSessionPlanningModal.tsx
  web-client/src/views/TrialSessions/TrialSessionPlanningReport.tsx
  web-client/src/views/TrialSessions/TrialSessionPlanningReportView.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test, Review Please

#5655 10491 work items fix
  cypress/local-only/support/pages/create-paper-petition.ts
  cypress/local-only/tests/integration/caseDetail/notes/judges-notes-icon.cy.ts
  cypress/local-only/tests/integration/fileAPetition/petitions-clerk-verifies-auto-generated-nane.cy.ts
  cypress/local-only/tests/integration/trialSession/trial-session-paper-pdf.cy.ts
  package-lock.json
  shared/src/proxies/createCaseFromPaperProxy.ts
  shared/src/proxies/workitems/assignWorkItemsProxy.ts
  web-api/src/business/useCases/createCaseFromPaperInteractor.test.ts
  web-api/src/business/useCases/createCaseFromPaperInteractor.ts
  web-api/src/business/useCases/workItems/assignWorkItemsInteractor.test.ts
  web-api/src/business/useCases/workItems/assignWorkItemsInteractor.ts
  web-client/src/presenter/actions/WorkItem/assignPetitionToAuthenticatedUserAction.test.ts
  web-client/src/presenter/actions/WorkItem/assignPetitionToAuthenticatedUserAction.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.ts
Labels: to test

#5658 10293: Fix Case Inventory Report Title
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to test

#5656 Fix format of response object in our logs
  web-api/src/logger.test.ts
  web-api/src/logger.ts
Labels: to staging, Review Please

#5659 10434: Handle Feedback
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.ts
  web-client/src/styles/custom.scss
  web-client/src/views/TrialSessions/TrialSessionPlanningReportView.tsx
Labels: to test

#5660 10504 dxox: Fix finalBriefDueDate issue in case worksheet
  web-api/src/database-types.ts
  web-api/src/persistence/postgres/caseWorksheets/upsertCaseWorksheets.ts
Labels: to test, Review Please

#5661 10434: Fix Special Case Count;
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.test.ts
  shared/src/business/utilities/trialSessionPlanningReport/trialSessionPlanningReportDataTypes.ts
  shared/src/proxies/trialSessions/getTrialSessionPlanningReportProxy.ts
  shared/src/proxies/trialSessions/runTrialSessionPlanningReportProxy.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/TrialSession/runTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.test.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.ts
  web-client/src/presenter/computeds/trialSessionPlanningReportViewHelper.ts
  web-client/src/presenter/sequences/gotoTrialSessionPlanningReportViewSequence.ts
  web-client/src/presenter/sequences/runTrialSessionPlanningReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/views/TrialSessions/TrialSessionPlanningReportView.tsx
Labels: to test

#5644 Modify restoreDbFromSource to drop all target tables before restore
  scripts/postgres/restoreDbFromSource.ts
Labels: to test, Review Please

#5624 10285: Fix: Wrap text in Filings and Proceedings column in Document View
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: to staging, Review Please

#5600 10489: Status Order Report Enhancements
  cypress/local-only/tests/integration/statusReportOrder/status-report-order-description-fields.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/replaceBracketed.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.test.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/setCourtIssuedDocumentInitialDataAction.ts
  web-client/src/presenter/sequences/gotoAddCourtIssuedDocketEntrySequence.ts
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
  web-client/src/views/StatusReportOrder.tsx
Labels: to staging, Review Please

#5642 Modify restoreDbFromSource to drop all target tables before restore
  scripts/postgres/restoreDbFromSource.ts
Labels: to staging

#5662 Dep updates 2024 12 20
  .circleci/config.yml
  Dockerfile
  aws/lambdas/RotateInfoIndices/src/index.js
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/src/persistence/s3/getStorageClient.ts
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-client/src/presenter/utilities/focusPaginatorTop.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/InfoNotification.tsx
  web-client/src/views/JudgeActivityReport/Statistics.tsx
  web-client/src/views/StepIndicator.tsx
  web-client/src/views/SuccessNotification.tsx
  web-client/src/views/WarningNotification.tsx
Labels: to staging, Review Please

#5610 10549- Fix long docket number cut off
  web-client/src/styles/typography.scss
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
Labels: to staging

#5665 10571 story intermediate branch to test 1735245869
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
Labels: to test, Review Please

#5666 10293-design-debt: Update length of each page for case inventory report
  shared/src/business/entities/EntityConstants.ts
Labels: to test
