Repository ustaxcourt/ef-cms, pull requests merged in 2024-09, with the labels that each got.

#5311 10401: Convert endpoint to use async sync logic TO TEST;
  shared/src/proxies/reports/generatePrintableCaseInventoryReportProxy.ts
  shared/src/proxies/requests.ts
  web-api/src/app.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/storage/scripts/loadTest/loadTestPdfGeneration.ts
  web-api/terraform/modules/api/api-async.tf
  web-client/src/ustc-ui/Pagination/Paginator.tsx
Labels: to test

#5314 10427 story intermediate branch to test 1725373107
  web-client/src/styles/buttons.scss
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Modal/ConfirmModal.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Login/Login.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/TrialSessionDetail/ServeThirtyDayNoticeModal.tsx
  web-client/src/views/TrialSessionDetail/TrialSessionInformation.tsx
  web-client/src/views/WorkQueue/RecentMessages.tsx
Labels: to test, Review Please

#5313 10437: Update empty Blocked Case report table message;
  web-client/src/presenter/computeds/blockedCasesReportHelper.test.ts
  web-client/src/presenter/computeds/blockedCasesReportHelper.ts
Labels: to test

#5315 10401: Improve script and spinner;
  web-api/storage/scripts/loadTest/loadTestPdfGeneration.ts
  web-client/src/presenter/sequences/submitCaseInventoryReportModalSequence.ts
Labels: to test

#5317 10470 design debt
  web-client/src/views/PDFPreviewButton.tsx
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to test, Review Please

#5274 10439: Docket Clerk - Remove Ability to Create Regular/Small/Hybrid/H-S Trial Sessions
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/views/TrialSessions/EditTrialSession.tsx
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging

#5286 10399 bug
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/docket-clerk-uploads-and-edits-court-issued-docket-entry.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/utilities/getFormattedCaseDetail.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/business/utilities/isDraftStatusReportOrder.test.ts
  shared/src/business/utilities/isDraftStatusReportOrder.ts
  shared/src/business/utilities/isMiscellaneousDocketEntry.test.ts
  shared/src/business/utilities/isMiscellaneousDocketEntry.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.ts
  web-client/src/presenter/actions/checkDocumentTypeAction.test.ts
  web-client/src/presenter/actions/checkDocumentTypeAction.ts
  web-client/src/presenter/actions/setCaseDetailPageTabActionGenerator.ts
  web-client/src/presenter/sequences/editUploadCourtIssuedDocumentSequence.ts
  web-client/src/presenter/sequences/navigateToEditOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
  web-client/src/views/EditUploadCourtIssuedDocument/EditUploadCourtIssuedDocument.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
Labels: to staging

#5309 10377: BUG: Double clicking "Complete" or "Complete and Send Message" when QCing work items causes issues
  shared/src/business/entities/EntityConstants.ts
  web-client/src/ustc-ui/Button/Button.tsx
  web-client/src/views/DocketEntryQc.tsx
Labels: to staging, Review Please

#5323 10401: Extend timeout for PDF generator lambda;
  shared/src/proxies/reports/generatePrintableCaseInventoryReportProxy.ts
  web-api/terraform/modules/api/pdf-generation.tf
Labels: to test

#5310 10455 Story: Add/Remove/Modify Judge Users
  cypress/local-only/tests/integration/trialSession/petitions-clerk-verify-chamber-phone-auto-fills.cy.ts
  cypress/local-only/tests/integration/trialSession/trial-session-paper-pdf.cy.ts
  docs/operations/runbooks/add-or-update-judge-user.md
  docs/operations/runbooks/offboard-judge-user.md
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.ts
  scripts/circleci/judge/judge_users.csv
  scripts/run-once-scripts/add-new-judge.ts
  scripts/run-once-scripts/add-phone-numbers-to-judge-records.ts
  scripts/run-once-scripts/promote-special-trial-judge.ts
  scripts/user/add-judge.ts
  scripts/user/add-or-update-judge-helpers.ts
  scripts/user/add-user.ts
  scripts/user/email-helpers.ts
  scripts/user/update-judge.ts
  shared/src/business/entities/User.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/test/mockJudgesChambers.ts
  shared/src/test/mockUsers.ts
  web-api/src/business/useCaseHelper/getJudgeForUserHelper.test.ts
  web-api/src/business/useCases/user/getUsersInSectionInteractor.test.ts
  web-api/src/business/useCases/workItems/getDocumentQCInboxForSectionInteractor.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/journey/docketClerkCreatesMessageWithCorrespondence.ts
  web-client/integration-tests/journey/petitionsClerkCreatesMessageToChambers.ts
  web-client/integration-tests/journey/userSendsMessage.ts
  web-client/integration-tests/messagesTableJourney.test.ts
  web-client/integration-tests/stampDispositionJudgeJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/business/chambers/getJudgesChambers.test.ts
  web-client/src/business/chambers/getJudgesChambers.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.test.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/getJudgesChambersAction.test.ts
  web-client/src/presenter/actions/getJudgesChambersAction.ts
  web-client/src/presenter/actions/setJudgesChambersAction.test.ts
  web-client/src/presenter/actions/setJudgesChambersAction.ts
  web-client/src/presenter/computeds/formattedCaseDetail.getUserIsAssignedToSession.test.ts
  web-client/src/presenter/computeds/messageModalHelper.test.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/presenter/sequences/getJudgesChambersSequence.ts
  web-client/src/presenter/sequences/openCreateMessageModalSequence.ts
  web-client/src/presenter/sequences/updateTrialSessionFormDataSequence.ts
  web-client/src/presenter/sequences/validateTrialSessionSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to test

#5324 10365 Bug: Remove leading/trailing spaces from user-entered passwords
  web-client/src/presenter/actions/Login/submitLoginAction.test.tsx
  web-client/src/presenter/actions/Login/submitLoginAction.tsx
Labels: to staging, Review Please

#5325 10401: Increase lambda memory size;
  web-api/terraform/modules/api/pdf-generation.tf
Labels: to test

#5327 Devex Make explicit unified logger
  web-api/src/app-public.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/createLogger.ts
  web-api/src/gateways/worker/workerLocal.ts
  web-api/src/genericHandler.ts
  web-api/src/lambdas/cases/sealInLowerEnvironmentLambda.ts
  web-api/src/lambdas/cognitoAuthorizer/cognito-authorizer.test.ts
  web-api/src/lambdas/cognitoAuthorizer/createAuthorizer.ts
  web-api/src/lambdas/cognitoAuthorizer/websocket-authorizer.test.ts
  web-api/src/lambdas/cognitoAuthorizer/worker-handler.ts
  web-api/src/lambdas/migration/migration-segments.ts
  web-api/src/lambdas/migration/migration.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
  web-api/src/logger.test.ts
  web-api/src/logger.ts
  web-api/src/middleware/userIdLimiter.ts
  web-api/src/utilities/logger/getLogger.ts
  web-api/storage/scripts/createUsers.ts
Labels: to test

#5331 10339: test - feedback
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-generate-petition.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-other--minor-or-legally-incompetent.cy.ts
  shared/src/business/entities/contacts/ContactFactoryUpdated.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  web-api/src/business/useCases/createCaseInteractor.test.ts
  web-api/src/business/useCases/createCaseInteractor.ts
  web-client/src/presenter/actions/formatPetitionAction.test.ts
  web-client/src/presenter/actions/formatPetitionAction.ts
  web-client/src/presenter/actions/saveAndSubmitCaseAction.test.ts
  web-client/src/presenter/actions/saveAndSubmitCaseAction.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.test.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/styles/overrides.scss
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCaseUpdated/BusinessInfo.tsx
  web-client/src/views/StartCaseUpdated/CounselInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherContactInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherInfo.tsx
  web-client/src/views/StartCaseUpdated/PetitionerInformation.tsx
  web-client/src/views/StartCaseUpdated/SecondaryMinorIncompetentOptions.tsx
  web-client/src/views/StartCaseUpdated/Spouse.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
Labels: to test

#5335 Revert 10427 changes that inadvertently had too broad of an impact
  web-client/src/styles/buttons.scss
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Modal/ConfirmModal.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Login/Login.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/TrialSessionDetail/ServeThirtyDayNoticeModal.tsx
  web-client/src/views/TrialSessionDetail/TrialSessionInformation.tsx
  web-client/src/views/WorkQueue/RecentMessages.tsx
Labels: to test, Review Please

#5332 10455 Story: Add/Remove/Modify Judge Users Updates
  scripts/user/add-judge.ts
  scripts/user/add-user.ts
  scripts/user/email-helpers.ts
  scripts/user/make-new-password.ts
  scripts/user/rotate-environment-secrets.ts
  scripts/user/update-judge.ts
Labels: to test, Review Please

#5337 Opex: fix for automated glue jobs (to `test`)
  .circleci/config.yml
Labels: to test

#5339 Opex: fix setup-glued-judges (to test)
  scripts/user/setup-glued-judges.ts
Labels: to test

#5336 Dep updates 2024 09 02
  .circleci/config.yml
  Dockerfile
  babel.config.js
  docs/dependency-updates.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  tsconfig.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-client/src/ustc-ui/Accordion/Accordion.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.cerebral.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.test.tsx
  web-client/src/ustc-ui/Text/TextView.test.tsx
Labels: to staging

#5328 10282: design debt
  web-client/src/styles/forms.scss
Labels: to test

#5343 10476: Slight changes to Status Report Order
  cypress/local-only/support/statusReportOrder.ts
  cypress/local-only/tests/integration/statusReportOrder/file-status-report-order.cy.ts
  shared/src/business/entities/StatusReportOrderForm.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.ts
  web-client/src/views/StatusReportOrder.tsx
Labels: to test

#5347 10339 test feedback
  web-client/src/presenter/computeds/updatedFilePetitionHelper.test.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.ts
  web-client/src/styles/forms.scss
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
Labels: to test

#5348 10427 story v2 intermediate branch to test 1725972506
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/InlineLink/InlineLink.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/Dashboards/FilingFeeOptions.tsx
  web-client/src/views/StartCaseUpdated/CorporateDisclosureUpload.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep2.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep4.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep5.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: to test

#5352 10409 story - Updated Trial sessions Page
  shared/src/business/dto/trialSessions/TrialSessionInfoDTO.ts
  shared/src/business/entities/trialSessions/TrialSession.noticeOfTrialReminder.test.ts
  shared/src/business/entities/trialSessions/TrialSession.thirtyDaysBeforeTrialFormatted.test.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/proxies/trialSessions/getTrialSessionsProxy.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionsInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionsInteractor.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/dismissNOTTReminder.test.ts
  web-client/integration-tests/docketClerkViewsTrialSessionTabs.test.ts
  web-client/integration-tests/journey/docketClerkClosesStandaloneRemoteTrialSession.ts
  web-client/integration-tests/journey/docketClerkVerifiesSessionIsNotClosed.ts
  web-client/integration-tests/journey/docketClerkViewsTrialSessionList.ts
  web-client/integration-tests/journey/docketClerkViewsTrialSessionsTab.ts
  web-client/integration-tests/serveNOTTsFromReminder.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionsFiltersAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionsFiltersAction.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionsPageAction.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.test.ts
  web-client/src/presenter/computeds/TrialSession/addTrialSessionInformationHelper.ts
  web-client/src/presenter/computeds/addToTrialSessionModalHelper.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.test.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/computeds/formattedTrialSessions.filterFormattedSessionsByStatus.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.formatSession.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.ts
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/presenter/sequences/setTrialSessionsFiltersSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/state/trialSessionsPageState.ts
  web-client/src/router.ts
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5342 Dep updates 2024 09 02
  .circleci/config.yml
  Dockerfile
  babel.config.js
  docs/dependency-updates.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  tsconfig.json
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.test.ts
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/bin/deploy-app-color.sh
  web-client/src/ustc-ui/Accordion/Accordion.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.cerebral.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.test.tsx
  web-client/src/ustc-ui/Text/TextView.test.tsx
Labels: to staging

#5301 First draft of sensitive data warning
  docs/sensitive-data.md
Labels: to staging, Review Please

#5356 10339: text change;
  web-client/integration-tests/admissionsClerkAddsPetitionerWithExistingAccountToCase.test.ts
  web-client/integration-tests/journey/petitionerCancelsCreateCase.ts
  web-client/integration-tests/journey/petitionerCreatesNewCaseTestAllOptions.ts
  web-client/integration-tests/journey/petitionerViewsDashboard.ts
  web-client/integration-tests/journey/petitionerViewsOpenAndClosedCases.ts
  web-client/integration-tests/journey/practitionerCreatesNewCase.ts
  web-client/integration-tests/journey/practitionerViewsDashboard.ts
  web-client/integration-tests/journey/practitionerViewsDashboardBeforeAddingCase.ts
  web-client/integration-tests/journey/privatePractitionerViewsOpenAndClosedCases.ts
  web-client/integration-tests/journey/privatePractitionerViewsOpenConsolidatedCases.ts
  web-client/src/presenter/computeds/headerHelper.test.ts
  web-client/src/presenter/sequences/gotoDashboardSequence.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/Dashboards/DashboardExternalUser.tsx
Labels: to test

#5354 10282 Design Debt
  web-client/src/styles/forms.scss
Labels: to staging

#5355 10470 Design Debt
  web-client/src/views/PDFPreviewButton.tsx
  web-client/src/views/TrialSessions/SessionInformationForm.tsx
Labels: to staging

#5316 10401: BUG: Printable Case Inventory Report times out;
  shared/src/proxies/reports/generatePrintableCaseInventoryReportProxy.ts
  shared/src/proxies/requests.ts
  web-api/src/app.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/storage/scripts/loadTest/loadTestPdfGeneration.ts
  web-api/terraform/modules/api/api-async.tf
  web-api/terraform/modules/api/pdf-generation.tf
  web-client/src/presenter/sequences/submitCaseInventoryReportModalSequence.ts
Labels: to staging

#5360 10409 story intermediate branch to test 1726077454
  .circleci/config.yml
  Dockerfile
  babel.config.js
  docs/dependency-updates.md
  docs/sensitive-data.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  tsconfig.json
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.test.ts
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/bin/deploy-app-color.sh
  web-client/integration-tests/dismissNOTTReminder.test.ts
  web-client/src/presenter/actions/TrialSession/setActiveTrialSessionsTabAction.test.ts
  web-client/src/presenter/actions/TrialSession/setActiveTrialSessionsTabAction.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/router.ts
  web-client/src/ustc-ui/Accordion/Accordion.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.cerebral.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.test.tsx
  web-client/src/ustc-ui/Text/TextView.test.tsx
  web-client/src/views/TrialSessions/TrialSessionsSummary.tsx
Labels: to test

#5359 10363: BUG: Court users are unable to download all documents on large cases - Download stalls out TO TEST
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.test.ts
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/BatchDownload/DocketEntries/mergeDocketEntriesBatchesAction.ts
  web-client/src/presenter/actions/BatchDownload/DocketEntries/singleDocketEntriesBatchCompleteAction.ts
  web-client/src/presenter/actions/BatchDownload/DocketEntries/updateDocketEntriesBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/batchDownloadDocketEntriesAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/updateDocketEntriesBatchDownloadDownloadSequence.ts
  web-client/src/presenter/sequences/updateDocketEntriesBatchDownloadProgressSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/utilities/downloadBlob.ts
  web-client/src/providers/socketRouter.ts
Labels: to test

#5364 10363: Modify batch size and download link TTL;
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-client/src/presenter/actions/batchDownloadDocketEntriesAction.ts
Labels: to test

#5349 Update phone number for Judge Way now that we have it
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to staging

#5361 10476: Slight changes to Status Report Order
  cypress/local-only/support/statusReportOrder.ts
  cypress/local-only/tests/integration/statusReportOrder/file-status-report-order.cy.ts
  shared/src/business/entities/StatusReportOrderForm.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.ts
  web-client/src/views/StatusReportOrder.tsx
Labels: to staging, Review Please

#5366 10363: Refactor
  web-api/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-client/src/presenter/actions/BatchDownload/DocketEntries/mergeDocketEntriesBatchesAction.ts
Labels: to test

#5367 10427 story v2 intermediate branch to test 1725995155
  web-client/src/styles/buttons.scss
  web-client/src/styles/nav.scss
  web-client/src/views/Header/ReportsMenu.tsx
Labels: to test

#5357 UX docs update
  docs/wiki/UX-Documentation.md
Labels: to staging

#5368 10409 story intermediate branch to test 1726178329
  docs/wiki/UX-Documentation.md
  web-client/integration-tests/journey/docketClerkViewsTrialSessionsTab.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.test.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.ts
  web-client/src/presenter/actions/TrialSession/resetTrialSessionsFiltersAction.test.ts
  web-client/src/presenter/actions/TrialSession/resetTrialSessionsFiltersAction.ts
  web-client/src/presenter/actions/clearLoginFormAction.test.ts
  web-client/src/presenter/actions/clearLoginFormAction.ts
  web-client/src/presenter/computeds/trialSessionsHelper.test.ts
  web-client/src/presenter/computeds/trialSessionsHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoTrialSessionsSequence.ts
  web-client/src/presenter/sequences/signOutSequence.ts
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to test

#5363 10466 Design Debt
  shared/src/business/entities/ChangePasswordForm.test.ts
  shared/src/business/entities/ChangePasswordForm.ts
  shared/src/business/entities/NewPetitionerUser.test.ts
  shared/src/business/entities/NewPetitionerUser.ts
  shared/src/business/entities/NewPractitioner.test.ts
  shared/src/business/entities/NewPractitioner.ts
  shared/src/business/entities/Practitioner.test.ts
  shared/src/business/entities/Practitioner.ts
  shared/src/business/entities/UpdateUserEmail.test.ts
  shared/src/business/entities/UpdateUserEmail.ts
  shared/src/business/entities/contacts/Contact.test.ts
  shared/src/business/entities/contacts/Contact.ts
  shared/src/business/entities/contacts/Petitioner.ts
  web-client/src/presenter/computeds/CreatePetitionerAccount/createAccountHelper.test.ts
Labels: to test

#5362 Dep updates 20240911
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/elasticsearch/client.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5374 10455 Story: Add/Remove/Modify Judge Users -- Disable updating name
  scripts/user/add-or-update-judge-helpers.ts
  scripts/user/update-judge.ts
Labels: to test

#5375 10001 (and 10002 and 10003): File Validation Updates
  cypress/helpers/file/upload-file.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.test.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
Labels: to test

#5344 10427 Adjust padding of inline links in petition generation flow
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/InlineLink/InlineLink.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/Dashboards/FilingFeeOptions.tsx
  web-client/src/views/StartCaseUpdated/CorporateDisclosureUpload.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep2.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep4.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep5.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: to staging

#5378 Bugfix: Do not attempt to sign user out if clientNeedsToRefresh is true
  web-client/src/presenter/sequences/signOutUserInitiatedSequence.ts
Labels: to test

#5264 10455 Story: Add/Remove/Modify Judge Users
  cypress/local-only/tests/integration/trialSession/petitions-clerk-verify-chamber-phone-auto-fills.cy.ts
  cypress/local-only/tests/integration/trialSession/trial-session-paper-pdf.cy.ts
  docs/operations/runbooks/add-or-update-judge-user.md
  docs/operations/runbooks/offboard-judge-user.md
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.ts
  scripts/circleci/judge/judge_users.csv
  scripts/run-once-scripts/add-new-judge.ts
  scripts/run-once-scripts/add-phone-numbers-to-judge-records.ts
  scripts/run-once-scripts/promote-special-trial-judge.ts
  scripts/user/add-judge.ts
  scripts/user/add-or-update-judge-helpers.ts
  scripts/user/add-user.ts
  scripts/user/make-new-password.ts
  scripts/user/rotate-environment-secrets.ts
  scripts/user/update-judge.ts
  shared/src/business/entities/User.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/test/mockJudgesChambers.ts
  shared/src/test/mockUsers.ts
  web-api/src/business/useCaseHelper/getJudgeForUserHelper.test.ts
  web-api/src/business/useCases/user/getUsersInSectionInteractor.test.ts
  web-api/src/business/useCases/workItems/getDocumentQCInboxForSectionInteractor.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/journey/docketClerkCreatesMessageWithCorrespondence.ts
  web-client/integration-tests/journey/petitionsClerkCreatesMessageToChambers.ts
  web-client/integration-tests/journey/userSendsMessage.ts
  web-client/integration-tests/messagesTableJourney.test.ts
  web-client/integration-tests/stampDispositionJudgeJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/business/chambers/getJudgesChambers.test.ts
  web-client/src/business/chambers/getJudgesChambers.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.test.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/getJudgesChambersAction.test.ts
  web-client/src/presenter/actions/getJudgesChambersAction.ts
  web-client/src/presenter/actions/setJudgesChambersAction.test.ts
  web-client/src/presenter/actions/setJudgesChambersAction.ts
  web-client/src/presenter/computeds/formattedCaseDetail.getUserIsAssignedToSession.test.ts
  web-client/src/presenter/computeds/messageModalHelper.test.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/presenter/sequences/getJudgesChambersSequence.ts
  web-client/src/presenter/sequences/openCreateMessageModalSequence.ts
  web-client/src/presenter/sequences/updateTrialSessionFormDataSequence.ts
  web-client/src/presenter/sequences/validateTrialSessionSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to staging, Manual Deploy Step(s) Required

#5384 Opex: revoke a petitioner's e-access
  scripts/user/revoke-e-access.ts
Labels: to staging

#5381 Devex chunk to pqueue to test
  jest.config.ts
  scripts/dynamo/archive-outboxes.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.ts
  web-api/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.ts
  web-api/src/persistence/dynamo/cases/deleteCaseTrialSortMappingRecords.ts
  web-api/src/persistence/dynamo/helpers/deleteByGsi.ts
  web-api/src/persistence/dynamo/locks/acquireLock.ts
  web-api/src/persistence/dynamo/notifications/deleteUserConnection.ts
  web-api/src/persistence/dynamo/workitems/deleteWorkItem.ts
  web-api/src/persistence/dynamodbClientService.ts
Labels: to test

#5387 10001 (and 10002 and 10003): Updates to client-side PDF Validation to mark read-only pdfs as invalid
  cypress/helpers/file/readonly-pdf.pdf
  cypress/helpers/file/upload-file.ts
  cypress/local-only/tests/integration/fileUpload/upload-court-issued-pdf-validation.cy.ts
  shared/src/business/entities/EntityConstants.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.test.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
  web-client/src/views/FileHandlingHelpers/pdfValidationHelpers.ts
Labels: to test, Review Please

#5390 More 10001 (and 10002 and 10003) Updates: skip file type validation for PractitionerAddEditDocoment
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
  web-client/src/views/FileHandlingHelpers/fileValidation.test.ts
  web-client/src/views/FileHandlingHelpers/fileValidation.ts
  web-client/src/views/Practitioners/PractitionerAddEditDocument.tsx
Labels: to test

#5395 10501 Bugfix: Fix judges chambers not populating in certain message modals
  cypress/local-only/support/pages/document-qc.ts
  cypress/local-only/tests/integration/messages/chambers-dropdown.cy.ts
  web-client/src/presenter/sequences/openCompleteAndSendMessageModalSequence.ts
  web-client/src/presenter/sequences/openForwardMessageModalSequence.ts
Labels: to staging, Review Please

#5394 Dependency Updates - 09/23/2024
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5388 updated QC process flow chart pdf
  docs/wiki/Petitions-Clerk-QC-Process-Flow.pdf
  docs/wiki/UX-Documentation.md
Labels: to staging, Review Please

#5389 Devex: automated glue fixerooni (to test)
  .circleci/config.yml
  scripts/migration/set-migration-complete-marker.sh
Labels: to test
