Repository ustaxcourt/ef-cms, pull requests merged in 2024-07, with the labels that each got.

#5014 Devex 10337 - AWS v2 -> v3 conversion: SQS
  shared/admin-tools/aws/sqsHelper.ts
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/user/generateChangeOfAddress.ts
  web-api/src/gateways/worker/worker.test.ts
  web-api/src/gateways/worker/worker.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/sendEmails/send-emails.ts
  web-api/src/lambdas/trial-session/trial-session.ts
  web-api/src/persistence/messages/getEmailClient.ts
  web-api/src/persistence/messages/sendEmailEventToQueue.ts
  web-api/src/persistence/messages/sendSetTrialSessionCalendarEvent.ts
  web-api/src/persistence/sqs/deleteMessage.ts
  web-api/src/persistence/sqs/getMessages.ts
Labels: to staging, Review Please

#5092 Devex 10337 - AWS v2 -> v3 conversion: SNS
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/applicationContext.ts
  web-api/src/dispatchers/sns/sendNotificationOfSealing.test.ts
  web-api/src/dispatchers/sns/sendNotificationOfSealing.ts
  web-api/src/notifications/getNotificationService.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to staging, Review Please

#5123 10420 bug intermediate branch to test 1720188275
  web-api/src/business/useCaseHelper/caseAssociation/removeCounselFromRemovedPetitioner.test.ts
  web-api/src/business/useCaseHelper/caseAssociation/removeCounselFromRemovedPetitioner.ts
Labels: to test, Review Please

#5128 10372: complete message from inbox
  cypress/local-only/tests/integration/messages/messages.cy.ts
  docs/wiki/Messages.md
  shared/src/proxies/messages/completeMessageProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/messages/completeMessageInteractor.test.ts
  web-api/src/business/useCases/messages/completeMessageInteractor.ts
  web-api/src/lambdas/messages/completeMessageLambda.ts
  web-client/integration-tests/journey/docketClerkCompletesMessageThread.ts
  web-client/src/presenter/actions/CaseDetail/completeMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/completeMessageAction.ts
  web-client/src/presenter/actions/CaseDetail/replyToMessageAction.test.ts
  web-client/src/presenter/actions/Messages/resetSelectedMessageAction.test.ts
  web-client/src/presenter/actions/Messages/resetSelectedMessageAction.ts
  web-client/src/presenter/actions/Messages/setCompleteMessageAlertAction.test.ts
  web-client/src/presenter/actions/Messages/setCompleteMessageAlertAction.ts
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.test.ts
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.ts
  web-client/src/presenter/actions/batchCompleteMessageAction.test.ts
  web-client/src/presenter/actions/batchCompleteMessageAction.ts
  web-client/src/presenter/actions/getMessagePageAction.test.ts
  web-client/src/presenter/actions/getMessagePageAction.ts
  web-client/src/presenter/actions/getMostRecentMessageInThreadAction.test.ts
  web-client/src/presenter/actions/getMostRecentMessageInThreadAction.ts
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.test.ts
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.ts
  web-client/src/presenter/actions/setMessageAsReadAction.test.ts
  web-client/src/presenter/computeds/createMessageModalHelper.test.ts
  web-client/src/presenter/computeds/formattedCaseMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/computeds/messagesHelper.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.test.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/batchCompleteMessageSequence.ts
  web-client/src/presenter/sequences/completeMessageSequence.ts
  web-client/src/presenter/sequences/setSelectedMessagesSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/Messages/MessageDetail.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
Labels: to test

#5075 10346 - Large PDF Errors
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/court-issued-documents.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-gets-unserved.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-signature-disappears.cy.ts
  cypress/deployed-and-local/integration/documentQC/complete-docket-qc.cy.ts
  cypress/helpers/caseDetail/docketRecord/courtIssuedFiling/create-order-and-decision.ts
  cypress/helpers/caseDetail/docketRecord/courtIssuedFiling/create-order.ts
  cypress/local-only/tests/integration/advancedSearch/content-search.cy.ts
  cypress/local-only/tests/integration/advancedSearch/external-user-searches-orders.cy.ts
  cypress/local-only/tests/integration/advancedSearch/title-search.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/docket-clerk-creates-draft-orders-for-lead-case.cy.ts
  cypress/local-only/tests/integration/judgeActivityReport/judge-activity-report.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/scrapePdfContents.test.ts
  shared/src/business/utilities/scrapePdfContents.ts
  web-api/src/app-local.ts
  web-api/src/business/useCaseHelper/pdf/parseAndScrapePdfContents.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.consolidatedCases.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.ts
  web-api/terraform/modules/api/alarms.tf
  web-client/integration-tests/externalUserOrderAdvancedSearch.test.ts
  web-client/integration-tests/journey/chambersUserAddsOrderToCase.ts
  web-client/integration-tests/journey/chambersUserSkipSigningOrder.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.ts
  web-client/integration-tests/journey/petitionsClerk1CreatesNoticeFromMessageDetail.ts
  web-client/integration-tests/journey/petitionsClerkAddsGenericOrderToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsNoticeToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsOrderToCase.ts
  web-client/integration-tests/journey/petitionsClerkCreateOrder.ts
  web-client/integration-tests/journey/petitionsClerkCreatesOrderFromMessage.ts
  web-client/integration-tests/orderSearchJourneyAndKeyword.test.ts
  web-client/integration-tests/orderSearchJourneyCaseCaption.test.ts
  web-client/integration-tests/orderSearchJourneyDocketNumber.test.ts
  web-client/integration-tests/orderSearchJourneyOrKeyword.test.ts
  web-client/integration-tests/orderSearchJourneySpecialCharacters.test.ts
  web-client/src/presenter/actions/CaseDetail/validateRemoveFromTrialSessionAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/validateCourtOrderAction.ts
  web-client/src/presenter/actions/getDocumentContentsAction.test.ts
  web-client/src/presenter/actions/getDocumentContentsAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.ts
  web-client/src/presenter/sequences/validateCourtOrderSequence.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/Loading.tsx
Labels: to staging

#5124 Dependency updates 07/05/2024
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/src/business/utilities/documentGenerators/document_generator.jest.config.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5111 10398 Ensure caption is still on documentContents when an Order is edited
  web-api/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.ts
Labels: to staging, Review Please

#5131 Bug calendaring large trial sessions intermediate branch to test 1720642131
  scripts/run-once-scripts/create-many-trial-session-cases.sh
  shared/src/proxies/trialSessions/setTrialSessionCalendarProxy.ts
  web-api/cases.txt
  web-api/create-cases.sh
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/calendarTrialSessionScript.ts
  web-api/src/business/useCases/trialSessions/eligibleJson.json
  web-api/src/business/useCases/trialSessions/removeCasesFromTrialSessionScript.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.ts
  web-api/src/lambdas/trialSessions/setTrialSessionCalendarLambda.ts
  web-api/src/persistence/dynamo/workitems/setPriorityOnAllWorkItems.ts
  web-api/ux_testing_data.csv
  web-client/src/presenter/actions/TrialSession/setTrialSessionCalendarAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionCalendarAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/completeTrialSessionCalendarSequence.ts
  web-client/src/presenter/sequences/setTrialSessionCalendarErrorSequence.ts
  web-client/src/presenter/sequences/setTrialSessionCalendarSequence.ts
  web-client/src/presenter/sequences/validateCourtOrderSequence.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/CreateOrder/CreateOrder.tsx
Labels: to test

#5121 10420: delete practitioners (if needed) after removing representing
  web-api/src/business/useCaseHelper/caseAssociation/removeCounselFromRemovedPetitioner.test.ts
  web-api/src/business/useCaseHelper/caseAssociation/removeCounselFromRemovedPetitioner.ts
Labels: to staging

#5130 10422: Bug calendaring large trial sessions
  shared/src/proxies/trialSessions/setTrialSessionCalendarProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.ts
  web-api/src/lambdas/trialSessions/setTrialSessionCalendarLambda.ts
  web-api/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.test.ts
  web-api/src/persistence/dynamo/cases/deleteCaseTrialSortMappingRecords.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionCalendarAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionCalendarAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/completeTrialSessionCalendarSequence.ts
  web-client/src/presenter/sequences/setTrialSessionCalendarErrorSequence.ts
  web-client/src/presenter/sequences/setTrialSessionCalendarSequence.ts
  web-client/src/providers/socketRouter.test.ts
  web-client/src/providers/socketRouter.ts
Labels: to staging

#5135 10404: Allow 'Petitioners" and "Private Practitioner" to view Docket Entries (P, ATP, DISC) user submitted when case is not served;
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
  web-client/src/presenter/actions/ColdCaseReport/getColdCaseReportAction.test.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.test.ts
  web-client/src/views/StartCase/StartCaseStep3.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
Labels: Do Not Merge, to test

#5136 10372: better toggling logic for message checkboxes
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.test.ts
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.ts
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesAction.test.ts
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
Labels: to test

#5143 Dependency updates 07/12/2024
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to staging

#5141 10372: reset cache key to allow recalculating messages in state
  web-client/src/presenter/sequences/batchCompleteMessageSequence.ts
Labels: to test, Review Please

#5153 10372: caching issues, again
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.test.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.ts
  web-client/src/presenter/sequences/batchCompleteMessageSequence.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test, Review Please

#5144 10404: Make Un-Served Petition Docs Visible To Logged In User
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
  web-client/src/presenter/actions/ColdCaseReport/getColdCaseReportAction.test.ts
  web-client/src/presenter/actions/StartCase/updatePartyTypeAction.test.ts
  web-client/src/views/StartCase/StartCaseStep3.tsx
Labels: to staging, Review Please

#5157 10417 minimum changes intermediate branch to test 1721159320
  shared/src/business/entities/authUser/AuthUser.test.ts
  shared/src/business/entities/authUser/AuthUser.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/test/mockAuthUsers.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionerByBarNumberInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/genericHandler.test.ts
  web-api/src/genericHandler.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/lambdas/cases/checkForReadyForTrialCasesLambda.ts
  web-api/src/lambdas/cases/sealInLowerEnvironmentLambda.ts
  web-api/src/lambdas/cases/sendMaintenanceNotificationsLambda.ts
  web-api/src/lambdas/notifications/disconnectLambda.ts
  web-api/src/lambdas/public-api/casePublicSearchLambda.ts
  web-api/src/lambdas/public-api/generatePublicDocketRecordPdfLambda.ts
  web-api/src/lambdas/public-api/getCaseForPublicDocketSearchLambda.ts
  web-api/src/lambdas/public-api/getPublicCaseExistsLambda.ts
  web-api/src/lambdas/public-api/getPublicCaseLambda.ts
  web-api/src/lambdas/public-api/getPublicDocumentDownloadUrlLambda.ts
  web-api/src/lambdas/public-api/getPublicJudgesLambda.ts
  web-api/src/lambdas/public-api/opinionPublicSearchLambda.ts
  web-api/src/lambdas/public-api/orderPublicSearchLambda.ts
  web-api/src/lambdas/public-api/todaysOpinionsLambda.ts
  web-api/src/lambdas/public-api/todaysOrdersLambda.ts
  web-api/src/lambdas/reports/getCustomCaseReportLambda.ts
  web-api/src/lambdas/v1/getCaseLambda.test.ts
  web-api/src/lambdas/v1/getDocumentDownloadUrlLambda.test.ts
  web-api/src/lambdas/v2/getCaseLambda.test.ts
  web-api/src/lambdas/v2/getDocumentDownloadUrlLambda.test.ts
  web-api/src/middleware/apiGatewayHelper.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-api/src/middleware/slowDownLimiter.test.ts
  web-api/src/middleware/slowDownLimiter.ts
Labels: to test

#5149 10405: Change "Finish" to "Save" for Adding Correspondence
  web-client/src/views/Correspondence/AddCorrespondenceDocument.tsx
Labels: to staging, Review Please

#5158 10372: filtering
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.test.ts
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.test.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoMessagesSequence.ts
  web-client/src/presenter/sequences/updateMessageFilterSequence.ts
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
Labels: to test, Review Please

#5162 5512 - Feedback
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petition-info.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-business.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-myself-and-spouse.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-myself.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-other.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/petition-helper.ts
  package-lock.json
  shared/src/business/entities/cases/ElectronicPetition.test.ts
  shared/src/business/entities/cases/ElectronicPetition.ts
  shared/src/business/entities/contacts/BusinessContact.test.ts
  shared/src/business/entities/contacts/ContactFactoryUpdated.test.ts
  shared/src/business/entities/contacts/ContactFactoryUpdated.ts
  shared/src/business/entities/contacts/ContactUpdated.ts
  shared/src/business/entities/contacts/DeceasedSpouseContact.test.ts
  shared/src/business/entities/contacts/DeceasedSpouseContact.ts
  shared/src/business/entities/contacts/SpouseContact.test.ts
  shared/src/business/entities/contacts/SpouseContact.ts
  web-client/src/presenter/actions/decreaseCurrentStepIndicatorAction.test.ts
  web-client/src/presenter/actions/decreaseCurrentStepIndicatorAction.ts
  web-client/src/presenter/actions/getStep1DataAction.test.ts
  web-client/src/presenter/actions/getStep1DataAction.ts
  web-client/src/presenter/actions/validateUploadPetitionStep1Action.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
  web-client/src/views/StartCase/AddressUpdated.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetition.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
  web-client/src/views/StepIndicator.tsx
Labels: to test

#5159 10372: complete message from inbox
  cypress/local-only/tests/integration/messages/messages.cy.ts
  docs/wiki/Messages.md
  shared/src/proxies/messages/completeMessageProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/messages/completeMessageInteractor.test.ts
  web-api/src/business/useCases/messages/completeMessageInteractor.ts
  web-api/src/lambdas/messages/completeMessageLambda.ts
  web-client/integration-tests/journey/docketClerkCompletesMessageThread.ts
  web-client/src/presenter/actions/CaseDetail/completeMessageAction.test.ts
  web-client/src/presenter/actions/CaseDetail/completeMessageAction.ts
  web-client/src/presenter/actions/CaseDetail/replyToMessageAction.test.ts
  web-client/src/presenter/actions/Messages/resetSelectedMessageAction.test.ts
  web-client/src/presenter/actions/Messages/resetSelectedMessageAction.ts
  web-client/src/presenter/actions/Messages/setCompleteMessageAlertAction.test.ts
  web-client/src/presenter/actions/Messages/setCompleteMessageAlertAction.ts
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.test.ts
  web-client/src/presenter/actions/Messages/setSelectedMessagesAction.ts
  web-client/src/presenter/actions/PendingMotion/getPendingMotionDocketEntriesAction.test.ts
  web-client/src/presenter/actions/batchCompleteMessageAction.test.ts
  web-client/src/presenter/actions/batchCompleteMessageAction.ts
  web-client/src/presenter/actions/getMessagePageAction.test.ts
  web-client/src/presenter/actions/getMessagePageAction.ts
  web-client/src/presenter/actions/getMostRecentMessageInThreadAction.test.ts
  web-client/src/presenter/actions/getMostRecentMessageInThreadAction.ts
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.test.ts
  web-client/src/presenter/actions/removeCompletedMessagesFromDisplayAction.ts
  web-client/src/presenter/actions/setMessageAsReadAction.test.ts
  web-client/src/presenter/computeds/createMessageModalHelper.test.ts
  web-client/src/presenter/computeds/formattedCaseMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/presenter/computeds/messagesHelper.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.test.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/batchCompleteMessageSequence.ts
  web-client/src/presenter/sequences/completeMessageSequence.ts
  web-client/src/presenter/sequences/gotoMessagesSequence.ts
  web-client/src/presenter/sequences/setSelectedMessagesSequence.ts
  web-client/src/presenter/sequences/updateMessageFilterSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/styles/buttons.scss
  web-client/src/views/Messages/MessageDetail.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
Labels: to staging, Review Please

#5161 10413: DOJ Practitioners cannot "Represent a Party" unless case is "On Appeal"
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/helpers/caseDetail/caseInformation/update-case-status.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/doj-practitioner-should-not-be-able-to-represent-case-for-non-appeal-cases.cy.ts
  scripts/user/setup-test-users.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/test/mockUsers.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: Do Not Merge, to test, Review Please

#5167 10421 story intermediate branch to test 1721337380
  shared/src/business/utilities/documentGenerators/generateAndVerifyPdfDiff.ts
  shared/src/business/utilities/documentGenerators/order.test.ts
  shared/src/business/utilities/documentGenerators/order.ts
  shared/src/business/utilities/pdfGenerator/components/PageMetaHeaderDocket.tsx
  shared/test-pdf-expected-images/Order_With_Added_Docket_Numbers_Second_Page.pdf.2.png
  shared/test-pdf-expected-images/Order_Without_Added_Docket_Numbers_Second_Page.pdf.2.png
Labels: to test

#5169 5512 test - feedback
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.test.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/proxies/generatePetitionPdfProxy.ts
  web-client/src/presenter/actions/generatePetitionPdfAction.test.ts
  web-client/src/presenter/actions/generatePetitionPdfAction.ts
  web-client/src/presenter/actions/getStep1DataAction.test.ts
  web-client/src/presenter/actions/getStep1DataAction.ts
  web-client/src/presenter/computeds/caseTypeDescriptionHelper.test.ts
  web-client/src/presenter/computeds/caseTypeDescriptionHelper.ts
  web-client/src/presenter/sequences/updatedFilePetitionCompleteStep5Sequence.ts
  web-client/src/styles/custom.scss
  web-client/src/views/PetitionSuccessHeader.tsx
  web-client/src/views/StepIndicator.tsx
Labels: to test

#5164 Dep updates july 17
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
Labels: to staging

#5174 5512: Handle feedback TO TEST
  shared/src/business/entities/cases/PaperPetition.ts
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: to test, Review Please

#5172 10426: DOJ Practitioners: Do Not Allow File First IRS Document -TO TEST
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/doj-practitioner-should-not-be-able-to-file-first-irs-document.cy.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: to test, Review Please

#5175 5512: Fix minor bug, property was not being passed through to Interactor
  shared/src/business/entities/cases/PaperPetition.test.ts
  shared/src/proxies/generatePetitionPdfProxy.ts
Labels: to test, Review Please

#5173 10416 bug - cold case report permissions for general user
  shared/src/authorization/authorizationClientService.ts
Labels: to test

#5178 5512: Add Header for Spouse Info + Backmerge
  .circleci/config.yml
  Dockerfile
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-case-procedure-and-trial-location.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-irs-notice.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-stin.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-7-pay-filing-fee.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-an-electronic-petition.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/petition-helper.ts
  package-lock.json
  package.json
  shared/src/business/utilities/documentGenerators/generateAndVerifyPdfDiff.ts
  shared/src/business/utilities/pdfGenerator/components/PageMetaHeaderDocket.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
Labels: to test

#5184 5512: Update Generated Petition Markup + Cypress tests
  cypress/helpers/fileAPetition/create-and-serve-paper-petition.ts
  cypress/local-only/tests/integration/fileAPetition/petitions-clerk-creates-paper-case.cy.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.test.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/petition.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  shared/src/proxies/generatePetitionPdfProxy.ts
Labels: Do Not Merge, to test

#5183 10403 bug: rework modal for selecting a scanner
  web-client/src/presenter/computeds/scanHelper.test.ts
  web-client/src/presenter/computeds/scanHelper.ts
  web-client/src/views/ScanBatchPreviewer/SelectScannerSourceModal.tsx
Labels: to staging

#5171 10413: IRSPractitioner: Restrict Access to DOJ Employees
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/helpers/caseDetail/caseInformation/update-case-status.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/doj-practitioner-should-not-be-able-to-represent-case-for-non-appeal-cases.cy.ts
  scripts/user/setup-test-users.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/test/mockUsers.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/storage/fixtures/seed/users.json
  web-client/src/presenter/computeds/caseDetailHeaderHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: to staging

#5186 Update DAWSON-team-charter.md (feat. Jen Bertrand)
  docs/additional-resources/DAWSON-team-charter.md
Labels: to staging

#5188 5512: Fix minor PDF generation bug + Backmerge
  cypress/helpers/caseDetail/caseInformation/petitionsclerk-adds-respondent-to-case.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case-updated.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/batch-download-documents.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/stamp-order.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/doj-practitioner-should-not-be-able-to-represent-case-for-non-appeal-cases.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/petitioner-files-external-document.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/petitioner-files-motion-to-stay-proceedings.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/practitioner-request-access-to-case.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/paperFiling/docket-clerk-adds-paper-filing.cy.ts
  cypress/local-only/tests/integration/dashboard/petitioner-dashboard.cy.ts
  cypress/local-only/tests/integration/dashboard/private-practitioner-dashboard.cy.ts
  cypress/local-only/tests/integration/documentQC/assign-a-work-item-to-self.cy.ts
  cypress/local-only/tests/integration/documentQC/docket-clerk-qcs-paper-filing.cy.ts
  cypress/local-only/tests/integration/fileAPetition/file-a-petition.cy.ts
  cypress/local-only/tests/integration/fileAPetition/start-a-case-practitioner.cy.ts
  cypress/local-only/tests/integration/myAccount/respondent-modifies-contact-info.cy.ts
  scripts/user/setup-test-users.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/startCase/UploadPetitionStep2.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.test.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/proxies/generatePetitionPdfProxy.ts
  web-client/src/presenter/actions/formatPetitionAction.test.ts
  web-client/src/presenter/actions/formatPetitionAction.ts
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: Do Not Merge, to test

#5191 10431 bug: fix for bug in bug fix 10403
  web-client/src/presenter/actions/primeScannerSourceAction.test.ts
  web-client/src/presenter/actions/primeScannerSourceAction.ts
  web-client/src/views/ScanBatchPreviewer/SelectScannerSourceModal.tsx
Labels: to test, Review Please

#5192 Dep updates 25 jul24 totest
  .circleci/config.yml
  Dockerfile
  docker-to-ecr.sh
  docs/additional-resources/DAWSON-team-charter.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: to test

#5189 10426: DOJ Practitioners: Do Not Allow File First IRS Document
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/doj-practitioner-should-not-be-able-to-file-first-irs-document.cy.ts
  web-client/src/presenter/computeds/caseDetailHeaderHelper.ts
Labels: to staging, Review Please

#5196 10417 minimum changes intermediate branch to test 1722272276
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
Labels: to test

#5190 10431 bug: fix for bug within bug fix 10403
  web-client/src/presenter/actions/primeScannerSourceAction.test.ts
  web-client/src/presenter/actions/primeScannerSourceAction.ts
  web-client/src/views/ScanBatchPreviewer/SelectScannerSourceModal.tsx
Labels: to staging

#5155 Remove PII from seed and test data
  shared/src/business/entities/cases/Case.getOtherFilers.test.ts
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/entities/cases/PaperPetition.test.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/documents/DocumentSearch.test.ts
  shared/src/business/useCases/generateSignedDocumentInteractor.test.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/opinionAdvancedSearchInteractor.test.ts
  shared/src/business/useCases/orderAdvancedSearchInteractor.test.ts
  shared/src/business/useCases/removePdfFromDocketEntryInteractor.test.ts
  shared/src/business/useCases/saveSignedDocumentInteractor.test.ts
  shared/src/business/utilities/caseFilter.test.ts
  shared/src/business/utilities/documentGenerators/documentServiceEmail.test.ts
  shared/src/test/mockCase.ts
  shared/test-pdf-expected-images/Document_Service_Email.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes_Usin_New_Calendar_Props.pdf.1.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.2.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.3.png
  shared/test-pdf-expected-images/Standing_Pretrial_Order_For_Small_Case.pdf.4.png
  web-api/src/business/useCaseHelper/caseAssociation/associateIrsPractitionerToCase.test.ts
  web-api/src/business/useCaseHelper/stampDisposition/addDraftStampOrderDocketEntryInteractor.test.ts
  web-api/src/business/useCases/caseAssociation/updateCounselOnCaseInteractor.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/docketEntry/strikeDocketEntryInteractor.test.ts
  web-api/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  web-api/src/business/useCases/manualAssociation/associateIrsPractitionerWithCaseInteractor.test.ts
  web-api/src/business/useCases/manualAssociation/associatePrivatePractitionerWithCaseInteractor.test.ts
  web-api/src/business/useCases/messages/createMessageInteractor.test.ts
  web-api/src/business/useCases/messages/replyToMessageInteractor.test.ts
  web-api/src/business/useCases/public/opinionPublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/orderPublicSearchInteractor.test.ts
  web-api/src/business/useCases/user/getUsersPendingEmailInteractor.test.ts
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.test.ts
  web-api/src/persistence/dynamo/documents/updateDocketEntry.test.ts
  web-api/src/persistence/dynamo/users/getUsersById.test.ts
  web-api/src/persistence/elasticsearch/advancedDocumentSearch.test.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/docketClerkOrderAdvancedSearch.test.ts
  web-client/integration-tests/orderSearchJourneyDocketNumber.test.ts
  web-client/src/presenter/actions/CaseAssociation/submitEditRespondentCounselAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/createOrderAction.test.ts
  web-client/src/presenter/actions/DocketEntry/updateDocketEntryWizardDataAction.test.ts
  web-client/src/presenter/actions/EditDocketRecordEntry/strikeDocketEntryAction.test.ts
  web-client/src/presenter/actions/EditDocketRecordEntry/updateDocketEntryMetaAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/getCaseCaptionForCaseInfoTabAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/getFormContactPrimaryAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.test.ts
  web-client/src/presenter/actions/batchDownloadTrialSessionAction.test.ts
  web-client/src/presenter/actions/defaultRemoveFromTrialSessionModalValuesAction.test.ts
  web-client/src/presenter/actions/validatePetitionerAction.test.ts
  web-client/src/presenter/computeds/Public/todaysOpinionsHelper.test.ts
  web-client/src/presenter/computeds/Public/todaysOrdersHelper.test.ts
  web-client/src/presenter/computeds/editDocketEntryMetaHelper.test.ts
  web-client/src/presenter/computeds/formattedCaseDetail.test.ts
Labels: to staging
