Repository ustaxcourt/ef-cms, pull requests merged in 2024-05, with the labels that each got.

#4771 10249 fix pre epoch cases
  cypress/local-only/integration/customCaseReport/custom-case-report-csv-export.cy.ts
  shared/src/business/entities/customCaseReportSearch/CustomCaseReportSearch.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getCustomCaseReportAction.ts
  web-client/src/presenter/customCaseReportState.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to staging

#4880 Devex: Fix api gateway custom domain mapping in switch colors
  web-client/switch-api-colors.ts
  web-client/switch-colors.sh
  web-client/switch-public-api-colors.ts
Labels: to staging

#4884 10281 - Practitioner Search Upgrades
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  web-api/elasticsearch/efcms-user-mappings.ts
  web-api/src/lambdas/practitioners/getPractitionersByNameLambda.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.test.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-client/integration-tests/admissionsClerkPractitionerJourney.test.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionerByBarNumber.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionersByName.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
Labels: to test

#4865 Devex 10334 - AWS v2 -> v3 conversion: API Gateway also comes in an ApiGatewayV2 flavor
  env-destroy-utils/deleteCustomDomains.js
  env-destroy-utils/deleteCustomDomains.ts
  env-destroy-utils/destroyEnvironment.ts
  env-destroy-utils/getApiGateway.js
  env-destroy-utils/getApiGateway.ts
  env-destroy-utils/getCustomDomains.js
  env-destroy-utils/getCustomDomains.ts
  env-destroy-utils/sleep.js
  env-destroy-utils/sleep.ts
  package-lock.json
  package.json
Labels: to staging

#4868 Devex 10297 - AWS v2 -> v3 conversion: Stragglers
  package-lock.json
  package.json
  web-api/switch-bounce-handler-colors.js
  web-api/switch-bounce-handler-colors.ts
  web-api/switch-health-check-domain.ts
  web-client/switch-api-colors.helpers.ts
  web-client/switch-api-colors.ts
  web-client/switch-colors.sh
  web-client/switch-public-api-colors.ts
  web-client/switch-public-ui-colors.js
  web-client/switch-public-ui-colors.ts
  web-client/switch-ui-colors.helpers.ts
  web-client/switch-ui-colors.js
  web-client/switch-ui-colors.ts
Labels: to staging

#4879 Dependency Updates for 05-01-24
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/runtimes/puppeteer/web-api/runtimes/puppeteer/package-lock.json
  web-client/src/views/FileUploadErrorModal.tsx
Labels: to staging

#4874 10358: add unit test to ensure multiple chunks over chunk size
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
Labels: to staging, to merge

#4896 Reduce throttling when creating test users. Create serially instead of parallel.
  scripts/user/setup-test-users.ts
Labels: to staging, Review Please

#4897 Smoketests Fix: Wait for OpenSearch to index newly created practitioner before searching for them
  .eslintrc.js
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
Labels: to staging

#4902 10281 story
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  web-api/elasticsearch/efcms-user-mappings.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/practitioners/getPractitionersByNameLambda.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.test.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-api/src/persistence/elasticsearch/searchClient.test.constants.ts
  web-api/src/persistence/elasticsearch/searchClient.test.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-client/integration-tests/admissionsClerkPractitionerJourney.test.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionerByBarNumber.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionersByName.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/CaseDetail/AddIrsPractitionerModal.tsx
  web-client/src/views/CaseDetail/AddPrivatePractitionerModal.tsx
Labels: to test, Mappings Change(s)

#4904 10361 deactivate colvin option2 intermediate branch to test 1715352201
  cypress/helpers/trialSession/petitionsclerk-creates-trial-session.ts
  cypress/local-only/integration/trialSession/petitions-clerk-verify-chamber-phone-auto-fills.cy.ts
  scripts/circleci/judge/judge_users.csv
  scripts/user/add-user.ts
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to test

#4908 Update docket entry flag missing
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
Labels: bugfix, to test

#4900 Dependencies update for 05-13-2024
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: dependencies, to staging, Review Please

#4914 10380: revert temporary fix for test
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
Labels: to test

#4892 Devex: Upgrade Github Action Helper Packages
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/e2e-pa11y-public.yml
  .github/workflows/e2e-pa11y.yml
  .github/workflows/shared.yml
  docs/ci-cd.md
  docs/flaky-tests.md
Labels: to staging

#4913 10381: Add correct environment variable for irs user pool id
  web-api/src/environment.ts
  web-api/src/lambdas/cognitoAuthorizer/createAuthorizer.ts
  web-api/terraform/applyables/green/green.tf
Labels: to staging, Review Please

#4915 10281 story intermediate branch to test 1715724279
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
Labels: to test

#4905 10294 - hide PDF icon in FileDocumentReview component
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/PDFPreviewButton.tsx
Labels: to test

#4919 10381 story
  .circleci/config.yml
  package-lock.json
  package.json
  web-api/hostedEnvironmentTests/irsSuperUser.test.ts
  web-api/hostedEnvironmentTests/jest-hosted-environment.ts
  web-api/jest-unit.config.ts
  web-api/src/environment.ts
Labels: to test, Review Please

#4903 10361: Deactivate Judge Colvin in deployed envs
  cypress/helpers/trialSession/petitionsclerk-creates-trial-session.ts
  cypress/local-only/integration/trialSession/petitions-clerk-verify-chamber-phone-auto-fills.cy.ts
  docs/operations/runbooks/offboard-judge-user.md
  docs/operations/runbooks/runbook-template.md
  scripts/circleci/judge/judge_users.csv
  scripts/user/add-user.ts
  scripts/user/disable-cognito-user.sh
  scripts/user/offboard-judge-user.sh
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to staging, Manual Deploy Step(s) Required

#4918 10290: design debt
  shared/src/business/entities/cases/Case.ts
Labels: to test, Review Please

#4883 10284: Make all state select (dropdowns) use full name for us states and other states.
  web-client/src/views/StartCase/Address.tsx
  web-client/src/views/StartCase/StateSelect.tsx
Labels: to staging, to merge

#4917 10355: design debt
  web-client/src/views/CaseDetail/CaseInformationExternal.tsx
  web-client/src/views/CaseListTable.tsx
Labels: to test, Review Please

#4916 10383: Create script to verify email addresses that should be verified.
  scripts/run-once-scripts/cognitoUserIdAndEmailMigration.ts
  scripts/run-once-scripts/verifyLowerCasedCognitoUsers.ts
Labels: to staging, Manual Deploy Step(s) Required, to merge

#4923 10381 Bug: IRS User Pool Cannot Authenticate
  .circleci/config.yml
  package-lock.json
  package.json
  web-api/hostedEnvironmentTests/irsSuperUser.test.ts
  web-api/hostedEnvironmentTests/jest-hosted-environment.ts
  web-api/jest-unit.config.ts
  web-api/src/environment.ts
Labels: to staging, to merge

#4907 Devex: Deploy Table Clean Up
  cypress/readonly/integration/public/advanced-search.cy.ts
  scripts/dynamo/setup-add-docket-numbers-to-orders-flag.sh
  scripts/dynamo/setup-use-layers-state.sh
  scripts/run-once-scripts/remove-node-version-records.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/workflow-terraform/migration/main/lambdas/migrations/0001-add-associated-judge-id.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0001-add-associated-judge-id.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0002-change-employer-to-practice-type.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migrations/0002-change-employer-to-practice-type.ts
  web-api/workflow-terraform/migration/main/lambdas/migrationsToRun.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.ts
  web-client/src/presenter/actions/setupCurrentPageAction.test.ts
  web-client/src/presenter/computeds/createOrderHelper.test.ts
  web-client/src/presenter/computeds/createOrderHelper.ts
Labels: to staging, Manual Deploy Step(s) Required, to merge

#4933 Backmerge `staging` into `test`
  cypress/readonly/integration/public/advanced-search.cy.ts
  docs/operations/runbooks/offboard-judge-user.md
  docs/operations/runbooks/runbook-template.md
  package-lock.json
  package.json
  scripts/dynamo/setup-add-docket-numbers-to-orders-flag.sh
  scripts/run-once-scripts/cognitoUserIdAndEmailMigration.ts
  scripts/run-once-scripts/remove-node-version-records.sh
  scripts/run-once-scripts/verifyLowerCasedCognitoUsers.ts
  scripts/user/disable-cognito-user.sh
  scripts/user/offboard-judge-user.sh
  shared/src/business/entities/EntityConstants.ts
  web-api/src/environment.ts
  web-api/src/lambdas/migration/migrations/0001-add-associated-judge-id.test.ts
  web-api/src/lambdas/migration/migrations/0001-add-associated-judge-id.ts
  web-api/src/lambdas/migration/migrations/0002-change-employer-to-practice-type.test.ts
  web-api/src/lambdas/migration/migrations/0002-change-employer-to-practice-type.ts
  web-api/src/lambdas/migration/migrationsToRun.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.ts
  web-client/src/presenter/actions/setupCurrentPageAction.test.ts
  web-client/src/presenter/computeds/createOrderHelper.test.ts
  web-client/src/presenter/computeds/createOrderHelper.ts
Labels: to test

#4930 (OpEx) Report: Total cases open on a specific day of the year in each of the last 5 years
  scripts/reports/cases-open-on-date.ts
Labels: to staging

#4941 10385 irs stin download to TEST
  scripts/reports/cases-open-on-date.ts
  scripts/user/disable-cognito-user.sh
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
Labels: to test

#4940 10354: design debt
  web-client/src/views/TrialSessionDetail/AllCases.tsx
  web-client/src/views/TrialSessionDetail/EligibleCases.tsx
  web-client/src/views/TrialSessionDetail/OpenCases.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
Labels: to test

#4938 10290: design debt
  shared/src/business/entities/cases/Case.ts
Labels: to test

#4845 10281 story
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionersByNameInteractor.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  web-api/elasticsearch/efcms-user-mappings.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/practitioners/getPractitionersByNameLambda.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.test.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-api/src/persistence/elasticsearch/searchClient.test.constants.ts
  web-api/src/persistence/elasticsearch/searchClient.test.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-client/integration-tests/admissionsClerkPractitionerJourney.test.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionerByBarNumber.ts
  web-client/integration-tests/journey/admissionsClerkSearchesForPractitionersByName.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/CaseDetail/AddIrsPractitionerModal.tsx
  web-client/src/views/CaseDetail/AddPrivatePractitionerModal.tsx
Labels: to staging, Mappings Change(s)

#4929 10330: design debt
  web-client/src/presenter/actions/setTodaysDateAction.test.ts
  web-client/src/presenter/actions/setTodaysDateAction.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.test.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.ts
  web-client/src/presenter/sequences/openCreateCaseDeadlineModalSequence.ts
  web-client/src/presenter/sequences/openEditCaseDeadlineModalSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedNonstandardForm.tsx
Labels: to test

#4942 10289: design debt
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
  web-client/src/views/FileDocument/SecondaryDocumentForm.tsx
  web-client/src/views/FileDocument/SecondarySupportingDocumentForm.tsx
  web-client/src/views/FileDocument/SupportingDocumentForm.tsx
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
Labels: to test

#4949 10294: design debt update
  web-client/src/views/PDFPreviewButton.tsx
Labels: to test

#4955 10263 story intermediate branch to test 1716302694
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/integration/documentQC/stin-visible-during-docket-qc.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
  shared/src/business/entities/cases/Case.ts
  web-client/src/presenter/computeds/formattedWorkQueue.getWorkItemDocumentLink.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
Labels: to test

#4956 10350 story intermediate branch to test 1716318473
  web-client/src/presenter/sequences/reviewExternalDocumentInformationSequence.ts
Labels: to test

#4951 10386 practitioner count bugfix
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
Labels: to test

#4957 10386 - (To Test) Practitioner Count Bugfix
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
Labels: to test

#4952 10355: design debt
  web-client/src/views/CaseDetail/CaseInformationExternal.tsx
  web-client/src/views/CaseListTable.tsx
Labels: to staging

#4954 10290: design debt
  shared/src/business/entities/cases/Case.ts
Labels: to staging

#4976 Devex manual deploys to test
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  docs/testing.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to test

#4950 10263: Allow Case Services Supervisor to see STIN during QC
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/integration/documentQC/stin-visible-during-docket-qc.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
  shared/src/business/entities/cases/Case.ts
  web-client/src/presenter/computeds/formattedWorkQueue.getWorkItemDocumentLink.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
Labels: to staging

#4971 10374 - fixing issue with indeterminate related to undefined dom element
  web-client/src/views/DocketRecord/DocketRecord.tsx
Labels: to staging, Review Please

#4968 Make Deploys manual
  .circleci/config.yml
Labels: to staging

#4983 10288: design debt
  web-client/src/views/TrialSessions/EditTrialSession.tsx
Labels: to staging

#4984 10289: design debt
  web-client/src/views/FileDocument/PrimaryDocumentForm.tsx
  web-client/src/views/FileDocument/SecondaryDocumentForm.tsx
  web-client/src/views/FileDocument/SecondarySupportingDocumentForm.tsx
  web-client/src/views/FileDocument/SupportingDocumentForm.tsx
  web-client/src/views/RequestAccess/RequestAccessDocumentForm.tsx
Labels: to staging

#4986 10350 story intermediate branch to test 1717099843
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/file-an-answer.cy.ts
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/irs-practitioner-files-entry-of-appearance-as-first-irs-doc.cy.ts
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/private-practitioner-files-external-document.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/cases/Case.isFirstIrsFiling.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/formattedWorkQueue.ts
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/PartiesFiling.tsx
Labels: to test

#4925 10350: Enable IRS Practitioners to file EA as First IRS Document on a case
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/file-an-answer.cy.ts
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/irs-practitioner-files-entry-of-appearance-as-first-irs-doc.cy.ts
  cypress/local-only/integration/caseDetail/docketRecord/electronicFiling/private-practitioner-files-external-document.cy.ts
  shared/src/business/entities/cases/Case.isFirstIrsFiling.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/tools/externalFilingEvents.json
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.test.ts
  web-client/src/presenter/actions/FileDocument/navigateToReviewFileADocumentAction.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDefaultFileDocumentFormValuesAction.ts
  web-client/src/presenter/actions/FileDocument/setDocumentFileForAutoGeneratedEntryOfAppearanceAction.test.ts
  web-client/src/presenter/actions/FileDocument/setDocumentFileForAutoGeneratedEntryOfAppearanceAction.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/sequences/reviewExternalDocumentInformationSequence.ts
  web-client/src/presenter/sequences/submitExternalDocumentSequence.ts
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/FileDocument/FileDocument.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/FileEntryOfAppearanceReview.tsx
  web-client/src/views/FileDocument/PartiesFiling.tsx
  web-client/src/views/FileDocument/PrimaryDocumentGeneratedTypeForm.tsx
  web-client/src/views/FileDocument/StateDrivenFileInput.tsx
Labels: to staging

#4946 10386 - Practitioner Count Bugfix
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
Labels: to staging

#4978 10387 irs superuser test
  cypress-smoketests.config.ts
  cypress/deployed-and-local/integration/irsSuperUser/irs-super-user-can-download-stin.cy.ts
  cypress/helpers/cypressTasks/cognito/cognito-helpers.ts
Labels: to test
