Repository ustaxcourt/ef-cms, pull requests merged in 2024-03, with the labels that each got.

#4692 10216 missing previous document refactor2 to test
  shared/src/business/entities/DocketEntry.isPublic.test.ts
  shared/src/business/entities/DocketEntry.ts
Labels: to test

#4672 Dep updates 2024 02 22
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-client/src/ustc-ui/Hint/Hint.tsx
Labels: to staging

#4654 Devex 1218: Tracking migration status on glued data
  .circleci/config.yml
  docs/backend.md
  docs/migrations.md
  scripts/run-once-scripts/move-migration-records-to-main-table.ts
  setup-for-blue-green-migration.sh
  web-api/is-migration-needed.js
  web-api/track-successful-migrations.js
  web-api/workflow-terraform/migration/bin/is-migration-needed.ts
  web-api/workflow-terraform/migration/bin/migrationFilesHelper.ts
  web-api/workflow-terraform/migration/bin/track-successful-migrations.ts
Labels: to staging, Manual Deploy Step(s) Required

#4699 10260: 504 fix for large files
  shared/src/business/useCases/addCoverToPdf.ts
  shared/src/business/useCases/getCoversheetInteractor.test.ts
  shared/src/business/useCases/getCoversheetInteractor.ts
  shared/src/business/useCases/updateDocketEntriesPostCoversheetInteractor.test.ts
  shared/src/business/useCases/updateDocketEntriesPostCoversheetInteractor.ts
  shared/src/proxies/getCoversheetProxy.ts
  shared/src/proxies/updateDocketEntriesPostCoversheetProxy.ts
  web-api/src/app.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/cases/updateDocketEntriesPostCoversheetLambda.ts
  web-api/src/lambdas/documents/getCoversheetLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/DocketEntry/generateCoversheetAction.test.ts
  web-client/src/presenter/actions/DocketEntry/generateCoversheetAction.ts
Labels: bugfix, to test

#4706 10249: Export Custom Case Report to Excel-Friendly Format
  cypress.config.ts
  cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/database.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/formatCustomCaseReportDataForCsvAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/formatCustomCaseReportDataForCsvAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/getAllCustomCaseReportDataAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getAllCustomCaseReportDataAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.ts
  web-client/src/presenter/computeds/batchDownloadHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/exportCsvCustomCaseReportSequence.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to test

#4693 Devex: Quickly create temporary ES indices for one-off queries
  docs/additional-resources/temporary-elasticsearch-indices.md
  scripts/elasticsearch/create-temporary-indices-helpers.ts
  scripts/elasticsearch/create-temporary-indices.test.ts
  scripts/elasticsearch/create-temporary-indices.ts
  scripts/elasticsearch/reindex.helpers.test.ts
  scripts/elasticsearch/reindex.helpers.ts
  scripts/jest-scripts.config.ts
Labels: to staging

#4701 Opex: trial sessions by fiscal year report
  package.json
  scripts/reports/practitioner-stats.ts
  scripts/reports/trial-sessions-by-calendar-year.ts
  scripts/reports/trial-sessions-by-fiscal-year.ts
  scripts/reports/trial-sessions-by-year.ts
  scripts/reports/trial-sessions-report-helpers.test.ts
  scripts/reports/trial-sessions-report-helpers.ts
Labels: to staging

#4707 10270: BUG: Email sent verification
  .eslintrc.js
  cypress-smoketests.config.ts
  cypress/cypress-smoketests/integration/verify-email-receipt.cy.ts
  cypress/cypress-smoketests/support/email-receipt.ts
  iam/terraform/account-specific/main/ses.tf
  package.json
  scripts/run-cypress.sh
  scripts/ses/get-ses-ruleset.sh
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/main-west.tf
  web-api/terraform/template/s3.tf
  web-api/terraform/template/ses.tf
  web-api/terraform/template/variables.tf
  webpack.config.lambda.rotate-info-indices.ts
Labels: to test, Needs Account Specific

#4715 Do not rethrow or log axios errors when passing sensitive info
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.ts
  scripts/circleci/judge/bulkImportJudgeUsers.ts
  shared/admin-tools/user/admin.ts
Labels: to staging

#4723 10249 : Add debugging logs to export feature
  cypress.config.ts
  cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/database.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/formatCustomCaseReportDataForCsvAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/formatCustomCaseReportDataForCsvAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/getAllCustomCaseReportDataAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/getAllCustomCaseReportDataAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.ts
  web-client/src/presenter/computeds/batchDownloadHelper.ts
  web-client/src/presenter/computeds/dashboardExternalHelper.test.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/exportCsvCustomCaseReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to test

#4730 10249 Move logic to backend
  cypress.config.ts
  cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/database.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.test.ts
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  shared/src/proxies/customCaseReport/createCsvCustomCaseReportFileProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/reports/createCsvCustomCaseReportFileLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.test.ts
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.ts
  web-client/src/presenter/actions/CsvFiles/downloadCsvFileAction.test.ts
  web-client/src/presenter/actions/CsvFiles/downloadCsvFileAction.ts
  web-client/src/presenter/actions/Public/submitPublicOpinionAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/setCaseDetailPageTabActionGenerator.test.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.test.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.ts
  web-client/src/presenter/computeds/batchDownloadHelper.ts
  web-client/src/presenter/computeds/draftDocumentViewerHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.filterFormattedSessionsByStatus.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.filterWorkItems.test.ts
  web-client/src/presenter/computeds/myAccountHelper.test.ts
  web-client/src/presenter/computeds/scanBatchPreviewerHelper.test.ts
  web-client/src/presenter/computeds/sealedCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/startCaseHelper.test.ts
  web-client/src/presenter/computeds/trialCitiesHelper.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.caseNotes.test.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/downloadCsvFileSequence.ts
  web-client/src/presenter/sequences/exportCsvCustomCaseReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/providers/socketRouter.test.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to test

#4732 10264: enable preserveWhitespaceOption
  web-client/src/views/CreateOrder/TextEditor.tsx
Labels: to test

#4734 10249: Fix asyn path
  shared/src/proxies/customCaseReport/createCsvCustomCaseReportFileProxy.ts
  web-api/src/app.ts
Labels: to test

#4736 10249: Fix mismatch count of records
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-client/src/presenter/computeds/batchDownloadHelper.test.ts
  web-client/src/presenter/computeds/batchDownloadHelper.ts
Labels: Do Not Merge, to test

#4740 10007: add temporary handling for users attempting to use the old Cognito hosted UI
  shared/src/proxies/auth/logOldLoginAttemptProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/logOldLoginAttemptInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/auth/oldLoginAttemptLambda.ts
  web-api/terraform/template/cognito.tf
  web-client/pa11y/pa11y-ci.base-config.js
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/Login/logOldLoginAttemptAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Login/gotoOldLoginSequence.ts
  web-client/src/router.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/OldLogin.tsx
Labels: to staging

#4750 10007: remove maintenance mode from deploy steps, re-enable smoketests
  .circleci/config.yml
Labels: to staging

#4749 Backmerge staging into test
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  docs/running-locally.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
Labels: to test

#4731 10264: enabled preserveWhitespaceOption
  web-client/src/views/CreateOrder/TextEditor.tsx
Labels: to staging

#4757 Fix Recurring Issue with Cognito Local File Formatting
  .cognito/config.json
  .cognito/db/clients.json
Labels: to staging

#4753 10315: Forgot password ignore leading or trailing spaces on code
  cypress/cypress-integration/integration/forgot-password.cy.ts
  web-client/src/presenter/actions/Login/submitChangePasswordAction.tsx
Labels: to staging

#4754 10270: back to test
  .eslintrc.js
  cypress-smoketests.config.ts
  cypress.config.ts
  cypress/cypress-smoketests/integration/verify-email-receipt.cy.ts
  cypress/cypress-smoketests/support/email-receipt.ts
  iam/terraform/account-specific/main/ses.tf
  scripts/run-cypress.sh
  scripts/ses/get-ses-ruleset.sh
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/s3.tf
  web-api/terraform/template/ses.tf
  web-api/terraform/template/variables.tf
Labels: to test

#4763 10270: update email string match with new verbiage
  cypress/cypress-smoketests/integration/verify-email-receipt.cy.ts
Labels: to test

#4759 10249 export custom case report
  cypress.config.ts
  cypress/cypress-integration/integration/custom-case-report-csv-export.cy.ts
  cypress/cypress-integration/support/commands.ts
  cypress/cypress-integration/support/database.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.test.ts
  shared/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  shared/src/proxies/customCaseReport/createCsvCustomCaseReportFileProxy.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/reports/createCsvCustomCaseReportFileLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.test.ts
  web-client/src/presenter/actions/BatchDownload/updateBatchDownloadProgressAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/createCsvCustomCaseReportFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/exportCsvFileAction.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.test.ts
  web-client/src/presenter/actions/CaseInventoryReport/setCustomCaseReportBatchDownloadAction.ts
  web-client/src/presenter/actions/CsvFiles/downloadCsvFileAction.test.ts
  web-client/src/presenter/actions/CsvFiles/downloadCsvFileAction.ts
  web-client/src/presenter/actions/Public/submitPublicOpinionAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/setCaseDetailPageTabActionGenerator.test.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.test.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.ts
  web-client/src/presenter/computeds/batchDownloadHelper.test.ts
  web-client/src/presenter/computeds/batchDownloadHelper.ts
  web-client/src/presenter/computeds/draftDocumentViewerHelper.test.ts
  web-client/src/presenter/computeds/fileDocumentHelper.test.ts
  web-client/src/presenter/computeds/formattedTrialSessions.filterFormattedSessionsByStatus.test.ts
  web-client/src/presenter/computeds/formattedWorkQueue.filterWorkItems.test.ts
  web-client/src/presenter/computeds/myAccountHelper.test.ts
  web-client/src/presenter/computeds/scanBatchPreviewerHelper.test.ts
  web-client/src/presenter/computeds/sealedCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/startCaseHelper.test.ts
  web-client/src/presenter/computeds/trialCitiesHelper.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.caseNotes.test.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/downloadCsvFileSequence.ts
  web-client/src/presenter/sequences/exportCsvCustomCaseReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/providers/socketRouter.test.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/TrialSessionWorkingCopy/BatchDownloadProgress.tsx
Labels: to staging

#4767 Devex: fix for stuck migrations
  web-api/workflow-terraform/migration/main/lambdas/migration.test.ts
  web-api/workflow-terraform/migration/main/lambdas/migration.ts
Labels: to staging

#4777 10068 back to test
  shared/src/proxies/documents/batchDownloadDocketEntriesProxy.ts
  web-api/src/app.ts
  web-api/src/lambdas/documents/batchDownloadDocketEntriesLambda.ts
  web-client/src/presenter/actions/StampMotion/validateStampAction.test.ts
  web-client/src/presenter/computeds/orderTypesHelper.test.ts
  web-client/src/views/DownloadDocketEntriesModal.tsx
Labels: to test

#4778 10321: do not preserve whitespace when copying into quill
  web-client/src/views/CreateOrder/TextEditor.tsx
Labels: to test

#4781 10260: Update Terraform template to pass ID to Lambda
  web-api/terraform/api/api-async.tf
Labels: bugfix, to test

#4784 Downgrade USWDS to 3.7.1
  package-lock.json
  package.json
Labels: to staging

#4787 10223 Bug: Validation error messages are not triggering appropriately when docket clerk adds paper filing
  cypress/cypress-integration/integration/consolidated-case.cy.ts
  cypress/cypress-integration/integration/docket-clerk-paper-filing.cy.ts
  cypress/cypress-integration/integration/petitioner-files-external-document.cy.ts
  cypress/cypress-integration/integration/stamp-order.cy.ts
  cypress/cypress-integration/support/pages/create-paper-petition.ts
  cypress/helpers/create-and-serve-paper-filing.ts
  cypress/helpers/create-and-serve-paper-petition.ts
  web-client/integration-tests/docketClerkSavesAndEditsPaperFiling.test.ts
  web-client/integration-tests/journey/docketClerkEditsPaperFiledDocketEntryFromQC.ts
  web-client/src/presenter/sequences/openConfirmPaperServiceModalSequence.ts
  web-client/src/views/PaperFiling/PaperFiling.tsx
  web-client/src/views/PaperFiling/PrimaryDocumentForm.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueue.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInProgress.tsx
Labels: to staging

#4717 10270: email sent verification
  .eslintrc.js
  cypress-smoketests.config.ts
  cypress.config.ts
  cypress/cypress-smoketests/integration/verify-email-receipt.cy.ts
  cypress/cypress-smoketests/support/email-receipt.ts
  iam/terraform/account-specific/main/ses.tf
  scripts/run-cypress.sh
  scripts/ses/get-ses-ruleset.sh
  web-api/terraform/bin/deploy-app.sh
  web-api/terraform/main/main.tf
  web-api/terraform/main/variables.tf
  web-api/terraform/template/main-east.tf
  web-api/terraform/template/s3.tf
  web-api/terraform/template/ses.tf
  web-api/terraform/template/variables.tf
Labels: to staging, Needs Account Specific

#4786 10260: Remove usage of WebSockets and use HTTP polling against DB
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/notifications/saveRequestResponse.test.ts
  shared/src/notifications/saveRequestResponse.ts
  shared/src/proxies/polling/startPollingForResultsProxy.test.ts
  shared/src/proxies/polling/startPollingForResultsProxy.ts
  shared/src/proxies/requests.test.ts
  shared/src/proxies/requests.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.test.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/lambdas/polling/startPollingForResultsLambda.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.test.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.ts
  web-client/integration-tests/caseServicesSupervisorJourney.test.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/resolveAsyncSyncRequestAction.test.ts
  web-client/src/presenter/actions/resolveAsyncSyncRequestAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/resolveAsyncSyncRequestSequence.ts
  web-client/src/providers/socketRouter.test.ts
  web-client/src/providers/socketRouter.ts
Labels: to test

#4796 10068 story
  shared/src/business/entities/cases/Case.ts
  shared/src/business/useCases/document/batchDownloadDocketEntriesInteractor.test.ts
  shared/src/business/useCases/document/batchDownloadDocketEntriesInteractor.ts
  web-client/integration-tests/permissions.test.ts
Labels: to staging
