Repository ustaxcourt/ef-cms, pull requests merged in 2024-08, with the labels that each got.

#5198 10349 bug intermediate branch to test 1722427896
  cypress.config.ts
  cypress/CYPRESS-README.md
  cypress/helpers/ITestableWindow.ts
  cypress/local-only/support/idleLogoutHelpers.ts
  cypress/local-only/support/index.ts
  cypress/local-only/tests/integration/logoutBehavior/idle-logout.cy.ts
  package-lock.json
  package.json
  shared/src/business/entities/EntityConstants.ts
  web-client/src/AppInstanceManager.tsx
  web-client/src/app.tsx
  web-client/src/presenter/actions/Login/navigateToLoginAction.test.ts
  web-client/src/presenter/actions/broadcastIdleStatusActiveAction.test.ts
  web-client/src/presenter/actions/broadcastIdleStatusActiveAction.ts
  web-client/src/presenter/actions/broadcastLogoutAction.test.ts
  web-client/src/presenter/actions/broadcastLogoutAction.ts
  web-client/src/presenter/actions/broadcastStayLoggedInAction.test.ts
  web-client/src/presenter/actions/broadcastStayLoggedInAction.ts
  web-client/src/presenter/actions/clearLogoutTypeAction.test.ts
  web-client/src/presenter/actions/clearLogoutTypeAction.ts
  web-client/src/presenter/actions/handleIdleLogoutAction.test.ts
  web-client/src/presenter/actions/handleIdleLogoutAction.ts
  web-client/src/presenter/actions/handlePeerResetIdleTimerAction.test.ts
  web-client/src/presenter/actions/handlePeerResetIdleTimerAction.ts
  web-client/src/presenter/actions/isLoggedInAction.test.ts
  web-client/src/presenter/actions/isLoggedInAction.ts
  web-client/src/presenter/actions/resetIdleTimerAction.test.ts
  web-client/src/presenter/actions/resetIdleTimerAction.ts
  web-client/src/presenter/actions/setLogoutTypeAction.test.ts
  web-client/src/presenter/actions/setLogoutTypeAction.ts
  web-client/src/presenter/computeds/showAppTimeoutModalHelper.test.ts
  web-client/src/presenter/computeds/showAppTimeoutModalHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoIdleLogoutSequence.ts
  web-client/src/presenter/sequences/handleIdleLogoutSequence.ts
  web-client/src/presenter/sequences/signOutIdleSequence.ts
  web-client/src/presenter/sequences/signOutSequence.ts
  web-client/src/presenter/sequences/signOutUserInitiatedSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/views/AppTimeoutModal.tsx
  web-client/src/views/Header/AccountMenu.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/IdleActivityMonitor.tsx
  web-client/src/views/IdleLogout.tsx
Labels: to test

#5093 Devex 10415: AWS v2 -> v3 conversion: ApiGatewayManagementApiClient
  package-lock.json
  package.json
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/maintenance/sendMaintenanceNotificationsInteractor.ts
  web-api/src/notifications/getNotificationClient.ts
  web-api/src/notifications/retrySendNotificationToConnections.test.ts
  web-api/src/notifications/retrySendNotificationToConnections.ts
  web-api/src/notifications/sendNotificationToConnection.test.ts
  web-api/src/notifications/sendNotificationToConnection.ts
  web-api/src/notifications/sendNotificationToUser.test.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/persistence/dynamo/notifications/getAllWebSocketConnections.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.ts
Labels: to staging

#5142 10425 - 10417 Remove Get CurrentUser minimum changes
  package-lock.json
  package.json
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/authUser/AuthUser.test.ts
  shared/src/business/entities/authUser/AuthUser.ts
  shared/src/business/entities/cases/Case.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/getCaseInteractor.ts
  shared/src/test/mockAuthUsers.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.test.ts
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/business/useCases/maintenance/sendMaintenanceNotificationsInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionerByBarNumberInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/genericHandler.test.ts
  web-api/src/genericHandler.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/lambdas/cases/checkForReadyForTrialCasesLambda.ts
  web-api/src/lambdas/cases/sealInLowerEnvironmentLambda.ts
  web-api/src/lambdas/cases/sendMaintenanceNotificationsLambda.ts
  web-api/src/lambdas/notifications/disconnectLambda.ts
  web-api/src/lambdas/public-api/casePublicSearchLambda.ts
  web-api/src/lambdas/public-api/generatePublicDocketRecordPdfLambda.ts
  web-api/src/lambdas/public-api/getCaseForPublicDocketSearchLambda.ts
  web-api/src/lambdas/public-api/getPublicCaseExistsLambda.ts
  web-api/src/lambdas/public-api/getPublicCaseLambda.ts
  web-api/src/lambdas/public-api/getPublicDocumentDownloadUrlLambda.ts
  web-api/src/lambdas/public-api/getPublicJudgesLambda.ts
  web-api/src/lambdas/public-api/opinionPublicSearchLambda.ts
  web-api/src/lambdas/public-api/orderPublicSearchLambda.ts
  web-api/src/lambdas/public-api/todaysOpinionsLambda.ts
  web-api/src/lambdas/public-api/todaysOrdersLambda.ts
  web-api/src/lambdas/reports/getCustomCaseReportLambda.ts
  web-api/src/lambdas/v1/getCaseLambda.test.ts
  web-api/src/lambdas/v1/getDocumentDownloadUrlLambda.test.ts
  web-api/src/lambdas/v2/getCaseLambda.test.ts
  web-api/src/lambdas/v2/getDocumentDownloadUrlLambda.test.ts
  web-api/src/middleware/apiGatewayHelper.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-api/src/middleware/slowDownLimiter.test.ts
  web-api/src/middleware/slowDownLimiter.ts
  web-api/src/notifications/getNotificationClient.ts
  web-api/src/notifications/retrySendNotificationToConnections.test.ts
  web-api/src/notifications/retrySendNotificationToConnections.ts
  web-api/src/notifications/sendNotificationToConnection.test.ts
  web-api/src/notifications/sendNotificationToConnection.ts
  web-api/src/notifications/sendNotificationToUser.test.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/persistence/dynamo/notifications/getAllWebSocketConnections.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.ts
Labels: to staging

#5201 10438: Case Caption Information Printing as Black
  web-client/src/styles/print.scss
Labels: to staging

#5205 Devex 10415: AWS v2 -> v3 conversion: ApiGatewayManagementApiClient
  scripts/enable-http-traffic-on-deploying-color.sh
  web-api/src/business/useCases/notifications/onConnectInteractor.test.ts
  web-api/src/business/useCases/notifications/onConnectInteractor.ts
  web-api/src/notifications/retrySendNotificationToConnections.ts
Labels: to staging

#5213 Devex: Remove AWS SDK v2 from package.json
  env-destroy-utils/clearS3Buckets.js
  env-destroy-utils/clearS3Buckets.test.js
  env-destroy-utils/clearS3Buckets.test.ts
  env-destroy-utils/clearS3Buckets.ts
  env-destroy-utils/deleteCloudWatchLogs.js
  env-destroy-utils/deleteCloudWatchLogs.ts
  env-destroy-utils/getCloudWatch.js
  env-destroy-utils/getCloudWatch.ts
  env-destroy-utils/getS3.js
  env-destroy-utils/getS3.ts
  env-destroy-utils/getS3Buckets.js
  env-destroy-utils/getS3Buckets.ts
  package-lock.json
  package.json
  web-api/src/app-local.ts
Labels: to staging, Review Please

#5216 Remove deprecated lines from husky pre-commit
  .husky/pre-commit
Labels: to staging

#5218 5512 test updates feedback
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-all-steps.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/petition-helper.ts
  shared/src/business/entities/startCase/GeneratePetitionPdf.ts
  shared/src/business/entities/startCase/IrsNoticeForm.test.ts
  shared/src/business/entities/startCase/IrsNoticeForm.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.test.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/petition.ts
  shared/src/proxies/generatePetitionPdfProxy.ts
  web-client/src/presenter/actions/generatePetitionPdfAction.test.ts
  web-client/src/presenter/actions/generatePetitionPdfAction.ts
Labels: to test

#5219 10441 to test
  scripts/circleci/judge/judge_users.csv
  scripts/run-once-scripts/add-new-judge.ts
  scripts/run-once-scripts/promote-special-trial-judge.ts
  scripts/user/add-user.ts
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to test

#5226 Remove aws-v2 sdk entirely
  scripts/user/setup-glued-judges.ts
  web-api/elasticsearch/client.ts
  web-api/src/applicationContext.ts
Labels: to test

#5217 10441-story: Adding Judge Way and updating Judge Landy
  scripts/circleci/judge/judge_users.csv
  scripts/run-once-scripts/add-new-judge.ts
  scripts/run-once-scripts/promote-special-trial-judge.ts
  scripts/user/add-user.ts
  web-client/src/business/chambers/getJudgesChambers.ts
Labels: to staging, Manual Deploy Step(s) Required

#5221 10396-story: Fix a11y nested-interactive issue
  cypress/local-only/support/generalCommands/checkA11y.ts
  cypress/local-only/support/pages/create-paper-petition.ts
  cypress/local-only/tests/integration/caseDetail/notes/judges-notes-icon.cy.ts
  cypress/local-only/tests/integration/fileAPetition/petitions-clerk-creates-paper-case.cy.ts
  cypress/local-only/tests/integration/trialSession/trial-session-paper-pdf.cy.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/tabs.scss
  web-client/src/ustc-ui/Tabs/Tabs.test.tsx
  web-client/src/ustc-ui/Tabs/Tabs.tsx
Labels: to staging, Review Please

#5227 Remove aws-sdk v2 Entirely
  scripts/user/setup-glued-judges.ts
  web-api/elasticsearch/client.ts
  web-api/src/applicationContext.ts
Labels: to staging

#5232 10433-design-debt
  web-client/src/presenter/computeds/caseDetailHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHelper.ts
Labels: to test

#5237 10458 devex: fix favicon pattern matching
  esbuildHelper.mjs
Labels: to test, Review Please

#5225 10339: Practitioner petition generation
  cypress/deployed-and-local/integration/caseDetail/parties/admissions-clerk-grants-e-access.cy.ts
  cypress/deployed-and-local/integration/caseDetail/parties/admissions-clerk-updates-practitioner-email.cy.ts
  cypress/helpers/fileAPetition/practitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/electronicFiling/logged-in-user-can-see-un-served-petition-document.cy.ts
  cypress/local-only/tests/integration/fileAPetition/start-a-case-practitioner.cy.ts
  shared/src/business/entities/contacts/ContactUpdated.test.ts
  shared/src/business/entities/contacts/ContactUpdated.ts
  shared/src/business/entities/contacts/DeceasedSpouseContact.test.ts
  shared/src/business/entities/contacts/DeceasedSpouseContact.ts
  shared/src/business/entities/contacts/SpouseContact.ts
  shared/src/business/entities/startCase/GeneratePetitionPdf.ts
  shared/src/business/entities/startCase/UploadPetitionStep1.test.ts
  shared/src/business/entities/startCase/UploadPetitionStep1.ts
  shared/src/business/useCases/generatePetitionPdfInteractor.ts
  shared/src/business/utilities/documentGenerators/petition.ts
  shared/src/business/utilities/htmlGenerator/documents/petition.scss
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  shared/src/proxies/generatePetitionPdfProxy.ts
  shared/src/test/mockUsers.ts
  web-client/integration-tests/journey/practitionerCreatesNewCase.ts
  web-client/integration-tests/journey/practitionerViewsDashboard.ts
  web-client/integration-tests/journey/practitionerViewsDashboardBeforeAddingCase.ts
  web-client/integration-tests/journey/privatePractitionerViewsOpenAndClosedCases.ts
  web-client/integration-tests/journey/privatePractitionerViewsOpenConsolidatedCases.ts
  web-client/src/presenter/actions/formatPetitionAction.test.ts
  web-client/src/presenter/actions/formatPetitionAction.ts
  web-client/src/presenter/computeds/dashboardExternalHelper.test.ts
  web-client/src/presenter/computeds/dashboardExternalHelper.ts
  web-client/src/presenter/computeds/headerHelper.test.ts
  web-client/src/presenter/computeds/startCaseHelper.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.test.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.ts
  web-client/src/presenter/sequences/gotoDashboardSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/CaseListTable.tsx
  web-client/src/views/Dashboards/DashboardPetitioner.tsx
  web-client/src/views/Dashboards/DashboardPractitioner.tsx
  web-client/src/views/ErrorBanner.tsx
  web-client/src/views/InfoNotification.tsx
  web-client/src/views/PetitionWelcomePage.tsx
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StartCaseUpdated/BusinessInfo.tsx
  web-client/src/views/StartCaseUpdated/CardHeader.tsx
  web-client/src/views/StartCaseUpdated/CounselInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherContactInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherInfo.tsx
  web-client/src/views/StartCaseUpdated/PetitionerAndSpouseInfo.tsx
  web-client/src/views/StartCaseUpdated/PetitionerInformation.tsx
  web-client/src/views/StartCaseUpdated/SecondaryMinorIncompetentOptions.tsx
  web-client/src/views/StartCaseUpdated/Spouse.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep5.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
Labels: to test

#5242 10291: Remove close link and cancel upload button from FileUploadProgressModal
  web-client/src/presenter/actions/cancelUploadsAction.test.ts
  web-client/src/presenter/actions/cancelUploadsAction.ts
  web-client/src/presenter/computeds/fileUploadStatusHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/cancelFileUploadSequence.ts
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/FileUploadStatusModal.tsx
Labels: to test, Review Please

#5239 10429 Design Debt: Align Iteration Field Error
  web-client/src/styles/forms.scss
  web-client/src/views/FileDocument/NonstandardForm.tsx
Labels: to test

#5245 10309 Opex: Fix MaxListenersExceededWarning
  web-api/src/logger.ts
Labels: to test

#5234 Dep updates 08/05/24
  .circleci/config.yml
  .eslintrc.js
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  web-api/runtimes/puppeteer/package-lock.json
  web-api/src/lambdas/cognitoAuthorizer/cognito-authorizer.test.ts
  web-api/src/lambdas/cognitoAuthorizer/createAuthorizer.ts
  web-api/src/lambdas/cognitoAuthorizer/websocket-authorizer.test.ts
Labels: to staging, Review Please

#5247 10102 Story: Status Report Order
  cypress/local-only/support/statusReportOrder.ts
  cypress/local-only/tests/integration/statusReportOrder/edit-status-report-order.cy.ts
  cypress/local-only/tests/integration/statusReportOrder/file-status-report-order.cy.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/presenter/actions/StatusReportOrder/clearStatusReportOrderFormAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/clearStatusReportOrderFormAction.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.ts
Labels: to test

#5236 10458-devex: fix favicon pattern matching
  esbuildHelper.mjs
Labels: to staging

#5248 Expand untouched file check to check ALL files for increased type error count
  .github/workflows/typescript-all-files-check.yml
  scripts/checkAllFilesForTypeErrorCount.ts
  scripts/jest-scripts.config.ts
Labels: to staging, Review Please

#5156 10323: Preserving initial tab in order
  web-client/src/views/CreateOrder/TextEditor.tsx
Labels: to staging

#5230 10433 Design Debt: Inaccurate Banner for Petitioner
  web-client/src/presenter/computeds/caseDetailHelper.test.ts
  web-client/src/presenter/computeds/caseDetailHelper.ts
Labels: to staging

#5243 10291: Remove close link and cancel upload button from FileUploadProgressModal
  web-client/src/presenter/actions/cancelUploadsAction.test.ts
  web-client/src/presenter/actions/cancelUploadsAction.ts
  web-client/src/presenter/computeds/fileUploadStatusHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/cancelFileUploadSequence.ts
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/FileUploadStatusModal.tsx
Labels: to staging

#5244 10309 Opex: Fix MaxListenersExceededWarning
  web-api/src/logger.ts
Labels: to staging

#5253 devex: clean up remaining references to 'untouched files'
  .github/workflows/typescript-all-files-check.yml
  scripts/checkAllFilesForTypeErrorCount.ts
Labels: to staging

#5238 10429 Design Debt: Align Iteration Field Error
  web-client/src/styles/forms.scss
  web-client/src/views/FileDocument/NonstandardForm.tsx
Labels: to staging

#5260 10353 Bug: Duplicate Cognito Accounts
  cypress/deployed-and-local/integration/authentication/petitioner-account-creation.cy.ts
  web-api/src/business/useCases/auth/signUpUserInteractor.ts
  web-client/src/views/CreatePetitionerAccount/CreatePetitionerAccountForm.tsx
Labels: to test

#5263 10463 Bug: update telephone input elements
  web-client/src/styles/forms.scss
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/Practitioners/PractitionerContactForm.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StyleGuide/Forms.tsx
  web-client/src/views/UserContactEditForm.tsx
Labels: to test

#5268 10353 Bug: Duplicate Cognito Users update (fix re-enable logic of submit button)
  cypress/deployed-and-local/integration/authentication/petitioner-account-creation.cy.ts
  web-client/src/views/CreatePetitionerAccount/CreatePetitionerAccountForm.tsx
Labels: to test, Review Please

#5266 10464 Bug: Invalid documents in scenario dropdowns
  web-client/src/presenter/computeds/selectDocumentTypeHelper.test.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.ts
  web-client/src/presenter/sequences/editUnsignedDraftDocumentSequence.ts
Labels: to staging

#5267 10366 Bug: hide "Load More" button if no judge is selected
  web-client/src/presenter/computeds/pendingReportListHelper.test.ts
  web-client/src/presenter/sequences/Pending/setPendingReportSelectedJudgeSequence.ts
Labels: to test, Review Please

#5269 10463 Bug: update telephone input elements
  web-client/src/styles/forms.scss
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/Practitioners/PractitionerContactForm.tsx
  web-client/src/views/StartCase/ContactPrimary.tsx
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCase/ContactSecondary.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StyleGuide/Forms.tsx
  web-client/src/views/UserContactEditForm.tsx
Labels: to staging

#5272 10366 Bug: hide "Load More" button if no judge is selected
  web-client/src/presenter/computeds/pendingReportListHelper.test.ts
  web-client/src/presenter/sequences/Pending/setPendingReportSelectedJudgeSequence.ts
Labels: to staging

#5271 10339 UX feedback
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-myself.cy.ts
  web-client/src/styles/forms.scss
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/StartCaseUpdated/AutoGeneratePetitionForm.tsx
  web-client/src/views/StartCaseUpdated/CounselInformation.tsx
  web-client/src/views/StartCaseUpdated/PetitionFactOrReason.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
Labels: to test

#5252 10353 Bug: Duplicate Cognito Accounts
  cypress/deployed-and-local/integration/authentication/petitioner-account-creation.cy.ts
  web-api/src/business/useCases/auth/signUpUserInteractor.ts
  web-client/src/views/CreatePetitionerAccount/CreatePetitionerAccountForm.tsx
Labels: to staging

#5276 10437: Blocked Cases Report (Improvements) - TO TEST
  shared/src/business/entities/EntityConstants.ts
  web-client/integration-tests/journey/petitionsClerkBlocksCase.ts
  web-client/integration-tests/journey/petitionsClerkUnblocksCase.ts
  web-client/integration-tests/petitionsClerkBlockCase.test.ts
  web-client/integration-tests/petitionsClerkFiltersBlockedCaseReport.test.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseDetail/getBlockedCasesByTrialLocationAction.test.ts
  web-client/src/presenter/actions/CaseDetail/getBlockedCasesByTrialLocationAction.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/exportCsvBlockedCaseReportAction.test.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/exportCsvBlockedCaseReportAction.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/resetBlockedCasesFiltersAction.test.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/resetBlockedCasesFiltersAction.ts
  web-client/src/presenter/actions/setFormValueAction.test.ts
  web-client/src/presenter/actions/setFormValueAction.ts
  web-client/src/presenter/actions/setProcedureTypeToAllAction.test.ts
  web-client/src/presenter/actions/setProcedureTypeToAllAction.ts
  web-client/src/presenter/computeds/blockedCasesReportHelper.test.ts
  web-client/src/presenter/computeds/blockedCasesReportHelper.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.test.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.test.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Reports/exportCsvBlockedCaseReportSequence.ts
  web-client/src/presenter/sequences/getBlockedCasesByTrialLocationSequence.ts
  web-client/src/presenter/sequences/updateFormValueSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/views/BlockedCasesReport/BlockedCasesReport.tsx
  web-client/src/views/BlockedCasesReport/SelectCriteria.tsx
Labels: Do Not Merge, to test

#5210 Devex rebuild cognito to test
  web-api/terraform/modules/dynamsoft/dynamsoft.tf
  web-api/terraform/modules/everything-else-deprecated/cognito.tf
Labels: to test

#5207 Devex rebuild cognito
  web-api/terraform/modules/dynamsoft/dynamsoft.tf
  web-api/terraform/modules/everything-else-deprecated/cognito.tf
Labels: to staging

#5273 10459 Bug: Fix cognito users missing attributes
  scripts/run-once-scripts/fix-cognito-users-without-ids-constants.ts
  scripts/run-once-scripts/fix-cognito-users-without-ids.ts
Labels: to staging, Manual Deploy Step(s) Required

#5283 10471: Consolidated Case Docket Numbers on the new Status Report Order PDF are out of order TO TEST
  web-api/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.ts
Labels: to test

#5285 10437: Filter out options in Select Criteria;
  cypress/local-only/tests/integration/blockedCasesReport/blocked-cases-report.cy.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/src/presenter/computeds/selectCriteriaHelper.test.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.ts
  web-client/src/views/BlockedCasesReport/BlockedCasesReport.tsx
  web-client/src/views/BlockedCasesReport/SelectCriteria.tsx
  web-client/src/views/Header/ReportsMenu.tsx
Labels: Do Not Merge, to test

#5287 10437 story intermediate branch to test 1724714304
  .eslintrc.js
  cypress/helpers/fileAPetition/create-and-serve-paper-petition.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case-updated.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/helpers/fileAPetition/practitioner-creates-electronic-case.ts
  cypress/local-only/support/pages/create-paper-petition.ts
  cypress/local-only/tests/accessibility/filePetition/petitioner.cy.ts
  cypress/local-only/tests/accessibility/petitionGeneration/petition-generation-step-4.cy.ts
  cypress/local-only/tests/integration/blockedCasesReport/blocked-cases-report.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-4.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-case-procedure-and-trial-location.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/petition-helper.ts
  shared/src/business/entities/EntityConstants.ts
  web-client/integration-tests/petitionsClerkFiltersBlockedCaseReport.test.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/setBlockedCaseReportProcedureTypeAction.test.ts
  web-client/src/presenter/actions/Reports/BlockedCaseReport/setBlockedCaseReportProcedureTypeAction.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.test.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Reports/BlockedCases/exportCsvBlockedCaseReportSequence.ts
  web-client/src/presenter/sequences/Reports/BlockedCases/setBlockedCaseReportProcedureTypeSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/BlockedCasesReport/BlockedCasesReport.tsx
  web-client/src/views/BlockedCasesReport/SelectCriteria.tsx
  web-client/src/views/CaseDetail/BlockFromTrialModal.tsx
  web-client/src/views/CaseDetail/CaseInformation/TrialInformation.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/PrioritizeCaseModal.tsx
  web-client/src/views/CaseDetail/RemoveFromTrialSessionModal.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
  web-client/src/views/EditDocketEntry/PrimaryDocumentForm.tsx
  web-client/src/views/FilingPartiesForm.tsx
  web-client/src/views/PaperFiling/PrimaryDocumentForm.tsx
  web-client/src/views/StampMotion/ApplyStamp.tsx
  web-client/src/views/StartCase/ProcedureType.tsx
  web-client/src/views/TrialCityOptions.tsx
  web-client/src/views/TrialSessions/AddTrialSession.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
Labels: to test

#5284 10397: Fix List Item Accessibility Violation
  cypress/local-only/tests/accessibility/customCaseReport/docket-clerk.cy.ts
  package-lock.json
  package.json
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to test, Review Please

#5293 10339 Feedback
  cypress/local-only/support/helpers.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-generate-petition.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-intro.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself-and-my-spouse.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-myself-and-spouse.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-6-petitioner-info-myself.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-an-electronic-petition.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/contacts/ContactFactoryUpdated.test.ts
  shared/src/business/entities/contacts/ContactFactoryUpdated.ts
  shared/src/business/entities/startCase/UploadPetitionStep1.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  web-client/src/presenter/actions/StartCase/setDefaultContactStateAction.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
  web-client/src/presenter/computeds/showContactsHelperUpdated.test.ts
  web-client/src/presenter/computeds/showContactsHelperUpdated.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.test.ts
  web-client/src/presenter/computeds/updatedFilePetitionHelper.ts
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StartCaseUpdated/AutoGeneratePetitionForm.tsx
  web-client/src/views/StartCaseUpdated/BusinessInfo.tsx
  web-client/src/views/StartCaseUpdated/CounselInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherContactInformation.tsx
  web-client/src/views/StartCaseUpdated/OtherInfo.tsx
  web-client/src/views/StartCaseUpdated/PetitionerAndSpouseInfo.tsx
  web-client/src/views/StartCaseUpdated/PetitionerInformation.tsx
  web-client/src/views/StartCaseUpdated/Spouse.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep1.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep4.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: to test

#5299 10437: Removing filtering of Procedure Type options;
  web-client/src/presenter/computeds/selectCriteriaHelper.test.ts
  web-client/src/presenter/computeds/selectCriteriaHelper.ts
Labels: to test

#5288 10365 Bug: Remove leading/trailing spaces from user-entered passwords
  web-client/src/presenter/actions/Login/submitLoginAction.test.tsx
  web-client/src/presenter/actions/Login/submitLoginAction.tsx
Labels: to test

#5280 10226 Bug: Fix Pill Button Accessibility
  web-client/src/styles/buttons.scss
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to staging

#5295 10471: BUG: Consolidated Case Docket Numbers on the new Status Report Order PDF are out of order
  web-api/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlInteractor.ts
Labels: to staging

#5297 10399 bug to test
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/docket-clerk-uploads-and-edits-court-issued-docket-entry.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/utilities/getFormattedCaseDetail.test.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/business/utilities/isDraftStatusReportOrder.test.ts
  shared/src/business/utilities/isDraftStatusReportOrder.ts
  shared/src/business/utilities/isMiscellaneousDocketEntry.test.ts
  shared/src/business/utilities/isMiscellaneousDocketEntry.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.ts
  web-client/src/presenter/actions/checkDocumentTypeAction.test.ts
  web-client/src/presenter/actions/checkDocumentTypeAction.ts
  web-client/src/presenter/actions/setCaseDetailPageTabActionGenerator.ts
  web-client/src/presenter/sequences/editUploadCourtIssuedDocumentSequence.ts
  web-client/src/presenter/sequences/navigateToEditOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/EditUploadCourtIssuedDocument/EditUploadCourtIssuedDocument.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
Labels: to test

#5300 Fix migration queue empty flag
  shared/admin-tools/aws/migrationWaitHelper.ts
Labels: to staging, Review Please

#5294 Convert sequences to arrays
  web-client/src/presenter/sequences/Public/gotoPublicPrintableDocketRecordSequence.ts
  web-client/src/presenter/sequences/gotoPrintPaperTrialNoticesSequence.ts
  web-client/src/presenter/sequences/setPdfPreviewUrlSequence.ts
  web-client/src/presenter/sequences/updateTrialSessionCompleteSequence.ts
Labels: to staging

#5296 refactoring instances where we pass sequence strings
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/CaseAssociationRequest/CaseAssociationRequestWizard.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/Correspondence/AddCorrespondenceDocument.tsx
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMeta.tsx
  web-client/src/views/EditPetitionerCounsel.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/EditRespondentCounsel.tsx
  web-client/src/views/EditUploadCourtIssuedDocument/EditUploadCourtIssuedDocument.tsx
  web-client/src/views/FileDocument/BeforeYouFileADocument.tsx
  web-client/src/views/FileDocument/FileDocumentWizard.tsx
  web-client/src/views/FileDocument/ViewAllDocumentsDesktop.tsx
  web-client/src/views/FormCancelModalDialog.tsx
  web-client/src/views/PaperFiling/PaperFiling.tsx
  web-client/src/views/Practitioners/PractitionerAddEditDocument.tsx
  web-client/src/views/StartCase/StartCaseWizard.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetition.tsx
  web-client/src/views/TrialSessions/AddTrialSession.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
Labels: to staging

#5277 Dependency updates for 2024-08-26
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/web-api/runtimes/puppeteer/package-lock.json
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.test.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
Labels: dependencies, to staging

#5302 10397: Fix List Item Accessibility Violation
  cypress/local-only/tests/accessibility/customCaseReport/docket-clerk.cy.ts
  package-lock.json
  package.json
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: to staging, Review Please

#5308 10399-bug: PO and UX Feedback
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
  web-client/src/views/EditUploadCourtIssuedDocument/EditUploadCourtIssuedDocument.tsx
Labels: to test
