Repository ustaxcourt/ef-cms, pull requests merged in 2024-06, with the labels that each got.

#4980 10387 - Test to ensure IRS Superuser can download STIN document
  cypress-smoketests.config.ts
  cypress/deployed-and-local/integration/irsSuperUser/irs-super-user-can-download-stin.cy.ts
  cypress/helpers/cypressTasks/cognito/cognito-helpers.ts
Labels: to staging, Review Please

#4999 10294 to staging
  web-client/src/presenter/actions/openPdfInNewTabAction.test.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.ts
  web-client/src/presenter/presenter-mock.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/openPdfInNewTabSequence.ts
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/PDFPreviewButton.tsx
  web-client/src/views/RequestAccess/RequestAccessReview.tsx
Labels: to staging

#5009 10294: missing commits
  web-client/src/presenter/actions/openPdfInNewTabAction.test.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/openPdfInNewTabSequence.ts
Labels: to staging, Review Please

#5010 10387: make irs superuser test compatible with all envs
  cypress/deployed-and-local/integration/irsSuperUser/irs-super-user-can-download-stin.cy.ts
  cypress/helpers/env/cypressEnvironment.ts
Labels: to test

#5012 Devex 10338 - AWS v2 -> v3 conversion: SES
  package-lock.json
  package.json
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/applicationContext.ts
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.test.ts
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.ts
  web-api/src/lambdas/sendEmails/send-emails.ts
  web-api/src/persistence/messages/sendEmailToUser.ts
  web-api/src/persistence/ses/getSesStatus.test.ts
  web-api/src/persistence/ses/getSesStatus.ts
Labels: to test

#4997 Opex: Report of the closed date of cases opened in a given year
  scripts/reports/closed-dates.ts
Labels: to staging

#5003 Dependency updates week of 06/03/24
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
Labels: to staging

#5018 10258: Public Practitioner Search - to test
  shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.test.ts
  shared/src/business/useCases/practitioners/getPractitionerByBarNumberInteractor.ts
  shared/src/business/utilities/documentGenerators/thirtyDayNoticeOfTrial.test.ts
  web-api/src/app-public.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.test.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/hasPractitionerDetailAction.test.ts
  web-client/src/presenter/actions/hasPractitionerDetailAction.ts
  web-client/src/presenter/computeds/trialCitiesHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/submitPractitionerBarNumberSearchSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AdvancedSearch/PractitionerSearchByBarNumber.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchForm.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/Public/PublicSearch.tsx
Labels: to test

#5028 5512 to test
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-3.cy.ts
  shared/src/business/entities/startCase/UploadPetitionStep3.test.ts
  shared/src/business/entities/startCase/UploadPetitionStep3.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  web-client/src/presenter/actions/getStep3DataAction.test.ts
  web-client/src/presenter/actions/getStep3DataAction.ts
  web-client/src/presenter/actions/validateUploadPetitionStep3Action.test.ts
  web-client/src/presenter/computeds/startCaseHelper.test.ts
  web-client/src/presenter/computeds/startCaseHelper.ts
  web-client/src/styles/buttons.scss
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/PdfPreview/PdfPreview.tsx
  web-client/src/ustc-ui/PdfPreview/PdfViewer.tsx
  web-client/src/uswds/_index.scss
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionButtons.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep7.tsx
Labels: to test

#5030 10394 Update dynamsoft to 18.5
  docs/environments.md
  web-api/terraform/bin/deploy-app-color.sh
  web-api/terraform/bin/destroy-app.sh
  web-api/terraform/modules/dynamsoft/setup_dynamsoft.sh
  web-client/build-dist.sh
  web-client/terraform/main/setup_dynamsoft.sh
Labels: to test

#5029 10258 - Feedback + fix Paginator BUG
  cypress/local-only/tests/integration/public/practitioner-search.cy.ts
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/ustc-ui/Tabs/Tabs.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByBarNumber.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/Public/PublicSearch.tsx
Labels: to test

#5032 test: remove style on test
  web-client/src/styles/custom.scss
Labels: to test

#5033 10330 to test
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeG.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeH.ts
  web-client/src/presenter/actions/setTodaysDateAction.test.ts
  web-client/src/presenter/actions/setTodaysDateAction.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.test.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.ts
  web-client/src/presenter/sequences/openCreateCaseDeadlineModalSequence.ts
  web-client/src/presenter/sequences/openEditCaseDeadlineModalSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedNonstandardForm.tsx
Labels: to test

#5039 10258: Update Wording
  web-client/src/views/Public/PublicSearch.tsx
Labels: to test

#5034 5512 - Switch Petition and Petitioner Information step
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case-updated.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-corupted-files.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-minor-feedback.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-business--corporation.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-other-than-tax-matters-partner.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-representative-under-BBA.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-tax-matters-partner.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-myself-and-my-spouse.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-myself.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-other--donor-transferee-deceased-spouse.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-other--estate-or-trust.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-1-other--minor-or-legally-incompetent.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-2-myself.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-2.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-3.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/file-a-petition-step-4.cy.ts
  cypress/local-only/integration/fileAPetitionUpdated/petition-helper.ts
  shared/src/business/entities/EntityConstants.ts
  web-client/src/presenter/actions/determineStepPathAction.test.ts
  web-client/src/presenter/actions/determineStepPathAction.ts
  web-client/src/presenter/actions/formatPetitionAction.test.ts
  web-client/src/presenter/actions/formatPetitionAction.ts
  web-client/src/presenter/actions/getFilePetitionPetitionInformationAction.test.ts
  web-client/src/presenter/actions/getFilePetitionPetitionInformationAction.ts
  web-client/src/presenter/actions/getFilePetitionPetitionerInformationAction.test.ts
  web-client/src/presenter/actions/getFilePetitionPetitionerInformationAction.ts
  web-client/src/presenter/actions/setStepIndicatorInfoForPetitionGeneratorAction.test.ts
  web-client/src/presenter/actions/setStepIndicatorInfoForPetitionGeneratorAction.ts
  web-client/src/presenter/actions/validateFilePetitionPetitionInformationAction.test.ts
  web-client/src/presenter/actions/validateFilePetitionPetitionInformationAction.ts
  web-client/src/presenter/actions/validateFilePetitionPetitionerInformationAction.test.ts
  web-client/src/presenter/actions/validateFilePetitionPetitionerInformationAction.ts
  web-client/src/presenter/actions/validateUploadPetitionStep1Action.ts
  web-client/src/presenter/computeds/caseTypeDescriptionHelper.test.ts
  web-client/src/presenter/computeds/caseTypeDescriptionHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/filePetitionCompletePetitionInformationSequence.ts
  web-client/src/presenter/sequences/filePetitionCompletePetitionerInformationSequence.ts
  web-client/src/presenter/sequences/petitionGenerationLiveValidationSequence.ts
  web-client/src/presenter/sequences/updatedFilePetitionCompleteStep5Sequence.ts
  web-client/src/presenter/sequences/validateFilePetitionPetitionInformationSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/StartCase/ContactPrimaryUpdated.tsx
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StartCaseUpdated/FilePetitionPetitionInformation.tsx
  web-client/src/views/StartCaseUpdated/FilePetitionPetitionerInformation.tsx
  web-client/src/views/StartCaseUpdated/IrsNoticeUploadForm.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetition.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionButtons.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
Labels: Do Not Merge, to test

#4965 10007 - Remove old login messaging for cognito
  shared/src/proxies/auth/logOldLoginAttemptProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/logOldLoginAttemptInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/auth/oldLoginAttemptLambda.ts
  web-api/terraform/modules/everything-else-deprecated/cognito.tf
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/Login/logOldLoginAttemptAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/Login/gotoOldLoginSequence.ts
  web-client/src/router.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/OldLogin.tsx
Labels: to staging

#5041 10400 bug intermediate branch to test 1718313002
  cypress/local-only/tests/integration/fileAPetition/file-a-petition.cy.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.test.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/openPdfInNewTabSequence.ts
  web-client/src/views/PDFPreviewButton.tsx
Labels: to test

#5026 Only run specific smoke test in a deployed environment
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-gets-unserved.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-signature-disappears.cy.ts
Labels: to staging

#5046 10345: Dynamsoft avoid destroy/recreate
  web-api/terraform/applyables/allColors/moved.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
Labels: to staging

#5001 Devex 10338 - AWS v2 -> v3 conversion: SES
  package-lock.json
  package.json
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/applicationContext.ts
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.test.ts
  web-api/src/dispatchers/ses/sendBulkTemplatedEmail.ts
  web-api/src/environment.ts
  web-api/src/lambdas/sendEmails/send-emails.ts
  web-api/src/persistence/messages/getEmailClient.ts
  web-api/src/persistence/messages/sendEmailToUser.ts
  web-api/src/persistence/ses/getSesStatus.test.ts
  web-api/src/persistence/ses/getSesStatus.ts
Labels: to staging

#5040 10400 - Bug Fix
  cypress/local-only/tests/integration/fileAPetition/file-a-petition.cy.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.test.ts
  web-client/src/presenter/actions/openPdfInNewTabAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/openPdfInNewTabSequence.ts
  web-client/src/views/PDFPreviewButton.tsx
Labels: to staging

#5036 10390: Limit allowable documents for IRS pracitioners on first IRS filing
  shared/src/tools/externalFilingEvents.json
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/internalTypesHelper.ts
Labels: to staging, Review Please

#5060 10407 bugfix intermediate branch to test 1718655765
  shared/src/business/useCases/loadPDFForSigningInteractor.ts
  shared/src/business/utilities/scrapePdfContents.ts
Labels: to test

#4987 10368 Prevent use of deploying color for real users
  .circleci/config.yml
  cypress/deployed-and-local/integration/irsSuperUser/irs-super-user-can-download-stin.cy.ts
  cypress/support/commands.ts
  scripts/delete-api-gateway-mappings.sh
  shared/src/utils/headers.ts
  web-api/hostedEnvironmentTests/irsSuperUser.test.ts
  web-api/src/app-public.ts
  web-api/src/app.ts
  web-api/src/lambdas/notifications/defaultLambda.ts
  web-api/storage/scripts/loadTest/loadTestPdfGeneration.ts
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/modules/api/api-async.tf
  web-client/deploy-public.sh
  web-client/src/app.tsx
  web-client/src/appPublic.tsx
  web-client/src/applicationContext.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/clearModalAction.ts
  web-client/src/presenter/actions/redirectToDashboardAction.ts
  web-client/src/presenter/actions/setupCurrentPageAction.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/openAppUpdatedModalSequence.ts
  web-client/src/presenter/sequences/redirectToDashboardSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/providers/httpClient.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/AppUpdatedModal.tsx
  web-client/src/views/ErrorView500.tsx
  web-client/src/views/GlobalModalWrapper.tsx
  web-client/switch-colors.sh
Labels: to staging, Review Please

#5063 10351 cold cases intermediate branch to test 1718399367
  package-lock.json
  package.json
  web-api/src/persistence/elasticsearch/reports/getColdCases.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
  web-client/src/views/Header/ReportsMenu.tsx
Labels: to test

#5066 10348 bug intermediate branch to test 1718726400
  web-client/src/presenter/computeds/Login/loginHelper.test.ts
  web-client/src/presenter/computeds/Login/loginHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/Login/Login.tsx
Labels: to test

#5056 10394: Upgrade Dynamsoft Web TWAIN server EC2 image to 18.x
  docs/environments.md
  web-api/terraform/bin/deploy-app-color.sh
  web-api/terraform/bin/destroy-app.sh
  web-api/terraform/modules/dynamsoft/dynamsoft.tf
  web-api/terraform/modules/dynamsoft/setup_dynamsoft.sh
  web-client/build-dist.sh
Labels: to staging, Manual Deploy Step(s) Required

#5069 10348 bug intermediate branch to test 1718738804
  cypress/readonly/integration/authentication/login.cy.ts
Labels: to test

#5067 10258: Handle code review feedback
  web-client/src/applicationContext.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/actions/getPractitionerDetailAction.ts
  web-client/src/presenter/actions/hasPractitionerDetailAction.test.ts
  web-client/src/presenter/actions/hasPractitionerDetailAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/presenter/computeds/practitionerSearchFormHelper.test.ts
  web-client/src/presenter/computeds/practitionerSearchFormHelper.ts
  web-client/src/presenter/state-public.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/views/AdvancedSearch/PractitionerSearchByBarNumber.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchForm.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/Public/PublicSearch.tsx
Labels: to test, Review Please

#5076 Devex 10337: Don't hardcode regions when instantiating SES and SQS clients (to `test`)
  web-api/src/applicationContext.ts
  web-api/src/persistence/messages/getEmailClient.ts
Labels: to test

#5077 Devex 10337: use the region that is contextual to the running lambda when instantiating the SES and SQS clients (to `test`)
  web-api/src/applicationContext.ts
  web-api/src/persistence/messages/getEmailClient.ts
Labels: to test

#5079 10351 cold cases intermediate branch to test 1718899989
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
Labels: to test

#5080 10371 story intermediate branch to test 1718903434
  shared/src/business/utilities/htmlGenerator/components/preformatted-text.scss
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes_Using_New_Calendar_Props.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Session_Notes.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.2.png
Labels: to test

#5082 Fix AppContext Typing in HTTP Requests
  .github/workflows/typescript-untouched-files-check.yml
  shared/src/proxies/caseAssociation/generateEntryOfAppearancePdfProxy.ts
  shared/src/proxies/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlProxy.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  shared/src/proxies/public/getPublicPractitionersByNameProxy.ts
  shared/src/proxies/requests.ts
  shared/src/proxies/users/checkEmailAvailabilityProxy.ts
Labels: to staging, Review Please

#5091 10376: Handle PO Feedback
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test

#5061 10348: Enable Login button with autofilled credentials on initial page load
  cypress/readonly/integration/authentication/login.cy.ts
  web-client/src/presenter/computeds/Login/loginHelper.test.ts
  web-client/src/presenter/computeds/Login/loginHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/Login/Login.tsx
Labels: to staging, Review Please

#5090 Dependency updates 2024-06-20
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
Labels: to staging

#5097 10351 cold cases intermediate branch to test 1719245861
  .circleci/config.yml
  .github/workflows/typescript-untouched-files-check.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/src/proxies/caseAssociation/generateEntryOfAppearancePdfProxy.ts
  shared/src/proxies/courtIssuedOrder/createCourtIssuedOrderPdfFromHtmlProxy.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  shared/src/proxies/public/getPublicPractitionersByNameProxy.ts
  shared/src/proxies/requests.ts
  shared/src/proxies/users/checkEmailAvailabilityProxy.ts
  shared/src/test/mockTrial.ts
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-client/src/views/ColdCaseReport/ColdCaseReport.tsx
  web-client/src/views/DocketRecord/FilingsAndProceedings.tsx
Labels: to test

#5096 dep-updates: update terraform aws provider;
  web-api/terraform/applyables/account-specific/account-specific.tf
Labels: to staging

#5098 5512: Feedback - TO TEST
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-corupted-files.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-minor-feedback.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-business--corporation.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-other-than-tax-matters-partner.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-representative-under-BBA.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-business--partnership-tax-matters-partner.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself-and-my-spouse.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-myself.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-other--donor-transferee-deceased-spouse.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-other--estate-or-trust.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-1-other--minor-or-legally-incompetent.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-2.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-3.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/file-a-petition-step-4.cy.ts
  cypress/local-only/tests/integration/fileAPetitionUpdated/petition-helper.ts
  package-lock.json
  shared/src/business/entities/startCase/UploadPetitionStep3.test.ts
  shared/src/business/entities/startCase/UploadPetitionStep3.ts
  shared/src/business/useCases/externalDocument/uploadExternalDocumentsInteractor.test.ts
  shared/src/business/useCases/externalDocument/uploadExternalDocumentsInteractor.ts
  web-client/src/presenter/actions/DocketEntry/uploadDocketEntryFileAction.ts
  web-client/src/presenter/actions/FileDocument/uploadExternalDocumentsAction.ts
  web-client/src/presenter/actions/addAnotherIrsNoticeToFormAction.test.ts
  web-client/src/presenter/actions/addAnotherIrsNoticeToFormAction.ts
  web-client/src/presenter/actions/clearIrsNoticeFormAction.test.ts
  web-client/src/presenter/actions/clearIrsNoticeFormAction.ts
  web-client/src/presenter/actions/saveCaseDetailInternalEditAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/setHasIrsNoticeSequence.ts
  web-client/src/uswds/_index.scss
  web-client/src/views/Public/PublicSearch.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep3.tsx
  web-client/src/views/cloneFile.error.test.ts
  web-client/src/views/cloneFile.test.ts
Labels: to test

#5102 10351 cold cases intermediate branch to test 1719254949
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
Labels: to test

#5094 10330: Fix validation messages for minimum date in CourtIssuedDocumentTypeD …
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.ts
Labels: to test

#5095 10376: Message Inbox - Additional Sorting
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
  web-client/src/views/Messages/MessagesIndividualCompleted.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
Labels: to staging, Review Please

#5099 Devex: Update Type Generation for objects
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/customCaseReportSearch/CustomCaseReportSearch.ts
  shared/src/business/utilities/DateHandler.ts
  web-client/src/presenter/computeds/customCaseReportHelper.ts
Labels: to staging

#5107 10379: Trigger computed when user logs out and logs back in;
  web-client/src/presenter/computeds/myAccountHelper.test.ts
  web-client/src/presenter/computeds/myAccountHelper.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test, Review Please

#5071 10371: Show Notes with Line Breaks + Spaces
  shared/src/business/utilities/htmlGenerator/components/preformatted-text.scss
  shared/src/business/utilities/htmlGenerator/index-main.scss
  shared/src/business/utilities/pdfGenerator/components/SessionNotesSection.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialCalendar.tsx
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_With_Case_Notes_Using_New_Calendar_Props.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.1.png
  shared/test-pdf-expected-images/Printable_Trial_Session_Working_Copy_Without_Case_Notes.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_In_Person.pdf.2.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Lead_Case.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_No_Session_Notes.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.1.png
  shared/test-pdf-expected-images/Trial_Calendar_Remote.pdf.2.png
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/PreformatedText/PreformattedText.tsx
  web-client/src/views/CaseDetail/CaseInformation/DisplayHearings.tsx
  web-client/src/views/CaseDetail/CaseInformation/TrialInformation.tsx
  web-client/src/views/CaseDetail/CaseNotes.tsx
  web-client/src/views/TrialSessionDetail/EligibleCases.tsx
  web-client/src/views/TrialSessionDetail/OpenCases.tsx
  web-client/src/views/TrialSessionDetail/TrialSessionInformation.tsx
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
  web-client/src/views/TrialSessionWorkingCopy/SessionNotes.tsx
Labels: to staging

#5113 10346 large pdf errors intermediate branch to test 1719491684
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/court-issued-documents.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-gets-unserved.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-signature-disappears.cy.ts
  cypress/helpers/caseDetail/docketRecord/courtIssuedFiling/create-order-and-decision.ts
  cypress/helpers/caseDetail/docketRecord/courtIssuedFiling/create-order.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/advancedSearch/content-search.cy.ts
  cypress/local-only/tests/integration/advancedSearch/external-user-searches-orders.cy.ts
  cypress/local-only/tests/integration/advancedSearch/title-search.cy.ts
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/docket-clerk-creates-draft-orders-for-lead-case.cy.ts
  cypress/local-only/tests/integration/judgeActivityReport/judge-activity-report.cy.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/scrapePdfContents.test.ts
  shared/src/business/utilities/scrapePdfContents.ts
  web-api/src/business/useCaseHelper/pdf/parseAndScrapePdfContents.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.consolidatedCases.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.ts
  web-api/terraform/modules/api/alarms.tf
  web-client/integration-tests/externalUserOrderAdvancedSearch.test.ts
  web-client/integration-tests/journey/chambersUserAddsOrderToCase.ts
  web-client/integration-tests/journey/chambersUserSkipSigningOrder.ts
  web-client/integration-tests/journey/docketClerkCreatesAnOrder.ts
  web-client/integration-tests/journey/petitionsClerk1CreatesNoticeFromMessageDetail.ts
  web-client/integration-tests/journey/petitionsClerkAddsGenericOrderToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsNoticeToCase.ts
  web-client/integration-tests/journey/petitionsClerkAddsOrderToCase.ts
  web-client/integration-tests/journey/petitionsClerkCreateOrder.ts
  web-client/integration-tests/journey/petitionsClerkCreatesOrderFromMessage.ts
  web-client/integration-tests/orderSearchJourneyAndKeyword.test.ts
  web-client/integration-tests/orderSearchJourneyCaseCaption.test.ts
  web-client/integration-tests/orderSearchJourneyDocketNumber.test.ts
  web-client/integration-tests/orderSearchJourneyOrKeyword.test.ts
  web-client/integration-tests/orderSearchJourneySpecialCharacters.test.ts
  web-client/src/presenter/actions/CaseDetail/validateRemoveFromTrialSessionAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/validateCourtOrderAction.ts
  web-client/src/presenter/actions/getDocumentContentsAction.test.ts
  web-client/src/presenter/actions/getDocumentContentsAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.ts
  web-client/src/presenter/sequences/validateCourtOrderSequence.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
Labels: to test

#5048 10351 cold cases
  package-lock.json
  package.json
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/proxies/reports/getColdCaseReportProxy.ts
  shared/src/test/mockTrial.ts
  web-api/src/app.ts
  web-api/src/business/useCases/reports/coldCaseReportInteractor.test.ts
  web-api/src/business/useCases/reports/coldCaseReportInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/reports/coldCaseReportLambda.ts
  web-api/src/persistence/elasticsearch/reports/getColdCases.test.ts
  web-api/src/persistence/elasticsearch/reports/getColdCases.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/ColdCaseReport/getColdCaseReportAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoColdCaseReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/views/AppComponent.tsx
  web-client/src/views/ColdCaseReport/ColdCaseReport.tsx
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
  web-client/src/views/Header/ReportsMenu.tsx
Labels: to staging

#5114 5512: Feedback
  package-lock.json
  shared/src/business/utilities/htmlGenerator/documents/petition.scss
  shared/src/business/utilities/pdfGenerator/components/PetitionDocketHeader.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/Petition.tsx
  web-client/src/presenter/actions/StartCaseInternal/resetContactSecondaryAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/resetContactSecondaryAction.ts
  web-client/src/presenter/actions/getFilePetitionPetitionerInformationAction.test.ts
  web-client/src/presenter/actions/getFilePetitionPetitionerInformationAction.ts
  web-client/src/views/StartCase/ContactSecondaryUpdated.tsx
  web-client/src/views/StartCaseInternal/ElectronicServiceCheckbox.tsx
  web-client/src/views/StartCaseUpdated/UpdatedFilePetitionStep6.tsx
Labels: to test

#5117 10398 bug intermediate branch to test 1719586003
  shared/src/business/entities/EntityConstants.ts
  web-api/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/updateCourtIssuedOrderInteractor.ts
  web-api/src/persistence/elasticsearch/reports/getColdCases.ts
  web-client/src/views/ColdCaseReport/ColdCaseReport.tsx
Labels: to test

#5115 10330 to staging
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeG.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeH.ts
  web-client/integration-tests/journey/docketClerkEditsDocketEntryFromOrderTypeH.ts
  web-client/src/presenter/actions/setTodaysDateAction.test.ts
  web-client/src/presenter/actions/setTodaysDateAction.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.test.ts
  web-client/src/presenter/computeds/addCourtIssuedDocketEntryNonstandardHelper.ts
  web-client/src/presenter/sequences/openCreateCaseDeadlineModalSequence.ts
  web-client/src/presenter/sequences/openEditCaseDeadlineModalSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedNonstandardForm.tsx
Labels: to staging

#5110 10379: BUG: The My Account information is displaying incorrect information
  cypress/local-only/tests/integration/myAccount/bug-switching-accounts-state-cache.cy.ts
  web-client/src/presenter/computeds/myAccountHelper.test.ts
  web-client/src/presenter/computeds/myAccountHelper.ts
  web-client/src/views/MyContactInformation.tsx
Labels: to staging
