Repository ustaxcourt/ef-cms, pull requests merged in 2024-02, with the labels that each got.

#4585 Devex health migration script
  .eslintrc.js
  shared/admin-tools/elasticsearch/health-migration.js
  shared/admin-tools/elasticsearch/health-migration.ts
Labels: to staging

#4619 10253: Increase timeout for Public API;
  web-api/terraform/api/api-public.tf
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
Labels: to test

#4573 10216 missing previous document refactor2
  package.json
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.test.ts
  scripts/circleci/judge/bulkImportJudgeUsers.helpers.ts
  shared/src/business/entities/DocketEntry.fetchRootDocument.test.ts
  shared/src/business/entities/DocketEntry.isPublic.test.ts
  shared/src/business/entities/DocketEntry.isTranscriptOldEnoughToUnseal.test.ts
  shared/src/business/entities/DocketEntry.isUnservable.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/Docketentry.isDownloadable.test.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/PublicCase.isPrivateDocument.test.ts
  shared/src/business/entities/cases/PublicCase.ts
  shared/src/business/useCaseHelper/addDocketEntryForSystemGeneratedOrder.ts
  shared/src/business/useCases/docketEntry/fileCourtIssuedDocketEntryInteractor.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/getDownloadPolicyUrlInteractor.ts
  shared/src/business/useCases/processStreamRecords/processDocketEntries.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.test.ts
  shared/src/business/useCases/public/getPublicDownloadPolicyUrlInteractor.ts
  shared/src/business/useCases/saveSignedDocumentInteractor.ts
  shared/src/business/utilities/getFormattedCaseDetail.ts
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.ts
  shared/src/test/mockDocketEntry.ts
  web-api/src/lambdas/v1/getDocumentDownloadUrlLambda.test.ts
  web-api/src/lambdas/v2/getDocumentDownloadUrlLambda.test.ts
  web-client/integration-tests/amicusBriefJourney.test.ts
  web-client/jest-unit.config.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/persistence/s3/uploadDocumentFromClient.test.ts
  web-client/src/presenter/actions/createNewPetitionerUserAction.test.ts
  web-client/src/presenter/actions/getOpinionTypesAction.ts
  web-client/src/presenter/actions/shouldSaveToConsolidatedGroupAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
  web-client/src/presenter/computeds/confirmInitiateServiceModalHelper.ts
  web-client/src/presenter/computeds/filingPartiesFormHelper.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getFormattedDocketEntry.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.getShowDocumentViewerLink.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.test.ts
  web-client/src/presenter/computeds/formattedDocketEntries.ts
  web-client/src/presenter/computeds/getShowNotServedForDocument.ts
Labels: to test

#4579 10219 - adding retry logic to prevent upload timeouts to s3
  types/IApplicationContext.d.ts
  web-api/src/applicationContext.ts
  web-client/src/persistence/s3/uploadPdfFromClient.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.ts
  web-client/src/presenter/computeds/fileUploadStatusHelper.ts
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/FileUploadStatusModal.tsx
  web-client/src/views/PDFPreviewButton.tsx
Labels: to staging

#4616 9584: Court User - Filtering Messages
  cypress/cypress-integration/integration/messages.cy.ts
  shared/src/business/entities/EntityConstants.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/computeds/formattedMessages.ts
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/Messages/MessagesIndividualInbox.tsx
  web-client/src/views/Messages/MessagesIndividualOutbox.tsx
  web-client/src/views/Messages/MessagesSectionCompleted.tsx
  web-client/src/views/Messages/MessagesSectionInbox.tsx
  web-client/src/views/Messages/MessagesSectionOutbox.tsx
Labels: to staging

#4624 Backmerge staging to test
  shared/src/business/entities/EntityConstants.ts
  web-client/src/presenter/computeds/formattedMessages.ts
Labels: to test

#4623 10253: Public user is getting a 502 error after clicking printable docket record link on 21959-16, also sometimes just accessing the case
  web-api/terraform/api/api-public.tf
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
Labels: to staging

#4612 10255: The Add/Edit docket numbers in the caption link adds all the docket numbers to an order even if you don't save
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.test.ts
  web-client/src/presenter/actions/CaseConsolidation/setMultiDocketingCheckboxesAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.test.ts
  web-client/src/presenter/actions/CourtIssuedOrder/getPdfUrlAction.ts
  web-client/src/presenter/actions/CourtIssuedOrder/submitCourtIssuedOrderAction.ts
  web-client/src/presenter/actions/getCreateOrderSelectedCases.test.ts
  web-client/src/presenter/actions/getCreateOrderSelectedCases.ts
  web-client/src/presenter/actions/setCreateOrderSelectedCasesAction.test.ts
  web-client/src/presenter/actions/setCreateOrderSelectedCasesAction.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.test.ts
  web-client/src/presenter/actions/setFormFromDraftStateAction.ts
  web-client/src/presenter/actions/unsetCreateOrderAddedDocketNumbers.test.ts
  web-client/src/presenter/actions/unsetCreateOrderAddedDocketNumbers.ts
  web-client/src/presenter/actions/unsetCreateOrderSelectedCases.test.ts
  web-client/src/presenter/actions/unsetCreateOrderSelectedCases.ts
  web-client/src/presenter/sequences/gotoEditOrderSequence.ts
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.ts
  web-client/src/presenter/sequences/submitUpdateAddDocketNumbersToOrderSequence.ts
  web-client/src/presenter/state.ts
Labels: bugfix, to staging

#4627 devex: remove deprecated stream-event-id
  web-api/storage/fixtures/seed/efcms-local.json
Labels: to staging

#4629 Devex 1195: Determine when the indexing of migrated data is complete without referencing another cluster
  .circleci/config.yml
  scripts/dynamo/set-local-migration-complete-marker.ts
  scripts/dynamo/set-migration-complete-marker.sh
  scripts/jest-scripts.config.ts
  shared/admin-tools/aws/lambdaHelper.test.ts
  shared/admin-tools/aws/lambdaHelper.ts
  shared/admin-tools/circleci/circleci-helper.ts
  shared/admin-tools/elasticsearch/check-reindex-complete.test.ts
  shared/admin-tools/elasticsearch/check-reindex-complete.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.test.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.ts
  shared/src/business/useCases/processStreamRecords/processStreamUtilities.test.ts
  shared/src/business/useCases/processStreamRecords/processStreamUtilities.ts
  shared/src/business/useCases/processStreamRecordsInteractor.ts
  web-api/enable-deploying-dynamo-stream-trigger.sh
  web-api/src/lambdas/streams/processStreamRecordsLambda.test.ts
  web-api/src/lambdas/streams/processStreamRecordsLambda.ts
  web-api/src/persistence/elasticsearch/bulkIndexRecords.ts
  web-api/terraform/bin/edit-lambda-environment.sh
  web-api/terraform/bin/edit-lambda-environment.ts
  web-api/workflow-terraform/reindex-cron/bin/deploy-init.sh
  web-api/workflow-terraform/reindex-cron/main/lambdas/reindex-status.js
  web-api/workflow-terraform/reindex-cron/main/lambdas/reindex-status.test.js
  web-api/workflow-terraform/reindex-cron/main/reindex-status.tf
  web-api/workflow-terraform/reindex-cron/main/variables.tf
Labels: to test

#4603 Dependency updates 2024 01 22
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  docs/dependency-updates.md
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/is-migration-needed.js
  web-api/runtimes/puppeteer/package-lock.json
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: to staging

#4622 10217 test
  cypress/cypress-integration/support/pages/start-a-case.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/ElectronicPetition.ts
  shared/src/business/entities/cases/ElectronicPetitionInformationFactory.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.test.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/filePetitionFromPaperInteractor.ts
  shared/src/business/useCases/filePetitionInteractor.test.ts
  shared/src/business/useCases/filePetitionInteractor.ts
  shared/src/business/useCases/uploadDocumentAndMakeSafeInteractor.ts
  shared/src/business/utilities/serveCaseDocument.test.ts
  shared/src/business/utilities/serveCaseDocument.ts
  shared/src/proxies/createCaseFromPaperProxy.ts
  shared/src/proxies/createCaseProxy.ts
  shared/src/proxies/getDocumentDownloadUrlProxy.ts
  shared/src/test/mockDocketEntry.ts
  web-client/src/getConstants.ts
  web-client/src/persistence/s3/uploadDocumentFromClient.ts
  web-client/src/presenter/actions/createCaseAction.test.ts
  web-client/src/presenter/actions/createCaseAction.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.ts
  web-client/src/presenter/actions/getDocumentSelectedForPreviewAction.test.ts
  web-client/src/presenter/actions/getDocumentSelectedForPreviewAction.ts
  web-client/src/presenter/computeds/petitionQcHelper.test.ts
  web-client/src/presenter/computeds/petitionQcHelper.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.test.ts
  web-client/src/presenter/computeds/reviewSavedPetitionHelper.ts
  web-client/src/presenter/computeds/scanHelper.test.ts
  web-client/src/presenter/computeds/scanHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/setDocumentForPreviewSequence.ts
  web-client/src/styles/icons.scss
  web-client/src/styles/overrides.scss
  web-client/src/uswds/_index.scss
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CaseDetailEdit/Attachments.tsx
  web-client/src/views/Dashboards/DashboardPetitioner.tsx
  web-client/src/views/Dashboards/OtherFilingOptions.tsx
  web-client/src/views/ErrorBanner.tsx
  web-client/src/views/FileDocument/FileInput.tsx
  web-client/src/views/PDFPreviewButton.tsx
  web-client/src/views/PetitionQcScanBatchPreviewer.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
  web-client/src/views/StartCase/StartCaseStep5.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
  web-client/src/views/WhatToExpect.tsx
Labels: to test

#4637 9787: Display Consolidated Cases Icons on Case Inventory Report
  shared/src/business/useCaseHelper/caseInventoryReport/generateCaseInventoryReportPdf.test.ts
  shared/src/business/useCaseHelper/caseInventoryReport/generateCaseInventoryReportPdf.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.test.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.tsx
  shared/test-pdf-expected-images/Case_Inventory_Report.pdf.1.png
  web-api/src/getUtilities.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.ts
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to test

#4643 10257 serve case to irs fixes to test
  cypress/cypress-integration/integration/judge-activity-report.cy.ts
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  cypress/helpers/create-and-serve-paper-petition.ts
  cypress/helpers/search-by-docket-number-in-header.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
  shared/src/proxies/serveCaseToIrs/serveCaseToIrsProxy.ts
  web-api/src/app.ts
  web-client/integration-tests/docketRecordJourney.test.ts
  web-client/integration-tests/eConsentJourney.test.ts
  web-client/integration-tests/journey/docketClerkVerifiesPetitionReceiptLength.ts
  web-client/integration-tests/journey/petitionsClerk1ServesPetitionFromMessageDetail.ts
  web-client/integration-tests/journey/petitionsClerkChangesCaseCaptionDuringQC.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkServesElectronicCaseToIrs.ts
  web-client/integration-tests/journey/petitionsClerkServesPetitionFromDocumentView.ts
  web-client/integration-tests/journey/petitionsClerkSubmitsCaseToIrs.ts
  web-client/integration-tests/journey/petitionsClerkSubmitsPaperCaseToIrs.ts
  web-client/integration-tests/petitionsClerkCreatesEstateCaseWithLongAdditionalName.test.ts
  web-client/integration-tests/petitionsClerkQCPaperFiledPetition.test.ts
  web-client/integration-tests/petitionsClerkServesPaperCaseToIRS.ts
  web-client/src/presenter/actions/CaseConfirmation/serveToIrsCompleteAction.ts
  web-client/src/presenter/actions/StartCaseInternal/serveCaseToIrsAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/serveCaseToIrsAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/serveCaseToIrsSequence.ts
  web-client/src/presenter/sequences/serveToIrsCompleteSequence.ts
  web-client/src/presenter/sequences/serveToIrsErrorSequence.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/DocketRecord/DraftDocumentViewer.tsx
  web-client/src/views/ServeCaseToIrsErrorModal.tsx
Labels: to test

#4645 10216 missing previous document refactor2 to test
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
Labels: to test

#4636 Dep updates 2024-02-05
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/terraform/main/main.tf
Labels: dependencies, to staging

#4649 10247: Replace values with spaces to keep PDF structure valid
  .circleci/config.yml
  Dockerfile
  cognito-triggers-sls/package-lock.json
  cognito-triggers-sls/package.json
  iam/terraform/account-specific/main/main.tf
  iam/terraform/environment-specific/main/main.tf
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/main/main.tf
  web-api/workflow-terraform/glue-cron/main/main.tf
  web-api/workflow-terraform/migration-cron/main/main.tf
  web-api/workflow-terraform/migration/main/main.tf
  web-api/workflow-terraform/reindex-cron/main/main.tf
  web-api/workflow-terraform/switch-colors-cron/main/main.tf
  web-api/workflow-terraform/wait-for-workflow-cron/main/main.tf
  web-client/src/persistence/s3/uploadPdfFromClient.test.ts
  web-client/src/persistence/s3/uploadPdfFromClient.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/terraform/main/main.tf
Labels: to test

#4652 10247 Don't clear out encrypted PDF meta data
  web-client/src/persistence/s3/uploadPdfFromClient.test.ts
  web-client/src/persistence/s3/uploadPdfFromClient.ts
Labels: to test

#4655 10217 UX Feedback
  web-client/src/views/FileDocument/FileInput.tsx
  web-client/src/views/StartCase/StartCaseStep2.tsx
Labels: to test

#4638 10225: BUGFIX: If you have multiple tabs open when serving the 30 day Notice of Trial, the other tabs display a 404 error
  shared/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.test.ts
  shared/src/business/useCases/trialSessions/serveThirtyDayNoticeInteractor.ts
  shared/src/proxies/trialSessions/serveThirtyDayNoticeProxy.ts
  web-api/src/lambdas/trialSessions/serveThirtyDayNoticeLambda.ts
  web-client/src/presenter/actions/TrialSession/serveThirtyDayNoticeOfTrialAction.ts
Labels: bugfix, to staging

#4640 9787: Consolidation: Add Icons to Case Inventory Report
  shared/src/business/useCaseHelper/caseInventoryReport/generateCaseInventoryReportPdf.test.ts
  shared/src/business/useCaseHelper/caseInventoryReport/generateCaseInventoryReportPdf.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.test.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.tsx
  shared/test-pdf-expected-images/Case_Inventory_Report.pdf.1.png
  web-api/src/business/useCases/caseInventoryReport/generatePrintableCaseInventoryReportInteractor.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.ts
  web-api/terraform/template/lambdas/cognito-authorizer.test.ts
  web-client/integration-tests-public/userTriesToViewUnsealedCaseWithSealedDocketEntry.test.ts
  web-client/integration-tests/journey/petitionerChoosesProcedureType.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to staging

#4632 Opex: List Trial Sessions by Year
  scripts/jest-scripts.config.ts
  scripts/reports/trial-sessions-by-year.ts
Labels: to staging

#4673 10270: BUG
  package-lock.json
  package.json
Labels: to staging

#4674 10270: BUG
  package-lock.json
  package.json
Labels: to test

#4657 10257 serve case to irs fixes
  cypress/cypress-integration/integration/judge-activity-report.cy.ts
  cypress/cypress-integration/integration/trial-session-paper-pdf.cy.ts
  cypress/cypress-integration/support/pages/create-paper-petition.ts
  cypress/helpers/create-and-serve-paper-petition.ts
  cypress/helpers/search-by-docket-number-in-header.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.ts
  shared/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
  shared/src/proxies/serveCaseToIrs/serveCaseToIrsProxy.ts
  web-api/src/app.ts
  web-client/integration-tests/docketRecordJourney.test.ts
  web-client/integration-tests/eConsentJourney.test.ts
  web-client/integration-tests/journey/docketClerkVerifiesPetitionReceiptLength.ts
  web-client/integration-tests/journey/petitionsClerk1ServesPetitionFromMessageDetail.ts
  web-client/integration-tests/journey/petitionsClerkChangesCaseCaptionDuringQC.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCase.ts
  web-client/integration-tests/journey/petitionsClerkServesElectronicCaseToIrs.ts
  web-client/integration-tests/journey/petitionsClerkServesPetitionFromDocumentView.ts
  web-client/integration-tests/journey/petitionsClerkSubmitsCaseToIrs.ts
  web-client/integration-tests/journey/petitionsClerkSubmitsPaperCaseToIrs.ts
  web-client/integration-tests/petitionsClerkCreatesEstateCaseWithLongAdditionalName.test.ts
  web-client/integration-tests/petitionsClerkQCPaperFiledPetition.test.ts
  web-client/integration-tests/petitionsClerkServesPaperCaseToIRS.ts
  web-client/src/presenter/actions/CaseConfirmation/serveToIrsCompleteAction.ts
  web-client/src/presenter/actions/StartCaseInternal/serveCaseToIrsAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/serveCaseToIrsAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/serveCaseToIrsSequence.ts
  web-client/src/presenter/sequences/serveToIrsCompleteSequence.ts
  web-client/src/presenter/sequences/serveToIrsErrorSequence.ts
  web-client/src/providers/socketRouter.test.ts
  web-client/src/providers/socketRouter.ts
  web-client/src/views/CaseDetail/CaseDetailHeader.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/ScanBatchPreviewer.tsx
  web-client/src/views/ServeCaseToIrsErrorModal.tsx
Labels: to staging

#4685 Backmerge Staging into Test
  cypress/cypress-integration/integration/petitions-clerk-views-case-detail.cy.ts
  cypress/cypress-readonly/integration/public/public-docket-record.cy.ts
  cypress/cypress-smoketests/integration/public-docket-record.cy.ts
  cypress/helpers/env/get-public-site-url.ts
  scripts/run-cypress.sh
  web-api/terraform/template/main-east.tf
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/Header/AccountMenu.tsx
  web-client/src/views/Public/PublicDocketRecordHeader.tsx
Labels: to test

#4615 DevEx 1195: Determine when the indexing of migrated data is complete without referencing another cluster
  .circleci/config.yml
  scripts/dynamo/set-local-migration-complete-marker.ts
  scripts/dynamo/set-migration-complete-marker.sh
  scripts/jest-scripts.config.ts
  shared/admin-tools/aws/lambdaHelper.test.ts
  shared/admin-tools/aws/lambdaHelper.ts
  shared/admin-tools/circleci/circleci-helper.ts
  shared/admin-tools/elasticsearch/check-reindex-complete.test.ts
  shared/admin-tools/elasticsearch/check-reindex-complete.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.test.ts
  shared/src/business/useCases/processStreamRecords/processCompletionMarkers.ts
  shared/src/business/useCases/processStreamRecords/processStreamUtilities.test.ts
  shared/src/business/useCases/processStreamRecords/processStreamUtilities.ts
  shared/src/business/useCases/processStreamRecordsInteractor.ts
  web-api/enable-deploying-dynamo-stream-trigger.sh
  web-api/src/lambdas/streams/processStreamRecordsLambda.test.ts
  web-api/src/lambdas/streams/processStreamRecordsLambda.ts
  web-api/src/persistence/elasticsearch/bulkIndexRecords.ts
  web-api/terraform/bin/edit-lambda-environment.sh
  web-api/terraform/bin/edit-lambda-environment.ts
  web-api/workflow-terraform/reindex-cron/bin/deploy-init.sh
  web-api/workflow-terraform/reindex-cron/main/lambdas/reindex-status.js
  web-api/workflow-terraform/reindex-cron/main/lambdas/reindex-status.test.js
  web-api/workflow-terraform/reindex-cron/main/reindex-status.tf
  web-api/workflow-terraform/reindex-cron/main/variables.tf
Labels: to staging

#4690 10217 DOD
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/ElectronicPetition.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.test.ts
  shared/src/business/useCases/createCaseFromPaperInteractor.ts
  shared/src/business/useCases/createCaseInteractor.test.ts
  shared/src/business/useCases/createCaseInteractor.ts
  shared/src/business/useCases/externalDocument/uploadExternalDocumentsInteractor.ts
  shared/src/business/useCases/filePetitionFromPaperInteractor.test.ts
  shared/src/business/useCases/filePetitionInteractor.ts
  shared/src/business/useCases/generateDocumentIds.test.ts
  shared/src/business/useCases/generateDocumentIds.ts
  shared/src/proxies/createCaseFromPaperProxy.ts
  shared/src/proxies/createCaseProxy.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/createCaseAction.test.ts
  web-client/src/presenter/actions/createCaseAction.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.test.ts
  web-client/src/presenter/actions/createCaseFromPaperAction.ts
  web-client/src/presenter/actions/setProgressForFileUploadAction.test.ts
  web-client/src/presenter/actions/setProgressForFileUploadAction.ts
  web-client/src/presenter/state.ts
Labels: to test
