Repository ustaxcourt/ef-cms, pull requests merged in 2025-05, with the labels that each got.

#6019 Fix Query Param Arrays;
  web-api/src/app-public.ts
Labels: to test

#6016 10502 to Test: Point All Traffic to the East
  web-api/src/business/useCases/user/queueEmailUpdateAssociatedCasesWorker.test.ts
  web-api/src/business/useCases/user/queueEmailUpdateAssociatedCasesWorker.ts
  web-api/src/database.ts
  web-api/src/environment.ts
  web-api/src/persistence/postgres/cases/mocks.jest.ts
  web-api/src/persistence/postgres/cases/reports/getCasesByEmailTotal.ts
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/allColors/variables.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/bin/delete-route53-latency-records.ts
  web-api/terraform/bin/deploy-app-all-colors.sh
  web-api/terraform/modules/api/api-public.tf
  web-api/terraform/modules/api/api.tf
  web-api/terraform/modules/api/variables.tf
  web-api/terraform/modules/api/websockets.tf
  web-api/terraform/modules/everything-else-deprecated/main-east.tf
  web-api/terraform/modules/everything-else-deprecated/main-west.tf
  web-api/terraform/modules/everything-else-deprecated/variables.tf
Labels: to test

#6021 10502: add migration 0017 to add columns to dw_case
  web-api/src/persistence/postgres/utils/migrate/migrations/0017-some-case-tables-to-jsonb.ts
Labels: to test

#6020 Fix Query Param Arrays;
  cypress/local-only/tests/integration/public/practitioner-search.cy.ts
  web-api/src/app-public.ts
Labels: to staging

#6028 10502: better error message for failure in acquireLock
  web-api/src/business/useCaseHelper/acquireLock.ts
Labels: to test

#6034 10658: Add stats when generating pdfs
  web-api/src/lambdas/pdfGeneration/lambdaStats.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
Labels: to test

#6038 10502 dxox: Fixes to getConnection
  web-api/src/business/useCases/createCaseFromPaperInteractor.ts
  web-api/src/business/useCases/createCaseInteractor.ts
  web-api/src/getConnection.ts
  web-api/src/getConnection1.test.ts
  web-api/src/getConnection2.test.ts
  web-api/src/getConnection3.test.ts
  web-api/src/getConnection4.test.ts
  web-api/src/persistence/postgres/cases/generateDocketNumber.ts
Labels: to test

#6053 10502-dxox: better logging around acquire lock error
  web-api/src/business/useCaseHelper/acquireLock.ts
Labels: to test

#6079 10643 Bug: Fix Order Response edit link issue
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/StatusReportOrder/isEditOrderResponseAction.ts
Labels: to test, Review Please

#6080 10419: Remove description from prepopulated actions and filings items
  shared/src/authorization/authorizationClientService.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.test.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.ts
Labels: to test

#6084 10506-dxox test
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/maintenance/sendMaintenanceNotificationsInteractor.ts
  web-api/src/business/useCases/notifications/onConnectInteractor.test.ts
  web-api/src/business/useCases/notifications/onConnectInteractor.ts
  web-api/src/business/useCases/notifications/onDisconnectInteractor.ts
  web-api/src/business/useCases/user/generateChangeOfAddress.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.locking.test.ts
  web-api/src/database-schema.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/src/dispatchers/slack/sendSlackNotification.test.ts
  web-api/src/dispatchers/slack/sendSlackNotification.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/rdsExpiredRecordsCleanup/rdsExpiredRecordsCleanupLambda.ts
  web-api/src/notifications/retrySendNotificationToConnections.ts
  web-api/src/notifications/sendNotificationToConnection.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/createChangeOfAddressJob.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/setChangeOfAddressCaseAsDone.ts
  web-api/src/persistence/dynamo/notifications/deleteUserConnection.test.ts
  web-api/src/persistence/dynamo/notifications/deleteUserConnection.ts
  web-api/src/persistence/dynamo/notifications/getAllWebSocketConnections.ts
  web-api/src/persistence/dynamo/notifications/getDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/getDispatchNotification.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.test.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.ts
  web-api/src/persistence/dynamo/notifications/saveDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/saveDispatchNotification.ts
  web-api/src/persistence/dynamo/notifications/saveUserConnection.test.ts
  web-api/src/persistence/dynamo/notifications/saveUserConnection.ts
  web-api/src/persistence/postgres/connections/deleteUserConnection.ts
  web-api/src/persistence/postgres/connections/getAllWebSocketConnections.ts
  web-api/src/persistence/postgres/connections/getWebSocketConnectionsByUserId.ts
  web-api/src/persistence/postgres/connections/saveUserConnection.ts
  web-api/src/persistence/postgres/connections/schema.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/createChangeOfAddressJob.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/deleteChangeOfAddressCaseRecord.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/schema.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/setChangeOfAddressCaseAsDone.ts
  web-api/src/persistence/postgres/notifications/getDispatchNotification.ts
  web-api/src/persistence/postgres/notifications/saveDispatchNotification.ts
  web-api/src/persistence/postgres/notifications/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0019-connections.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0020-notification.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0021-change-of-adress.ts
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/lambda/lambda.tf
  web-api/terraform/modules/rds-expired-records-cleanup/rds-expired-records-cleanup.tf
  web-api/terraform/modules/rds-expired-records-cleanup/variables.tf
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/websocketConnectionDisconnection.test.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: Do Not Merge, to test

#6086 10502: added steps to enable and disable maintenance mode during deployment
  .circleci/config.yml
  scripts/user/setup-glued-judges.ts
Labels: to staging
