Repository ustaxcourt/ef-cms, pull requests merged in 2025-02, with the labels that each got.

#5746 devex: limit QC user inbox to only uncompleted (to test)
  web-api/src/persistence/postgres/workitems/getDocumentQCInboxForUser.ts
Labels: to test

#5745 deploy docker-image-zipper in parallel in prod
  .circleci/config.yml
Labels: to staging

#5748 HOTFIX: limit QC user inbox to only uncompleted work items
  web-api/src/persistence/postgres/workitems/getDocumentQCInboxForUser.ts
Labels: bugfix

#5749 10333 to test 20250203
  package-lock.json
  package.json
  web-client/src/styles/custom.scss
  web-client/src/uswds/_index.scss
  web-client/src/views/AdvancedSearch/CaseSearchByDocketNumber.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/AdvancedSearch/OpinionSearchForm.tsx
  web-client/src/views/AdvancedSearch/OrderSearchForm.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByBarNumber.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/EditPetitionerCounsel.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/EditRespondentCounsel.tsx
  web-client/src/views/Login/ForgotPassword.tsx
  web-client/src/views/Login/Login.tsx
  web-client/src/views/ModalDialog.tsx
Labels: to test

#5747 devex: limit QC user inbox to only uncompleted
  web-api/src/persistence/postgres/workitems/getDocumentQCInboxForUser.ts
Labels: to staging

#5753 OpEx: Once a month, generate a fresh "stale cases" CSV and email it to stakeholders
  .circleci/config.yml
  package.json
  scripts/reports/stale-cases.helpers.ts
  scripts/reports/stale-cases.ts
  web-api/src/dispatchers/ses/sendEmailWithAttachment.test.ts
  web-api/src/dispatchers/ses/sendEmailWithAttachment.ts
  web-api/src/lambdas/staleCasesEmail/staleCasesEmailLambda.test.ts
  web-api/src/lambdas/staleCasesEmail/staleCasesEmailLambda.ts
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/variables.tf
  web-api/terraform/bin/deploy-stale-cases-email-cron.sh
  web-api/terraform/bin/destroy-stale-cases-email-cron.sh
  web-api/terraform/modules/stale-cases-email-cron/stale-cases-email-cron.tf
  web-api/terraform/modules/stale-cases-email-cron/variables.tf
Labels: to staging, Review Please

#5757 fix dynamodb table replicas being recreated
  web-api/terraform/modules/dynamo-table/dynamo.tf
Labels: to staging, Review Please

#5762 Dependency updates for week of 2025-02-03
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: dependencies, to staging, Review Please

#5760 10333 to test 20250203
  stylelint.config.js
  web-client/src/styles/overrides.scss
Labels: to test, Review Please

#5698 bug-fix: use absolute paths for podmon-compose
  run-local.sh
Labels: Review Please

#5768 Remove flaky multi-tab tests
  cypress/local-only/tests/integration/logoutBehavior/idle-logout.cy.ts
Labels: to staging

#5772 10598 Bug: Case Deadlines Blocked Issues in West
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/Case.updateAutomaticBlocked.test.ts
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.test.ts
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
Labels: to test

#5774 10373: Handle Feedback
  scripts/run-once-scripts/lockingManager.sh
  shared/src/proxies/polling/startPollingForResultsProxy.test.ts
  shared/src/proxies/polling/startPollingForResultsProxy.ts
  web-client/src/presenter/actions/closeFileUploadStatusModalAction.test.ts
  web-client/src/presenter/actions/closeFileUploadStatusModalAction.ts
Labels: to test

#5771 10570: Full Spectrum Sorting: Pending Report TO TEST
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.test.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.ts
  shared/src/proxies/pendingItems/exportPendingReportProxy.ts
  shared/src/proxies/pendingItems/generatePrintablePendingReportProxy.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.test.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.ts
  web-api/src/business/useCases/pendingItems/generatePrintablePendingReportInteractor.ts
  web-client/src/presenter/actions/PendingItems/generatePrintablePendingReportAction.ts
  web-client/src/presenter/actions/exportPendingReportAction.test.ts
  web-client/src/presenter/actions/exportPendingReportAction.ts
  web-client/src/presenter/computeds/pendingReportHelper.test.ts
  web-client/src/presenter/computeds/pendingReportHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/ustc-ui/Table/SortableHeader.tsx
  web-client/src/views/PendingReport/PendingReport.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
Labels: to test, Review Please

#5780 Fix Buggy cypress tests on document upload
  cypress/helpers/cypressTasks/cognito/cognito-helpers.ts
  cypress/support/commands.ts
Labels: to test

#5778 10570: Refactor + UI Feedback;
  shared/src/proxies/pendingItems/generatePrintablePendingReportProxy.ts
  web-client/src/presenter/actions/PendingItems/generatePrintablePendingReportAction.test.ts
  web-client/src/presenter/actions/PendingItems/generatePrintablePendingReportAction.ts
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/PendingReport/PendingReport.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to test, Review Please

#5776 10598 Bug: Case Deadlines Blocked Issues in West (Part 2)
  web-api/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  web-client/src/presenter/actions/CaseDeadline/createCaseDeadlineAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/createCaseDeadlineAction.ts
  web-client/src/presenter/actions/CaseDeadline/deleteCaseDeadlineAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/deleteCaseDeadlineAction.ts
Labels: to test, Review Please

#5789 10419: fix setting of trial clerk name on initialization
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.ts
Labels: to test

#5777 Dependency Updates Week of 2025 Feb 10
  .circleci/config.yml
  .github/workflows/typescript-all-files-check.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/checkAllFilesForTypeErrorCount.ts
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging, Review Please

#5792 Add GitHub actions kysely migrations check
  .github/workflows/kysely-migration-order.yml
  scripts/postgres/checkKyselyMigrations.ts
Labels: to test, Review Please

#5794 10570: Add default sorting settings in Pending Report table
  web-client/src/presenter/actions/PendingItems/setDefaultPendingReportTableSortAction.test.ts
  web-client/src/presenter/actions/PendingItems/setDefaultPendingReportTableSortAction.ts
  web-client/src/presenter/sequences/gotoPendingReportSequence.ts
Labels: to test

#5781 10536: Fix messages jumping when clicking message complete checkbox;
  cypress/local-only/tests/integration/messages/messages.cy.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test, Review Please

#5775 10598 Bug: Case Deadlines Blocked Issues in West
  shared/src/business/entities/cases/Case.ts
  shared/src/business/entities/cases/Case.updateAutomaticBlocked.test.ts
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.test.ts
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.ts
  web-api/src/business/useCaseHelper/docketEntry/fileAndServeDocumentOnOneCase.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.ts
  web-client/src/presenter/actions/CaseDeadline/createCaseDeadlineAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/createCaseDeadlineAction.ts
  web-client/src/presenter/actions/CaseDeadline/deleteCaseDeadlineAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/deleteCaseDeadlineAction.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/tables.scss
Labels: to staging, Review Please

#5788 Upgrade React v19
  package-lock.json
  package.json
  shared/jest-shared.config.ts
  web-client/JsdomWithTextEncoderEnvironment.js
  web-client/JsdomWithTextEncoderEnvironment.ts
  web-client/jest-unit.config.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/ustc-ui/Quill/Quill.tsx
  web-client/src/ustc-ui/Quill/quill.snow.css
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
  web-client/src/views/CreateOrder/TextEditor.tsx
  web-client/src/views/InfoNotification.tsx
Labels: to test

#5808 USWDS: Fix alignment of ModalDialog buttons
  web-client/src/views/ModalDialog.tsx
Labels: to staging

#5809 USWDS: Fix alignment of ModalDialog buttons
  web-client/src/views/ModalDialog.tsx
Labels: to test

#5816 10570: Add missing properties for sorting;
  shared/src/business/utilities/pendingItem/sortPendingReportItems.test.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.ts
  web-client/src/views/PendingReport/PendingReportList.tsx
Labels: to test, Review Please

#5827 10600: enable the expensive_request_limit WAF rule in test
  web-api/terraform/modules/waf/main.tf
Labels: to test

#5831 10502: add statusUpdateId primary key
  shared/src/business/entities/cases/Case.ts
  web-api/src/database-types.ts
  web-api/src/persistence/postgres/cases/mapper.ts
  web-api/src/persistence/postgres/cases/upsertCaseStatusUpdates.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0010-case-status-updates.ts
  web-api/src/persistence/postgres/utils/seed/seed.ts
Labels: to test

#5821 10570: Full Spectrum Sorting: Pending Report
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.test.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.ts
  shared/src/proxies/pendingItems/exportPendingReportProxy.ts
  shared/src/proxies/pendingItems/generatePrintablePendingReportProxy.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.test.ts
  web-api/src/business/useCases/pendingItems/exportPendingReportInteractor.ts
  web-api/src/business/useCases/pendingItems/generatePrintablePendingReportInteractor.ts
  web-client/src/presenter/actions/PendingItems/generatePrintablePendingReportAction.test.ts
  web-client/src/presenter/actions/PendingItems/generatePrintablePendingReportAction.ts
  web-client/src/presenter/actions/PendingItems/setDefaultPendingReportTableSortAction.test.ts
  web-client/src/presenter/actions/PendingItems/setDefaultPendingReportTableSortAction.ts
  web-client/src/presenter/actions/exportPendingReportAction.test.ts
  web-client/src/presenter/actions/exportPendingReportAction.ts
  web-client/src/presenter/computeds/pendingReportHelper.test.ts
  web-client/src/presenter/computeds/pendingReportHelper.ts
  web-client/src/presenter/sequences/gotoPendingReportSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/ustc-ui/Table/SortableHeader.tsx
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/PendingReport/PendingReport.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
  web-client/src/views/Public/PublicDocketRecord.tsx
Labels: to staging, Review Please

#5790 Add GitHub actions kysely migrations check
  .github/workflows/kysely-migration-order.yml
  scripts/postgres/checkKyselyMigrations.ts
Labels: to staging

#5810 Fix Flaky Cypress test
  cypress/helpers/retry.ts
  cypress/local-only/tests/integration/statusReportOrder/edit-status-report-order.cy.ts
Labels: to staging, Review Please

#5793 Create and serve paper petition fix
  cypress/helpers/fileAPetition/create-and-serve-paper-petition.ts
Labels: to staging

#5820 5377: return country in v2 API results
  docs/additional-resources/troubleshooting.md
  docs/api/v2.yaml
  docs/running-locally.md
  web-api/src/lambdas/v2/marshallers/marshallContact.test.ts
  web-api/src/lambdas/v2/marshallers/marshallContact.ts
Labels: to staging

#5836 10536: Bug - redeploy
  cypress/local-only/tests/integration/messages/messages.cy.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to test

#5838 10569 story
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  shared/src/business/utilities/aggregateCommonQueryParams.test.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-api/src/persistence/elasticsearch/caseAdvancedSearch.test.ts
  web-api/src/persistence/elasticsearch/caseAdvancedSearch.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByDocketNumber.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/AdvancedSearch/CaseSearchForm.tsx
Labels: to test

#5834 10587 depricate unused and add M045A event code
  cypress/local-only/tests/integration/documentQC/docket-clerk-qcs-paper-filing.cy.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
Labels: to test

#5829 10536: Fix messages jumping when clicking message complete checkbox;
  cypress/local-only/tests/integration/messages/messages.cy.ts
  web-client/src/presenter/computeds/formattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.test.ts
  web-client/src/presenter/utilities/processFormattedMessages.ts
Labels: to staging, Review Please

#5842 devex: support postgres connections locally when using the env switcher
  scripts/env/environments/00-common
  scripts/env/unset-env.zsh
Labels: to staging
