Repository ustaxcourt/ef-cms, pull requests merged in 2025-08, with the labels that each got.

#6305 10701: Stubbing out folder structure for new consolidated dawson components.
  web-client/src/dawson-ui/dawson-alert/dummyfile
  web-client/src/dawson-ui/dawson-banner/dummyfile
  web-client/src/dawson-ui/dawson-button/dummyfile
  web-client/src/dawson-ui/dawson-card/dummyfile
  web-client/src/dawson-ui/dawson-colors/dummyfile
  web-client/src/dawson-ui/dawson-date-picker/dummyfile
  web-client/src/dawson-ui/dawson-radio/dummyfile
  web-client/src/dawson-ui/dawson-search/dummyfile
  web-client/src/dawson-ui/dawson-tag/dummyfile
  web-client/src/dawson-ui/dawson-text-input/dummyfile
  web-client/src/dawson-ui/dawson-text/dummyfile
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/Public/goToDawsonUIComponentSequence.ts
  web-client/src/routerPublic.ts
  web-client/src/views/Public/DawsonUIComponents.tsx
Labels: to staging

#6373 devex: fix condition in merge-staging-to script
  scripts/git/merge-staging-to.sh
Labels: to staging

#6270 10652: status report order enhancement
  cypress/helpers/caseDetail/docketRecord/courtIssuedFiling/create-status-report-order.ts
  cypress/helpers/trialSession/calendar-trial-session.ts
  cypress/helpers/trialSession/schedule-trial-session.ts
  cypress/local-only/tests/integration/statusReportOrder/status-report-order-description-fields.cy.ts
  web-client/src/presenter/actions/CaseDetail/isCaseCalendaredAction.test.ts
  web-client/src/presenter/actions/CaseDetail/isCaseCalendaredAction.ts
  web-client/src/presenter/actions/CaseDetail/setTrialSessionIdFromCaseDetailAction.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/prepareStatusReportOrderAction.ts
  web-client/src/presenter/computeds/statusReportOrderHelper.test.ts
  web-client/src/presenter/computeds/statusReportOrderHelper.ts
  web-client/src/presenter/sequences/StatusReportOrder/statusReportOrderPdfPreviewSequence.ts
  web-client/src/views/StatusReportOrder.tsx
Labels: to staging, Review Please

#6263 10603 deadline report usability
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReport.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/updateDateRangeForDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/updateDateRangeForDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/updateJudgeIdForDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/sequences/filterCaseDeadlinesByJudgeSequence.ts
  web-client/src/presenter/sequences/updateCaseDeadlineReportPageSequence.ts
  web-client/src/presenter/sequences/updateDateRangeForDeadlinesSequence.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to staging, Review Please

#6379 opex-dkim-naming-for-prod: set the dkim name format
  web-api/terraform/modules/everything-else-deprecated/ses.tf
Labels: to staging

#6363 10139 prevent practitioner employer change when associated with open cases
  web-api/src/business/useCases/practitioner/updatePractitionerUserInteractor.test.ts
  web-api/src/business/useCases/practitioner/updatePractitionerUserInteractor.ts
  web-client/src/presenter/actions/Practitioners/setPractitionerDetailOnFormAction.test.ts
  web-client/src/presenter/actions/Practitioners/setPractitionerDetailOnFormAction.ts
  web-client/src/presenter/actions/hasUpdatedPracticeTypeFactoryAction.test.ts
  web-client/src/presenter/actions/hasUpdatedPracticeTypeFactoryAction.ts
  web-client/src/presenter/actions/validatePracticeTypeChangeAction.test.ts
  web-client/src/presenter/actions/validatePracticeTypeChangeAction.ts
  web-client/src/presenter/sequences/submitUpdatePractitionerUserSequence.ts
  web-client/src/views/Practitioners/PractitionerForm.tsx
Labels: to staging

#6385 10576: Handle Lead Cases being closed;
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.deadlines.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.consolidateCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/mocks.jest.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-11T22_34_57Z-add-consolidated-case-deadline-id-column.ts
  web-client/src/presenter/computeds/formattedCaseDeadlines.test.ts
Labels: to test

#6387 10735 case deadlines report hotfix to test
  cypress/local-only/tests/integration/caseDeadlines/run-deadlines-report.cy.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to test, Review Please

#6382 10574 add deadline to sro to test unblocked
  cypress/local-only/tests/integration/caseDeadline/case-deadline-on-a-status-report-order.cy.ts
  web-api/src/business/useCaseHelper/autoGenerateDeadline.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.deadlines.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.consolidateCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.deadlines.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
  web-client/src/views/StatusReportOrder.tsx
Labels: to test, Review Please

#6376 10637 dxox postgres intermediate branch to test 1754060304
  .circleci/config.yml
  scripts/archived/run-once/postgres-migration/delete-messages.ts
  scripts/run-once-scripts/postgres-migration/delete-practitioner-documents.ts
  scripts/run-once-scripts/postgres-migration/migrateAllPractitionerDocumentsIntoPostgres.ts
  scripts/upload-practitioner-application-packages.md
  scripts/upload-practitioner-application-packages.ts
  shared/src/proxies/getPractitionerDocumentDownloadUrlProxy.ts
  web-api/src/business/useCases/practitioner/createPractitionerDocumentInteractor.test.ts
  web-api/src/business/useCases/practitioner/createPractitionerDocumentInteractor.ts
  web-api/src/business/useCases/practitioner/deletePractitionerDocumentInteractor.test.ts
  web-api/src/business/useCases/practitioner/deletePractitionerDocumentInteractor.ts
  web-api/src/business/useCases/practitioner/editPractitionerDocumentInteractor.test.ts
  web-api/src/business/useCases/practitioner/editPractitionerDocumentInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentDownloadUrlInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentDownloadUrlInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentInteractor.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentsInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionerDocumentsInteractor.ts
  web-api/src/database-schema.ts
  web-api/src/database.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/dynamo/practitioners/createPractitionerDocument.ts
  web-api/src/persistence/dynamo/practitioners/deletePractitionerDocument.test.ts
  web-api/src/persistence/dynamo/practitioners/deletePractitionerDocument.ts
  web-api/src/persistence/dynamo/practitioners/editPractitionerDocument.test.ts
  web-api/src/persistence/dynamo/practitioners/editPractitionerDocument.ts
  web-api/src/persistence/dynamo/practitioners/getPractitionerDocumentByFileId.ts
  web-api/src/persistence/dynamo/practitioners/getPractitionerDocuments.ts
  web-api/src/persistence/postgres/practitionerDocuments/createOrEditPractitionerDocument.ts
  web-api/src/persistence/postgres/practitionerDocuments/deletePractitionerDocument.ts
  web-api/src/persistence/postgres/practitionerDocuments/getPractitionerDocumentByFileId.ts
  web-api/src/persistence/postgres/practitionerDocuments/getPractitionerDocuments.ts
  web-api/src/persistence/postgres/practitionerDocuments/mapper.ts
  web-api/src/persistence/postgres/practitionerDocuments/mocks.jest.ts
  web-api/src/persistence/postgres/practitionerDocuments/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-03T15_25_30Z-connections.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-07-17T17_05_49Z-practitioner-documents.ts
Labels: to test

#6388 Devex: Remove processDocketEntries
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.test.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/elasticsearch/deleteRecord.test.ts
  web-api/src/persistence/elasticsearch/deleteRecord.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to staging

#6360 10687 - Add Docket Index Number to Message Attachment UI
  shared/src/business/utilities/formatAttachments.test.ts
  shared/src/business/utilities/formatAttachments.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
Labels: to staging

#6398 10576: Bug Fix
  cypress/helpers/caseDetail/add-case-to-group.ts
  cypress/helpers/fileAPetition/create-consolidated-case-group.ts
  cypress/local-only/tests/integration/caseDeadline/case-deadline-on-a-consolidated-group.cy.ts
  cypress/local-only/tests/integration/caseDeadline/case-deadline-on-a-status-report-order.cy.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.ts
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.consolidatedCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.getDeleteCaseDeadlineInteractorLockInfo.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/elasticsearch/deleteRecord.test.ts
  web-api/src/persistence/elasticsearch/deleteRecord.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineIds.ts
  web-api/src/persistence/postgres/caseDeadlines/mocks.jest.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-11T22_34_57Z-add-consolidated-case-deadline-id-column.ts
  web-client/src/styles/custom.scss
  web-client/src/test/createClientTestApplicationContext.ts
Labels: Do Not Merge, to test

#6399 10685 display recently filed docs to test 1754680653
  cypress/local-only/tests/integration/recentFilings/irsPractitioner.cy.ts
  cypress/local-only/tests/integration/recentFilings/petitioner.cy.ts
  cypress/local-only/tests/integration/recentFilings/privatePractitioner.cy.ts
  cypress/local-only/tests/integration/recentFilings/recentFilingsJourney.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/RecentFiling.ts
  shared/src/business/useCases/getNotificationsInteractor.test.ts
  shared/src/business/useCases/getRecentFilingsForUserInteractor.test.ts
  shared/src/business/useCases/getRecentFilingsForUserInteractor.ts
  shared/src/business/utilities/sortRecentFilings.test.ts
  shared/src/business/utilities/sortRecentFilings.ts
  shared/src/proxies/getRecentFilingsForUserProxy.ts
  web-api/src/app.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/recentFilings/getRecentFilingsForUserLambda.ts
  web-client/src/presenter/actions/Dashboard/getRecentFilingsForUserAction.ts
  web-client/src/presenter/actions/setRecentFilingsAction.ts
  web-client/src/presenter/actions/setRecentFilingsTableSortAction.ts
  web-client/src/presenter/computeds/headerHelper.ts
  web-client/src/presenter/computeds/recentFilingsHelper.test.ts
  web-client/src/presenter/computeds/recentFilingsHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoRecentFilingsSequence.ts
  web-client/src/presenter/sequences/loadRecentFilingsSequence.ts
  web-client/src/presenter/sequences/setRecentFilingsTableSortSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponent.tsx
  web-client/src/views/BigHeader.tsx
  web-client/src/views/Dashboards/DashboardExternalUser.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/RecentFilings/RecentFilings.tsx
  web-client/src/views/RecentFilings/RecentFilingsDocumentDisplay.test.tsx
  web-client/src/views/RecentFilings/RecentFilingsDocumentDisplay.tsx
  web-client/src/views/RecentFilings/RecentFilingsMobile.tsx
  web-client/src/views/RecentFilings/RecentFilingsNonMobile.tsx
Labels: to test, Review Please

#6392 updated packages & fixed security issues
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging

#6406 10495 big ol user table latest to test
  .circleci/config.yml
  scripts/jest-scripts.config.ts
  scripts/judge/change-chief-judge.sh
  scripts/judge/get-judge-name.ts
  scripts/judge/set-judge-title.ts
  scripts/reindex/index-users/_index-users-child.ts
  scripts/reindex/index-users/index-users.ts
  scripts/run-once-scripts/postgres-migration/move-petitioners-out-of-case.ts
  shared/src/business/useCases/automations/automationsHelpers.test.ts
  shared/src/business/useCases/automations/automationsHelpers.ts
  shared/src/business/useCases/automations/deactivateUserInteractor.test.ts
  shared/src/business/useCases/automations/deactivateUserInteractor.ts
  shared/src/business/useCases/automations/getRegStatusInteractor.test.ts
  shared/src/business/useCases/automations/getRegStatusInteractor.ts
  web-api/src/lambdas/automations/regStatusLambda.ts
  web-api/src/persistence/postgres/cases/getCasesByDocketNumbers.ts
  web-api/src/persistence/postgres/users/deactivateUser.ts
Labels: to test

#6416 bug: fix terraform providers
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/ui/providers.tf
Labels: to staging

#6414 10576: Handle Lead Cases being closed;
  cypress/helpers/caseDetail/add-case-to-group.ts
  cypress/helpers/fileAPetition/create-consolidated-case-group.ts
  cypress/local-only/tests/integration/caseDeadline/case-deadline-on-a-consolidated-group.cy.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.ts
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.consolidateCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.consolidatedCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.getDeleteCaseDeadlineInteractorLockInfo.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineIds.ts
  web-api/src/persistence/postgres/caseDeadlines/mocks.jest.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-11T22_34_57Z-add-consolidated-case-deadline-id-column.ts
  web-client/src/views/CaseDetail/CaseDeadline/ConsolidatedCaseGroupInfo.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/DeleteCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
Labels: to staging

#6438 Devex promote docker image from one ecr to another;
  docs/additional-resources/troubleshooting.md
  docs/ci-cd.md
  docs/environments.md
  docs/operations/runbooks/create-new-lower-environment.md
  package.json
  scripts/ecr/docker-to-ecr.sh
  scripts/ecr/pull-and-tag.ts
  scripts/jest-scripts.config.ts
Labels: to staging

#6353 10684 Large Case Followup (dropping a table)
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-07-26T23_34_53Z-drop-docketEntry-from-dwWorkItem.ts
Labels: to staging

#6458 8727 order search improvements
  shared/src/business/entities/EntityConstants.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
Labels: to test

#6459 Backmerge `staging` into `test` 1755724089
  docs/running-locally.md
Labels: to test

#6462 Backmerge `staging` into `test` 1755737557
  shared/src/business/utilities/getWorkQueueFilters.ts
  web-api/src/business/useCases/workItems/getDocumentQCInboxForUserInteractor.ts
  web-api/src/persistence/postgres/docketEntries/schema.ts
Labels: to test

#6327 10695 UX Design: added Daw fonts
  web-client/src/styles/dawson_fonts.scss
Labels: to staging

#6469 10749 BUG: ignore suffixes when sorting docket numbers
  shared/src/business/entities/cases/Case.getSortableDocketNumber.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/utilities/sortRecentFilings.test.ts
Labels: to test, Review Please

#6461 dependencies: update packages for debian trixie
  Dockerfile
Labels: dependencies

#6475 8727: order search improvements
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
Labels: to test

#6433 Updated packages
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/ecr/docker-to-ecr.sh
  scripts/ecr/pull-and-tag.ts
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: dependencies, to staging, Review Please

#6480 9619 sealing email address to test
  cypress/local-only/tests/integration/sealedContactInformation/sealed-contact-information.cy.ts
  shared/src/business/useCases/updateContactInteractor.ts
  shared/src/business/utilities/calculateEmail.test.ts
  shared/src/business/utilities/calculateEmail.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/ChangeOfAddress.tsx
  web-api/src/business/useCaseHelper/service/createChangeItems.ts
  web-client/src/presenter/computeds/partiesInformationHelper.test.ts
  web-client/src/presenter/computeds/partiesInformationHelper.ts
  web-client/src/ustc-ui/Modal/ConfirmModal.tsx
  web-client/src/views/CaseDetail/AddressDisplay.tsx
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
  web-client/src/views/CaseDetail/SealAddressModal.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
Labels: to test, Review Please

#6487 8727: split advanced search into two 5k calls to prevent Lambda 502
  shared/src/business/useCases/opinionAdvancedSearchInteractor.test.ts
  shared/src/business/useCases/opinionAdvancedSearchInteractor.ts
  shared/src/business/useCases/orderAdvancedSearchInteractor.test.ts
  shared/src/business/useCases/orderAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/opinionPublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/opinionPublicSearchInteractor.ts
  web-api/src/business/useCases/public/orderPublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/orderPublicSearchInteractor.ts
  web-client/src/presenter/actions/AdvancedSearch/submitOpinionAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitOpinionAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitOrderAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitOrderAdvancedSearchAction.ts
  web-client/src/presenter/actions/Public/submitPublicOpinionAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicOpinionAdvancedSearchAction.ts
  web-client/src/presenter/actions/Public/submitPublicOrderAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/Public/submitPublicOrderAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
Labels: to test

#9051 Opex: script to transfer issues
  scripts/archived/run-once/transfer-issues.ts
Labels: to staging

#6485 10576: Short circuit when no lead deadline is provided TEST;
  cypress/local-only/tests/integration/caseDeadline/lead-case-can-be-unconsolidated.cy.ts
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineIds.ts
Labels: to test, Review Please

#9061 9619 sealing email address to test
  web-api/src/business/useCaseHelper/service/createChangeItems.ts
  web-client/src/views/CaseDetail/ParticipantsAndCounsel.tsx
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
Labels: to test, Review Please
