Repository ustaxcourt/ef-cms, pull requests merged in 2025-01, with the labels that each got.

#5671 10293 design debt intermediate branch to test 1732629359
  shared/src/business/entities/EntityConstants.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.ts
Labels: to test, Review Please

#5670 10491 (Postgres Work Items): Fix Document QC Served
  web-api/src/persistence/postgres/workitems/getDocumentQCServedForUser.ts
Labels: to test

#5663 10434: Trial Session Planning Report - Screen Version
  cypress/local-only/tests/accessibility/trialSessionPlanningReport/trial-session-planning-report-view.cy.ts
  cypress/local-only/tests/integration/trialSessionsPlanningReport/trial-session-planning-report-view.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.test.ts
  shared/src/business/utilities/documentGenerators/trialSessionPlanningReport.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/TrialSessionPlanningReport.tsx
  shared/src/business/utilities/trialSessionPlanningReport/trialSessionPlanningReportDataTypes.ts
  shared/src/proxies/trialSessions/getTrialSessionPlanningReportProxy.ts
  shared/test-pdf-expected-images/Trial_Session_Planning_Report.pdf.1.png
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.test.ts
  web-api/src/business/useCases/trialSessions/runTrialSessionPlanningReportInteractor.ts
  web-api/src/getUseCases.ts
  web-api/src/lambdas/trialSessions/getTrialSessionPlanningReportLambda.ts
  web-client/src/app.tsx
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/TrialSession/getTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/getTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/TrialSession/runTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/runTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/TrialSession/setTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportAction.test.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportAction.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportViewAction.test.ts
  web-client/src/presenter/actions/navigateToTrialSessionPlanningReportViewAction.ts
  web-client/src/presenter/actions/setupTrialSessionPlanningReportViewDataAction.test.ts
  web-client/src/presenter/actions/setupTrialSessionPlanningReportViewDataAction.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.test.ts
  web-client/src/presenter/actions/validateTrialSessionPlanningAction.ts
  web-client/src/presenter/computeds/trialSessionPlanningReportViewHelper.test.ts
  web-client/src/presenter/computeds/trialSessionPlanningReportViewHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/gotoTrialSessionPlanningReportSequence.ts
  web-client/src/presenter/sequences/gotoTrialSessionPlanningReportViewSequence.ts
  web-client/src/presenter/sequences/navigateToTrialSessionPlanningReportViewSequence.ts
  web-client/src/presenter/sequences/runTrialSessionPlanningReportSequence.ts
  web-client/src/presenter/sequences/validateTrialSessionPlanningSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponent.tsx
  web-client/src/views/Header/ReportsMenu.tsx
  web-client/src/views/TrialSessionPlanningModal.tsx
  web-client/src/views/TrialSessions/TrialSessionPlanningReport.tsx
  web-client/src/views/TrialSessions/TrialSessionPlanningReportView.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to staging, Review Please

#5672 10293: fix import of constant
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.test.ts
  web-api/src/persistence/elasticsearch/getCaseInventoryReport.ts
Labels: to test, Review Please

#5664 10571 : Add Docket Suffix to Custom Case Report Results
  web-api/src/business/useCases/caseInventoryReport/getCustomCaseReportInteractor.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.test.ts
  web-api/src/business/useCases/customCaseReport/createCsvCustomCaseReportFileInteractor.ts
  web-api/src/persistence/elasticsearch/getCasesByFilters.ts
Labels: to staging, Review Please

#5676 10266 story staging intermediate branch to test 1735926536
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
Labels: to test, Review Please

#5673 Dep updates 2025 01 03
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
Labels: to staging

#5678 10293: fix width of two columns in Case Inventory report
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
Labels: to test

#5682 Devex: tear down postgres volumes on (re)starting api locally
  run-local.sh
Labels: to staging

#5684 10522: Notice of Change Trial Location - TO TEST
  cypress/local-only/tests/integration/trialSession/trial-session-change-of-location.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessions/TrialSession.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeOfTrialLocation.test.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeOfTrialLocation.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeOfTrialLocation.tsx
  shared/src/business/utilities/trialSession/hasTrialLocationBeenUpdated.test.ts
  shared/src/business/utilities/trialSession/hasTrialLocationBeenUpdated.ts
  shared/test-pdf-expected-images/Notice_Of_Change_Of_Trial_Location.pdf.1.png
  web-api/src/business/useCaseHelper/trialSessions/setNoticeOfChangeOfTrialLocation.test.ts
  web-api/src/business/useCaseHelper/trialSessions/setNoticeOfChangeOfTrialLocation.ts
  web-api/src/business/useCases/trialSessions/generateNoticeOfChangeOfTrialJudgeInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateNoticeOfChangeOfTrialJudgeInteractor.ts
  web-api/src/business/useCases/trialSessions/generateNoticeOfChangeOfTrialLocationInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateNoticeOfChangeOfTrialLocationInteractor.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  web-api/src/getDocumentGenerators.ts
  web-api/src/getUseCaseHelpers.ts
  web-api/src/getUseCases.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.test.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.ts
  web-client/src/presenter/actions/setConfirmTrialSessionLocationChangeModalAction.test.ts
  web-client/src/presenter/actions/setConfirmTrialSessionLocationChangeModalAction.ts
  web-client/src/presenter/actions/setTrialSessionLocationDifferencesAction.test.ts
  web-client/src/presenter/actions/setTrialSessionLocationDifferencesAction.ts
  web-client/src/presenter/computeds/formattedTrialSessionDetails.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/displayTrialSessionLocationChangeModalSequence.ts
  web-client/src/presenter/sequences/updateTrialSessionSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDetail/AddToTrialModal.tsx
  web-client/src/views/CaseDetail/CaseInformation/TrialInformation.tsx
  web-client/src/views/ConfirmTrialSessionLocationChangeModalDialog.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
Labels: to test, Review Please

#5685 Devex: clear judgeUser state on logout
  web-client/src/presenter/actions/clearUserAction.ts
Labels: to test

#5692 devex: use the right env var in the setup-glued-judges script (to test)
  scripts/user/setup-glued-judges.ts
Labels: to test

#5691 devex: use the right env var in the setup-glued-judges script
  scripts/user/setup-glued-judges.ts
Labels: to staging

#5686 10559 fix h1
  web-client/src/styles/nav.scss
  web-client/src/views/Header/Header.tsx
Labels: to staging

#5693 10491-dxox: Fix processWorkItemEntries
  scripts/run-once-scripts/postgres-migration/delete-work-items.ts
  web-api/src/business/useCases/processStreamRecords/processWorkItemEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processWorkItemEntries.ts
Labels: to test, Review Please

#5696 10580: Fix structured clone error
  web-client/src/applicationContext.ts
Labels: to test, Review Please

#5699 10580: Fix structured clone error
  web-client/src/applicationContext.ts
Labels: to staging

#5687 OpEx: more reports for 2025 Congressional Budget Justification
  scripts/reports/attorneys-admitted-in-year.ts
  scripts/reports/documents-filed-by-nonattorneys.ts
  scripts/reports/lea-stats.ts
  scripts/reports/non-attorney-practitioners.ts
  web-api/elasticsearch/efcms-docket-entry-mappings.ts
  web-api/elasticsearch/efcms-user-mappings.ts
Labels: to staging, Mappings Change(s), Review Please

#5706 10566 - Idle Inactivity Monitor Bug
  cypress.config.ts
  cypress/local-only/support/idleLogoutHelpers.ts
  cypress/local-only/tests/integration/logoutBehavior/idle-logout.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/proxies/auth/deleteAuthCookieProxy.ts
  web-client/src/AppInstanceManager.tsx
  web-client/src/app.tsx
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.test.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.ts
  web-client/src/presenter/actions/broadcastIdleStatusActiveAction.test.ts
  web-client/src/presenter/actions/broadcastIdleStatusActiveAction.ts
  web-client/src/presenter/actions/broadcastLogoutAction.ts
  web-client/src/presenter/actions/broadcastStayLoggedInAction.test.ts
  web-client/src/presenter/actions/broadcastStayLoggedInAction.ts
  web-client/src/presenter/actions/handleIdleLogoutAction.test.ts
  web-client/src/presenter/actions/handleIdleLogoutAction.ts
  web-client/src/presenter/actions/handlePeerResetIdleTimerAction.test.ts
  web-client/src/presenter/actions/handlePeerResetIdleTimerAction.ts
  web-client/src/presenter/actions/resetIdleTimerAction.test.ts
  web-client/src/presenter/actions/resetIdleTimerAction.ts
  web-client/src/presenter/actions/setIdleStatusFactoryAction.test.ts
  web-client/src/presenter/actions/setIdleStatusFactoryAction.ts
  web-client/src/presenter/actions/setIdleTimerRefAction.test.ts
  web-client/src/presenter/actions/setIdleTimerRefAction.ts
  web-client/src/presenter/actions/setLogoutTypeAction.test.ts
  web-client/src/presenter/actions/setLogoutTypeAction.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.test.ts
  web-client/src/presenter/actions/startDelayedLogoutAction.ts
  web-client/src/presenter/computeds/showAppTimeoutModalHelper.test.ts
  web-client/src/presenter/computeds/showAppTimeoutModalHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/broadcastIdleStatusActiveSequence.ts
  web-client/src/presenter/sequences/broadcastStayLoggedInSequence.ts
  web-client/src/presenter/sequences/confirmStayLoggedInSequence.ts
  web-client/src/presenter/sequences/handleIdleLogoutSequence.ts
  web-client/src/presenter/sequences/resetIdleTimerSequence.ts
  web-client/src/presenter/sequences/setIdleStatusActiveSequence.ts
  web-client/src/presenter/sequences/signOutIdleSequence.ts
  web-client/src/presenter/sequences/signOutSequence.ts
  web-client/src/presenter/sequences/signOutUserInitiatedSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AppTimeoutModal.tsx
  web-client/src/views/IdleActivityMonitor.tsx
Labels: to test

#5707 10522: Only display modal if Trial Session is calendared; Refactoring;
  cypress/local-only/tests/integration/trialSession/trial-session-change-of-location.cy.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeOfTrialLocation.tsx
  shared/src/business/utilities/trialSession/shouldGenerateNoticeOfChangeTrialLocation.test.ts
  shared/src/business/utilities/trialSession/shouldGenerateNoticeOfChangeTrialLocation.ts
  shared/test-pdf-expected-images/Notice_Of_Change_Of_Trial_Location.pdf.1.png
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.test.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.ts
Labels: to test, Review Please

#5712 10491-dxox: improve efficiency of fileExternalDocumentInteractor (other, similarly named PR was running into issues with eslint)
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
  web-api/src/business/useCases/externalDocument/fileExternalDocumentInteractor.test.ts
  web-api/src/business/useCases/externalDocument/fileExternalDocumentInteractor.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/postgres/caseCorrespondences/upsertCaseCorrespondences.ts
  web-api/src/persistence/postgres/caseDeadlines/upsertCaseDeadlines.ts
Labels: to test

#5715 10522: Refactor + Improve typing;
  scripts/email/resend-service-email-to-irs-superuser.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCaseHelper/docketEntry/createAndServeNoticeDocketEntry.test.ts
  web-api/src/business/useCaseHelper/docketEntry/createAndServeNoticeDocketEntry.ts
  web-api/src/business/useCaseHelper/service/appendPaperServiceAddressPageToPdf.test.ts
  web-api/src/business/useCaseHelper/service/appendPaperServiceAddressPageToPdf.ts
  web-api/src/business/useCaseHelper/service/sendServedPartiesEmails.test.ts
  web-api/src/business/useCaseHelper/service/sendServedPartiesEmails.ts
  web-api/src/business/useCaseHelper/trialSessions/serveGeneratedNoticesOnCase.test.ts
  web-api/src/business/useCaseHelper/trialSessions/serveGeneratedNoticesOnCase.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractorHelper.ts
Labels: to test, Review Please

#5713 10578 story intermediate branch to test 1737385268
  cypress.config.ts
  cypress/local-only/tests/integration/logoutBehavior/idle-logout.cy.ts
  cypress/tsconfig.json
  docker-compose.yml
  docker-run.sh
  docs/entities/PublicCase.md
  eslint.config.mjs
  scripts/reports/non-attorney-practitioners-constants.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/courtIssuedEventCodes.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
  shared/src/tools/Event Codes - External Filings - Internal Document List.csv
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/courtIssuedEventCodes.json
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
  web-api/README.md
  web-api/src/app-local.ts
  web-client/integration-tests/journey/userTriesToFileAnUnavailableDocumentType.ts
  web-client/src/applicationContext.ts
  web-client/src/applicationContextPublic.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/DocketEntry/updateDocketEntryWizardDataAction.ts
  web-client/src/presenter/actions/FileDocument/refreshExternalDocumentTitleFromEventCodeAction.ts
  web-client/src/presenter/actions/FileDocument/setSupportingDocumentScenarioAction.ts
  web-client/src/presenter/actions/getOpinionTypesAction.ts
  web-client/src/presenter/computeds/PendingMotions/pendingMotionsHelper.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.test.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/editDocketEntryMetaHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/internalTypesHelper.test.ts
  web-client/src/presenter/computeds/internalTypesHelper.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.test.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/IdleActivityMonitor.tsx
  web-client/src/views/StartCase/TrialCity.tsx
Labels: to test, Review Please

#5722 10585: Fix json
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
Labels: to test

#5718 10578 Deprecate M129 in favor of M129A
  cypress.config.ts
  cypress/tsconfig.json
  docs/entities/PublicCase.md
  eslint.config.mjs
  package-lock.json
  scripts/reports/non-attorney-practitioners-constants.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/courtIssuedEventCodes.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
  shared/src/tools/Event Codes - External Filings - Internal Document List.csv
  shared/src/tools/Event Codes - External Filings.csv
  shared/src/tools/courtIssuedEventCodes.json
  shared/src/tools/externalFilingEvents.json
  shared/src/tools/internalFilingEvents.json
  web-client/integration-tests/journey/userTriesToFileAnUnavailableDocumentType.ts
  web-client/src/applicationContext.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/DocketEntry/updateDocketEntryWizardDataAction.ts
  web-client/src/presenter/actions/FileDocument/refreshExternalDocumentTitleFromEventCodeAction.ts
  web-client/src/presenter/actions/FileDocument/setSupportingDocumentScenarioAction.ts
  web-client/src/presenter/actions/getOpinionTypesAction.ts
  web-client/src/presenter/computeds/PendingMotions/pendingMotionsHelper.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.test.ts
  web-client/src/presenter/computeds/addDocketEntryHelper.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.test.ts
  web-client/src/presenter/computeds/completeDocumentTypeSectionHelper.ts
  web-client/src/presenter/computeds/editDocketEntryMetaHelper.ts
  web-client/src/presenter/computeds/fileDocumentHelper.ts
  web-client/src/presenter/computeds/internalTypesHelper.test.ts
  web-client/src/presenter/computeds/internalTypesHelper.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.test.ts
  web-client/src/presenter/computeds/selectDocumentTypeHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/StartCase/TrialCity.tsx
Labels: to staging, Review Please

#5721 10585: Fix json
  shared/src/business/useCases/getCaseInteractor.test.ts
  shared/src/business/useCases/getCaseInteractor.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
Labels: to staging

#5719 Remove app context creation intermediate branch to test 1737559059
  cypress-public.config.ts
  cypress-smoketests-readonly-public.config.ts
  cypress/local-only/support/pages/public/advanced-search.ts
  cypress/local-only/tests/integration/fileAPetition/petitions-clerk-creates-paper-case.cy.ts
  cypress/local-only/tests/integration/logoutBehavior/idle-logout.cy.ts
  cypress/local-only/tests/integration/public/advanced-search.cy.ts
  eslint.config.mjs
  jest.config.ts
  web-api/src/app-public.ts
  web-api/src/app.ts
  web-api/src/applicationContext.ts
  web-api/src/business/getEntityByName.ts
  web-api/src/gateways/worker/workerLocal.ts
  web-api/src/genericHandler.test.ts
  web-api/src/genericHandler.ts
  web-api/src/lambdas/cognitoAuthorizer/worker-handler.ts
  web-api/src/lambdas/v1/getCaseLambda.test.ts
  web-api/src/lambdas/v1/getDocumentDownloadUrlLambda.test.ts
  web-api/src/lambdas/v2/getCaseLambda.test.ts
  web-api/src/lambdas/v2/getDocumentDownloadUrlLambda.test.ts
  web-api/src/middleware/apiGatewayHelper.ts
  web-client/integration-tests/docketClerkConsolidatesCases.test.ts
  web-client/integration-tests/sentWorkItemsExpireAfterNDays.test.ts
Labels: to test, Review Please

#5727 10504: Adding commits from test that did not get into staging
  shared/src/business/entities/Correspondence.ts
  shared/src/business/entities/caseWorksheet/CaseWorksheet.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/postgres/caseCorrespondences/upsertCaseCorrespondences.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0007-additional-indexes.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0007-init-case-correspondence-indexes.ts
Labels: to staging

#5724 10333 to test: USWDS upgrade
  package-lock.json
  package.json
  web-client/src/styles/custom.scss
  web-client/src/styles/nav.scss
  web-client/src/styles/overrides.scss
  web-client/src/styles/tables.scss
  web-client/src/uswds/_index.scss
  web-client/src/views/AddPetitionerToCase/AddPetitionerToCase.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CaseAssociationRequest/CaseAssociationRequest.tsx
  web-client/src/views/CaseAssociationRequest/CaseAssociationRequestReview.tsx
  web-client/src/views/CaseDetail/AddDeficiencyStatistics.tsx
  web-client/src/views/CaseDetail/AddOtherStatistics.tsx
  web-client/src/views/CaseDetail/CaseDetail.tsx
  web-client/src/views/CaseDetail/EditCaseDetails.tsx
  web-client/src/views/CaseDetail/EditDeficiencyStatistic.tsx
  web-client/src/views/CaseDetail/EditOtherStatistics.tsx
  web-client/src/views/CaseDetailEdit/CaseDetailEdit.tsx
  web-client/src/views/CaseDetailEdit/ReviewSavedPetition.tsx
  web-client/src/views/ChangeLoginAndServiceEmail.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/Correspondence/AddCorrespondenceDocument.tsx
  web-client/src/views/Correspondence/EditCorrespondenceDocument.tsx
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
  web-client/src/views/CreateOrder/CreateOrder.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/EditDocketEntry/EditDocketEntryMeta.tsx
  web-client/src/views/EditPetitionerCounsel.tsx
  web-client/src/views/EditPetitionerInformationInternal.tsx
  web-client/src/views/EditRespondentCounsel.tsx
  web-client/src/views/EditUploadCourtIssuedDocument/EditUploadCourtIssuedDocument.tsx
  web-client/src/views/FileDocument/BeforeYouFileADocument.tsx
  web-client/src/views/FileDocument/FileDocument.tsx
  web-client/src/views/FileDocument/FileDocumentReview.tsx
  web-client/src/views/FileDocument/FileEntryOfAppearanceReview.tsx
  web-client/src/views/FileDocument/SelectDocumentType.tsx
  web-client/src/views/Header/AccountMenu.tsx
  web-client/src/views/Header/Header.tsx
  web-client/src/views/Messages/MessageDetail.tsx
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/ModalDialog.tsx
  web-client/src/views/PaperFiling/PaperFiling.tsx
  web-client/src/views/Practitioners/CreatePractitionerUser.tsx
  web-client/src/views/Practitioners/EditPractitionerUser.tsx
  web-client/src/views/Practitioners/PractitionerAddEditDocument.tsx
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
  web-client/src/views/StartCaseUpdated/FilePetitionButtons.tsx
  web-client/src/views/StatusReportOrder.tsx
  web-client/src/views/TrialSessionDetails/ServeThirtyDayNoticeModal.tsx
  web-client/src/views/TrialSessions/AddTrialSession.tsx
  web-client/src/views/TrialSessions/EditTrialSession.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
  web-client/src/views/UploadCourtIssuedDocument/UploadCourtIssuedDocument.tsx
  web-client/src/views/UserContactEdit.tsx
Labels: to test

#5723 10522: Update Displaying Modal Logic, Refactor, improve testing;
  cypress/local-only/tests/integration/trialSession/trial-session-change-of-location.cy.ts
  shared/src/business/utilities/documentGenerators/combineAllPdfDocuments.test.ts
  shared/src/business/utilities/documentGenerators/combineAllPdfDocuments.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeOfTrialLocation.tsx
  shared/src/business/utilities/trialSession/shouldGenerateNoticeOfChangeTrialLocation.test.ts
  shared/src/business/utilities/trialSession/shouldGenerateNoticeOfChangeTrialLocation.ts
  shared/src/proxies/trialSessions/getTrialSessionOpenCasesCountProxy.ts
  shared/test-pdf-expected-images/Notice_Of_Change_Of_Trial_Location.pdf.1.png
  web-api/src/app.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionOpenCasesCountInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionOpenCasesCountInteractor.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractorHelper.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractorHelper.ts
  web-api/src/lambdas/trialSessions/getTrialSessionOpenCasesCountLambda.ts
  web-client/integration-tests/journey/userTriesToFileAnUnavailableDocumentType.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.test.ts
  web-client/src/presenter/actions/hasTrialSessionLocationChangedAction.ts
Labels: to test, Review Please

#5730 10522: Remove Application Context;
  docs/postgres/restore.md
  package-lock.json
  scripts/judge/change-chief-judge.sh
  scripts/run-once-scripts/open-search-playground.ts
  scripts/run-once-scripts/postgres-migration/delete-case-correspondences.ts
  scripts/run-once-scripts/postgres-migration/delete-case-deadlines.ts
  scripts/run-once-scripts/postgres-migration/delete-case-worksheets.ts
  scripts/run-once-scripts/postgres-migration/delete-section-outboxes.ts
  scripts/run-once-scripts/postgres-migration/delete-user-outboxes.ts
  scripts/run-once-scripts/postgres-migration/delete-work-items.ts
  shared/src/proxies/workitems/completeWorkItemProxy.ts
  web-api/src/business/useCases/processStreamRecords/processCaseCorrespondenceEntries.ts
  web-api/src/business/useCases/processStreamRecords/processCaseDeadlineEntries.ts
  web-api/src/business/useCases/processStreamRecords/processCaseWorksheetEntries.ts
  web-api/src/business/useCases/processStreamRecords/processMessageEntries.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionOpenCasesCountInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionOpenCasesCountInteractor.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.locking.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.noticeGeneration.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.test.ts
  web-api/src/business/useCases/trialSessions/updateTrialSessionInteractor.ts
  web-api/src/business/useCases/workItems/completeWorkItemInteractor.test.ts
  web-api/src/business/useCases/workItems/getDocumentQCInboxForSectionInteractor.test.ts
  web-api/src/business/useCases/workItems/getDocumentQCInboxForSectionInteractor.ts
  web-api/src/business/useCases/workItems/getDocumentQCServedForUserInteractor.test.ts
  web-api/src/business/useCases/workItems/getDocumentQCServedForUserInteractor.ts
  web-api/src/business/useCases/workItems/getWorkItemInteractor.test.ts
  web-api/src/business/useCases/workItems/getWorkItemInteractor.ts
  web-api/src/lambdas/trialSessions/getTrialSessionOpenCasesCountLambda.ts
  web-api/src/lambdas/v1/getCaseLambda.test.ts
  web-api/src/lambdas/workitems/getDocumentQCInboxForSectionLambda.ts
  web-api/src/lambdas/workitems/getDocumentQCServedForUserLambda.ts
  web-api/src/lambdas/workitems/getWorkItemLambda.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.test.ts
  web-api/src/persistence/dynamo/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/postgres/utils/seed/fixtures/caseDeadlines.ts
  web-api/src/persistence/postgres/utils/seed/fixtures/correspodence.ts
  web-api/src/persistence/postgres/utils/seed/seed.ts
Labels: to test, Review Please

#5734 Increase AWS Batch Timeout;
  cypress/deployed-and-local/integration/aws-batch-docket-entries-download/aws-batch-docket-entries-download.cy.ts
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/batch/docker-image/src/docketEntryBatchDownloader.ts
Labels: to staging, Review Please

#5729 no-new-dates
  aws/lambdas/LogsToElasticSearch_info/index.js
  esbuild.config.mjs
  esbuild.public.config.mjs
  eslint-custom-rules/eslint-custom-rules-plugin.mjs
  eslint-custom-rules/eslint-no-new-dates-rule.mjs
  eslint.config.mjs
  shared/src/business/utilities/DateHandler.test.ts
  web-api/src/app-local.ts
  web-api/src/business/useCases/processStreamRecords/processStreamUtilities.test.ts
  web-api/src/logger.ts
  web-api/src/persistence/postgres/utils/seed/fixtures/workItems.ts
  web-api/src/utilities/cookieFormatting.ts
  web-client/integration-tests-public/unauthedUserOrderSearchExactMatchDocumentTitle.test.ts
  web-client/integration-tests/trialSessionChangeToRemoteProceedingJourney.test.ts
  web-client/src/persistence/s3/uploadPdfFromClient.ts
  web-client/src/presenter/actions/setProgressForFileUploadAction.ts
  web-client/src/presenter/actions/waitForSpinnerAction.test.ts
  web-client/src/views/AppMaintenance.tsx
Labels: to staging, Review Please

#5701 Devex modify postgres restore to staging
  .circleci/config.yml
  scripts/postgres/restoreDbFromSource.ts
Labels: to staging

#5739 Devex: Optionally get deployment-related env vars from the env switcher
  scripts/env/environments/00-common
  scripts/env/set-env.zsh
Labels: to staging

#5741 devex: fix path to create rds users script
  .circleci/config.yml
Labels: to staging

#5742 devex: circle's env var is set as POSTGRES_HOST
  .circleci/config.yml
Labels: to staging
