Repository ustaxcourt/ef-cms, pull requests merged in 2025-09, with the labels that each got.

#9064 dep updates and package update script 08-28-25
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  scripts/reindex/index-users/index-users.ts
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging, Review Please

#6484 10576: Short circuit when no lead deadline is provided;
  cypress/local-only/tests/integration/caseDeadline/lead-case-can-be-unconsolidated.cy.ts
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineIds.ts
Labels: to staging, Review Please

#9059 Random process diagram
  docs/USTC-development-process.drawio.png
Labels: to staging

#9081 9041 text change email
  web-api/src/business/useCaseHelper/auth/createUserConfirmation.ts
Labels: to test

#9089 9041: text change email
  web-api/src/business/useCaseHelper/auth/createUserConfirmation.ts
  web-api/terraform/modules/everything-else-deprecated/cognito.tf
Labels: to test, Review Please

#9095 deps: roll dwt package back to 19.1.0
  package-lock.json
  package.json
  scripts/reports/stale-cases.helpers.ts
Labels: to staging

#9108 8727 to test
  web-client/src/views/AdvancedSearch/OpinionSearchForm.tsx
  web-client/src/views/AdvancedSearch/OrderSearchForm.tsx
Labels: to test

#9104 9012 : DocketEntry set to pending in order to facilitate feature
  web-api/src/business/useCases/docketEntry/strikeDocketEntryInteractor.ts
Labels: to test, Review Please

#9110 8955 cleanup - to test
  .circleci/config.yml
Labels: to test, Review Please

#9075 9004: adds prosechecklist to notr
  cypress/deployed-and-local/integration/myAccount/change-address.cy.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/documentQC/document-title.cy.ts
  cypress/local-only/tests/integration/proSeChecklist/pro-se-checklist.cy.ts
  shared/src/business/entities/EntityConstants.ts
  web-api/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.test.ts
  web-api/src/business/useCases/serveCaseToIrs/serveCaseToIrsInteractor.ts
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/pro-se-checklist._S3rver_metadata.json
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/pro-se-checklist._S3rver_object
  web-api/storage/fixtures/s3/noop-documents-local-us-east-1/pro-se-checklist._S3rver_object.md5
  web-client/integration-tests/petitionsClerkFilesPetitionWithClinicLetterAttached.test.ts
  web-client/src/views/DocketRecord/DocketRecord.tsx
  web-client/src/views/EditPetitionerCounsel.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
Labels: to staging, Manual Deploy Step(s) Required

#9111 8955-cleanup: remove migration script from circleci conf
  .circleci/config.yml
Labels: to staging

#9092 Dependency updates week of 09/01/25
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  eslint.config.mjs
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/trialSessions/TrialSession.test.ts
  shared/src/business/useCases/removeSignatureFromDocumentInteractor.test.ts
  shared/src/business/utilities/chromium/getChromiumBrowser.test.ts
  shared/src/business/utilities/createPractitionerUser.test.ts
  shared/src/business/utilities/createPractitionerUser.ts
  shared/src/business/utilities/documentGenerators/jest_document_generator.config.ts
  shared/src/business/utilities/pdfs/getPdfJs.test.ts
  shared/src/business/utilities/pendingItem/sortPendingReportItems.test.ts
  shared/src/business/utilities/trialSession/getFormattedTrialSessionDetails.compareCasesByDocketNumber.test.ts
  shared/src/business/utilities/trialSession/getFormattedTrialSessionDetails.setPretrialMemorandumFilter.test.ts
  shared/src/business/utilities/trialSession/getFormattedTrialSessionDetails.test.ts
  split-tests-glob.ts
  tsconfig.json
  web-api/hostedEnvironmentTests/jest-hosted-environment.ts
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
  web-client/jest-integration.config.ts
  web-client/jest.mock-broadcast-channel.ts
  web-client/src/presenter/actions/CaseDetail/getIsOnCaseDetailAction.test.ts
  web-client/src/presenter/actions/openCaseDocumentDownloadUrlAction.test.ts
  web-client/src/presenter/actions/openCaseDocumentDownloadUrlAction.ts
  web-client/src/presenter/actions/reloadPageAction.test.ts
Labels: to staging

#6464 8813 opex speed up cypress tests in deployed environments (formerly flexion#10478)
  .circleci/config.yml
  .github/workflows/e2e-cypress.yml
  cypress/deployed-and-local/integration/authentication/login.cy.ts
  cypress/deployed-and-local/integration/authentication/petitioner-account-creation.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-gets-unserved.cy.ts
  cypress/deployed-and-local/integration/caseDetail/docketRecord/courtIssuedFiling/order-signature-disappears.cy.ts
  cypress/deployed-and-local/integration/caseDetail/parties/admissions-clerk-grants-e-access.cy.ts
  cypress/deployed-and-local/integration/caseDetail/parties/admissions-clerk-updates-practitioner-email.cy.ts
  cypress/deployed-and-local/integration/irsSuperUser/irs-super-user-can-download-stin.cy.ts
  cypress/deployed-and-local/integration/myAccount/petitioner-updates-email.cy.ts
  cypress/helpers/authentication/login-as-helpers.ts
  cypress/helpers/cypressTasks/cognito/cognito-helpers.ts
  cypress/support/commands.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/user/cleanup-cypress-test-accounts.ts
  scripts/user/setup-test-users.ts
Labels: to staging, Review Please

#9152 8727 to test
  shared/src/business/entities/EntityConstants.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/src/presenter/actions/AdvancedSearch/clearSearchResultsAction.ts
  web-client/src/presenter/actions/setCurrentPaginationPageAction.test.ts
  web-client/src/presenter/actions/setCurrentPaginationPageAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/advancedSearchHelper.ts
  web-client/src/presenter/sequences/setCurrentPaginationPageSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/presenter/state.ts
  web-client/src/views/AdvancedSearch/DocumentSearchResults.tsx
  web-client/src/views/AdvancedSearch/OpinionSearchForm.tsx
  web-client/src/views/AdvancedSearch/OrderSearchForm.tsx
  web-client/src/views/AdvancedSearch/SearchResults.tsx
Labels: to test, Review Please

#9145 9036 part 1: support lambda env var for maintence mode
  cypress/local-only/support/pages/maintenance.ts
  cypress/local-only/tests/integration/maintenanceMode/maintenance-mode.cy.ts
  cypress/local-only/tests/integration/public/maintenance-public.cy.ts
  docs/environments.md
  docs/operations/runbooks/create-new-lower-environment.md
  docs/postgres/decision/research.md
  package.json
  scripts/disengage-maintenance-mode.sh
  scripts/engage-maintenance-mode.sh
  scripts/jest-scripts.config.ts
  scripts/postgres/featureFlags/setup-maintenance-mode-flag.ts
  scripts/send-maintenance-mode-notifications-locally.ts
  scripts/setup-all-env-configuration.sh
  web-api/src/business/useCases/maintenance/sendMaintenanceNotificationsInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/persistence/postgres/featureFlag/getMaintenanceMode.ts
  web-api/src/persistence/postgres/featureFlag/updateMaintenanceMode.ts
  web-api/src/persistence/postgres/utils/seed/fixtures/featureFlags.ts
Labels: to staging, Review Please

#9167 9031: Updating launch json to have more configurations.
  .vscode/launch.json
Labels: to staging, Review Please

#9170 8813 - Github action workflows caching part 2
  .github/workflows/api.yml
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-accessibility.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  .github/workflows/typescript-all-files-check.yml
  .github/workflows/typescript-error-check.yml
Labels: to staging

#9183 8006: remove copypasta tests
  cypress/deployed-and-local/integration/advancedSearch/opinion-search.cy.ts
  cypress/deployed-and-local/integration/advancedSearch/order-search.cy.ts
Labels: to staging

#9186 10685 display recently filed docs reverted to test 1758557038
  web-api/src/persistence/postgres/docketEntries/getRecentFilingsByDocketNumbers.ts
  web-client/src/presenter/actions/Dashboard/getRecentFilingsForUserAction.test.ts
  web-client/src/presenter/actions/setRecentFilingsAction.test.ts
  web-client/src/presenter/actions/setRecentFilingsTableSortAction.test.ts
Labels: to test

#9164 Dep updates 9 17 25
  .circleci/config.yml
  Dockerfile
  cypress/helpers/constants/forgot-password.ts
  cypress/helpers/cypressTasks/cognito/cognito-helpers.ts
  cypress/local-only/tests/integration/authentication/forgot-password.cy.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  scripts/postgres/rds-upgrade-global-engine.sh
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/hostedEnvironmentTests/irsSuperUser.test.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: Do Not Merge

#9191 8006: update search cypress deploy and local test
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
Labels: to staging

#9196 9195
  cypress/deployed-and-local/integration/caseDetail/add-remove-case-hearings.cy.ts
  web-api/src/persistence/postgres/cases/getCasesByDocketNumbers.ts
  web-client/src/views/CaseDetail/CaseInformation/CaseInformationInternal.tsx
  web-client/src/views/CaseDetail/CaseInformation/DisplayHearings.tsx
Labels: bugfix, to staging

#9214 devex: disambiguate client-integration and client-integration-public actions
  .github/workflows/client-integration-public.yml
Labels: to staging

#9210 8764: part 1
  .circleci/config.yml
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/e2e-cypress-accessibility.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  docs/postgres/migrations.md
  package.json
  run-api.sh
  run-local.sh
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
  shared/src/test/mockComplexCase.ts
  web-api/src/persistence/postgres/cases/reports/fetchPendingItems.ts
  web-api/src/persistence/postgres/docketEntries/mapper.ts
  web-api/src/persistence/postgres/docketEntries/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrate.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-09-16T16_12_14Z-rtp-documentType-update.expand.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/deprecated/.gitkeep
  web-api/src/persistence/postgres/utils/migrate/migrations/future/2025-09-16T20_05_16Z-rtp-2nd-migration.expand.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/future/2025-09-16T20_07_53Z-rtp-remove-colum.contract.ts
Labels: to staging, Review Please

#9148 8937 calendaring federal holiday rules
  shared/src/business/utilities/DateHandler.test.ts
  shared/src/business/utilities/DateHandler.ts
  shared/src/business/utilities/getHolidaysInDateRange.test.ts
  shared/src/business/utilities/getHolidaysInDateRange.ts
  shared/src/test/mockTermSpreadsheet.xlsx
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/writeTrialSessionDataToExcel.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.test.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.ts
  web-client/src/presenter/computeds/termBuilderHelper.test.ts
  web-client/src/presenter/computeds/termBuilderHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/TermBuilderView.tsx
Labels: to staging, Review Please

#9218 devex: increase resource class for some underperforming jobs
  .circleci/config.yml
Labels: to staging

#9222 OpEx: turn our yellow `info` clusters green
  aws/lambdas/LogsToElasticSearch_info/index-template.json
Labels: to staging, Devex

#9227 9013 extend special sessions
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
Labels: to test, Review Please
