Repository ustaxcourt/ef-cms, pull requests merged in 2025-04, with the labels that each got.

#5951 Fix failing tests
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
Labels: to staging

#5940 10540: Fix Calculate Penalties on IRS Notice link for cases that have pre-existing penalties/statistics
  web-client/src/views/StartCaseInternal/StatisticsForm.tsx
Labels: to staging

#5938 Dependency updates
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
Labels: to staging

#5947 devex: fix for first RUM deployment
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
Labels: to staging

#5955 10474: feedback
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  shared/src/business/utilities/groupStatesOptions.test.ts
  shared/src/business/utilities/groupStatesOptions.ts
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
Labels: to test, Review Please

#5959 10619: Fix judge filter setting/unsetting
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByDateRange.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineReportJudgeFilterAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineReportJudgeFilterAction.ts
Labels: to test

#5958 10537 bug test
  web-api/terraform/modules/rum/rum.tf
  web-client/integration-tests/docketRecordFilterJourney.test.ts
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/journey/irsSuperuserAdvancedSearchForCaseDocketNumber.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/DocketRecord/setDefaultDocketRecordSortAndFilterAction.test.ts
  web-client/src/presenter/actions/DocketRecord/setDefaultDocketRecordSortAndFilterAction.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.test.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.ts
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
  web-client/src/presenter/sequences/advancedSearchTabChangeSequence.ts
  web-client/src/presenter/sequences/gotoAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/signOutSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/providers/realUserMonitoring.ts
Labels: to test

#5957 10619 Bug: Filtering by Judge on Case Deadlines Report
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/proxies/caseDeadline/getCaseDeadlinesProxy.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByDateRange.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReport.ts
  web-client/integration-tests/petitionsClerkVerifiesOffboardedJudgeJourney.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineReportJudgeFilterAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlineReportJudgeFilterAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to staging

#5963 10502 Cases: Fix terraform variables
  web-api/terraform/modules/opensearch-sync/opensearch-sync.tf
Labels: to test

#5964 10502 fix practitionerMappingEntries
  web-api/src/business/useCases/processStreamRecords/getCaseDataFromDynamo.ts
  web-api/src/business/useCases/processStreamRecords/processCaseEntries.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.ts
Labels: to test

#5965 10502 dxox: Wrap processPractitionerMappingEntries in a try/catch
  web-api/src/business/useCases/processStreamRecords/processCaseEntries.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.ts
Labels: to test, Review Please

#5966 Dependency updates for week of 2025-03-31
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/src/app.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: dependencies, to staging

#5956 10576: New Tests
  cypress/helpers/fileAPetition/create-consolidated-case-group.ts
  cypress/local-only/tests/integration/caseDeadline/case-deadline-on-a-consolidated-group.cy.ts
  cypress/local-only/tests/integration/judgeActivityReport/judge-activity-report.cy.ts
  cypress/local-only/tests/integration/trialSession/blocked-cases.cy.ts
  package-lock.json
  shared/src/business/entities/cases/Case.findLeadCaseForCases.test.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/getConsolidatedCaseDeadlines.ts
  web-client/src/presenter/actions/CaseDeadline/getConsolidatedCaseDeadlineAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setConsolidatedCaseDeadlineAction.test.ts
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
Labels: Do Not Merge, to test

#5970 10612: Remove petitioner email
  shared/src/authorization/authorizationClientService.ts
  shared/src/proxies/removePetitionerEmailProxy.ts
  types/TEntity.d.ts
  web-api/src/app.ts
  web-api/src/business/useCases/removePetitionerEmailInteractor.test.ts
  web-api/src/business/useCases/removePetitionerEmailInteractor.ts
  web-api/src/lambdas/cases/removePetitionerEmailLambda.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseAssociation/removePetitionerEmailAction.test.ts
  web-client/src/presenter/actions/CaseAssociation/removePetitionerEmailAction.ts
  web-client/src/presenter/actions/setRemovePetitionerEmailAction.test.ts
  web-client/src/presenter/actions/setRemovePetitionerEmailAction.ts
  web-client/src/presenter/computeds/partiesInformationHelper.test.ts
  web-client/src/presenter/computeds/partiesInformationHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/removePetitionerEmailSequence.ts
  web-client/src/presenter/sequences/showRemovePetitionerEmailModalSequence.ts
  web-client/src/views/AppComponent.tsx
  web-client/src/views/CaseDetail/PetitionersAndCounsel.tsx
  web-client/src/views/CaseDetail/RemovePetitionerEmailModal.tsx
Labels: to test

#5972 10612: update aws terraform provider version;
  web-api/terraform/modules/opensearch-sync/providers.tf
Labels: to test

#5969 10586 to test
  shared/src/authorization/authorizationClientService.test.ts
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/MotionOrderResponseForm.test.ts
  shared/src/business/entities/MotionOrderResponseForm.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/MotionOrderResponse/clearMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/clearMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/prepareMotionOrderResponseAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/prepareMotionOrderResponseAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/validateMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/validateMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/StatusReportOrder/getOrderTypeAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/getOrderTypeAction.ts
  web-client/src/presenter/actions/StatusReportOrder/isEditOrderResponseAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/isEditOrderResponseAction.ts
  web-client/src/presenter/actions/StatusReportOrder/isStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/setDocketEntryIdAction.ts
  web-client/src/presenter/actions/setupOrderResponseFormAction.ts
  web-client/src/presenter/computeds/documentViewerHelper.test.ts
  web-client/src/presenter/computeds/documentViewerHelper.ts
  web-client/src/presenter/computeds/documentViewerLinksHelper.test.ts
  web-client/src/presenter/computeds/documentViewerLinksHelper.ts
  web-client/src/presenter/computeds/messageDocumentHelper.test.ts
  web-client/src/presenter/computeds/messageDocumentHelper.ts
  web-client/src/presenter/computeds/motionOrderResponseFormHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/MotionOrderResponse/clearMotionOrderResponseFormSequence.ts
  web-client/src/presenter/sequences/MotionOrderResponse/motionOrderResponsePdfPreviewSequence.ts
  web-client/src/presenter/sequences/MotionOrderResponse/submitMotionOrderResponseSequence.ts
  web-client/src/presenter/sequences/StatusReportOrder/gotoStatusReportOrderSequence.ts
  web-client/src/presenter/sequences/convertHtml2PdfSequence.ts
  web-client/src/presenter/sequences/editUnsignedDraftDocumentSequence.ts
  web-client/src/presenter/sequences/gotoOrderResponseSequence.ts
  web-client/src/presenter/sequences/navigateToEditOrderSequence.ts
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/AppComponent.tsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.tsx
  web-client/src/views/Messages/MessageDocument.tsx
  web-client/src/views/OrderResponse/OrderResponse.tsx
Labels: to test

#5973 10419 to test 20250409
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/MinuteSheet.tsx
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.test.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.test.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.ts
  web-client/src/views/TrialSessionMinutes/RespondentsFieldset.tsx
Labels: to test

#5950 10537: reset all global state on logout (with some exceptions)
  web-client/integration-tests/docketRecordFilterJourney.test.ts
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/journey/irsSuperuserAdvancedSearchForCaseDocketNumber.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/DocketRecord/setDefaultDocketRecordSortAndFilterAction.test.ts
  web-client/src/presenter/actions/DocketRecord/setDefaultDocketRecordSortAndFilterAction.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.test.ts
  web-client/src/presenter/actions/Login/resetToBaseStateAction.ts
  web-client/src/presenter/sequences/Public/gotoPublicCaseDetailSequence.ts
  web-client/src/presenter/sequences/advancedSearchTabChangeSequence.ts
  web-client/src/presenter/sequences/gotoAdvancedSearchSequence.ts
  web-client/src/presenter/sequences/gotoCaseDetailSequence.ts
  web-client/src/presenter/sequences/signOutSequence.ts
  web-client/src/presenter/state.ts
Labels: to staging

#5914 10474 story
  cypress/deployed-and-local/integration/authentication/login.cy.ts
  cypress/deployed-and-local/integration/authentication/petitioner-account-creation.cy.ts
  cypress/deployed-and-local/integration/caseDetail/parties/admissions-clerk-updates-practitioner-email.cy.ts
  cypress/helpers/accountCreation/create-a-practitioner.ts
  cypress/helpers/fileAPetition/petitioner-creates-electronic-case.ts
  cypress/local-only/tests/integration/advancedSearch/practitioner-search.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/utilities/groupStatesOptions.test.ts
  shared/src/business/utilities/groupStatesOptions.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  shared/src/proxies/public/getPublicPractitionersByNameProxy.ts
  web-api/elasticsearch/efcms-user-mappings.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/lambdas/practitioners/getPractitionersByNameLambda.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/AdvancedSearch/AdvancedSearch.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to staging, Mappings Change(s)

#5979 10628 Fix to Test
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
Labels: to test

#5982 10502 Case Updates
  cypress/local-only/tests/integration/caseDetail/caseInformation/edit-case-detail.cy.ts
  cypress/local-only/tests/integration/trialSession/run-suggested-calendar-generator.cy.ts
  web-api/src/business/useCases/createCaseFromPaperInteractor.ts
  web-api/src/business/useCases/createCaseInteractor.ts
  web-api/src/persistence/postgres/cases/mocks.jest.ts
  web-api/src/persistence/postgres/cases/updateCase.ts
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/TrialSessionDetails/TrialSessionDetails.tsx
Labels: to test, Review Please

#5985 Devex: Add withValidation Wrapper for Postgres Upserts
  web-api/src/errors/errors.ts
  web-api/src/persistence/postgres/utils/withValidation.test.ts
  web-api/src/persistence/postgres/utils/withValidation.ts
Labels: to staging

#5988 10576: Display Lead Case in modal;
  web-client/src/views/CaseDetail/CaseDeadline/ConsolidatedCaseGroupInfo.tsx
Labels: to test

#5990 10576: Include Lead Docket Number when fetching consolidated deadlines;
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
Labels: to test

#5986 10626: find served documents with no service timestamp
  scripts/reports/served-docket-entries-missing-service-date-in-open-cases.ts
Labels: to staging

#5993 10612 to test again
  web-client/src/presenter/sequences/removePetitionerEmailSequence.ts
Labels: to test

#5994 Return fake host string when running Jest tests;
  package.json
  web-api/src/environment.ts
Labels: to staging, Review Please

#5996 10612: fix infinite spinner on edit petitioner after removing email, v2
  web-api/src/business/useCases/removePetitionerEmailInteractor.test.ts
  web-api/src/business/useCases/removePetitionerEmailInteractor.ts
  web-client/src/presenter/actions/CaseAssociation/removePetitionerEmailAction.test.ts
  web-client/src/presenter/actions/CaseAssociation/removePetitionerEmailAction.ts
  web-client/src/presenter/sequences/removePetitionerEmailSequence.ts
Labels: to test

#5984 10628 Fix to Staging
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.ts
Labels: to staging

#5995 Devex: Adjust preparation of expected dates in test cases
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeD.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeE.test.ts
  shared/src/business/entities/courtIssuedDocument/CourtIssuedDocumentTypeG.test.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.test.ts
  web-client/src/presenter/computeds/caseStatusHistoryHelper.ts
Labels: to staging

#5980 Dependency updates week of 21 April 2025
  .circleci/config.yml
  Dockerfile
  cypress/helpers/cypressTasks/pdf/parsePdf.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging, Review Please

#5997 Backmerge `staging` into `test`
  .circleci/config.yml
  Dockerfile
  cypress/helpers/cypressTasks/pdf/parsePdf.ts
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/reports/petition-counts.ts
  scripts/reports/represented-count-by-year.ts
  scripts/reports/served-docket-entries-missing-service-date-in-open-cases.ts
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/src/environment.ts
  web-api/src/persistence/postgres/utils/operation/pgDeleteFrom.ts
  web-api/src/persistence/postgres/utils/operation/pgUpdateTable.ts
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
  web-client/src/presenter/computeds/Public/publicCaseDetailHelper.test.ts
Labels: to test

#5999 Devex: fix kysely type errors
  web-api/src/persistence/postgres/utils/operation/pgDeleteFrom.ts
  web-api/src/persistence/postgres/utils/operation/pgUpdateTable.ts
Labels: to test, Review Please

#6002 10502-dxox: Fix archived correspondences
  web-api/src/persistence/postgres/cases/getCasesByDocketNumbers.ts
Labels: to test

#5968 10586 generate response to motion order
  cypress/local-only/tests/integration/motionOrderResponse/edit-order-response-for-motion.cy.ts
  cypress/local-only/tests/integration/motionOrderResponse/file-order-response-for-motion.cy.ts
  shared/src/authorization/authorizationClientService.test.ts
  shared/src/authorization/authorizationClientService.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/MotionOrderResponseForm.test.ts
  shared/src/business/entities/MotionOrderResponseForm.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.test.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/getConstants.ts
  web-client/src/presenter/actions/MotionOrderResponse/clearMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/clearMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/prepareMotionOrderResponseAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/prepareMotionOrderResponseAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/setEditMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/MotionOrderResponse/validateMotionOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/MotionOrderResponse/validateMotionOrderResponseFormAction.ts
  web-client/src/presenter/actions/StatusReportOrder/getOrderTypeAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/getOrderTypeAction.ts
  web-client/src/presenter/actions/StatusReportOrder/isEditOrderResponseAction.test.ts
  web-client/src/presenter/actions/StatusReportOrder/isEditOrderResponseAction.ts
  web-client/src/presenter/actions/StatusReportOrder/isStatusReportOrderAction.test.ts
  web-client/src/presenter/actions/setDocketEntryIdAction.ts
  web-client/src/presenter/actions/setupOrderResponseFormAction.test.ts
  web-client/src/presenter/actions/setupOrderResponseFormAction.ts
  web-client/src/presenter/computeds/documentViewerHelper.test.ts
  web-client/src/presenter/computeds/documentViewerHelper.ts
  web-client/src/presenter/computeds/documentViewerLinksHelper.test.ts
  web-client/src/presenter/computeds/documentViewerLinksHelper.ts
  web-client/src/presenter/computeds/messageDocumentHelper.test.ts
  web-client/src/presenter/computeds/messageDocumentHelper.ts
  web-client/src/presenter/computeds/motionOrderResponseFormHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/MotionOrderResponse/clearMotionOrderResponseFormSequence.ts
  web-client/src/presenter/sequences/MotionOrderResponse/motionOrderResponsePdfPreviewSequence.ts
  web-client/src/presenter/sequences/MotionOrderResponse/submitMotionOrderResponseSequence.ts
  web-client/src/presenter/sequences/MotionOrderResponse/validateMotionOrderResponseSequence.ts
  web-client/src/presenter/sequences/StatusReportOrder/gotoStatusReportOrderSequence.ts
  web-client/src/presenter/sequences/convertHtml2PdfSequence.ts
  web-client/src/presenter/sequences/editUnsignedDraftDocumentSequence.ts
  web-client/src/presenter/sequences/gotoOrderResponseSequence.ts
  web-client/src/presenter/sequences/navigateToEditOrderSequence.ts
  web-client/src/presenter/sequences/submitCourtIssuedOrderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/views/AppComponent.tsx
  web-client/src/views/DocketRecord/DocumentViewerDocument.tsx
  web-client/src/views/Messages/MessageDocument.tsx
  web-client/src/views/OrderResponse/OrderResponse.tsx
Labels: to staging

#6004 10419 to Test
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessionMinutes/MinuteSheet.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.test.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.ts
  web-client/src/presenter/actions/TrialSessionMinutes/updateTrialSessionMinutesFormAction.test.ts
  web-client/src/presenter/actions/TrialSessionMinutes/updateTrialSessionMinutesFormAction.ts
  web-client/src/presenter/computeds/TrialSession/TrialSessionMinutes/trialSessionMinutesFormOptionsHelper.ts
  web-client/src/presenter/computeds/TrialSessionMinutes/trialSessionMinutesFormOptionsHelper.test.ts
  web-client/src/presenter/computeds/TrialSessionMinutes/trialSessionMinutesFormOptionsHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/state.ts
  web-client/src/views/TrialSessionMinutes/ActionsAndFilingsFieldset.tsx
  web-client/src/views/TrialSessionMinutes/TrialSessionMinutesForm.tsx
Labels: to test

#6013 Add some error catching to avoid potential re-indexing failure in the glue job
  web-api/src/business/useCases/processStreamRecords/processCaseEntries.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntries.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.ts
Labels: to test

#6014 10502 Drop unnecessary notNull constraint and add kysely migration step to glue job
  .circleci/config.yml
  web-api/src/persistence/postgres/utils/migrate/migrations/0011-case-petitioners.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0016-drop-notnull-for-petitioner-phone-number.ts
Labels: to test
