Repository ustaxcourt/ef-cms, pull requests merged in 2025-07, with the labels that each got.

#6236 BUG: OpenSearch queries that sort on `sortableDocketNumber` stopped working (to test)
  shared/src/business/useCases/getAllUsersByRoleInteractor.ts
  web-api/elasticsearch/efcms-case-mappings.ts
  web-api/src/persistence/elasticsearch/searchClient.ts
  web-api/src/persistence/elasticsearch/users/getAllUsersByRole.ts
Labels: to test

#6238 10620 - Paginatior not working on mobile devices
  shared/src/business/entities/EntityConstants.ts
  web-client/src/ustc-ui/Pagination/Paginator.tsx
  web-client/src/ustc-ui/Responsive/Responsive.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
Labels: bugfix, to test

#6227 10506: Fix cron expression
  web-api/terraform/modules/rds-expired-records-cleanup/rds-expired-records-cleanup.tf
Labels: to staging

#6196 10584: pdf Icon was invisible when viewing a document in mobile
  web-client/src/styles/custom.scss
  web-client/src/styles/icons.scss
  web-client/src/variables/variables.scss
Labels: to staging, design debt

#6228 10444: TS Error Cleanup: Import and Module Errors
  shared/src/business/useCases/updateContactInteractor.ts
  shared/src/business/utilities/documentGenerators/addressLabelCoverSheet.test.ts
  shared/src/business/utilities/documentGenerators/addressLabelCoverSheet.ts
  shared/src/business/utilities/documentGenerators/caseInventoryReport.ts
  shared/src/business/utilities/documentGenerators/changeOfAddress.test.ts
  shared/src/business/utilities/documentGenerators/changeOfAddress.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToInPersonProceeding.test.ts
  shared/src/business/utilities/documentGenerators/noticeOfChangeToInPersonProceeding.ts
  shared/src/business/utilities/documentGenerators/practitionerCaseList.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrder.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.ts
  shared/src/business/utilities/pdfGenerator/components/AddressLabel.tsx
  shared/src/business/utilities/pdfGenerator/components/CompressedDocketHeader.tsx
  shared/src/business/utilities/pdfGenerator/components/PretrialMemorandum.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/AddressLabelCoverSheet.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/ChangeOfAddress.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/DocketRecord.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/GettingReadyForTrialChecklist.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/NoticeOfChangeToInPersonProceeding.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PractitionerCaseList.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/ReceiptOfFiling.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/StandingPretrialOrderForSmallCase.tsx
  shared/test-pdf-expected-images/Address_Label_Cover_Sheet.pdf.1.png
  types/pdf.d.ts
  types/png.d.ts
  types/svg.d.ts
  web-api/src/business/useCaseHelper/trialSessions/generateNoticeOfChangeToInPersonProceeding.test.ts
  web-api/src/business/useCaseHelper/trialSessions/generateNoticeOfChangeToInPersonProceeding.ts
Labels: to staging

#6229 OpEx: add 'requested place of trial' to the stale cases report
  scripts/reports/stale-cases.helpers.ts
Labels: to staging, Review Please

#6182 10532: update login & service email language
  web-client/src/views/Practitioners/PractitionerLoginServiceEmailForm.tsx
Labels: to staging, design debt, Review Please

#6246 10671 story
  web-api/src/business/useCases/practitioner/getPractitionerByBarNumberInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionerByBarNumberInteractor.ts
Labels: to staging

#6248 10484 update alert messages to current styling
  web-client/src/styles/typography.scss
  web-client/src/views/CaseDetailEdit/UpdateCaseModalDialog.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/MyAccount.tsx
  web-client/src/views/StartCaseInternal/OrdersNeededSummary.tsx
  web-client/src/views/UserContactEdit.tsx
Labels: to staging

#6259 OpEx: tweak glue job for new aws accounts (to test)
  .circleci/config.yml
  docs/operations/runbooks/create-new-lower-environment.md
  scripts/glue/start-glue-job.ts
  shared/admin-tools/aws/glueHelper.ts
  shared/admin-tools/glue/remote_role/bin/deploy-init.sh
  shared/admin-tools/glue/remote_role/bin/deploy-remote-role.sh
  shared/admin-tools/glue/remote_role/bin/destroy-remote-role.sh
  web-api/terraform/bin/deploy-account-specific.sh
Labels: to test

#6255 10356
  web-client/src/presenter/sequences/gotoMessageDetailSequence.ts
Labels: bugfix, to test

#6262 Devex: test better indexing script
  .circleci/config.yml
  scripts/run-once-scripts/postgres-migration/index-docket-entries.ts
  scripts/run-once-scripts/postgres-migration/index-docket-entries/_index-docket-entries-child.ts
  scripts/run-once-scripts/postgres-migration/index-docket-entries/index-docket-entries.ts
Labels: to test

#6251 10632: Inhibit clipping of calender control in IRSNotice component
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
Labels: to test

#6243 10670 update browser modal alert to test
  shared/src/business/utilities/pdfs/getPdfJs.test.ts
  shared/src/business/utilities/pdfs/getPdfJs.ts
  web-client/src/views/FileHandlingHelpers/fileValidation.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.test.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
Labels: to test, Review Please

#6274 10494 dxox: Docket Entries updates to test
  shared/src/business/entities/DocketEntry.setQCed.test.ts
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityValidationConstants.ts
  shared/src/business/useCases/courtIssuedDocument/addDraftWatermarkToDocument.test.ts
  shared/src/business/utilities/chromium/getChromiumBrowser.test.ts
  shared/src/business/utilities/chromium/getChromiumBrowser.ts
  shared/src/business/utilities/chromium/getChromiumBrowserAws.ts
  shared/src/business/utilities/chromium/getChromiumBrowserLocal.ts
  shared/src/business/utilities/documentGenerators/generateAndVerifyPdfDiff.ts
  shared/src/business/utilities/shouldGenerateDocketRecordIndex.test.ts
  shared/src/test/mockDocketEntry.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.ts
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.test.ts
  web-api/src/business/useCases/pdf/generatePdfFromHtmlInteractor.ts
  web-api/src/business/useCases/user/updatePetitionerInformationInteractor.test.ts
  web-api/src/lambdas/pdfGeneration/pdf-generation.ts
  web-api/src/persistence/postgres/docketEntries/mapper.ts
  web-api/src/persistence/postgres/docketEntries/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-07-08T20_47_40Z-drop-unused-columns-from-docket-entries.ts
  web-api/src/persistence/postgres/utils/seed/fixtures/docketEntries.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-client/integration-tests/permissions.test.ts
  web-client/integration-tests/v2ApiJourney.test.ts
  web-client/src/presenter/actions/validateSelectDocumentTypeAction.test.ts
Labels: to test

#6253 Dep updates 07 02 2025
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging

#6280 10469 test
  web-client/jest-unit.config.ts
  web-client/src/presenter/computeds/Public/todaysOpinionsHelper.test.ts
  web-client/src/presenter/computeds/Public/todaysOpinionsHelper.ts
  web-client/src/presenter/computeds/docketRecordHelper.test.ts
  web-client/src/presenter/computeds/docketRecordHelper.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.test.ts
  web-client/src/presenter/computeds/messagesIndividualInboxHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/Table/TableFilters.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/BlockedCasesReport/BlockedCasesReport.tsx
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/CaseDetail/CaseDeadlinesInternal.tsx
  web-client/src/views/CaseDetail/CaseDetailPendingReportList.tsx
  web-client/src/views/CaseDetail/CaseStatusHistory.tsx
  web-client/src/views/CaseDetail/MessagesCompleted.tsx
  web-client/src/views/CaseDetail/MessagesInProgress.tsx
  web-client/src/views/CaseInventoryReport/CaseInventoryReport.tsx
  web-client/src/views/CaseWorksheet/CaseWorksheets.tsx
  web-client/src/views/ColdCaseReport/ColdCaseReportList.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/Dashboards/DashboardChambers.tsx
  web-client/src/views/Dashboards/DashboardJudge.tsx
  web-client/src/views/DocketRecord/DocketRecordHeader.tsx
  web-client/src/views/JudgeActivityReport/Statistics.tsx
  web-client/src/views/JudgeActivityReport/SubmittedAndCav.tsx
  web-client/src/views/Messages/MessageTable.tsx
  web-client/src/views/PendingMotion/PendingMotion.tsx
  web-client/src/views/PendingReport/PendingReportList.tsx
  web-client/src/views/Practitioners/PractitionerCaseList.tsx
  web-client/src/views/Practitioners/PractitionerDocumentation.tsx
  web-client/src/views/Practitioners/PractitionerInformation.tsx
  web-client/src/views/Public/PublicDocketRecordHeader.tsx
  web-client/src/views/Public/TodaysOpinions.tsx
  web-client/src/views/Public/TodaysOrders.tsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopyFilterHeader.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/IndividualWorkQueueOutbox.tsx
  web-client/src/views/WorkQueue/RecentMessages.tsx
  web-client/src/views/WorkQueue/RecentMessagesInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueue.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInProgress.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueInbox.tsx
  web-client/src/views/WorkQueue/SectionWorkQueueOutbox.tsx
  web-client/src/views/WorkQueue/WorkQueueAssignments.tsx
Labels: to test

#6290 10707: remove unneeded validation
  web-client/src/presenter/sequences/generatePdfFromScanSessionSequence.ts
Labels: to test, Review Please

#6277 10672: Move Locks to Postgres
  scripts/run-cypress.sh
  shared/src/business/useCases/prioritizeCaseInteractor.test.ts
  web-api/src/business/useCases/blockCaseFromTrialInteractor.test.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.test.ts
  web-api/src/business/useCases/trialSessions/removeCaseFromTrialInteractor.test.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.ts
Labels: to staging

#6076 10633: fix condition PR to Staging
  shared/src/business/entities/EntityConstants.ts
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.test.ts
  web-client/src/presenter/computeds/internalPetitionPartiesHelper.ts
Labels: to staging

#6300 Backmerge `staging` into `test`
  docs/operations/runbooks/create-irs-superuser.md
  scripts/env/environments/example.env
  scripts/irs-super-user.helpers.ts
  scripts/run-cypress.sh
  scripts/run-once-scripts/postgres-migration/index-cases.ts
  shared/src/business/useCases/prioritizeCaseInteractor.test.ts
  web-api/src/business/useCases/processStreamRecords/processRemoveEntries.test.ts
  web-api/src/business/useCases/processStreamRecords/processRemoveEntries.ts
  web-api/src/business/useCases/trialSessions/removeCaseFromTrialInteractor.test.ts
  web-api/src/business/useCases/trialSessions/setTrialSessionCalendarInteractor.ts
Labels: to test

#6254 10356
  web-client/src/presenter/sequences/gotoMessageDetailSequence.ts
Labels: bugfix, to staging

#6178 10614: add counters to trial session copies headers
  cypress/local-only/tests/integration/trialSessionWorkingCopy/trial-session-working-copy-filter.cy.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.ts
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.test.ts
  shared/src/business/utilities/pdfGenerator/components/SelectedFiltersSection.tsx
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.tsx
  shared/src/proxies/trialSessions/generatePrintableTrialSessionCopyReportProxy.ts
  web-api/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  web-api/src/lambdas/trialSessions/getGeneratePrintableTrialSessionCopyReportLambda.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.test.ts
  web-client/src/presenter/computeds/trialSessionWorkingCopyHelper.ts
  web-client/src/views/TrialSessionWorkingCopy/CaseListRowTrialSession.tsx
  web-client/src/views/TrialSessionWorkingCopy/WorkingCopyFilterHeader.tsx
Labels: to staging

#6306 10632 rm overflow tag in tab control (id: tab-parties) to prevent clipping …
  web-client/src/views/StartCaseInternal/StartCaseInternal.tsx
Labels: to staging

#6311 devex: IRS superusers' cognito records must have custom:userId attrib
  docker-to-ecr.sh
  docs/additional-resources/irs-super-user.md
  docs/operations/runbooks/create-irs-superuser.md
  scripts/generate-uuid.ts
  scripts/jest-scripts.config.ts
Labels: to staging

#6310 Backmerge `staging` into `test`
  docker-to-ecr.sh
  docs/additional-resources/irs-super-user.md
  docs/operations/runbooks/create-irs-superuser.md
  scripts/generate-uuid.ts
  scripts/jest-scripts.config.ts
  shared/src/business/utilities/documentGenerators/constants/printableTrialSessionWorkingCopyConstants.ts
  shared/src/business/utilities/documentGenerators/printableWorkingCopySessionList.test.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/PrintableWorkingCopySessionList.tsx
  shared/src/proxies/trialSessions/generatePrintableTrialSessionCopyReportProxy.ts
  web-api/src/business/useCases/trialSessions/generatePrintableTrialSessionCopyReportInteractor.ts
  web-api/src/lambdas/trialSessions/getGeneratePrintableTrialSessionCopyReportLambda.ts
  web-api/src/persistence/postgres/polling/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-05-29T19_02_29Z-add-table-response-strings.ts
  web-client/src/presenter/actions/TrialSessionWorkingCopy/generatePrintableTrialSessionCopyReportAction.ts
Labels: to test

#6316 use latest fork of the dynamo action to fix issue
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/e2e-cypress-accessibility.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  docs/flaky-tests.md
Labels: to staging

#6303 Better indexing scripts (and a better docket entry deletion script)
  .circleci/config.yml
  scripts/jest-scripts.config.ts
  scripts/reindex/index-cases/_index-cases-child.ts
  scripts/reindex/index-cases/index-cases.ts
  scripts/reindex/index-docket-entries/_index-docket-entries-child.ts
  scripts/reindex/index-docket-entries/index-docket-entries.ts
  scripts/run-once-scripts/postgres-migration/delete-all-docket-entries.ts
  scripts/run-once-scripts/postgres-migration/delete-all-docket-entries/_delete-docket-entries-child.ts
  scripts/run-once-scripts/postgres-migration/delete-all-docket-entries/delete-docket-entries.ts
  scripts/run-once-scripts/postgres-migration/index-cases.ts
  web-api/elasticsearch/cases/indexOpenSearchCases.ts
Labels: to staging

#6321 10574 add deadline to sro fix merge
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.test.ts
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/business/useCases/courtIssuedOrder/fileCourtIssuedOrderInteractor.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.test.ts
  web-client/src/presenter/actions/CourtIssuedDocketEntry/fileAndServeCourtIssuedDocumentAction.ts
Labels: to test

#6325 devex: index in circle during migration deployments and glue jobs
  .circleci/config.yml
  scripts/migration/toggle-migrate-flag.sh
Labels: to staging

#6261 10589 unable to edit notice of receipt of petition intermediate branch to test 1751915647
  shared/src/business/entities/EntityConstants.ts
  web-api/src/business/useCases/docketEntry/updateDocketEntryMetaInteractor.ts
  web-client/src/business/useCases/externalDocument/generateExternalDocumentTitle.ts
  web-client/src/presenter/actions/DocketEntry/updateDocketEntryWizardDataAction.ts
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
Labels: bugfix, to test, Review Please

#6317 Dependency Updates 2025-07-18
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging

#6332 10686 todays orders sorting to test 1753194548
  web-client/src/presenter/actions/Public/resetTodaysOrdersPageAction.ts
  web-client/src/presenter/computeds/Public/todaysOrdersHelper.test.ts
  web-client/src/presenter/computeds/Public/todaysOrdersHelper.ts
  web-client/src/presenter/presenter-public.ts
  web-client/src/presenter/sequences/Public/sortTodaysOrdersSequence.test.ts
  web-client/src/presenter/sequences/Public/sortTodaysOrdersSequence.ts
  web-client/src/presenter/state-public.ts
  web-client/src/styles/tables.scss
  web-client/src/views/Public/TodaysOrders.tsx
  web-client/src/views/Public/TodaysOrdersConstants.ts
Labels: to test

#6338 10670: update browser message
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
Labels: to test

#6312 10693 prevent overwriting subject line to test
  cypress/local-only/tests/integration/caseDetail/docketRecord/courtIssuedFiling/docket-clerk-uploads-and-edits-court-issued-docket-entry.cy.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
Labels: to test, Review Please

#6351 10687 story to test
  shared/src/business/utilities/formatAttachments.test.ts
  shared/src/business/utilities/formatAttachments.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
  web-client/src/presenter/computeds/messageModalHelper.ts
  web-client/src/styles/overrides.scss
  web-client/src/views/CaseDetail/CaseDetailInternal.tsx
  web-client/src/views/Messages/MessageModalAttachments.tsx
Labels: to test

#6355 10684 Large Case Followup (dropping a table)
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-07-26T23_34_53Z-drop-docketEntry-from-dwWorkItem.ts
Labels: to test

#6358 10507: Update script permissions;
  scripts/run-once-scripts/postgres-migration/migrate-feature-flags-dynamo-to-postgres.ts
Labels: to test, Review Please

#6252 10668: update automatic block when removing a pending item for a case…
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.test.ts
  web-api/src/business/useCaseHelper/automaticBlock/updateCaseAutomaticBlock.ts
Labels: to staging

#6289 10707: remove unneeded validation
  web-client/src/presenter/sequences/generatePdfFromScanSessionSequence.ts
Labels: to staging

#6370 resolve merge conflicts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.test.ts
  web-client/src/presenter/actions/updateMessageModalAttachmentsAction.ts
Labels: to test, Review Please

#6188 10286: Service parties colun wrap long text
  web-client/src/styles/custom.scss
  web-client/src/styles/forms.scss
  web-client/src/views/CourtIssuedDocketEntry/CourtIssuedDocketEntry.tsx
Labels: to staging, design debt

#6239 10539: BUG: Document View is displaying a document when it shouldn't be
  web-client/src/presenter/actions/getDefaultDocketViewerDocumentToDisplayAction.ts
  web-client/src/views/DocketRecord/DocumentViewer.tsx
Labels: bugfix, to staging, Review Please

#6233 10589 unable to edit notice of receipt of petition
  shared/src/business/entities/EntityConstants.ts
  web-client/src/business/useCases/externalDocument/generateExternalDocumentTitle.ts
  web-client/src/presenter/actions/DocketEntry/updateDocketEntryWizardDataAction.ts
  web-client/src/views/EditDocketEntry/EditDocketEntryMetaFormDocument.tsx
Labels: bugfix, to staging, Review Please
