Repository ustaxcourt/ef-cms, pull requests merged in 2025-06, with the labels that each got.

#6092 opex: try to resume a glue job
  .circleci/config.yml
Labels: to test

#6023 Dep-Updates: 5 may25 dep updates
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  jest.config.ts
  package-lock.json
  package.json
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  tsconfig.json
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging, Review Please

#6099 Fix regex in emailReplacer
  scripts/emailReplacer.ts
Labels: to test

#6108 Fix promise returns in updateCaseAndAssociations
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
Labels: to staging

#6107 10502 cleanup: fix the delete-route53-latency-records script
  web-api/terraform/bin/delete-route53-latency-records.ts
Labels: to staging, Review Please

#6113 10636: Moving Docket Entry Worksheets to Postgres
  scripts/run-once-scripts/postgres-migration/delete-docket-entry-worksheets.ts
  web-api/src/business/useCases/pendingMotion/deleteDocketEntryWorksheetInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/deleteDocketEntryWorksheetInteractor.ts
  web-api/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  web-api/src/business/useCases/pendingMotion/updateDocketEntryWorksheetInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/updateDocketEntryWorksheetInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntryWorksheet.test.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntryWorksheetEntries.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.test.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processStreamUtilities.ts
  web-api/src/database-schema.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/pendingMotion/deleteDocketEntryWorksheetLambda.ts
  web-api/src/lambdas/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeLambda.ts
  web-api/src/lambdas/pendingMotion/updateDocketEntryWorksheetLambda.ts
  web-api/src/persistence/dynamo/docketEntryWorksheet/getDocketEntryWorksheetsByDocketEntryIds.ts
  web-api/src/persistence/dynamo/pendingMotion/deleteDocketEntryWorksheetRecord.ts
  web-api/src/persistence/dynamo/pendingMotion/updateDocketEntryWorksheet.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/deleteDocketEntryWorksheet.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/getDocketEntryWorksheetsByDocketEntryIds.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/mapper.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/schema.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/upsertDocketEntryWorksheets.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-05-26T16_22_33Z-docket-entry-worksheet.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/terraform/bin/delete-route53-latency-records.ts
Labels: to test

#6100 Fix regex in emailReplacer
  scripts/emailReplacer.ts
Labels: to staging

#6118 10506: Fix kysely typing when fetching Dispatch Notifications;
  web-api/src/persistence/postgres/notifications/getDispatchNotification.ts
Labels: Do Not Merge, to test

#6119 10505 - Do not reset timer when scoping connections.
  web-api/src/getConnection.ts
Labels: to test

#6124 Backmerge `staging` into `test`
  scripts/run-once-scripts/deleteWest/allColors/disassociateResourcesFromWebAcl.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteBatchResources.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteEcrImages.ts
Labels: to test

#6131 Review - Removed Amazon pay language
  web-client/src/views/StartCaseUpdated/FilePetitionStep7.tsx
Labels: to test, Review Please

#6121 Dep updates 06 06 2025
  .circleci/config.yml
  .nvmrc
  Dockerfile
  docs/dependency-updates.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/Dockerfile
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/everything-else-deprecated/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/opensearch-sync/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging

#6136 10677: fixed missing comma on remove amazon pay
  web-client/src/views/StartCaseUpdated/FilePetitionStep7.tsx
Labels: to test, Review Please

#6126 10633-Should only copy address and phone number from the primary petitioner object when use primary contact address is checked.
  web-client/integration-tests/journey/petitionsClerkCreatesNewCaseFromPaper.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.test.ts
  web-client/src/presenter/actions/StartCaseInternal/setFormContactSecondaryAddressAction.ts
Labels: to test

#6143 10494 to test fix routing
  web-api/elasticsearch/docketEntries/indexOpenSearchDocketEntries.ts
Labels: to test

#6142 10558 - Pagination tweaks in Practitioner Information
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to test

#6074 10636: Docket Entry Worksheet
  scripts/run-once-scripts/postgres-migration/delete-docket-entry-worksheets.ts
  scripts/run-once-scripts/postgres-migration/move-docket-entry-worksheets-to-postgres.ts
  web-api/src/business/useCases/pendingMotion/deleteDocketEntryWorksheetInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/deleteDocketEntryWorksheetInteractor.ts
  web-api/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeInteractor.ts
  web-api/src/business/useCases/pendingMotion/updateDocketEntryWorksheetInteractor.test.ts
  web-api/src/business/useCases/pendingMotion/updateDocketEntryWorksheetInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.test.ts
  web-api/src/database-schema.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/pendingMotion/deleteDocketEntryWorksheetLambda.ts
  web-api/src/lambdas/pendingMotion/getPendingMotionDocketEntriesForCurrentJudgeLambda.ts
  web-api/src/lambdas/pendingMotion/updateDocketEntryWorksheetLambda.ts
  web-api/src/persistence/dynamo/docketEntryWorksheet/getDocketEntryWorksheetsByDocketEntryIds.ts
  web-api/src/persistence/dynamo/pendingMotion/deleteDocketEntryWorksheetRecord.ts
  web-api/src/persistence/dynamo/pendingMotion/updateDocketEntryWorksheet.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/deleteDocketEntryWorksheet.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/getDocketEntryWorksheetsByDocketEntryIds.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/mapper.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/schema.ts
  web-api/src/persistence/postgres/docketEntryWorksheets/upsertDocketEntryWorksheets.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-05-26T16_22_33Z-docket-entry-worksheet.ts
  web-api/storage/fixtures/seed/efcms-local.json
Labels: to staging, Manual Deploy Step(s) Required

#6151 10636: 'chmod +x' on some scripts that have an executable shebang
  scripts/run-once-scripts/postgres-migration/delete-docket-entry-worksheets.ts
  scripts/run-once-scripts/postgres-migration/move-docket-entry-worksheets-to-postgres.ts
Labels: to staging

#6152 Backmerge `staging` into `test`
  scripts/run-once-scripts/postgres-migration/delete-docket-entry-worksheets.ts
  scripts/run-once-scripts/postgres-migration/move-docket-entry-worksheets-to-postgres.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntryWorksheet.test.ts
  web-api/src/business/useCases/processStreamRecords/processDocketEntryWorksheetEntries.ts
  web-api/src/business/useCases/processStreamRecords/processStreamRecordsInteractor.ts
  web-api/src/business/useCases/processStreamRecords/processStreamUtilities.ts
Labels: to test

#6160 10103 story 2 postdeploy cleanup
  scripts/dynamo/delete-dynamo-table.sh
  scripts/run-once-scripts/deleteWest/README.md
  scripts/run-once-scripts/deleteWest/allColors/deleteWestAllColors.ts
  scripts/run-once-scripts/deleteWest/allColors/disassociateResourcesFromWebAcl.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteBatchResources.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteEcrImages.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteWestColorSpecific.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-09T14_50_39Z-remove-work-item-columns.ts
  web-api/terraform/bin/delete-route53-latency-records.ts
  web-api/terraform/bin/deploy-app-all-colors.sh
  web-api/terraform/bin/deploy-app-color.sh
Labels: to test

#6162 devex: only turn on the active color's stream during a glue job
  scripts/migration/toggle-streams.sh
Labels: to staging

#6154 10683-story: Fix throttling issue
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.test.ts
  web-api/src/business/useCaseHelper/caseAssociation/updateCaseAndAssociations.ts
Labels: to staging

#6164 10583 review filing
  web-client/src/ustc-ui/Focus/Focus.tsx
Labels: to staging

#5960 10625 postdeploy cleanup
  scripts/dynamo/delete-dynamo-table.sh
  scripts/run-once-scripts/deleteWest/README.md
  scripts/run-once-scripts/deleteWest/allColors/deleteWestAllColors.ts
  scripts/run-once-scripts/deleteWest/allColors/disassociateResourcesFromWebAcl.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteBatchResources.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteEcrImages.ts
  scripts/run-once-scripts/deleteWest/colorSpecific/deleteWestColorSpecific.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-09T14_50_39Z-remove-work-item-columns.ts
  web-api/terraform/bin/delete-route53-latency-records.ts
  web-api/terraform/bin/deploy-app-all-colors.sh
  web-api/terraform/bin/deploy-app-color.sh
Labels: to staging

#6123 10505 requests final test
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.test.ts
  web-api/src/business/useCases/polling/startPollingForResultsInteractor.ts
  web-api/src/database-schema.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdaWrapper.test.ts
  web-api/src/lambdaWrapper.ts
  web-api/src/lambdas/polling/startPollingForResultsLambda.ts
  web-api/src/notifications/notificationClient/getNotificationGateway.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.test.ts
  web-api/src/persistence/dynamo/polling/getRequestResults.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.test.ts
  web-api/src/persistence/dynamo/polling/saveRequestResponse.ts
  web-api/src/persistence/postgres/polling/getRequestResults.ts
  web-api/src/persistence/postgres/polling/mocks.jest.ts
  web-api/src/persistence/postgres/polling/saveRequestResponse.ts
  web-api/src/persistence/postgres/polling/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-05-29T19_02_29Z-add-table-response-strings.ts
Labels: to test

#6167 10631 radio button format for efiling to test
  web-client/src/views/FileDocument/ExternalConsolidatedCaseGroupFilingCard.tsx
Labels: to test

#6144 10562 delete mismatch error messages to test
  web-client/integration-tests/journey/docketClerkCreatesARemoteTrialSession.ts
  web-client/integration-tests/journey/docketClerkCreatesATrialSession.ts
  web-client/integration-tests/journey/docketClerkCreatesAnIncompleteTrialSessionBeforeCalendaring.ts
  web-client/integration-tests/journey/petitionerFilesDocumentForCase.ts
  web-client/integration-tests/journey/respondentAddsAnswer.ts
  web-client/integration-tests/journey/respondentAddsMotionWithBrief.ts
  web-client/integration-tests/journey/respondentAddsStipulatedDecision.ts
  web-client/src/presenter/actions/TrialSession/computeTrialSessionFormDataAction.ts
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.test.ts
  web-client/src/presenter/actions/TrialSession/validateTrialSessionAction.ts
  web-client/src/presenter/actions/validateSelectDocumentTypeAction.test.ts
  web-client/src/presenter/actions/validateSelectDocumentTypeAction.ts
Labels: to test, Review Please

#6180 10484 to test
  web-client/src/views/CaseDetailEdit/UpdateCaseModalDialog.tsx
  web-client/src/views/ContactEdit.tsx
  web-client/src/views/DocketEntryQc.tsx
  web-client/src/views/MyAccount.tsx
  web-client/src/views/StartCaseInternal/OrdersNeededSummary.tsx
  web-client/src/views/UserContactEdit.tsx
Labels: to test

#6169 Backmerge `staging` to `test`
  scripts/migration/toggle-streams.sh
Labels: to test

#6149 10645: Validation error is displayed on the Opinion Search page when it shouldn't be
  shared/src/business/entities/documents/DocumentSearch.test.ts
  shared/src/business/entities/documents/DocumentSearch.ts
Labels: to test

#6184 10532: update login & service email language
  web-client/src/views/Practitioners/PractitionerLoginServiceEmailForm.tsx
Labels: to test, Review Please

#6172 devex: add resource def for west dynamo tables in the ci/cd perms
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
Labels: to staging

#6141 10558 - Pagination tweaks in Practitioner Information
  web-client/src/views/Practitioners/PractitionerInformation.tsx
Labels: to staging

#6166 10631: change display styling from default-inline-block to block
  web-client/src/views/FileDocument/ExternalConsolidatedCaseGroupFilingCard.tsx
Labels: to staging, Review Please

#6069 10506: Move Notifications and Jobs to Postgres
  shared/src/business/test/createTestApplicationContext.ts
  web-api/src/business/useCaseHelper/generateChangeOfAddressHelper.ts
  web-api/src/business/useCases/maintenance/sendMaintenanceNotificationsInteractor.ts
  web-api/src/business/useCases/notifications/onConnectInteractor.test.ts
  web-api/src/business/useCases/notifications/onConnectInteractor.ts
  web-api/src/business/useCases/notifications/onDisconnectInteractor.ts
  web-api/src/business/useCases/user/generateChangeOfAddress.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.irsPractitioners.test.ts
  web-api/src/business/useCases/user/generateChangeOfAddressForPractitioner.privatePractitioners.test.ts
  web-api/src/business/useCases/user/updateUserContactInformationInteractor.locking.test.ts
  web-api/src/database-schema.ts
  web-api/src/dispatchers/batch/sendZipperBatchJob.ts
  web-api/src/dispatchers/slack/sendSlackNotification.test.ts
  web-api/src/dispatchers/slack/sendSlackNotification.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/rdsExpiredRecordsCleanup/rdsExpiredRecordsCleanupLambda.test.ts
  web-api/src/lambdas/rdsExpiredRecordsCleanup/rdsExpiredRecordsCleanupLambda.ts
  web-api/src/notifications/retrySendNotificationToConnections.test.ts
  web-api/src/notifications/retrySendNotificationToConnections.ts
  web-api/src/notifications/sendNotificationToConnection.test.ts
  web-api/src/notifications/sendNotificationToConnection.ts
  web-api/src/notifications/sendNotificationToUser.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/createChangeOfAddressJob.ts
  web-api/src/persistence/dynamo/jobs/ChangeOfAddress/setChangeOfAddressCaseAsDone.ts
  web-api/src/persistence/dynamo/notifications/deleteUserConnection.test.ts
  web-api/src/persistence/dynamo/notifications/deleteUserConnection.ts
  web-api/src/persistence/dynamo/notifications/getAllWebSocketConnections.ts
  web-api/src/persistence/dynamo/notifications/getDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/getDispatchNotification.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.test.ts
  web-api/src/persistence/dynamo/notifications/getWebSocketConnectionsByUserId.ts
  web-api/src/persistence/dynamo/notifications/saveDispatchNotification.test.ts
  web-api/src/persistence/dynamo/notifications/saveDispatchNotification.ts
  web-api/src/persistence/dynamo/notifications/saveUserConnection.test.ts
  web-api/src/persistence/dynamo/notifications/saveUserConnection.ts
  web-api/src/persistence/postgres/connections/deleteUserConnection.ts
  web-api/src/persistence/postgres/connections/getAllWebSocketConnections.ts
  web-api/src/persistence/postgres/connections/getWebSocketConnectionsByUserId.ts
  web-api/src/persistence/postgres/connections/saveUserConnection.ts
  web-api/src/persistence/postgres/connections/schema.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/createChangeOfAddressJob.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/deleteChangeOfAddressCaseRecord.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/schema.ts
  web-api/src/persistence/postgres/jobs/changeOfAddress/setChangeOfAddressCaseAsDone.ts
  web-api/src/persistence/postgres/notifications/getDispatchNotification.ts
  web-api/src/persistence/postgres/notifications/saveDispatchNotification.ts
  web-api/src/persistence/postgres/notifications/schema.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-03T15_25_30Z-connections.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-03T15_25_52Z-notification.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/2025-06-03T15_26_07Z-change-of-adress.ts
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/lambda/lambda.tf
  web-api/terraform/modules/rds-expired-records-cleanup/rds-expired-records-cleanup.tf
  web-api/terraform/modules/rds-expired-records-cleanup/variables.tf
  web-client/integration-tests/helpers.ts
  web-client/integration-tests/websocketConnectionDisconnection.test.ts
  web-client/src/test/createClientTestApplicationContext.ts
Labels: Do Not Merge, to staging

#6218 10494 Docket Entries Update To Test
  web-api/src/business/useCases/courtIssuedDocument/fileAndServeCourtIssuedDocumentInteractor.ts
  web-api/src/persistence/postgres/docketEntries/mapper.ts
Labels: to test, Review Please

#6222 devex: set STAGE to ENV not CLIENT_STAGE
  web-client/build-dist-public.sh
Labels: to staging

#6221 10428: Consolidate two date range components into one
  web-client/src/presenter/computeds/AdvancedSearch/advancedDocumentSearchHelper.ts
  web-client/src/views/AdvancedSearch/OpinionSearchForm.tsx
  web-client/src/views/AdvancedSearch/OrderSearchForm.tsx
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
Labels: to test, design debt, Review Please
