Repository ustaxcourt/ef-cms, pull requests merged in 2025-03, with the labels that each got.

#5846 devex: update test case with hardcoded date
  web-api/src/business/useCases/trialSessions/closeTrialSessionInteractor.test.ts
Labels: to staging

#5839 10561: Term Generator - Rulesheet UI
  cypress/local-only/tests/integration/trialSession/run-suggested-calendar-generator.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermModal.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermModal.ts
  shared/src/proxies/trialSessions/generateSuggestedTrialSessionCalendarProxy.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/checkIfTermInfoIsInStateAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/checkIfTermInfoIsInStateAction.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/navigateToTermBuilderPageAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/navigateToTermBuilderPageAction.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/saveTermBuilderInfoAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/saveTermBuilderInfoAction.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.test.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.test.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermFormAction.test.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermFormAction.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermModalAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/TrialSessions/navigateToTermBuilderPageSequence.ts
  web-client/src/presenter/sequences/TrialSessions/submitCreateTermFormSequence.ts
  web-client/src/presenter/sequences/gotoTrialSessionTermBuilderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponent.tsx
  web-client/src/views/CreateTermModal.tsx
  web-client/src/views/TermBuilderView.tsx
Labels: to test

#5848 10602: Bug - fix previous document reverting to original data in Document QC;
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.test.ts
  web-api/src/business/useCases/docketEntry/completeDocketEntryQCInteractor.ts
Labels: to test

#5841 Dependency Updates 2/28/2025
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  docs/testing.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: to staging

#5852 10569 story intermediate branch to test 1741106698
  .circleci/config.yml
  Dockerfile
  docs/dependency-updates.md
  docs/testing.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/package-lock.json
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
  web-client/src/styles/custom.scss
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to test

#5850 10601: Devex cerebral fork intermediate branch to test 1741103982
  package-lock.json
  package.json
  shared/jest-shared.config.ts
  web-client/JsdomWithTextEncoderEnvironment.js
  web-client/JsdomWithTextEncoderEnvironment.ts
  web-client/jest-unit.config.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/ustc-ui/Quill/Quill.tsx
  web-client/src/ustc-ui/Quill/quill.snow.css
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
  web-client/src/views/CreateOrder/TextEditor.tsx
  web-client/src/views/InfoNotification.tsx
  web-client/src/views/TermBuilderView.tsx
Labels: to test

#5854 devex: postgres support in the env switcher, take 2
  scripts/env/environments/00-common
  scripts/env/unset-env.zsh
  web-api/src/environment.ts
Labels: to staging

#5857 Update message in verify-terraform-version.sh
  scripts/verify-terraform-version.sh
Labels: to staging

#5858 10600 opex opensearch rightsizing
  docs/aws.md
  scripts/dynamo/setup-document-search-limiter-limits.sh
  scripts/setup-all-env-configuration.sh
  setup-local-env.sh
  shared/src/business/test/createTestApplicationContext.ts
  web-api/elasticsearch/elasticsearch-settings.ts
  web-api/src/app-public.ts
  web-api/src/app.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/middleware/advancedQueryLimiter.test.ts
  web-api/src/middleware/advancedQueryLimiter.ts
  web-api/src/middleware/ipLimiter.test.ts
  web-api/src/middleware/ipLimiter.ts
  web-api/src/middleware/userIdLimiter.test.ts
  web-api/src/middleware/userIdLimiter.ts
  web-api/src/persistence/dynamo/helpers/store.test.ts
  web-api/src/persistence/dynamo/helpers/store.ts
  web-api/storage/fixtures/seed/efcms-local.json
  web-api/terraform/modules/api/api-public.tf
  web-client/src/test/createClientTestApplicationContext.ts
Labels: to test

#5856 10419 to Test: Remove deprecated brief type options
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessionMinutes/MinuteSheet.ts
  web-client/src/presenter/actions/TrialSessionMinutes/updateTrialSessionMinutesFormAction.ts
  web-client/src/views/TrialSessionMinutes/BriefDetailsFieldsets/SeriatimFieldset.tsx
  web-client/src/views/TrialSessionMinutes/BriefDetailsFieldsets/SimultaneousMemorandumFormFieldset.tsx
  web-client/src/views/TrialSessionMinutes/TrialBriefFieldset.tsx
Labels: to test

#5862 10573: automatically delete case deadlines;
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.test.ts
  web-client/src/presenter/sequences/submitUpdateCaseModalSequence.ts
Labels: to test

#5863 10587: depricate unused and add M045A event code
  cypress/local-only/tests/integration/documentQC/docket-clerk-qcs-paper-filing.cy.ts
  shared/src/business/entities/docketEntry/externalFilingEvents.ts
  shared/src/business/entities/docketEntry/internalFilingEvents.ts
Labels: to staging

#5860 10419: Minute Sheet Feedback
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
  shared/src/business/entities/DocketEntry.test.ts
  shared/src/business/entities/DocketEntry.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/docketEntry/generateFiledBy.test.ts
  shared/src/business/entities/docketEntry/generateFiledBy.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/generateMinuteSheetFilename.test.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/generateMinuteSheetFilename.ts
  web-api/src/business/useCases/trialSessionMinutes/generateTrialSessionMinutesPdfInteractor.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.test.ts
  web-client/src/presenter/actions/TrialSessionMinutes/initializeTrialSessionMinuteSheetFormAction.ts
  web-client/src/presenter/computeds/draftDocumentViewerHelper.ts
  web-client/src/views/TrialSessionDetails/InactiveCases.tsx
  web-client/src/views/TrialSessionDetails/OpenCases.tsx
Labels: to test

#5869 Fix broken import in test
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
Labels: to test

#5865 10594 story intermediate branch to test 1741300568
  web-client/src/presenter/computeds/formattedCaseDetail.test.ts
  web-client/src/presenter/computeds/formattedCaseDetail.ts
  web-client/src/views/FileDocument/PartiesFiling.tsx
Labels: to test

#5872 Devex: Add Migrate Postgres Data Schema action to config
  .circleci/config.yml
Labels: to test

#5874 Devex fix broken migration schema command
  .circleci/config.yml
  web-api/elasticsearch/efcms-case-deadline-mappings.ts
  web-api/elasticsearch/efcms-case-mappings.ts
  web-api/elasticsearch/efcms-work-item-mappings.ts
  web-api/elasticsearch/elasticsearch-mappings.ts
  web-api/src/business/useCases/processStreamRecords/processPractitionerMappingEntries.ts
  web-api/src/database.ts
  web-api/src/persistence/elasticsearch/bulkIndexRecords.test.ts
  web-api/src/persistence/elasticsearch/getIndexNameForRecord.test.ts
  web-api/src/persistence/elasticsearch/getIndexNameForRecord.ts
  web-api/src/persistence/elasticsearch/helpers/getIndexName.test.ts
  web-api/src/persistence/elasticsearch/searchClient.test.constants.ts
  web-api/src/persistence/postgres/cases/mapper.ts
Labels: to test

#5873 10569 story intermediate branch to test
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/utilities/aggregateCommonQueryParams.test.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to test, Review Please

#5868 10419: PO Feedback Continued
  cypress/local-only/tests/integration/trialSessionMinutes/create-and-print-minute-sheet.cy.ts
  shared/src/business/utilities/documentGenerators/minuteSheet.test.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/MinuteSheet.tsx
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.test.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/formatMinuteSheet.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/generateMinuteSheetFilename.test.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/generateMinuteSheetFilename.ts
  web-api/src/business/useCaseHelper/trialSessionMinutes/mockFormattedMinuteSheet.ts
  web-api/src/business/useCases/trialSessionMinutes/generateTrialSessionMinutesPdfInteractor.ts
Labels: to test

#5880 10594 story intermediate branch to test 1741798091
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.test.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.ts
  web-client/src/presenter/actions/FileDocument/validateExternalDocumentInformationAction.ts
Labels: to test

#5884 10608 to Test: Deadlines Report Pagination Defect
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/proxies/caseDeadline/getCaseDeadlinesProxy.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReport.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReportForSingleCase.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/updateCaseDeadlineReportPageSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to test

#5867 Dependency Updates
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  scripts/verify-terraform-version.sh
  web-api/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  web-api/src/persistence/s3/saveDocumentFromLambda.ts
Labels: dependencies, to staging

#5879 Devex: clear judgeUser state on logout
  web-client/src/presenter/actions/clearUserAction.test.ts
  web-client/src/presenter/actions/clearUserAction.ts
Labels: to staging, Review Please

#5866 10594: Disable checkbox for petitioner corresponding to currently logged in user when e-filing
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.test.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.ts
  web-client/src/presenter/actions/FileDocument/validateExternalDocumentInformationAction.ts
  web-client/src/presenter/computeds/formattedCaseDetail.test.ts
  web-client/src/presenter/computeds/formattedCaseDetail.ts
  web-client/src/views/FileDocument/PartiesFiling.tsx
Labels: to staging

#5885 10573: auto remove case deadlines feedback
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
Labels: to test

#5883 10608: Deadlines Report Pagination Defect
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/proxies/caseDeadline/getCaseDeadlinesProxy.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReport.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReportForSingleCase.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/updateCaseDeadlineReportPageSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
Labels: to staging

#5887 10569 story intermediate branch to test 1741886422
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
Labels: to test, Review Please

#5892 Merge `staging` into `prod`
  .circleci/config.yml
  Dockerfile
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  scripts/verify-terraform-version.sh
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.test.ts
  shared/src/business/entities/externalDocument/ExternalDocumentInformationFactory.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.test.ts
  shared/src/business/useCases/externalDocument/validateExternalDocumentInformationInteractor.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getCaseDeadlinesInteractor.ts
  shared/src/proxies/caseDeadline/getCaseDeadlinesProxy.ts
  web-api/src/business/useCaseHelper/saveFileAndGenerateUrl.ts
  web-api/src/persistence/s3/saveDocumentFromLambda.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReport.ts
  web-client/integration-tests/journey/petitionsClerkViewsDeadlineReportForSingleCase.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/clearCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/getCaseDeadlinesAction.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.test.ts
  web-client/src/presenter/actions/CaseDeadline/setCaseDeadlinesAction.ts
  web-client/src/presenter/actions/FileDocument/validateExternalDocumentInformationAction.ts
  web-client/src/presenter/actions/clearUserAction.test.ts
  web-client/src/presenter/actions/clearUserAction.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.test.ts
  web-client/src/presenter/computeds/caseDeadlineReportHelper.ts
  web-client/src/presenter/computeds/formattedCaseDetail.test.ts
  web-client/src/presenter/computeds/formattedCaseDetail.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/updateCaseDeadlineReportPageSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDeadlines/CaseDeadlines.tsx
  web-client/src/views/FileDocument/PartiesFiling.tsx
Labels: Manual Deploy Step(s) Required

#5889 Dependency Updates for March 14, 2025
  .circleci/config.yml
  .github/workflows/api.yml
  .github/workflows/client-integration-public.yml
  .github/workflows/client-integration.yml
  .github/workflows/client.yml
  .github/workflows/e2e-cypress-accessibility.yml
  .github/workflows/e2e-cypress-public.yml
  .github/workflows/e2e-cypress-smoketests-local.yml
  .github/workflows/e2e-cypress.yml
  .github/workflows/kysely-migration-order.yml
  .github/workflows/lint.yml
  .github/workflows/pdfs.yml
  .github/workflows/scripts.yml
  .github/workflows/shared.yml
  .github/workflows/typescript-all-files-check.yml
  .github/workflows/typescript-error-check.yml
  .nvmrc
  Dockerfile
  docker-to-ecr.sh
  docs/ci-cd.md
  docs/dependency-updates.md
  docs/running-locally.md
  package-lock.json
  package.json
  scripts/verify-terraform-version.sh
  shared/admin-tools/glue/glue_migrations/main.tf
  shared/admin-tools/glue/remote_role/main.tf
  web-api/runtimes/puppeteer/Dockerfile
  web-api/runtimes/puppeteer/package.json
  web-api/terraform/applyables/account-specific/account-specific.tf
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/blue/blue.tf
  web-api/terraform/applyables/glue-cron/glue-cron-applyable.tf
  web-api/terraform/applyables/green/green.tf
  web-api/terraform/applyables/migration-cron/migration-cron-applyable.tf
  web-api/terraform/applyables/migration/migration-applyable.tf
  web-api/terraform/applyables/reindex-cron/reindex-cron-applyable.tf
  web-api/terraform/applyables/stale-cases-email-cron/stale-cases-email-cron-applyable.tf
  web-api/terraform/applyables/switch-colors-cron/switch-colors-cron-applyable.tf
  web-api/terraform/applyables/wait-for-workflow/wait-for-workflow-cron-applyable.tf
  web-api/terraform/modules/api/layers.tf
  web-api/terraform/modules/api/providers.tf
  web-api/terraform/modules/batch/docker-image/package-lock.json
  web-api/terraform/modules/batch/docker-image/package.json
  web-api/terraform/modules/default-vpc/providers.tf
  web-api/terraform/modules/dynamo-table/providers.tf
  web-api/terraform/modules/dynamsoft/providers.tf
  web-api/terraform/modules/elasticsearch/providers.tf
  web-api/terraform/modules/health-alarms/providers.tf
  web-api/terraform/modules/kibana/providers.tf
  web-api/terraform/modules/kms/providers.tf
  web-api/terraform/modules/lambda/lambda.tf
  web-api/terraform/modules/rds/providers.tf
  web-api/terraform/modules/regional-log-subscription-filters/providers.tf
  web-api/terraform/modules/ui/providers.tf
  web-api/terraform/modules/waf/providers.tf
  web-api/terraform/modules/worker/providers.tf
Labels: dependencies, to staging

#5896 Fix cerebral
  package-lock.json
  package.json
Labels: to test

#5898 test: providers should match
  web-api/terraform/modules/opensearch-sync/providers.tf
Labels: to test

#5878 10576: Automatically Add/Remove/Edit Deadlines in Consolidated Group
  shared/src/business/entities/CaseDeadline.test.ts
  shared/src/business/entities/CaseDeadline.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/Case.findLeadCaseForCases.test.ts
  shared/src/business/entities/cases/Case.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.test.ts
  shared/src/business/useCases/getConsolidatedCaseDeadlinesInteractor.ts
  shared/src/proxies/caseDeadline/getConsolidatedCaseDeadlinesProxy.ts
  web-api/src/app.ts
  web-api/src/business/useCases/caseConsolidation/addConsolidatedCaseInteractor.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.deadlines.test.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.test.ts
  web-api/src/business/useCases/caseConsolidation/removeConsolidatedCasesInteractor.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.consolidateCases.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.getcreateCaseDeadlineLockInfo.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/createCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.consolidatedCases.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.getDeleteCaseDeadlineInteractorLockInfo.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.test.ts
  web-api/src/business/useCases/caseDeadline/updateCaseDeadlineInteractor.ts
  web-api/src/database-types.ts
  web-api/src/lambdas/caseDeadline/getConsolidatedCaseDeadlinesLambda.ts
  web-api/src/persistence/dynamo/cases/createCaseTrialSortMappingRecords.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/getConsolidatedCaseDeadlines.ts
  web-api/src/persistence/postgres/caseDeadlines/mapper.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0014-add-column-to-case-deadline.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/CaseDeadline/getConsolidatedCaseDeadlineAction.ts
  web-client/src/presenter/actions/CaseDeadline/setConsolidatedCaseDeadlineAction.ts
  web-client/src/presenter/sequences/openDeleteCaseDeadlineModalSequence.ts
  web-client/src/presenter/sequences/openEditCaseDeadlineModalSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/views/CaseDetail/CaseDeadline/ConsolidatedCaseGroupInfo.tsx
  web-client/src/views/CaseDetail/CreateCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/DeleteCaseDeadlineModalDialog.tsx
  web-client/src/views/CaseDetail/EditCaseDeadlineModalDialog.tsx
Labels: to test, Review Please

#5904 10436: attempt to optimize trial session planning report
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.test.ts
  web-api/src/business/useCases/trialSessions/getTrialSessionPlanningReportDataInteractor.ts
  web-api/src/persistence/postgres/cases/getEligibleCasesCount.ts
  web-api/src/persistence/postgres/cases/mocks.jest.ts
  web-api/src/persistence/postgres/cases/reports/getBlockedCasesCount.ts
Labels: to test

#5877 10569 story - Add caseType to Advanced Search
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/business/utilities/aggregateCommonQueryParams.test.ts
  shared/src/business/utilities/aggregateCommonQueryParams.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.test.ts
  web-api/src/business/useCases/caseAdvancedSearchInteractor.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.test.ts
  web-api/src/business/useCases/public/casePublicSearchInteractor.ts
  web-api/src/persistence/elasticsearch/caseAdvancedSearch.test.ts
  web-api/src/persistence/elasticsearch/caseAdvancedSearch.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.test.ts
  web-api/src/persistence/elasticsearch/casePublicSearch.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByDocketNumber.tsx
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/AdvancedSearch/CaseSearchForm.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsTable.tsx
  web-client/src/views/TrialSessions/TrialSessionsTable.tsx
Labels: to staging, Review Please

#5910 Devex: Improve Kysely Migrations Check Messaging
  scripts/postgres/checkKyselyMigrations.ts
Labels: to staging

#5911 10502 Cases: make some improvements to hopefully fix some timeout errors
  web-api/src/persistence/postgres/cases/getCaseByDocketNumber.ts
  web-api/src/persistence/postgres/cases/getCaseMetadataWithCounsel.ts
  web-api/src/persistence/postgres/cases/reports/getCasesByFilters.ts
  web-api/src/persistence/postgres/cases/reports/getColdCases.ts
  web-api/src/persistence/postgres/utils/migrate/migrations/0015-add-more-indices.ts
Labels: to test

#5913 10561: bugfixes to test
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
Labels: to test

#5915 10436: sort blocked cases
  web-client/src/presenter/computeds/trialLocationHelper.test.ts
  web-client/src/presenter/computeds/trialLocationHelper.ts
Labels: to test

#5923 Update the version of hashicorp to 5.92.0;
  web-api/terraform/modules/opensearch-sync/providers.tf
Labels: to test

#5924 10502: limit work item return values and switch cold case to opensearch
  web-api/src/business/useCases/reports/coldCaseReportInteractor.test.ts
  web-api/src/business/useCases/reports/coldCaseReportInteractor.ts
  web-api/src/getPersistenceGateway.ts
  web-api/src/lambdas/reports/coldCaseReportLambda.ts
  web-api/src/persistence/elasticsearch/getColdCases.ts
  web-api/src/persistence/postgres/cases/mapper.ts
  web-api/src/persistence/postgres/cases/mocks.jest.ts
  web-api/src/persistence/postgres/cases/reports/getColdCases.ts
  web-api/src/persistence/postgres/workitems/getWorkItemsByDocketNumber.ts
Labels: to test

#5925 PdfJS-Dist Upgrade, React V19, Cerebral Fork. Update Extravaganza
  cypress.config.ts
  cypress/helpers/cypressTasks/pdf/parsePdf.ts
  cypress/local-only/support/helpers.ts
  docs/dependency-updates.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  shared/jest-shared.config.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/loadPDFForSigningInteractor.test.ts
  shared/src/business/useCases/loadPDFForSigningInteractor.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrder.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.tsx
  shared/src/business/utilities/pdfs/combineAllPdfDocuments.test.ts
  shared/src/business/utilities/pdfs/combineAllPdfDocuments.ts
  shared/src/business/utilities/pdfs/combineTwoPdfs.test.ts
  shared/src/business/utilities/pdfs/combineTwoPdfs.ts
  shared/src/business/utilities/pdfs/getPdfJs.ts
  shared/src/business/utilities/scrapePdfContents.test.ts
  shared/src/business/utilities/scrapePdfContents.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.test.ts
  web-api/src/getUtilities.ts
  web-api/terraform/modules/lambda/esbuildLambda.mjs
  web-client/JsdomWithTextEncoderEnvironment.js
  web-client/JsdomWithTextEncoderEnvironment.ts
  web-client/jest-unit.config.ts
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/setPDFForSigningAction.ts
  web-client/src/presenter/actions/setPDFForStampAction.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/ustc-ui/DateInput/DateRangePickerComponent.tsx
  web-client/src/ustc-ui/DateInput/DateSelector.tsx
  web-client/src/ustc-ui/FormGroup/FormGroup.tsx
  web-client/src/ustc-ui/PdfPreview/PdfPreview.tsx
  web-client/src/ustc-ui/PdfPreview/PdfViewer.tsx
  web-client/src/ustc-ui/Quill/Quill.tsx
  web-client/src/ustc-ui/Quill/quill.snow.css
  web-client/src/views/AdvancedSearch/SearchDateRangePickerComponent.tsx
  web-client/src/views/CreateOrder/TextEditor.tsx
  web-client/src/views/FileHandlingHelpers/pdfValidation.test.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
  web-client/src/views/FileHandlingHelpers/pdfValidationHelpers.ts
  web-client/src/views/InfoNotification.tsx
Labels: to staging, Review Please

#5926 10606 fix circle perms intermediate branch to test 1742833467
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
Labels: to test, Needs Account Specific

#5927 Backmerge `staging` into `test`
  cypress.config.ts
  cypress/helpers/cypressTasks/pdf/parsePdf.ts
  cypress/local-only/support/helpers.ts
  docs/dependency-updates.md
  esbuildHelper.mjs
  package-lock.json
  package.json
  scripts/npm/upgrade-npm-packages.ts
  shared/src/business/test/createTestApplicationContext.ts
  shared/src/business/useCases/loadPDFForSigningInteractor.test.ts
  shared/src/business/useCases/loadPDFForSigningInteractor.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrder.ts
  shared/src/business/utilities/documentGenerators/standingPretrialOrderForSmallCase.ts
  shared/src/business/utilities/pdfGenerator/documentTemplates/CaseInventoryReport.tsx
  shared/src/business/utilities/pdfs/combineAllPdfDocuments.test.ts
  shared/src/business/utilities/pdfs/combineAllPdfDocuments.ts
  shared/src/business/utilities/pdfs/combineTwoPdfs.test.ts
  shared/src/business/utilities/pdfs/combineTwoPdfs.ts
  shared/src/business/utilities/pdfs/getPdfJs.ts
  shared/src/business/utilities/scrapePdfContents.test.ts
  shared/src/business/utilities/scrapePdfContents.ts
  web-api/src/applicationContext.ts
  web-api/src/business/useCases/trialSessions/generateNoticesForCaseTrialSessionCalendarInteractor.test.ts
  web-api/src/getUtilities.ts
  web-api/terraform/modules/lambda/esbuildLambda.mjs
  web-client/src/applicationContext.ts
  web-client/src/presenter/actions/setPDFForSigningAction.ts
  web-client/src/presenter/actions/setPDFForStampAction.ts
  web-client/src/test/createClientTestApplicationContext.ts
  web-client/src/ustc-ui/PdfPreview/PdfPreview.tsx
  web-client/src/ustc-ui/PdfPreview/PdfViewer.tsx
  web-client/src/views/FileHandlingHelpers/pdfValidation.test.ts
  web-client/src/views/FileHandlingHelpers/pdfValidation.ts
  web-client/src/views/FileHandlingHelpers/pdfValidationHelpers.ts
Labels: to test

#5929 10576: Add DELETE endpoint to async API
  web-api/terraform/modules/api/api-async.tf
  web-api/terraform/modules/api/api.tf
Labels: to test

#5931 10616 Bug: Navigating Back to Case Detail from Edit Petitioner
  web-client/src/presenter/computeds/editPetitionerInformationHelper.test.ts
  web-client/src/presenter/computeds/editPetitionerInformationHelper.ts
Labels: to test

#5919 10462 dxox
  docs/state-management-migration/1-overview.md
  docs/state-management-migration/2-technical-analysis/a-current-architecture.md
  docs/state-management-migration/2-technical-analysis/b-migration-challenges.md
  docs/state-management-migration/2-technical-analysis/c-libraries/redux.md
  docs/state-management-migration/2-technical-analysis/c-libraries/replacing-cerebral-mobx.md
  docs/state-management-migration/2-technical-analysis/c-libraries/replacing-cerebral-redux-saga.md
  docs/state-management-migration/2-technical-analysis/c-libraries/replacing-cerebral-zustand-rxjs.md
  docs/state-management-migration/2-technical-analysis/c-libraries/replacing-cerebral-zustand-xstate.md
  docs/state-management-migration/2-technical-analysis/c-libraries/replacing-cerebral-zustand.md
  docs/state-management-migration/2-technical-analysis/c-libraries/zustand.md
  docs/state-management-migration/3-recommendation.md
  docs/state-management-migration/4-findings-presentation/index.html
  docs/state-management-migration/4-findings-presentation/start.sh
Labels: to staging, Review Please

#5928 10502: Some query optimization
  web-api/src/business/useCaseHelper/caseAssociation/createCaseAndAssociations.ts
  web-api/src/business/useCases/createCaseFromPaperInteractor.ts
  web-api/src/business/useCases/createCaseInteractor.ts
  web-api/src/persistence/postgres/caseCorrespondences/getCaseCorrespondenceByDocketNumber.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByConsolidatedCaseDeadlineId.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByDateRange.ts
  web-api/src/persistence/postgres/caseDeadlines/getCaseDeadlinesByDocketNumber.ts
  web-api/src/persistence/postgres/cases/generateDocketNumber.ts
  web-api/src/persistence/postgres/cases/getCasesByLeadDocketNumber.ts
  web-api/src/persistence/postgres/cases/getCasesMetadataWithCounselByLeadDocketNumber.ts
  web-api/src/persistence/postgres/cases/mocks.jest.ts
  web-api/src/persistence/postgres/messages/getCompletedSectionInboxMessages.ts
  web-api/src/persistence/postgres/messages/getCompletedUserInboxMessages.ts
  web-api/src/persistence/postgres/messages/getMessageById.ts
  web-api/src/persistence/postgres/messages/getMessageThreadByParentId.ts
  web-api/src/persistence/postgres/messages/getMessagesByDocketNumber.ts
  web-api/src/persistence/postgres/messages/getSectionInboxMessages.ts
  web-api/src/persistence/postgres/messages/getSectionOutboxMessages.ts
  web-api/src/persistence/postgres/messages/getUserInboxMessages.ts
  web-api/src/persistence/postgres/messages/getUserOutboxMessages.ts
  web-api/src/persistence/postgres/utils/mutex.ts
  web-api/src/persistence/postgres/workitems/getDocumentQCInboxForSection.ts
  web-api/src/persistence/postgres/workitems/getDocumentQCInboxForUser.ts
  web-api/src/persistence/postgres/workitems/getDocumentQCServedForSection.ts
  web-api/src/persistence/postgres/workitems/getDocumentQCServedForUser.ts
  web-api/src/persistence/postgres/workitems/getWorkItemById.ts
  web-api/src/persistence/postgres/workitems/getWorkItemsByDocketNumber.ts
Labels: to test

#5871 10573: automatically delete case deadlines
  shared/src/business/useCases/updateCaseContextInteractor.test.ts
  shared/src/business/useCases/updateCaseContextInteractor.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.test.ts
  web-api/src/business/useCaseHelper/docketEntry/closeCaseAndUpdateTrialSessionForEnteredAndServedDocuments.ts
  web-api/src/business/useCases/caseDeadline/deleteCaseDeadlineInteractor.test.ts
  web-client/src/presenter/sequences/submitUpdateCaseModalSequence.ts
Labels: to staging

#5930 10474: Practitioner Search Filters
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/cases/CaseSearch.ts
  shared/src/proxies/practitioners/getPractitionersByNameProxy.ts
  shared/src/proxies/public/getPublicPractitionersByNameProxy.ts
  web-api/elasticsearch/efcms-user-mappings.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.test.ts
  web-api/src/business/useCases/practitioner/getPractitionersByNameInteractor.ts
  web-api/src/lambdas/practitioners/getPractitionersByNameLambda.ts
  web-api/src/persistence/elasticsearch/getPractitionersByName.ts
  web-client/integration-tests-public/journey/unauthedUserSearchesByMeta.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/clearAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/defaultAdvancedSearchFormAction.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/getPractitionersByNameAction.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/submitCaseAdvancedSearchAction.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.test.ts
  web-client/src/presenter/actions/AdvancedSearch/updateAdvancedSearchFormAction.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/CaseSearchByNameHelper.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.test.ts
  web-client/src/presenter/computeds/AdvancedSearch/practitionerSearchHelper.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AdvancedSearch/CaseSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchResults.tsx
  web-client/src/views/CustomCaseReport/CustomCaseReport.tsx
  web-client/src/views/Public/TrialSessions/PublicTrialSessionsFilters.tsx
  web-client/src/views/TrialSessions/TrialSessions.tsx
Labels: to test

#5936 10606: adjust role name to match convention
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/rum/rum.tf
Labels: to test, Manual Deploy Step(s) Required, Needs Account Specific

#5934 Fix flaky cypress test
  cypress/deployed-and-local/integration/advancedSearch/search.cy.ts
  cypress/helpers/accountCreation/create-a-practitioner.ts
Labels: to staging, Review Please

#5932 10616 Bug: Navigating Back to Case Detail from Edit Petitioner
  web-client/src/presenter/computeds/editPetitionerInformationHelper.test.ts
  web-client/src/presenter/computeds/editPetitionerInformationHelper.ts
Labels: to staging, Review Please

#5937 10618 Bug: Fix Radio Button Positioning for Step 2 of Petition Generator
  web-client/src/views/StartCaseUpdated/FilePetitionStep2.tsx
Labels: to test

#5941 10540 bug intermediate branch to test 1743108525
  web-client/src/views/StartCaseInternal/StatisticsForm.tsx
Labels: to test

#5943 10606 branch to test
  web-client/src/providers/realUserMonitoring.ts
Labels: to test

#5903 10606 Add AWS Real User Monitoring Infrastructure and UI instrumentation
  esbuildHelper.mjs
  package-lock.json
  package.json
  scripts/env/environments/00-common
  web-api/src/lambdas/headerSecurity/header-security-lambda.ts
  web-api/terraform/applyables/allColors/allColors.tf
  web-api/terraform/applyables/allColors/outputs.tf
  web-api/terraform/applyables/allColors/variables.tf
  web-api/terraform/bin/deploy-app-all-colors.sh
  web-api/terraform/modules/ci-cd/ci-cd-permissions.tf
  web-api/terraform/modules/rum/outputs.tf
  web-api/terraform/modules/rum/rum.tf
  web-api/terraform/modules/rum/variables.tf
  web-client/build-dist.sh
  web-client/src/app.tsx
  web-client/src/appPublic.tsx
  web-client/src/providers/realUserMonitoring.ts
Labels: to staging, Manual Deploy Step(s) Required, Needs Account Specific

#5921 10561: Term Generator - Rulesheet UI
  cypress/local-only/tests/integration/trialSession/run-suggested-calendar-generator.cy.ts
  shared/src/business/entities/EntityConstants.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermForm.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermModal.test.ts
  shared/src/business/entities/trialSessions/GenerateSuggestedTermModal.ts
  shared/src/proxies/trialSessions/generateSuggestedTrialSessionCalendarProxy.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/createProspectiveTrialSessions.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.test.ts
  web-api/src/business/useCaseHelper/trialSessions/trialSessionCalendaring/generateCalendar.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.test.ts
  web-api/src/business/useCases/trialSessions/generateSuggestedTrialSessionCalendarInteractor.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/checkIfTermInfoIsInStateAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/checkIfTermInfoIsInStateAction.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/navigateToTermBuilderPageAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/navigateToTermBuilderPageAction.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/saveTermBuilderInfoAction.test.ts
  web-client/src/presenter/actions/TrialSession/TermBuilder/saveTermBuilderInfoAction.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.test.ts
  web-client/src/presenter/actions/TrialSession/formatCreateTermDatesAction.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.test.ts
  web-client/src/presenter/actions/TrialSession/runCreateTermAction.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermFormAction.test.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermFormAction.ts
  web-client/src/presenter/actions/TrialSession/validateCreateTermModalAction.ts
  web-client/src/presenter/presenter.ts
  web-client/src/presenter/sequences/TrialSessions/navigateToTermBuilderPageSequence.ts
  web-client/src/presenter/sequences/TrialSessions/submitCreateTermFormSequence.ts
  web-client/src/presenter/sequences/gotoTrialSessionTermBuilderSequence.ts
  web-client/src/presenter/state.ts
  web-client/src/router.ts
  web-client/src/styles/custom.scss
  web-client/src/views/AppComponent.tsx
  web-client/src/views/BeforeStartingCase.tsx
  web-client/src/views/CreateTermModal.tsx
  web-client/src/views/TermBuilderView.tsx
Labels: to staging

#5946 10474: Practitioner search filters - UX feedback
  cypress/helpers/accountCreation/create-a-practitioner.ts
  cypress/local-only/tests/integration/advancedSearch/practitioner-search.cy.ts
  shared/src/business/utilities/groupStatesOptions.test.ts
  shared/src/business/utilities/groupStatesOptions.ts
  web-client/src/ustc-ui/Button/PillButton.tsx
  web-client/src/views/AdvancedSearch/PractitionerSearchByName.tsx
Labels: to test
